### ISSUE TITLE
Danish data for coal, gas & biomass on ENTSO-E seems wrong

### ISSUE THREAD

**Issue by alixunderplatz** [tmrowco/electricitymap-contrib#1161]
@corradio @brunolajoie ⚠️ From my latest comment in #1069 on Denmark:

There seems to be a very high mismatch between reported biomass and coal generation vs. installed capacity in Denmark.
____________________

[Here is the report ](https://en.energinet.dk/-/media/Energinet/El-RGD/Miljrapport-2017_EN.pdf) with the following chart: 

![image](https://user-images.githubusercontent.com/25743609/36775469-72ae10ac-1c62-11e8-9c6d-e86b83d701f1.png)

**Some coal units have been converted to biomass** as primary fuel in the last years, but the reported generation of the "biomass"-category on ENTSO-E is around 80 MW only. Waste makes up another ~150 MW (installed cap ~350 MW), which results in about 230 to 250 MW generation from biomass on electricitymap.

Nevertheless, as you can see in the table above, biomass capacity is beyond 1500 MW and had risen from 2015 to 2016 due to conversion of 2 hard coal units. 
In the text of the report it says, that full effects of conversion to biomass will be observed in 2017, so there must have been a huge increase in use of biomass in that year.
Hard coal capacity in return decreased to ~1600 MW. Gas capacity is at ~2150 MW according to energinet.dk.

For yesterday (27. Feb), on ENTSO-E you can observe, that generation from coal was between 2000 and 2700 MW. This should not be possible anymore due to the installed capacity, except I am missing something. 

I assume, it is very likely that data reported to ENTSO-E for hard coal and natural gas (see next part of my comment) is including the data for the converted biomass units. This would explain the too high coal & gas numbers and the too low biomass figures.

To present some more evidence, let's look at some generation figures for the converted units (avaiable after ~1 day):

For the **Sudstrup unit 3**, it says **"hard coal"** for fuel type, which should be **biomass**!!!

![image](https://user-images.githubusercontent.com/25743609/36776469-2ba97076-1c66-11e8-9290-aa25cca61a2f.png)

For **Avedore unit 2**, it says **"fossil gas"** for its fuel type, which should also be **biomass**!!!

![image](https://user-images.githubusercontent.com/25743609/36776509-6041b8f2-1c66-11e8-8f9b-9a10c4a95f89.png)

Same applies to **Avedore unit 1**, which is should not be using **"fossil gas"**, but **biomass** as well. 
![image](https://user-images.githubusercontent.com/25743609/36776649-d2c255b2-1c66-11e8-81c8-f4f0aa1f2e74.png)
________________________

So there are some biomass units obviously included in the type "fossil gas" and at least one unit in "hard coal".

Do you guys have a summary of the data for 2017 from your database by fuel type? I could download it from ENTSO-E, but maybe you have it ready somewhere.
**If data for 2017 proves this wrong allocation of fuel types as well, this needs to be adressed to Energinet.dk and ENTSO-E.** ⚠️

**Comment by alixunderplatz** [comment]
This is from a yearly report on Europe for 2017 by Agora Energiewende (Germany).
Hard coal and biomass should have produced an equal amount of electricity based on their estimates:

![image](https://user-images.githubusercontent.com/25743609/36777987-b940cde4-1c6b-11e8-9133-ba658f7d65c4.png)

**Comment by brunolajoie** [comment]
@alixunderplatz, here are EMap's average values for power production in DK for 2017 (MW)
>power_production_biomass_avg        205.130411
power_production_coal_avg           927.950361
power_production_gas_avg            485.802520
power_production_hydro_avg                 NaN
power_production_nuclear_avg               NaN
power_production_oil_avg             97.312931
power_production_solar_avg           83.659302
power_production_wind_avg          1628.132378
power_production_geothermal_avg            NaN
power_production_unknown_avg               NaN

Indeed, it seems that our parser (from ENTSOE) under-report biomass output relative to coal

**Comment by brunolajoie** [comment]
Dear @Dalius-ENTSO-E, I wanted to inform you that we may have found a discrepency in ENTSOE's power production data for Danemark, where recent conversion of power plants from coal/gas to biomass may not yet have been taken into account. It seems to be a matter of classification of plant type rather than of a matter of data missing. Any feedback on this on your side?

**Comment by corradio** [comment]
@fedders do you have any insights from energinet.dk?

**Comment by fedders** [comment]
@corradio I'll ask around

**Comment by alixunderplatz** [comment]
I had another look at the data on ENTSO-E to highlight the dimensions of this issue.

First off, it seems like Studstrup power plant near Aarhus was even fully converted to biomass (units 3 and 4)? Articles I could find were a bit unclear about it.
https://www.endswasteandbioenergy.com/article/1411848/dong-energy-reveals-finish-studstrup-conversion

However, here are some Excel graphs for the 27 February 2018 to highlight what's currently wrong:
___________

First figure: I downloaded the available "per unit" generation from ENTSO-E. This seems to cover hard coal units entirely, as you can see comparing it to the black line (total "per type" that is used on the map). 
But for gas, only a part of "per unit" generation (3 units) is covered. Probably, because there are a lot of small-scale CHP plants for district heating from gas in Denmark, which are not required to report their "per unit" output.
The bars are stacked on top of each other, so are the two lines. You can see hard coal meets the black line pretty well, for gas, there is the gap because only 3 units are reporting. There are some small deviations for hard coal units compared to the total output, but let's neglect this.

![image](https://user-images.githubusercontent.com/25743609/36835262-ebe42aa0-1d35-11e8-9d08-aec54233d186.png)
___________________

Second figure: Here, I simply colored the units that are probably running on biomass (wood pellets, straw, ...) as main fuel. During their maximum generation, they have a combined output of almost 1200 MW, which is not reported in the "biomass" section on ENTSO-E (~80 MW).

![image](https://user-images.githubusercontent.com/25743609/36835596-08f08ec6-1d37-11e8-8f79-48d19a82a8eb.png)
___________________

Third figure: This is a seperate diagram for the units labeled "hard coal". Studstrup units 3 and 4 (near Aarhus) colored green. I had not yet investigated, whether other coal units were also converted in the last year. Studstrup units account for ~1/4 of generation currently labeled as "hard coal".

![image](https://user-images.githubusercontent.com/25743609/36835817-b4d84422-1d37-11e8-9223-dc290242743f.png)
___________________
Third figure: This is a seperate diagram for the units labeled "fossil gas". Avedoere units 1 and 2 (near Copenhagen) colored green. They make up about 50% of the "per type" output of fossil gas.
![image](https://user-images.githubusercontent.com/25743609/36835875-e42bf4d0-1d37-11e8-9d6d-bdcccc6aef2b.png)

___________________
If these units were converted to their respective actual types, fossil gas and hard coal generation would lose a huge part of their recent output, which would be transferred to biomass. This would lower DK's emissions significantly and show the results of the conversion to biomass of the last years.

**Comment by alixunderplatz** [comment]
Finally, here is what total generation by type looked like if units Standstrup 3+4 and Avedoere 1+2 were mapped to the correct type biomass and removed from coal and gas:
- Left side is current situation, right side after fixing.

![image](https://user-images.githubusercontent.com/25743609/36839257-ce9ad136-1d41-11e8-8e37-424db7becff6.png)

Daily generation from:
- biomass would increase to 29 GWh from 4.9 GWh (+24.1 GWh)
- coal would decrease to 36.9  GWh from 48.6 GWh (-11.7 GWh)
- gas would decrease to 11.7 GWh from 24.2 GWh (-12.5 GWh)

Emissions for that day would be composed as follows (imports excluded):

- Left side is current situation, right side after fixing.
![image](https://user-images.githubusercontent.com/25743609/36840215-8012b314-1d44-11e8-844c-db733f6c5cd5.png)

Total emissions for that specific day would decrease by about 20%.

**Comment by brunolajoie** [comment]
🔍 nice job. 

So if I summarize for coal it's quite easy to fix because "sum of each coal power plant output" = "total coal output" on ENTSOE. Therefore we just have to substract the real time biomass plants output from it to get real coal figure.

But for gas, "sum per power plant < total gas output" on ENTSOE. Which gas figure should we take as the reference, from where we would substract the biogas from it?

**Comment by alixunderplatz** [comment]
@brunolajoie I just found an error in my diagrams, I was including a unit twice. Fixed the previous comment, now I'll fix the emission graph.

**Comment by alixunderplatz** [comment]
@brunolajoie okay this error was just for the upper comment, emissions and total output should be fine.

After fixing, it seems like there is a small gap of ~300 MW in the coal part. But I left units out that are displaying "0 MW" generation on ENTSO-E. Maybe there will be data for them later to fill the gap.

If my assumptions, that "Studstrupvaerket 3" and "Studstrupvaerket 4" (mapped as coal on ENTSO-E) are fueled with wood / other biomass, are true, then these must be subtracted from the total "per type" output for "hard coal". And added to "biomass" in return.

Yes, for gas, the gap is a bit bigger (~400 MW). 
The two (probably) biomass fired units "Avedoerevaerket 1" and "Avedoerevaerket 2" are currently reported as "fossil gas". So you'd have to subtract these from the per type total "fossil gas". And add them to biomass as well.

In general, the published "per unit" data in Denmark seems to be 24 hours behind, so fixing is only possible afterwards and not in real-time, unfortunately. 
But let's see what Energinet.dk & ENTSO-E will answer or fix.

**Comment by corradio** [comment]
It seems like energinet is aware of this. I am awaiting a longer answer from them.

**Comment by corradio** [comment]
Is this still an issue? I didn't get an answer :/

**Comment by alixunderplatz** [comment]
@corradio Yes it still is, unfortunately :-/ 
Would be interesting to see how this affects each ot the two zones.

**Comment by alixunderplatz** [comment]
I think we managed to have another data issue fixed on ENTSO-E :)
We now observe way more biomass being used, especially in DK-2 (not sure for how long it has been like that. Maybe you can cross-check the Danish electricity data for the last months?):

![image](https://user-images.githubusercontent.com/25743609/50519882-4852e680-0abd-11e9-93a3-9b86cf131bc2.png)

On ENTSO-E per unit generation, the mentioned generators Studstrup 3 for DK-West and Avedoerevaerket 1 and 2 for DK-East are now equipped with the correct fuel type "biomass" ;)

![image](https://user-images.githubusercontent.com/25743609/50519839-1b9ecf00-0abd-11e9-9142-55fa3b11d498.png)

![image](https://user-images.githubusercontent.com/25743609/50519850-278a9100-0abd-11e9-9c0d-3bcd6d02a103.png)

I'll close this issue!

**Comment by corradio** [comment]
yay!

**Comment by brunolajoie** [comment]
Noted! Thanks!!
