### ISSUE TITLE
Add Bangladesh (d-1 data)

### ISSUE THREAD

**Issue by alixunderplatz** [tmrowco/electricitymap-contrib#1213]
⚠️ **WARNING** ⚠️ Using Win10, my Antivirus says their site is infected and blocks it - so I won't post any direct links here to keep everyone safe ;) The cause of the warning  is "HTML:iframe-BWC[Trj]". ⚠️  

I accessed it through a safe virtual browser environment instead. 😷
_ _ _ _

There is data by "**Power Grid Company of Bangladesh**" (PGCB) on the hourly generation mix and exchanges with India. I searched their site for useful info and found their "operational daily reports" with a full breakdown by type and even by unit.

⚠️Here is a screenshot of the link to the daily reports ⚠️:
![image](https://user-images.githubusercontent.com/25743609/37426459-cf752450-27c6-11e8-97f3-d5ae6536c901.png)

This is the link-structure to the XLSM-files (date in the end "dd-mm-yy"). They changed format from XLS to XLSM from 15th Jan 2018.
![image](https://user-images.githubusercontent.com/25743609/37426536-0d30e40a-27c7-11e8-9e78-a3a6fea8ba8c.png)

You can go further back to 01st Jan 2014 until 14th Jan 2018 to download the XLS-files. The link-structure is inconsistent and sometimes there is a space or "0" missing.

![image](https://user-images.githubusercontent.com/25743609/37418113-b8e80abe-27b1-11e8-80cd-ac1163b26c95.png)

The "daily report" download-link wasn't causing a virus warning in a usual browser and so didn't opening the file.
It is provided as XLS/XLSM file with several sheets. There is **half-hourly generation data** for yesterday and exchanges. The forecast is only for peak hours.

![image](https://user-images.githubusercontent.com/25743609/37413195-c5a15db0-27a6-11e8-8f04-3e52d72023ad.png)

Here is a copy of the data for 13th March. Mostly GAS and OIL. 
HVDC and TRIPURA are imports from India.

TIME | GAS | HVDC | P.GEN(GAS). | P.GEN(OIL). | COAL | HYDRO | OIL | SHORTAGE | TRIPURA
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
00:00 | 3027 | 467 | 1440 | 1343 | 364 | 69 | 652 | 0 | 257
00:30 | 2916 | 473 | 1450 | 1320 | 362 | 69 | 698 | 0 | 285
01:00 | 2804 | 479 | 1460 | 1296 | 359 | 68 | 743 | 0 | 312
01:30 | 2803 | 479 | 1462 | 1265 | 359 | 68 | 627 | 0 | 304
02:00 | 2801 | 478 | 1463 | 1234 | 359 | 68 | 511 | 0 | 295
02:30 | 2800 | 479 | 1481 | 1109 | 357 | 68 | 484 | 0 | 292
03:00 | 2799 | 479 | 1499 | 983 | 354 | 68 | 456 | 0 | 289
03:30 | 2799 | 478 | 1516 | 934 | 354 | 69 | 449 | 0 | 292
04:00 | 2799 | 477 | 1532 | 884 | 354 | 69 | 442 | 0 | 295
04:30 | 2798 | 477 | 1517 | 811 | 354 | 69 | 427 | 0 | 297
05:00 | 2797 | 477 | 1501 | 738 | 354 | 69 | 411 | 0 | 298
05:30 | 2808 | 477 | 1592 | 796 | 354 | 70 | 388 | 0 | 297
06:00 | 2819 | 477 | 1683 | 854 | 353 | 70 | 364 | 0 | 296
06:30 | 2876 | 478 | 1648 | 961 | 353 | 71 | 387 | 0 | 294
07:00 | 2933 | 478 | 1613 | 1068 | 353 | 71 | 410 | 0 | 292
07:30 | 2997 | 478 | 1537 | 1197 | 355 | 72 | 412 | 0 | 292
08:00 | 3060 | 477 | 1461 | 1326 | 357 | 72 | 414 | 0 | 291
08:30 | 3001 | 478 | 1470 | 1407 | 355 | 72 | 478 | 0 | 298
09:00 | 2942 | 478 | 1479 | 1487 | 352 | 71 | 541 | 0 | 304
09:30 | 2947 | 478 | 1468 | 1587 | 352 | 71 | 543 | 0 | 298
10:00 | 2952 | 478 | 1457 | 1687 | 352 | 70 | 545 | 0 | 292
10:30 | 2935 | 478 | 1467 | 1784 | 353 | 70 | 572 | 0 | 300
11:00 | 2917 | 477 | 1477 | 1880 | 354 | 70 | 598 | 0 | 308
11:30 | 2887 | 477 | 1518 | 1905 | 353 | 70 | 637 | 0 | 314
12:00 | 2856 | 477 | 1558 | 1929 | 352 | 69 | 676 | 0 | 319
12:30 | 2902 | 477 | 1546 | 1891 | 353 | 69 | 664 | 0 | 310
13:00 | 2948 | 477 | 1533 | 1852 | 353 | 69 | 651 | 0 | 301
13:30 | 2948 | 477 | 1533 | 1852 | 353 | 69 | 651 | 0 | 301
14:00 | 2948 | 477 | 1533 | 1852 | 353 | 69 | 651 | 0 | 301
14:30 | 2992 | 478 | 1512 | 1850 | 356 | 69 | 603 | 0 | 318
15:00 | 3035 | 478 | 1491 | 1848 | 358 | 68 | 555 | 0 | 334
15:30 | 3060 | 478 | 1388 | 1890 | 358 | 68 | 572 | 0 | 329
16:00 | 3085 | 477 | 1285 | 1932 | 357 | 68 | 588 | 0 | 324
16:30 | 3074 | 477 | 1247 | 1919 | 357 | 86 | 639 | 0 | 227
17:00 | 3062 | 477 | 1208 | 1905 | 357 | 104 | 689 | 0 | 130
17:30 | 3032 | 477 | 1181 | 1919 | 357 | 104 | 793 | 0 | 140
18:00 | 3002 | 476 | 1154 | 1932 | 357 | 104 | 897 | 0 | 150
18:30 | 3218 | 477 | 1417 | 2016 | 357 | 105 | 1028 | 0 | 228
19:00 | 3433 | 477 | 1680 | 2099 | 357 | 105 | 1159 | 0 | 306
19:30 | 3296 | 478 | 1704 | 2106 | 356 | 105 | 1185 | 0 | 305
20:00 | 3299 | 478 | 1577 | 2076 | 358 | 105 | 1212 | 0 | 308
20:30 | 3337 | 478 | 1509 | 2049 | 359 | 105 | 1160 | 0 | 304
21:00 | 3375 | 477 | 1441 | 2021 | 360 | 105 | 1107 | 0 | 299
21:30 | 3320 | 477 | 1448 | 1941 | 363 | 105 | 1082 | 0 | 256
22:00 | 3265 | 477 | 1454 | 1860 | 365 | 105 | 1056 | 0 | 213
22:30 | 3183 | 472 | 1449 | 1774 | 365 | 87 | 966 | 0 | 201
23:00 | 3101 | 467 | 1444 | 1688 | 364 | 69 | 876 | 0 | 188
23:30 | 3064 | 467 | 1442 | 1516 | 364 | 69 | 764 | 0 | 223
24:00 | 3027 | 467 | 1440 | 1343 | 364 | 69 | 652 | 0 | 257

**Comment by alixunderplatz** [comment]
Capacity data and some of the data from the daily reports can be found under this link as .pdf (unfortunately the 30min breakdown only as .gif). This site seems safe^^):

http://www.bpdb.gov.bd/bpdb/index.php?option=com_content&view=article&id=150&Itemid=16

![image](https://user-images.githubusercontent.com/25743609/37427474-dd7d7bc6-27c9-11e8-8b4a-ee2ae09728a3.png)

**Comment by systemcatch** [comment]
There is a bitcoin miner embedded on some of the pages. I recommend you avoid the site unless you have ublock origin installed or a throwaway virtual env running.

**Comment by brunolajoie** [comment]
!!! wtf on the company official website?

**Comment by systemcatch** [comment]
Yup I've no idea how it got there. I doubt the company know about it.

**Comment by systemcatch** [comment]
So an update on this. I've been able to build the basic parser but unfortunately the data format changes significantly before 11th January 2018. To get that format parsing will take longer than I anticipated.
