### ISSUE TITLE
Data for Armenia AM

### ISSUE THREAD

**Issue by alixunderplatz** [tmrowco/electricitymap-contrib#1253]
There is a generation **schedule** for Armenia with data for hydro, gas and nuclear:

It is in the PDF in the second link on this side (ends with aktiv.pdf)

http://www.energyoperator.am/information.html

I ran the PDF through an OCR converter for fun do decipher the first column. Worked perfectly for letters and numbers, just the "-" signs had to be replaced.

I attached an [Excel file](https://github.com/tmrowco/electricitymap/files/1833243/armenia.xlsx) with the outcomes and some edits to highlight the rows of interest.

Here is what the result looks like:

![image](https://user-images.githubusercontent.com/25743609/37710411-dc194f1e-2d0d-11e8-8e66-739028c5bdc6.png)

Even if this is only a day-ahead schedule, it could be worth downloading the PDF each day just to have them, since there seems to be no data for the previous days or any historical data.

**Comment by brunolajoie** [comment]
Do you think it's worth implementing in order to get the "last 24h" graphs working?

**Comment by alixunderplatz** [comment]
As long as there is nothing that is "more live", the day-ahead schedule is the only option for AM now.
But because this is in conflict with being as close to live as possible, I'd say *NO*.

If there was an option to highlight countries with scheduled data (striped/dottet/etc.) in the future, let's come back to this.

**Comment by jarek** [comment]
I will close this as no real-time or recently-retrospective data appears to be available

**Comment by tmslaine** [comment]
@jarek Can we reopen this one?
Real-time data seems to be available from Electro Power Systems Operator at:
http://epso.am/scada.htm
![Armenia_Scada](https://user-images.githubusercontent.com/25774514/55820851-c71bde80-5b04-11e9-92f5-1f2e16bc3500.png)
What is included:
Top left, in blue: 
- Սպառում - Consumption
- Գեներացիա - Generation
- Փոխհոսք - Exchanges, Positive number=Export?

Boxes top row:
- left: ԱԷԿ - nuclear units and total in yellow
- second from left, upper: Hrazdan 5, gas
- second from left, lower: Yerevan Thermal Power Plant, gas
- middle upper: Hrazdan TPP 1-4, gas
- middle bottom row: Total thermal
- right bottom right corner row: Total hydro

Bottom row, left column: Միջհամ փոխհոսքեր - Interdependencies
- Again, positive number=export?
- Ահար -Ahar:Iran, two cables listed together and then separately
- Ալավեիդի - Alaverdi:Georgia?
- Արցախ - Artsakh: Officially Azerbaijan(?)
- Շինուհայր - Shinuhayr: no idea
- Լալվար - Lalvar: Georgia?
- Մեղրհ - Meghr(i):Iran?

**Comment by jarek** [comment]
Yep, and the numbers are different now than in your screenshot, so we know the data is not leftover static.

It's all one big image and the contrast between text and background colour isn't great, so I don't know how successful OCR will be, but might be worth a shot for someone.

**Comment by systemcatch** [comment]
Great work @tmslaine!

There looks to be exchange info at http://epso.am/poweren.htm

![AM_ex](https://user-images.githubusercontent.com/30196510/55869087-b5c2e880-5b7d-11e9-9d65-897f90813553.png)

**Comment by jarek** [comment]
Could we manually check if the data on http://epso.am/poweren.htm matches the data on http://epso.am/scada.htm a couple of times a day? The former is text so would be a lot easier to integrate. I guess it doesn't break out the thermal power plants nor "alternative station" by fuel though.

**Comment by alixunderplatz** [comment]
FYI: I am working on this parser atm and will submit a work-in-progress PR soon ;)
