### ISSUE TITLE
El Hierro carbon intensity is undefined when producing only from hydro storage

### ISSUE THREAD

**Issue by strassburger** [tmrowco/electricitymap-contrib#1274]
disappeared in ranking
Carbon data not shown.
situation:  hydro only

**Comment by jarek** [comment]
Thanks for noticing! Looks like currently El Hierro is running on _only_ discharge from hydro storage, which was charged up during windy weather recently:

![only storage production](https://user-images.githubusercontent.com/47415/38016670-068bf3b6-3270-11e8-9972-53f2ded2df7f.png)

This is possibly similar/same issue as seen for Aland #883 which can run on only imports with no local production.

**Comment by jarek** [comment]
Here is screenshot from https://demanda.ree.es/movil/canarias/el_hierro/total/2018-03-28 at 9:13 local time, confirming load of ~5.6 MW and production fully from hydro as of half an hour ago:
![demand and production](https://user-images.githubusercontent.com/47415/38016928-e6bb3fdc-3270-11e8-971d-a82689c8358a.png)

**Comment by systemcatch** [comment]
I think it should show in the rankings in this case?

**Comment by alixunderplatz** [comment]
The emissions from Pumped Storage are not displayed / accounted: 😟 

![image](https://user-images.githubusercontent.com/25743609/38018843-5acc3fd4-3276-11e8-85d1-86736dee299c.png)

**Comment by alixunderplatz** [comment]
Given the fact that PS consume energy from the mix, the carbon content of the storage has already been considered previously. But still, the "other" LCA emissions of PS should be included. 
It also says 24 g/kWh like for usual hydro, but once you switch to the Emissions tab, there are no absolute emissions for the pumped storage category.

**Comment by corradio** [comment]
We have opened a backend issue to fix the issue about carbon intensity.
@alixunderplatz I opened https://github.com/tmrowco/electricitymap/issues/1276 to deal with the specific issue you mention.

**Comment by jarek** [comment]
As noted in #1508, this is still happening. Last happened on morning local time of 2018-07-09.

Screenshots in case it helps debugging in any way (sorry, dumb series of 4 screenshots from my small-screen mobile):

<img src="https://user-images.githubusercontent.com/47415/42656874-e56a9aa2-8620-11e8-803b-38855b5baac6.png" width=200> <img src="https://user-images.githubusercontent.com/47415/42656875-e598b9dc-8620-11e8-8d4d-c60f73ab85e4.png" width=200> <img src="https://user-images.githubusercontent.com/47415/42656876-e5ce27a2-8620-11e8-8609-ad922d079d2d.png" width=200> <img src="https://user-images.githubusercontent.com/47415/42656877-e5fad37e-8620-11e8-9df7-379e00847c7e.png" width=200>
