### ISSUE TITLE
Add Idaho (IPCO / US-ID)

### ISSUE THREAD

**Issue by alixunderplatz** [tmrowco/electricitymap-contrib#1275]
There is generation data for **Idaho Power Company**:
https://www.idahopower.com/energy/delivering-power/generation-and-demand/

It has a delay of about 2-3 hours. It's also available as a table for the timeframe displayed in the chart.

![image](https://user-images.githubusercontent.com/25743609/38018727-063001c2-3276-11e8-8940-145545641c3a.png)

If you select one of the bars, a new window will open with this link-structure:
https://www.idahopower.com/energy/delivering-power/generation-demand-detail/?date=2017undefined25&hr=19 

I tried to find out the format of how to replace the "undefined" with the month. Just replace it with 03 for March and there you go. This option could retrieve data from the past as well. 
See:
https://www.idahopower.com/energy/delivering-power/generation-demand-detail/?date=20180327&hr=19#tab-1-2

@systemcatch I am not sure if it is a sub-region of BPA #1040 , but BPA's transmission lines you see in the map below don't really cover much of Idaho. Do you have any insights? 
I assume it is not part of BPA, because exchanges with "BPAT" are also shown on the EIA website.

![image](https://user-images.githubusercontent.com/25743609/38019475-f63d086c-3277-11e8-9dea-8ae57ed396db.png)

Imports and exports seem to be relatively low, therer are mostly transit flows from "PACW" to "PACE" according to [the chart on EIA](https://www.eia.gov/realtime_grid/?src=home-undefined#/data/graphs?end=20180322T00&start=20180315T00&bas=0000000000g&regions=0)

![image](https://user-images.githubusercontent.com/25743609/38020274-13343b5a-327a-11e8-9ff4-9bfe05177fd1.png)

**Comment by systemcatch** [comment]
Excellent find as usual Alex! I have some problems getting the chart to work in firefox but chromium handles it fine. Watching the network requests the chart is populated by data from https://api.idahopower.com/Energy/Api/V1/GenerationAndDemand/Subset

Looking at areas https://www.idahopower.com/about-us/service-area-map/ indicates they are separate from BPA.

**Comment by alixunderplatz** [comment]
@systemcatch perfect! I also couldn't revisit the [hourly chart](https://www.idahopower.com/energy/delivering-power/generation-demand-detail/?date=20180327&hr=19#tab-1-2), only works when I have been on another page of their site - maybe some cookie issue?

Looks like Idaho has been a net importer in 2017, covering 62% of their domestic demand according to this chart from [here](https://www.ceres.org/sites/default/files/reports/2017-06/Benchmarking-Air-Emissions-2017%20%281%29.pdf) (4th from the right):

![image](https://user-images.githubusercontent.com/25743609/38022758-abc3cd76-3280-11e8-99ff-f3df183fc177.png)

So we'll have to find some more info on the exchanges

**Comment by systemcatch** [comment]
Hourly D-1 exchanges are available at https://www.eia.gov/opendata/qb.php?category=2122572

**Comment by alixunderplatz** [comment]
And "total" hourly exchanges close to real-time are here:
https://www.eia.gov/realtime_grid/?src=home-undefined#/data/graphs?end=20180328T05&start=20180321T09&bas=0000000000g&regions=0

**Comment by alixunderplatz** [comment]
I could figure out where the some of the recently excluded generation of IPC happens. :)

Geothermal can safely be #uncommented in the parser and added to the map! 😃 I found the following info in the [wind energy study for Idaho by Idaho Power.](https://www.idahopower.com/energy/renewable-energy/wind/wind-study/):

> * Raft River Energy I, LLC—For up to 13 MW (nameplate generation) from its Raft River Geothermal Power Plant Unit #1 **located in southern Idaho.** The contract term is through April 2033.
> * USG Oregon LLC—For 22 MW (*estimated average annual output*) from the Neal Hot Springs geothermal power plant located near **Vale, Oregon.** The contract term is through 2037 with an option to extend.

Vale, Oregon is very close to Idaho's border: [LINK TO MAPS](https://www.google.de/maps/place/Vale,+Oregon+97918,+USA/@43.2867044,-125.526134,5z/) and located within the [service area of Idaho Power](https://www.idahopower.com/about-us/service-area-map/). A seperate power line was built to connect it with Idaho Power's grid.

The average sum of these of 35 MW makes up 100% of the recently contracted generation of these two mentioned above. 
However, the output may exceed the "average" capacity in winter due to air cooling with colder air.
So I tried to find total nameplate capacity. According to the EIA map, https://www.eia.gov/state/maps.php?src=home-f3 (select only geothermal and go to Idaho),
the nameplate capacity is 33 MW + 18 MW = 51 MW, and the summer capacity is 17.7 + 10 MW = 27.7 MW.
So I suggest using **51 MW as installed geothermal capacity for Idaho.**

_ _ _ _ _

I tried to find some more recent figures for the other installed capacity.

For oil generation, it says [on their site](https://www.idahopower.com/energy/delivering-power/power-plants/#tab-1-3) they have a 5 MW emergency generator power by diesel, that's all.

I calculated some more capacity values from their data on "generation and demand". The [hourly view](https://www.idahopower.com/energy/delivering-power/generation-demand-detail/?date=20180417&hr=16#tab-3-2) lists the utilized capacity and generation per type. So after a simple calculation, these recent installed capacities are applicable:

ENERGY SOURCE | MWgen | % utilized | Installed capacity
-- | -- | -- | --
Hydro | 1255 | 64 | 1961
PURPA/Non-Utility   Wind | 443 | 65 | 682
PURPA/Non-Utility   Solar | 230 | 79 | 291
Coal | 190 | 18 | 1056
PURPA   Other | 82 | 40 | 205
Natural   Gas | 38 | 5 | 760
Non-Utility   Geothermal | 33 | 94 | 35

Here's the summary:
```
"capacity": {
"coal": 1056,
"gas": 760,
"geothermal": 51,
"hydro": 1961,
"oil": 5,
"wind": 682,
"solar": 291
},
```

I will investigate on where their *solar* and *wind* are really installed and will come back to this.

**Comment by brunolajoie** [comment]
🔍 Nice Job for geothermal !  We'll add it then. They don't write it "PURPA", that might explain why its still physically located under their "control area". I'm very curious about PURPA wind and solar.

**Comment by corradio** [comment]
So happy to see this working! Anything left to be done here?

**Comment by alixunderplatz** [comment]
@corradio
* we need to check whether wind and solar generation happens in IPC's zone or outside of it.
I'll try to figure this out roughly by comparing some wind speed vs production from wind. Maybe I can find something for solar, too.
* (I think you can delete the US-IPC_add_geothermal branch, that one was merged already)

**Comment by brunolajoie** [comment]
Asked IdahoPower without answer. 
Have just asked someone from the US Federal Energy Policy.

**Comment by brunolajoie** [comment]
answer below:
![image](https://user-images.githubusercontent.com/22095643/40022376-193ece98-57c8-11e8-8edd-5f94524dca45.png)
Therefore, chances are good that PURPA wind & solar comes from the same Idaho grid.
However, how does it fits with your recent finding in #1040 ?

**Comment by systemcatch** [comment]
@alixunderplatz do you want to reactivate wind and solar? It should just be be a case of uncommenting a few things, else I will do it.

**Comment by alixunderplatz** [comment]
@systemcatch I can do this! :) 
Just biomass will remain excluded from the mix. Not sure about adding this one, on EIA I saw around 30 MW while ~100 MW are reported as "PURPA Other"

**Comment by brunolajoie** [comment]
Awesome team work guys! 💪
