### ISSUE TITLE
Hydro discharge total emissions not shown

### ISSUE THREAD

**Issue by corradio** [tmrowco/electricitymap-contrib#1276]
As explained in https://github.com/tmrowco/electricitymap/issues/1274#issuecomment-376813737

![image](https://user-images.githubusercontent.com/1655848/38026189-751f7ac6-328b-11e8-9cad-93924984bbcb.png)

![image](https://user-images.githubusercontent.com/1655848/38026191-7adc8e5e-328b-11e8-8121-961a5a93a50c.png)

**Comment by jarek** [comment]
Still happening as of on morning local time on 2018-07-09, including 0 emissions shown when producing fully from hydro storage.

**Comment by systemcatch** [comment]
Where would be the place to fix this @corradio ?

**Comment by corradio** [comment]
I think it would require debugging the `sortedProductionData` object in countrytable.js, L491

**Comment by systemcatch** [comment]
Seems like on [L492](https://github.com/tmrowco/electricitymap-contrib/blob/master/web/src/components/countrytable.js#L492) it is checking whether each type is not storage and assigns a value of zero if that comparison it returns false.

**Comment by corradio** [comment]
I have a local fix:

![image](https://user-images.githubusercontent.com/1655848/45640003-c6145880-bab1-11e8-96ab-efbfc5067694.png)
