### ISSUE TITLE
Revise and improve AR.py plant mapping

### ISSUE THREAD

**Issue by alixunderplatz** [tmrowco/electricitymap-contrib#1288]
Data for categories ["thermal"](http://portalweb.cammesa.com/MEMNet1/Pages/Informes%20por%20Categor%C3%ADa/Operativos/DespachoGenTermica_Minimal.aspx) and ["hydro"](http://portalweb.cammesa.com/memnet1/Pages/Informes%20por%20Categor%C3%ADa/Operativos/DespachoGenHidra_Minimal.aspx) generation from Cammesa is used for the map.
Some recently comissioned power plants were causing a warning every once in a while, because they were not yet included in the type mapping. This could be fixed by improving the parser a bit. 

I just copy and edit the rest of my comment from #1284:
_ _ _ _

1. There is a clear pattern behind the power plant IDs: In general, everything that ends with "TG" before the numeric part is a gas turbine and should be running on natural gas as main fuel (e.g. ABCD**TG**01)
Actually, the plant mapping in the AR.py could be entirely dismissed, when only the the fourth and fifth letter of the plant IDs will be considered.

2. The mapping could be refined and updated by using the first column on
http://portalweb.cammesa.com/memnet1/revistas/estacional/base_gen.html for all of the existing power plants. 

![image](https://user-images.githubusercontent.com/25743609/38309401-4b0e623a-381a-11e8-85da-af7530e82a87.png)

Could that page also be used to map the reporting plants by their IDs automatically? (see mapping below)
- Here is the mapping of that first column to the fuel types (from what I could relate to the power plant IDs):
* TG is gas (turbina de gas)
* CC is gas (combined cycle)
* AG is gas (no idea what the A means, but the web leads me to CCGT plants)
* TV is mostly gas in the recent mapping - maybe this category needs a seperate review:
  * In the recent mapping, 5 of the steam turbines TV (turbina de vapor) are running on coal (~170 MW), which seems easy enough to consider, the rest of TV should be using gas, too. Maybe some biomass is included here as well.
* DI is oil (diesel)
* EO is wind (eolico)
* HI is hydro (hidro)
* FV is solar (fotovoltaica)
* BG is biomass (biogeneradora)
* BM is biomass (biomassa)
* NU is nuclear
* BRS and MH have a very tiny amount of MWs, I suggest mapping them to "unknown" together with any other abbreviation they might come up with in the future.

This would eliminate/limit this issue that pops up every once in a while when a new unit (or previously unused unit) suddenly enters operation.

I went through the mapping in the parser and found some errors as well, like "EO" wind power plants and "FV" solar power plants recently being mapped to "hydro". Probably because they are included in the page with hydro generation data. There are only 5 of these, that need to be changed, so that has no huge impact.

**Comment by systemcatch** [comment]
I'd rather not make assumptions about the power plants based on 2 letters tbh. Better we just update them as necessary, I've used the link posted before to do that.

Good spot with the EO and FV plants, it's weird they're in the hydro section but possibly that's more of a renewable section now anyway.

**Comment by alixunderplatz** [comment]
@systemcatch and I had a brief chat on this. Mapping the entire power plant list from http://portalweb.cammesa.com/memnet1/revistas/estacional/base_gen.html is the easiest solution.
It also includes units to be commissioned in the near future, so the warnings will be avoided to some extent.

**Comment by corradio** [comment]
Awesome that sounds like a good plan

**Comment by systemcatch** [comment]
@alixunderplatz are you still able to do this one?

**Comment by alixunderplatz** [comment]
@systemcatch nope, not much spare time atm, sorry 😢 I even forgot I had self-assigned this one back then^^
