### ISSUE TITLE
Split Balearic islands ES-IB generation

### ISSUE THREAD

**Issue by alixunderplatz** [tmrowco/electricitymap-contrib#1347]
**It is possible to split the Balearic islands** (just like the Canary Islands in #626)
This would solve the recent issue #1346, too.

Here is the equivalent website for the Balearic system:

http://www.ree.es/en/activities/balearic-islands-electricity-system/balearic-electricity-demand-in-real-time

![image](https://user-images.githubusercontent.com/25743609/39114040-df8fd26e-46dd-11e8-896f-f1e79e22c226.png)

It is using the same request structure like @systemcatch described in #626 , just a few changes in the URL brought me to this:

**Mallorca:**
https://demanda.ree.es/WSvisionaMovilesBalearesRest/resources/demandaGeneracionBaleares?callback=angular.callbacks._2&curva=MALLORCA&fecha=2018-04-23

**Menorca:**
https://demanda.ree.es/WSvisionaMovilesBalearesRest/resources/demandaGeneracionBaleares?callback=angular.callbacks._2&curva=MENORCA&fecha=2018-04-23

**Ibiza:**
https://demanda.ree.es/WSvisionaMovilesBalearesRest/resources/demandaGeneracionBaleares?callback=angular.callbacks._2&curva=IBIZA&fecha=2018-04-23

**Formentera:**
https://demanda.ree.es/WSvisionaMovilesBalearesRest/resources/demandaGeneracionBaleares?callback=angular.callbacks._2&curva=FORMENTERA&fecha=2018-04-23

Interconnectors are labeled "emm" for "Mallorca<->Menorca" (inoperative!), "eif" for "Ibiza<->Formentera" and "eim" for "Ibiza<->Mallorca".  "cb" is Mallorca<->Spanish peninsula.

Formentera is recently missing on the map due to its smaller size and should be added in the process.

**Comment by alixunderplatz** [comment]
@blackleg is this possibly covered by your reescaper already?

**Comment by alixunderplatz** [comment]
@blackleg that's lovely, thanks! :)

I guess these are the next steps:

* seperate the islands' geometry and create new zones:
  * ES-IB-MA for Mallorca
  * ES-IB-ME for Menorca
  * ES-IB-IZ for Ibiza
  * ES-IB-FO for Formentera
    * Formentera is not on the map and must be added to the geometries.
     @systemcatch Same approach as in #1022 required?

* update the [ES_IB parser](https://github.com/tmrowco/electricitymap/blob/master/parsers/ES_IB.py) to split generation per island and feature exchanges between the Balearic islands
  * change library from "reescraper" to "ree" (I guess we can do that for [the Canaries / ES_CN](https://github.com/tmrowco/electricitymap/blob/master/parsers/ES_CN.py), too? Any major changes to consider, @blackleg ?)
  * add exchanges and arrows between the zones
  * **Note**: Formentera seems to have no own generation, except for some PV during the day, so it should also be colored when generation = 0 MW and the island is fully powered by imports from Ibiza

**Comment by systemcatch** [comment]
@alixunderplatz Formentera is currently being removed from the map by the topojson simplification just like Aruba was, so hopefully we can apply the same fix again.

I think the approach I took on the the Canaries will work here but I'll need to refresh my memory how I actually did it with qgis.

**Comment by alixunderplatz** [comment]
@blackleg I saw this generation category for the Baleares (on Mallorca): 

`"resid":38.9`

That's probably residuos / waste? It has a share of about 5-7% in the total mix of all the Islands.

I guess, this is assigned to "other" by ree at the moment? Could you put it in a seperate "waste" category, so it can be mapped to biomass? That'll reduce the "unknown" category significantly. :-)

**Comment by alixunderplatz** [comment]
Hey guys 😸

I tried to use "human pattern recognition" to update the ES_IB parser for splitting their generation with basically no knowledge of Python 🐍 ^^

I 'stole' and adapted some of the existing code from ES_IB and ES_CN and tried to figure out how it should work.

Feels like I got the basic stuff working in Python, at least printing demand, generation and exchanges were working fine for me^^

Since github does not support uploading .py files in the comments, here is the .txt for you guys for improvements.

I had to comment some parts to run this locally in Python, see my ##comments in the file.

[ES_IB_new.txt](https://github.com/tmrowco/electricitymap/files/2009422/ES_IB_new.txt)

Greetings, Alex

**Comment by systemcatch** [comment]
Hey @alixunderplatz I'll take a look at this in detail later on today. You could put the .py file into a Gist if that helps?

**Comment by blackleg** [comment]
@alixunderplatz Ree version with waste production: https://pypi.org/project/ree/2.2.0/

**Comment by alixunderplatz** [comment]
ref PR #1448 
I thought about having Ibiza+Formentera as a combined zone (ES-IB-IZFO). We could barely fit the exchange arrow between these two islands anyway, which is the main reason, plus we wouldn't have to deal with getting Formentera's geometries on the map, which makes the whole process a bit easier. 

Not too much of a compromise in terms of zone-wise granularity, in my opinion, and you could still collect data island-wise in the background if need be.
The pattern of  Formentera's supply is very interesting at the moment, though:

![image](https://user-images.githubusercontent.com/25743609/42132182-700e1fce-7d13-11e8-95c8-9b2e4fd9520c.png)

"Generacion auxiliar" looks like several 1.5 MW **diesel** generators that are switched on/off following the demand pattern. 

@blackleg Thank you for adding waste to ree! :) I think I have to bother you one last time to add 'genAux' as 'aux' ;-)

**Comment by jarek** [comment]
Please see #1580 for the latest progress on this

**Comment by systemcatch** [comment]
Is there anything else that needs to be done here?

**Comment by systemcatch** [comment]
@corradio if you add Formentera to your specific exclusion list so it's coloured correctly when solely importing from Ibiza this can be closed.

**Comment by alixunderplatz** [comment]
@systemcatch one small thing that needs to be done for Formentera in general, is adding "Generacion auxiliar" to the ree scraper of @blackleg and assign this type to "oil" here (see my last comment above). This is a bit more relevant for the summer months with higher peak loads, when this category is constantly running.

**Comment by corradio** [comment]
@systemcatch `ES-IB-FO` is already added to the list.

**Comment by systemcatch** [comment]
@corradio weird because it's still coloured grey in the image below. Maybe I'm not understanding correctly?

![fo-no-colour](https://user-images.githubusercontent.com/30196510/49338762-562c5d80-f61e-11e8-9ca2-510d2541cb9c.png)

@alixunderplatz ah ok fair enough, maybe when @blackleg has a moment he can add that.

**Comment by corradio** [comment]
Indeed I'll take a look.

**Comment by corradio** [comment]
@systemcatch fixed
