### ISSUE TITLE
Data for Southwest USA (SVERI)

### ISSUE THREAD

**Issue by systemcatch** [tmrowco/electricitymap-contrib#1405]
There is generation by fuel type at https://sveri.energy.arizona.edu/#generation-by-fuel-type plus many other measurements. Looks like 1min data with a very good breakdown!

SVERI = **Southwest Variable Energy Resource Initiative**

From the site.
>The SVERI participants include Arizona Electric Power Cooperative, Arizona Public Service, El Paso >Electric, Imperial Irrigation District, Public Service Company of New Mexico, Salt River Project, Tucson >Electric Power and the Western Area Power Administration’s Desert Southwest Region.

Practically this covers parts of Arizona, Texas, California and New Mexico. But as far as I can tell there is no overlap in data with anything we get currently.

**Comment by alixunderplatz** [comment]
Amazing find!

Just leaving the link to instructions for using the **API** here:
https://sveri.energy.arizona.edu/#howto

Looks like their large scale [solar and wind assets](https://sveri.energy.arizona.edu/#renewmap) are in **Arizona** and **New Mexico**, except for one smaller PV array (23 MW) which is located in California.

![image](https://user-images.githubusercontent.com/25743609/39965846-229c9c86-56a1-11e8-965d-e5cbfee0382e.png)

@systemcatch You're right, nothing overlaps. According to the [EIA map](https://www.eia.gov/realtime_grid/?src=home-undefined#/status?end=20180513T04) the area in Texas is rather small. Seems like the southern tip of Nevada (including Las Vegas) is within the service area, too, if these are the correct borders:

![image](https://user-images.githubusercontent.com/25743609/39966540-d107f35e-56ad-11e8-92cf-fea6206f8188.png)

Based on the EIA map, it looks like we could also implement exchanges of the Southwest with CAISO and SPP - at least for dates in the past.

**Comment by jarek** [comment]
Warning, that EIA map is for Southwest balancing area, not SVERI area! Las Vegas is serviced by Nevada Power Co which is not part of that SVERI list above. Meanwhile Imperial Irrigation District is a rural part of southern California which is not actually serviced by CAISO.

Arizona Electric Power Cooperative = small area in southeast Arizona, I think?
Arizona Public Service = most of Arizona except for Phoenix and Tucson
El Paso Electric = western corner of Texas under New Mexico, and a bit of southern New Mexico
Imperial Irrigation District = rural southeastern California
Public Service Company of New Mexico = most of New Mexico, including Santa Fe and Albuquerque
Salt River Project = around Phoenix
Tucson Electric Power = around Tucson and southeast corner of Arizona
Western Area Power Administration’s Desert Southwest Region = northwest Arizona, including Arizona side of Hoover Dam

**Comment by systemcatch** [comment]
@alixunderplatz @jarek nice so we could potentially represent this as Arizona & New Mexico until we get a proper split of the USA :wink: 

Regarding past exchange data I'm hopeful that the package I've made (https://github.com/systemcatch/eiapy) will make it easier.

**Comment by systemcatch** [comment]
Things left to do;
- [ ]  Add capacities.
- [ ] Resolve negative geothermal generation (awaiting email response from site admin).

**Comment by systemcatch** [comment]
The SVERI initiative has been shutdown (see #1527 ), closing this issue until we hear about any positive changes there.
