### ISSUE TITLE
CO2 emissions for CHP seems off

### ISSUE THREAD

**Issue by husmanden** [tmrowco/electricitymap-contrib#1445]
In scandinavian countries large amounts of electricity is produced in CHP plants, where excess heat from electricity production is used for district heating.
In this setting part of the emission from the production should be accounted to the heat production.
In your calculation you seem to assume standard power production, and account the full emission to electricity, which gives a wrong impression.
There are different ways to decide how much of the emissions to assign to the heat production.
A CHP plant typically delivers approximately the same amount of heat, as it does electricity.

Kind regards,
Torben

**Comment by jarek** [comment]
@corradio @brunolajoie could you briefly check?

**Comment by corradio** [comment]
You're absolutely right Torben. In principle we should have reduced emission factors for CHP plants.
A quick fix would be to divide emissions by half as you suggest. We would however need to know the percentage of CHP plants that run at a given time in a given area, which might be trickier than it seems.
@brunolajoie anything to add?

**Comment by brunolajoie** [comment]
There are two main methods to adjust electricity carbon intensity in CHP plants:
1. Physical: In proportion to primary energy used for generating electricity vs. primary energy used for generating heat. 
2. Economical: In proportion to economic values of electricity sales vs. heat sales

The first approach would make electricity a bit dirtier than the second (but still cleaner than if we had not taken into account heat).

These computation requires to know the amount / or the revenue sales of both heat vs. power which might be difficult to do ourself. However, this will be solved by using econinvent database that did these computation for each countries (issue #738)

**Comment by jarek** [comment]
Hello,

I will close this issue as it appears we intend to resolve this using the approach in issue #738.
