### ISSUE TITLE
[CY] Add another source for Cyprus (biomass)

### ISSUE THREAD

**Issue by alexaristotelous** [tmrowco/electricitymap-contrib#1450]
Cyprus has biomass with capacity 9.7MW, generating electricity and heat - electricity is generated at an annual average efficiency of 42.95%, having generated 36.5GWh in 2017 (0.7% of total generation). 

I think they don't publish live-data at the moment of its generation from biomass, but the annual RES generation report includes it. 
https://www.dsm.org.cy/media/attachments/RES/RES_PENETRATION_2016-2017_EN.PDF

I'm opening this issue as I (hopefully) assume they will publish live-data of their biomass generation in the near future.

**Comment by systemcatch** [comment]
In #122 we made the decision to assign all of Cyprus's non renewable generation to oil since that dominates (1478MW to 10MW at the time). If they split biomass out from conventional generation we would modify our breakdown accordingly.  Maybe you could get in touch with them and see if this could be done?

**Comment by alexaristotelous** [comment]
Hi @systemcatch - Apologies for not reading #122 beforehand. 
Everything sounds reasonable, and all details listed there seem correct to me. I sent an email today for something else to the transmission system operator, so if I establish communication I will pass on the message, since total electricity demand on the island is also a bit unclear (usually they include units to and from the areas north of the ceasefire line, where the republic of Cyprus has no effective control, but not always).

**Comment by jarek** [comment]
@alexaristotelous Did you ever hear back from the Cyprus transmission system operator?

I just looked and there haven't been numbers for production capacity (1478MW oil to 10MW biomass as referred to by systemcatch), latest capacities numbers in ENTSOE are from 2017.

If there hasn't been an update, maybe we can close the issue?

**Comment by alexaristotelous** [comment]
Hey @jarek 

Thanks for reaching out, I got involved in something else and forgot to check up on this.
Afraid they didn't get back to me regarding biomass. I know they'll be adding more power capacity soon, so hopefull that will force them to be a bit more transparent.
