### ISSUE TITLE
Add Uttarakhand (India) IN-UT

### ISSUE THREAD

**Issue by alixunderplatz** [tmrowco/electricitymap-contrib#1465]
Digging through the Indian "state load despatch centres" I found real-time data for generation in the state of Uttarakhand.

http://uksldc.in/real-time-data.php

They seem to have domestic generation from gas and hydro, although this seems to cover only ~50% of IN-UT's recent demand, so they have quite high imports. The state seems to own shares
of central power stations in Uttar Pradesh, listed under CSGS. So a share of these is produced for IN-UT as well, but in IN-UP (I think we probably cover all of this for UP already).

![image](https://user-images.githubusercontent.com/25743609/41819042-3313a688-77ba-11e8-9c6e-2f2766a4ca16.png)

It's possible to include interconnections with two neighbouring states (this would be first time for India) with Uttar Pradesh as well as Himchal Pradesh (we don't have generation for this state atm).

I compared data from the tie line table with these two maps on this site:
http://uksldc.in/power-map

For the interconnectors with Uttar Pradesh, these are the tie lines that need to be considered when summing up IN-UP->IN-UT (main flow should usually be towards Uttarakhand).
Note that the line don't follow a strict pattern like "outside->inside". The **BOLD TIE LINES** point from Uttarakhand to Uttar Pradesh, so these lines should be accounted negatively for the mentioned direction IN-UP->IN-UT when balancing.

Interconnectors with Uttar Pradesh:

400KV MORADABAD-KASHIPUR
**400KV KASHIPUR-BARIELY 2
400KV KASHIPUR-BARIELY 1
400 KV POHANA-MUZZAFFARNAGAR
220KV ROORKEE-NARA
220KV KHODRI-SHARANPUR2
220KV KHODRI-SHARANPUR1**
220KV BAREILLY-PANTNAGAR
**132KV SITARGANJ-DOHANA
132KV RAMGANGA-DHAMPUR
132KV MAHUAKHEDAGANJ-THAKURDWARA
132KV KHATIMA-PILIBHIT**

Interconnectors with Himachal Pradesh IN-HP->IN-UT (again, when balancing, **bold** is negative, not bold is positive):

**220KV KHODRI-MAJRI**
132KV GIRBATTAI-KULHAL

From the two columns, only the "MW" column must be used, the "MVA" is just for reactive power which is unimportant for us.

There also is a 132 kV line towards nepal indicated on one of the maps, but, unfortunately, it is not listed in the tie line table.

**Comment by lorrieq** [comment]
I can take this one
