### ISSUE TITLE
Should we remove red from the color scale?

### ISSUE THREAD

**Issue by corradio** [tmrowco/electricitymap-contrib#1483]
From this picture, to me it seems a bit hard to see which area is worse than another.
![image](https://user-images.githubusercontent.com/1655848/42032009-75be9508-7ad8-11e8-9754-aa1af4e256dd.png)

I'm thinking (and proposing) that maybe if the scale went from orange to brown to darkbrown (and less do a detour to the red), we wouldn't have that problem?

Let me know if this is a shared opinion or just my personal bias :)

Olivier

**Comment by jarek** [comment]
I think this is mostly only an issue in Australia where there aren't many nearby regions to give context through intermediate colours.

It seems clearer in North America for example:

![image](https://user-images.githubusercontent.com/47415/42052385-ed4eb73e-7b0e-11e8-9071-dd9190cf50c6.png)

**Comment by jarek** [comment]
Although to be honest taking a second look at this America screenshot I wouldn't be sure if MISO is cleaner than PJM without checking

**Comment by jarek** [comment]
Hallway test anecdote: I showed both of the above screenshots to a third person who wouldn't have otherwise known what the correct answer was, and they got the ordering correct in both. Could someone else try it with their neighbours? "What would you say is the relative order in terms of how 'green' the areas are?"

However a question was raised whether the colour scheme works for colour blind people. (We do have a colour-blind mode, but it's not exactly easy to spot on the first glance if you don't know it's there.)

**Comment by systemcatch** [comment]
I like the red but it can be confusing unless the carbon scale is present.  I will try and do some tests with people who have zero experience with the map or electricity later today.

**Comment by brunolajoie** [comment]
Color scale seems clear to me, but i'm definitively biased! :D

**Comment by jbuverud** [comment]
In general I like the idea of removing the red step. We are currently representing the extreme end of the carbon scale with black, which I think is good, as it kind of symbolizes "extreme pollution" (I imagine sooty, black clouds of pollution). Red is also a colour which (at least to me) symbolizes some kind of an extreme (extreme heat, extreme danger, etc), and I don't really see how having red as an intermediary step on our color scale adds anything beyond potential confusion.

There is a potential issue however. There are a lot of people who have a weak color blindness, but who have strong enough color vision to not have to use the color blind mode. For these people (up to 8% of the male population), removing the red step might make the scale less clear, as distinguishing green/brown/orange-ish colors is the main issue for people with weak color blindness. However, if we also made the color scale scale with light/dark colors (going from a light green to black), then that might  alleviate this problem. 

In any case I think user testing is the only way forward on this. We should consider making a prototype new color scale 🙂

**Comment by Hyric89** [comment]
When you have countries whose bottom source of electricity according to Electricitymap's sorting is gas and imports are coming from a territory at certain carbon intensities, the imports and gas look very similar in color in the graph:
![image](https://user-images.githubusercontent.com/35940453/42381007-bc676de2-80fd-11e8-8312-52f1a7899c59.png)

**Comment by jarek** [comment]
As another data point, I asked another un-involved person (has some technical knowledge) and they also interpreted the relative order in the two screenshots correctly. I think if anything we should look at colour blindness.

**Comment by corradio** [comment]
To make the case clearer, I've made a proposal.
The pathological case (to me) seems to happen when we have a country at 600g which shows in red, as red seems (to me again) not to fit very well into the scale green->orange->red->darkbrown.
The idea is that if we remove red with a darker orange / light brown, maybe the order will be a bit more obvious.

Original:
![image](https://user-images.githubusercontent.com/1655848/43315920-dd31d90e-9197-11e8-97f4-a500f5cc4f63.png)
new:
![image](https://user-images.githubusercontent.com/1655848/43315971-f787c9e4-9197-11e8-9f14-c3d309b76a28.png)

I think the lower example looks better and is more intuitive, as it only mixes two colors (green and brown) intead of three (green, red, brown). Again, this is mostly because I do not perceive red to fit naturally in the green -> brown transition, so I wanted to make that red a bit closer to orange.

@ovbm final word is yours. I can make a PR if you wish. It only requires changing 600g color to #9E4229
