### ISSUE TITLE
colors too subtle in new bright mode left panel

### ISSUE THREAD

**Issue by brunolajoie** [tmrowco/electricitymap-contrib#1489]
In my non-retina display screen, i can hardly see two details:
1. the unkonwn generation vs. unknown capacity installed. The former should be made darker.
2. the slider is white over white: it could be made a bit darker too
![image](https://user-images.githubusercontent.com/22095643/42097704-12854630-7bb9-11e8-94d6-4638de343cc5.png)

**Comment by qwjhvbxi** [comment]
Agree, same problem for me, I cannot see the difference.
Also, shouldn't the left panel change color too in dark-mode?
