### ISSUE TITLE
California Elec. Imports

### ISSUE THREAD

**Issue by joshuasgoldstein** [tmrowco/electricitymap-contrib#1497]
Olivier asked me to post this issue to get responses. - Prof. Joshua Goldstein

On 4/9/2018 9:06 AM, Olivier Corradi wrote:
> Hi Joshua,
> For now we simply assume that the imports don't dilute the current mix - so no matter how much power is imported, the current mix will remain unchanged.
> That's the least wrong assumption we can do without any other information.
> Olivier

Dear Olivier,
    I'm following up on the question of California imports now that you have AZ and NM on the U.S. map at the moment.  I believe the "least wrong assumption" you can make is to take the monthly fuel mix for exporting regions, or the real-time fuel mix if you have it. Assuming that imports don't dilute the current mix is obviously wrong, and in the case of California that assumption makes CA seem "greener" than it really is.  Many people are using the electricity map app (I tell people about it all the time), and Calif. is the world's leading example of heavily integrating solar on the grid, so what happens at night is important to evaluating the results.
    I looked at the data yesterday morning at 6 am (July 2):

You showed CA at 183 g.  As the sun had not yet risen, there were (as every night) a LOT of imports, 32%, which you also showed at 183g. [23% gas @490g; 17% wind@11g]. A more accurate estimate, I believe, is about 325g for the imports, raising the state's overall intensity to 230g. Here is my reasoning:

  First, we know something about where the imports come from -- in summer, about equally from the Northwest and Southwest; in winter, about two-thirds from Northwest and one-third from Southwest.*
  The electricity generated in Oregon as of March (latest data) is three-quarters hydro and one-quarter gas. Counting hydro @24g and gas @490g, that mix is around 140g. But the whole of the Northwest grid has a lot of coal. That's the pool from which Calif. draws electricity, and seems more consistent with your methodology. Oregon shows the fuel mix of electricity consumed in Oregon as 32% coal (@820g), 17% gas (@490g), 41% hydro, which is overall something like 350g.**  That's a little out of date (2014-16). The main point is that you can't cherry-pick the clean energy from a grid region and say that's what's being exported, because if not exported it would displace the dirty sources in that region. Even with changes since 2014-16,the imports from the north seem to be at least something like 250g.
  Your real-time data for SVERI show 480g: from 38% coal @820g, 34% gas @490g, and 25% nuclear @12g. [Again, the nuclear is closer to Calif. but if not exported it would displace coal on the SVERI grid, so you can't say the imports are clean.]
  For Nevada the monthly data from EIA*** for March show 66% gas, @490g, and 30% hydro, wind, & solar. [Same logic for the Hoover Dam closer to Calif. but integrated with the rest of the Nevada grid.] So the mix is on the order of 325g.

    So, with a small effort and using available government data, you can make a much better estimate of that critically important one-third of Calif. electricity that comes from out of state: 
-- About half at this time of year is from the north at, generously, something like 250g.
-- The other half an unknown split between SVERI at 480g and Nevada around 325g; perhaps 400g combined.
-- A reasonable estimate is half @250g and half @400g, or something like 325g overall. This is also the estimate for Nevada, which is the only region you show as exporting to Calif. at that time.
-- California's electric carbon intensity would be around 230g at 6 am yesterday, not 183g as shown. This reflects a systematic error, repeated for the half of every day when solar power is not producing.

A bit of further research could improve these estimates. But the big conclusion jumps out:  Your estimate of 183g is nowhere near the real number, closer to 325g!  This has big implications for energy policy, as Calif. is held up to show that (1) solar power can create a clean grid (versus, falls back on fossil electricity every night), and (2) renewables are so successful we don't need nuclear power (versus, imports nuclear electricity from Arizona every night). 
    Now that your app is so widely used -- and rightly so; it's really great! -- you have a responsibility to get the story right as best you can.  I urge you to do the modest amount of work needed to more accurately estimate imports from non-reporting regions. The assumption that "imports don't dilute the current mix" is clearly wrong.

* https://www.eia.gov/todayinenergy/detail.php?id=30192#
** https://www.oregon.gov/energy/energy-oregon/Pages/Electricity-Mix-in-Oregon.aspx
*** https://www.eia.gov/state/?sid=NV#tabs-4

Best,
Joshua
-- 
Prof. Joshua S. Goldstein
www.joshuagoldstein.com

**Comment by jarek** [comment]
Hello,

Thank you for the information. With this help, making the change should actually be really easy!

The assumption we make otherwise is simplest and least wrong _in absence of other information_ and the U.S. power system isn't really the easiest to find comprehensive real-time information about. But yes, refining this is on our priority list and this is of great help!

As we're here - do you know if there is a source where we can find real-time Californian imports broken down into where they are imported from? Knowing this (rather than generic "imported from rest of U.S.") would allow us to refine the imports quite a lot more.

**Comment by brunolajoie** [comment]
Dear @joshuasgoldstein, (cc @systemcatch)

- We are about to update (here #1500) the default carbon intensity of electricity imported from other US states, to your suggested value of 325gCO2eq/kWh. I have summarized your computation to 325 in [this simple spreadsheet to be updated later as we refine our understanding of california](https://docs.google.com/spreadsheets/d/1grrWRVbmNbpfiUvXFbkh55QfY7CK5lizow7aNX-C9NU/edit?usp=sharing) (Feel free to update it with more precise number is you wish.)

- We have found also to real-time exchange data with Mexico Baja California (here #1512), but we lack a default carbon-intensity for the imports from this zone. Would you happen to know how the electricity exported from Mexico is produced?

**Comment by systemcatch** [comment]
Some thoughts on the exchange with Baja California.  We can find out what power plants are present then work towards estimating a emissions factor.  http://datasets.wri.org/dataset/globalpowerplantdatabase shows individual plants in Mexico but we will have to dig out the relevant ones to the region.  As @alixunderplatz said it's isolated from the Mexican national grid which makes things easier.

Interesting report on the Southern part, only skimmed so far.
https://www.wartsila.com/twentyfour7/in-detail/optimising-the-power-grid-in-baja-california-sur

Actually this link describes the breakdown quite well.
http://www.investinbaja.gob.mx/en/industries/energy

**Comment by joshuasgoldstein** [comment]
I have some queries out about the northern Baja grid as well as the 
general question of Calif. imports, and will report back when I hear 
something.  For the moment, given the amounts are small, probably 
assuming combined-cycle gas is the safest course.
Joshua

Prof. Joshua S. Goldstein
16 Poets Corner Rd., Amherst, MA 01002
(413) 687-4842   www.joshuagoldstein.com

**Comment by joshuasgoldstein** [comment]
Bruno,
     I'm not sure about posting to GitHub, so sending this to you and 
the "list" and asking you to post as relevant.  I've gotten suggestions 
from Jesse Jenkins who is a leading expert on this issue. Here's his 
response:


Yeah you can get imports/exports from EIA by balancing area. Here is 
Caiso for example 
https://www.eia.gov/realtime_grid/?src=data#/data/graphs?end=20180719T09&start=20180712T13&bas=000002 


There is an api for the underlying data I believe.

I don't think there is marginal emissions data here. If you can get real 
time fuel mix from each balancing area or at least each major Balancing 
area/ISO you could estimate the average and marginal rate in each region 
and then assign exports/imports the marginal emissions rate of the 
exporting region at that time. Should be close to accurate.


This marginal emissions data set may also be useful if you want to try 
to get a better estimate of how marginal rates change on average over 
days/seasons: https://cedm.shinyapps.io/MarginalFactors/

Jesse Jenkins
_______________________
jesse.d.jenkins@gmail.com <mailto:jesse.d.jenkins@gmail.com>






Prof. Joshua S. Goldstein
16 Poets Corner Rd., Amherst, MA 01002
(413) 687-4842   www.joshuagoldstein.com

**Comment by systemcatch** [comment]
More information on Baja California. It has quite a bit of geothermal power which will effect the export mix. Rough breakdown of capacity found so far (likely out of date).

Geothermal - 600-700MW
Oil ~ 200MW
Gas ~ 1500MW (bulk of new generation added recently)
Wind & Solar ~ very little contribution
Hydro - no information found yet, though to be low

**Comment by brunolajoie** [comment]
These may be contractual agreement, which might (or might not) reflect physical power flow, depending on the topology of the Baja grid. If electricity from these gas power plant is mixed within the Baja power grid, we'll need to look at the whole Baja grid power mix. I've asked Dra. Gabriela for some details!

**Comment by brunolajoie** [comment]
Answer from Dra. Gabriela Muñoz Meléndez:

>Regarding interconnections Sistema Eléctrico Nacional (SEN) [The Mexican Electricity System] and two regional councils in the U.S.—the WECC and the Electric Reliability Council of Texas (ERCOT), control the transfer of electric energy between the U.S. and Mexico. WECC operates the largest energy transfers between Mexico and the U.S. covering nearly 1.8 million square miles (4.7 million km2). 
The WECC joins the Mexican energy system in Baja throughout two main substations in California using three synchronous and permanent interconnections of 800 MW capacities, for a voltage level of 230 kW each. They are operated by the California Independent System Operator (CAISO). Along the northern Mexican border, the BC plants account for 99% (2,626.5 GWh) of border-region exports. 
**In few words, there are three interconnection between Baja and CA, two joining the Natural Gas fired Combined Cycle power plants (that I mentioned in my previous message) and one that interconnects a wind farm of 157 MW of installed capacity; this facility is owned by SEMPRA and INTERGEN (sorry I forgot to mention this in my previous message. I was away for my sabbatical leave and this wind farm started operation right before...in the summer of 2015). Actually the SEMPRA facilities are not interconnected to the Baja electricity network they only serve CA.**
In relation to the fuel mix and technology of the Baja system; by 2015, the total installed capacity in BC was 4,108 MW with a gross generation of 19,902 GWh. Regarding technology and fuel type, 61% of electric power was generated at natural gas fired combined cycle plants, 13% at steam turbine thermoelectric centrals, 8% at conventional thermoelectric stations, 14% at geothermal plants, 4% at wind farms and 1% at solar fields.

I'm therefore hesitating, for the Baja-imports mix to input to the eMap, bewteen
- 7.7% wind (171 MW direct conection) +  92.3% gas (625+1250 MW)
- or to use the Baja production mix given by Dra. Gabriela: "61% of electric power was generated at natural gas fired combined cycle plants, 13% at steam turbine thermoelectric centrals, 8% at conventional thermoelectric stations, 14% at geothermal plants, 4% at wind farms and 1% at solar fields."

**Comment by systemcatch** [comment]
If only those plants are capable of exporting to California then it seems like the correct method is to use the first mix you proposed.

**Comment by brunolajoie** [comment]
answer from Dra. Melendez:
> The first seems a bit more correct but see, NGCC power plants only serve CA on demand, and this is almost by the minute- if CAISO requires extra power asks from Imperial Valley substation and then electricity flows from Baja. TDM (the sempra facility)  sometimes is turn on to cover demand. 

So, it seems reasonable to use a carbon intensity of 453gCO2eq/kWh for US-CA imports from Baja, with the following assumptions: 92.3% gas, 7.7% wind

**Comment by systemcatch** [comment]
Seems like the Baja California exchange is broken right now, easy fix though. However I don't think we ever actually assigned it a carbon intensity??
