### ISSUE TITLE
Check DE->SE-SE4 exchange direction is correct

### ISSUE THREAD

**Issue by maxbellec** [tmrowco/electricitymap-contrib#1499]
In https://github.com/tmrowco/electricitymap/pull/1498, I realised `parsers.ENTSOE.ENTSOE_EXCHANGE_DOMAIN_OVERRIDE` had inverted tuples values for `DE->SE-SE4`. We need to check `ENTSOE.py` code to see if that resulted in exchanges having the wrong sign or if that had no effect.

**Comment by lorrieq** [comment]
Hey, this did have an effect and the historic values in the database need to be updated. I ran the parser twice just now, once with the current correct code and once with the previous inverted code, see values below and refer to [source](https://transparency.entsoe.eu/transmission-domain/physicalFlow/show?name=&defaultValue=false&viewType=TABLE&areaType=BORDER_BZN&atch=false&dateTime.dateTime=13.07.2018+00:00|UTC|DAY&border.values=CTY|10Y1001A1001A83F!BZN_BZN|10Y1001A1001A63L_BZN_BZN|10Y1001A1001A47J&dateTime.timezone=UTC&dateTime.timezone_input=UTC):

Current correct:
> [{'netFlow': -4.0, 'datetime': datetime.datetime(2018, 7, 13, 7, 0, tzinfo=tzutc())},
{'netFlow': -176.0, 'datetime': datetime.datetime(2018, 7, 13, 6, 0, tzinfo=tzutc())}, 
{'netFlow': -436.0, 'datetime': datetime.datetime(2018, 7, 13, 5, 0, tzinfo=tzutc())}, 
{'netFlow': 29.0, 'datetime': datetime.datetime(2018, 7, 13, 4, 0, tzinfo=tzutc())}, 
{'netFlow': 283.0, 'datetime': datetime.datetime(2018, 7, 13, 3, 0, tzinfo=tzutc())}, 
{'netFlow': 247.0, 'datetime': datetime.datetime(2018, 7, 13, 2, 0, tzinfo=tzutc())}, 
{'netFlow': 262.0, 'datetime': datetime.datetime(2018, 7, 13, 1, 0, tzinfo=tzutc())}]

Old incorrect:
> [{'netFlow': 4.0, 'datetime': datetime.datetime(2018, 7, 13, 7, 0, tzinfo=tzutc())}, 
{'netFlow': 176.0, 'datetime': datetime.datetime(2018, 7, 13, 6, 0, tzinfo=tzutc())}, 
{'netFlow': 436.0, 'datetime': datetime.datetime(2018, 7, 13, 5, 0, tzinfo=tzutc())}, 
{'netFlow': -29.0, 'datetime': datetime.datetime(2018, 7, 13, 4, 0, tzinfo=tzutc())}, 
{'netFlow': -283.0, 'datetime': datetime.datetime(2018, 7, 13, 3, 0, tzinfo=tzutc())}, 
{'netFlow': -247.0, 'datetime': datetime.datetime(2018, 7, 13, 2, 0, tzinfo=tzutc())}, 
{'netFlow': -262.0, 'datetime': datetime.datetime(2018, 7, 13, 1, 0, tzinfo=tzutc())}]

**Comment by brunolajoie** [comment]
Very good news! We'll re-fetch historical data to update this all! (after our summer break ;)

**Comment by corradio** [comment]
Thank you for checking @lorrieq !
I'm closing this as this is strictly a backend issue
