### ISSUE TITLE
GB-NIR invalid data in database

### ISSUE THREAD

**Issue by corradio** [tmrowco/electricitymap-contrib#1507]
The latest observation seems to be problematic:

![image](https://user-images.githubusercontent.com/1655848/42372212-eecab938-8111-11e8-808c-779694b74962.png)

therefore it is not shown on the map. However it is inserted in the database.
We should add proper validations to make sure coal/gas are present and that load > 0

**Comment by systemcatch** [comment]
You could add a check in https://github.com/tmrowco/electricitymap/blob/master/parsers/lib/quality.py for the sum of all production keys. Right now it checks each key individually.

This seems like something best applied to every parser, the only time it could cause a problem is if the zone is running wholly on storage.
