### ISSUE TITLE
El Hierro problems with 100% hydro

### ISSUE THREAD

**Issue by strassburger** [tmrowco/electricitymap-contrib#1508]
El Hierro problems with 100% hydro:
![hierro-hydralico-only-2018-07-09 14-06-40](https://user-images.githubusercontent.com/28303688/42450187-a196e1b8-8383-11e8-90ce-407ae1142331.png)

**Comment by systemcatch** [comment]
@strassburger I think this is related to #1274 and #1276, when a zone is running on 100% storage no emissions are assigned.

**Comment by strassburger** [comment]
@systemcatch 
That is correct,
sorry for opening new issue.
