### ISSUE TITLE
electricitymap Running locally

### ISSUE THREAD

**Issue by strassburger** [tmrowco/electricitymap-contrib#1514]
electricitymap Running locally

Problems with this line:
docker-compose run --rm web npm run watch
stops working here:

[1] multi babel-polyfill ./src/main.js 40 bytes {bundle} [built]
[./src/store.js] 1.4 KiB {bundle} [built]
    + 1066 hidden modules
Child extract-text-webpack-plugin node_modules/extract-text-webpack-plugin/dist node_modules/css-loader/index.js??ref--4-2!node_modules/mapbox-gl/dist/mapbox-gl.css:
       2 modules
Child extract-text-webpack-plugin node_modules/extract-text-webpack-plugin/dist node_modules/css-loader/index.js??ref--4-2!src/styles.css:
    [./node_modules/css-loader/index.js?!./src/styles.css] ./node_modules/css-loader??ref--4-2!./src/styles.css 40.6 KiB {0} [built]
        + 1 hidden module

after CTRL+C:
hild extract-text-webpack-plugin node_modules/extract-text-webpack-plugin/dist node_modules/css-loader/index.js??ref--4-2!src/styles.css:
    [./node_modules/css-loader/index.js?!./src/styles.css] ./node_modules/css-loader??ref--4-2!./src/styles.css 40.6 KiB {0} [built]
        + 1 hidden module
^Cnpm info lifecycle electricitymap-web@0.0.1~postwatch: electricitymap-web@0.0.1
npm info ok 

Working fine:
docker-compose build
and
docker-compose up --build
and also:
 http://localhost:8000/

Think should solve this problem before starting working in electricitymap
My brandnew installation with 16 GB RAM now  is ubuntu 18.04  amd.

**Comment by strassburger** [comment]
Sorry to make a lot of words about things pretty clear for the insiders:
The description above:
could it be just be the normal behavior??
The local map runs.
Only data not up to date.
If zhis is just the way a local installation starts let me know.
Will delete this issue then.
Thank you

**Comment by systemcatch** [comment]
Hey @strassburger that first part is working fine, it should stop at that point. The data won't be up to date as the local map only updates when parsers are run manually using update_state.py

**Comment by strassburger** [comment]
@systemcatch 
Thank you
