### ISSUE TITLE
Restore access to India-Gujarat (IN-GJ) wind and solar data

### ISSUE THREAD

**Issue by alixunderplatz** [tmrowco/electricitymap-contrib#1516]
Hey everyone,

looks like SLDCGUJ has also removed the access to real-time data websites for wind and solar, just like they did for the conventional real-time data.
The solution should be really simple: We can use the same link which still gives access to that ["print" page](http://www.sldcguj.com/RealTimeData/PrintPage.php?page=realtimedemand.php). It has wind and solar generation on the right side, too ;)

![image](https://user-images.githubusercontent.com/25743609/43044321-0939e890-8da4-11e8-868d-51a54a1a5b60.png)

Greetings, Alex

**Comment by lorrieq** [comment]
This parser is breaking because now that the new month has come the day is a single digit and `arrow` cannot parse the datetime format without a leading zero on the day.
e.g. `3-08-2018 19:39:41` vs `03-08-2018 19:39:41`

**Comment by systemcatch** [comment]
Looks like the entire sldc.com site has been down for most of January!
