### ISSUE TITLE
CA-QC no data

### ISSUE THREAD

**Issue by ggtronic** [tmrowco/electricitymap-contrib#1521]
Hello...i'm new to github and  live in CA-QC :  no source/data show up for my province ? 
https://www.electricitymap.org/?page=country&solar=false&remote=true&wind=false&countryCode=CA-QC

is it possible to at least show static current source for our province ?
seems like only real data fetching can show things ?
We dont have "live" data yet but have this energy source confirmation : 
http://www.hydroquebec.com/generation/

thanks

**Comment by ggtronic** [comment]
thanks for reply : Québec doesnt have a live fetch since its source doesnt change much :  95%+renewable with only 5% to 10% source shift ... your map would look so complete & nice if you would show static historical source for country that doesnt offer live info feed ? our rate are also fix : 5.82centsCAD+tx/kwh first 33kwh/day and 8.92centsCAD+tx/kwh for whats left/day   http://yvesauger.com/wp-content/uploads/HQ_Facture_Tarif-768x330.jpg

**Comment by corradio** [comment]
Hi @ggtronic,

Thanks for reaching out. I understand your point of view. The electricityMap project really is about showing real-time data. Even if the color doesn't change much, other parameters might evolve over time (load for example). Therefore, we require real-time data. Also, this enables us to put pressure on data providers to publish real-time data.
At this stage we don't have real-time data for Quebec, so I will have to close this issue.
If anyone stumbles upon real-time data, please re-open!

**Comment by pjakobsen** [comment]
If finding some good data sources from Quebec,  updates every 15 minutes.  I will try to code the parser and see what happens.

**Comment by jarek** [comment]
Let's follow up in https://github.com/tmrowco/electricitymap-contrib/issues/3218 where a link to a data source has been posted :+1:

**Comment by pjakobsen** [comment]
Hello friends, I have written the parser , but getting quick stuck on `poetry run test` with a python3.7.1.1 virtualenv on MacOS has yet to be successful.  `FileNotFoundError: [Errno 2] No such file or directory: 'tesseract': 'tesseract'` seems to  be the sticking point.   I will search for it in Git issues

**Comment by madsnedergaard** [comment]
> Hello friends, I have written the parser , but getting quick stuck on `poetry run test` with a python3.7.1.1 virtualenv on MacOS has yet to be successful. `FileNotFoundError: [Errno 2] No such file or directory: 'tesseract': 'tesseract'` seems to be the sticking point. I will search for it in Git issues

Did you run `poetry install -E parsers` or see the steps here for debugging? https://github.com/tmrowco/electricitymap-contrib/wiki/Set-up-local-environment

Otherwise feel free to create a draft PR and then we can see if someone else can run the tests :)
