### ISSUE TITLE
Any parseable countries left?

### ISSUE THREAD

**Issue by antifa-ev** [tmrowco/electricitymap-contrib#1533]
Do you have all countries with live electricity generation data done? Are there any left?

**Comment by corradio** [comment]
Hi @antifa-ev, 

The best is to look at the issues to figure out if some countries have data that is not yet on the map.
We created this label but it's not fully up to date:
https://github.com/tmrowco/electricitymap-contrib/issues?q=is%3Aopen+is%3Aissue+label%3A%22parser+buildable%21%22

Olivier
