### ISSUE TITLE
Add JP forecasts

### ISSUE THREAD

**Issue by corradio** [tmrowco/electricitymap-contrib#1550]
@tmslaine discovered forecasted data for Japan, which we could add!

See https://github.com/tmrowco/electricitymap-contrib/pull/1543

**Comment by lorrieq** [comment]
From the conversation in the issue it looks like we can get forecasts for demand and the exchanges. @tmslaine can you detail a bit more where this forecast data is as opposed to the actual data as it's a bit unclear in the issue.
