### ISSUE TITLE
Switch French RTE parser to new API

### ISSUE THREAD

**Issue by corradio** [tmrowco/electricitymap-contrib#1551]
The old API is deprecated, and we should use this one instead. The parser needs to be updated:

https://opendata.reseaux-energies.fr/explore/dataset/eco2mix-national-tr/api/?disjunctive.nature

Currently France is gray on the map :(

**Comment by lorrieq** [comment]
I believe RTE have a [new API](https://data.rte-france.com) with the same generation mix on a 15 minute resolution if you want to stick with them!

**Comment by corradio** [comment]
The data.rte-france.com platform is going to be deprecated aswell
apparently.

**Comment by lorrieq** [comment]
Damn. I'll get to work on updating the parser.

**Comment by brunolajoie** [comment]
eCO2mix API is working again as I speak! Closing and reopening is needed!
