### ISSUE TITLE
JP data is mostly unknown

### ISSUE THREAD

**Issue by corradio** [tmrowco/electricitymap-contrib#1562]
Hi @tmslaine,

I've been monitoring JP data, and it seems like most states are returning only "unknown" generation. How come?

![image](https://user-images.githubusercontent.com/1655848/44191450-d1c7d480-a12b-11e8-8615-d88720a3239d.png)

**Comment by corradio** [comment]
Duplicate of #541

**Comment by jarek** [comment]
> I've been monitoring JP data, and it seems like most states are returning only "unknown" generation

because we never had a breakdown, other than nuclear production (which needs to be mapped to region), and solar for the one southern region
