### ISSUE TITLE
Real-time production data for South Korea

### ISSUE THREAD

**Issue by scottlee120** [tmrowco/electricitymap-contrib#1563]
http://epsis.kpx.or.kr/epsisnew/selectMain.do

Data is provided in 5-minute intervals across the country as a whole. For now, there's only numbers on total production capacity (공급능력(MW)), actual production (현재부하(MW)), and a reserve capacity/ratio. Working on seeing if there's more detail on production mix. 

The EN and KR versions are not the same - for live data, it seems available only on the KR version although CSV exports are available only on the EN version seemingly.

**Comment by scottlee120** [comment]
http://epsis.kpx.or.kr/epsisnew/selectMainEpsMep.ajax

Chart data raw format

**Comment by scottlee120** [comment]
Historical data by year with a composition breakdown (thermal, nuclear, etc.)

http://epsis.kpx.or.kr/epsisnew/selectEkesKepGrid.do?menuId=010400

**Comment by systemcatch** [comment]
Further info in #855  that might help you.

**Comment by jarek** [comment]
Hi @scottlee120, were you able to find real-time production mix for South Korea?

**Comment by alixunderplatz** [comment]
SUMMARY
-----
From the data sources presented here and in #855, we could write a parser with all nuclear + hydro generation and fill the rest as "unknown".
@brunolajoie @corradio do you think that is enough info to begin with?

__________________

- South Korea is an electrical island with no exchanges so far.
- Load is 70-90 GW at the moment.
- [Renewable electricity goal for 2030](https://renewablesnow.com/news/south-korea-plans-4-gw-solar-offshore-wind-complex-631803/) of 20% - oh, c'mon, thats all?!?
- General capacity data is available on [this website](http://cms.khnp.co.kr/content/163/main.do?mnCd=FN05040101) in MW:

nuclear | hydro (incl. pumped storage) | coal | oil | gas | RES | Sum
-- | -- | -- | -- | -- | -- | -- 
22,529 | 6,489 | 36,709 | 4,155 | 37,838 | 9,187 | 116,908

- RES breakdown [According to IRENA](http://resourceirena.irena.org/gateway/countrySearch/?countryCode=KOR) for 2017:
  - 5.06 GW solar
  - 1.2 GW wind energy
  - 1.07 GW biomass
  - That is 7.3 GW combined, so 1.4 GW are missing to fill the RES from the official Korean source.

- Monitored hydro capacity is 603 MW according to http://cms.khnp.co.kr/eng/content/566/main.do?mnCd=EN040201
 - the total renewable hydro power on irena is given as 1.7 GW, so there is a difference of 1.1 GW. Again, I don't think there is significant output compared to the load.
- there is a tidal power plant [with 255 MW](https://en.wikipedia.org/wiki/Sihwa_Lake_Tidal_Power_Station), but there is no info on its live-output.
- fuel cells (wow!) have an [installed capacity of 110 MW](http://cms.khnp.co.kr/eng/content/564/main.do?mnCd=EN04010201)
- [Pumped storage generation capacity](http://cms.khnp.co.kr/eng/content/762/main.do?mnCd=EN040301) is 4.7 GW. There is a website for the real-time status, but it is only showing water levels. If we had flows we could make some more calculations on the output.

_______________

Nuclear is the sum of all these NPPs' units (22.5 GW):
- Kori
http://cms.khnp.co.kr/eng/kori/realTimeMgr/list.do?mnCd=EN03020201&brnchCd=BR0302
- Hanbit
http://cms.khnp.co.kr/eng/hanbit/realTimeMgr/list.do?mnCd=EN03020202&brnchCd=BR0303
- Wolsong
http://cms.khnp.co.kr/eng/wolsong/realTimeMgr/list.do?mnCd=EN03020203&brnchCd=BR0305
- Hanul
http://cms.khnp.co.kr/eng/hanul/realTimeMgr/list.do?mnCd=EN03020204&brnchCd=BR0304
- Saeul
http://cms.khnp.co.kr/eng/saeul/realTimeMgr/list.do?mnCd=EN03020205&brnchCd=BR0312

Status of the NPPs (maintenance etc)
http://cms.khnp.co.kr/sub/main05.do?mnCd=FN05

_______________

Hydro
- real-time output of different larger HPPs - at the moment only Paldang was generating
http://cms.khnp.co.kr/eng/realTimeMgr/water.do?mnCd=EN040203
I noticed the generation was either showing 201 MW or 20.1 MW (capacity of Paldang is 120 MW), so we need to be careful the values really are correct.
_______________

Load
- from http://epsis.kpx.or.kr/epsisnew/selectMain.do (entire day incl. latest value)

or from
- http://power.kpx.or.kr/powerinfo_en.php (latest value only)

_____________

I'll try to find some PV or wind sources and will try to provide an average emission factor for the unknown share ;)

**Comment by brunolajoie** [comment]
Thanks Alex! And I guess the power exchanges are not that big for South Korea, so doing the delta between total consumption and partial production would make sense. Let us know if you find wind or PV values (even historical only)

**Comment by systemcatch** [comment]
I'm thinking of taking a crack at writing a basic parser here, but before I start are we happy with @alixunderplatz's suggestion of a breakdown of nuclear, hydro and unknown (with a specific emissions factor)? Since there's no exchanges this setup shouldn't 'contaminate' the rest of the data set.

**Comment by brunolajoie** [comment]
I'm pretty much aligned with @alixunderplatz's suggestion! 👍

**Comment by planetbb** [comment]
This is monthly data breakdown into production source (available up to DEC2017).
Let me contact them for more updated veraion.
BTW, why do you need real-time data anyway?

http://kosis.kr/statisticsList/statisticsListIndex.do?menuId=M_01_01&vwcd=MT_ZTITLE&parmTabId=M_01_01&parentId=G.1;G2.2;339_33901.3;#SelectStatsBoxDiv

**Comment by jarek** [comment]
>  BTW, why do you need real-time data anyway?

In some regions the production mix changes greatly on a daily basis. Check out California's CO2eq intensity when their solar kicks in as an example. Changes to European CO2 intensity from wind tend to take closer to 48 hours, but nevertheless make a big difference. Electricity Map was built to track (and predict) these intra-day CO2 intensity differences, so it needs hourly data.

**Comment by scottlee120** [comment]
hey guys - just logged in and saw this. unknown in KR is going to be pretty high (i guess like 60% coal minimum as LNG is usually more expensive). not sure you'll get much of a reply if you contact KOSIS directly but if you see a phone number, let me know and i might be able to call them -> generally, in korea, you need eventually to call someone to get an answer as email is not a suitable means of first contact.

**Comment by systemcatch** [comment]
Hey everyone I've made a rough draft of the parser, couple of things I need help with atm.

1. Carbon intensity for the unknown portion of generation.
2. Each source returns data at different times, e.g. right now hydro is 18:20, load 18:30, nuclear 18:33. How do we combine these together?

**Comment by alixunderplatz** [comment]
@systemcatch 
1. Here's the carbon intensity based on data of IEA for South Korea:
2016: 41.8% coal, 3.1% oil, 22.5% gas, 1.1% biofuels, 0.9% solar, 0.3% wind
This leads to a carbon intensity of 680 g/kWh for the unknown part (nuclear and hydro excluded).
Solar capacity in 2018 has nearly doubled since 2016, but the share is still small.

2. In my opinion, it's never 100% sure whether the timestamp is for a discrete value, an average period or the starting or ending time of the measured period, so I think using a unified timestamp should do.
What about implementing a check if the time of each source is within a limit to the actual time and each timestamp is in the same range (like 15 min to 30 min), and then applying a unified timestamp for the data (e.g. from the load)? 
Should still be sufficiently accurate. Nuclear won't change too much over time, hydro has a very small influence only, so the load will be what's jumping up and down most of the time.

**Comment by systemcatch** [comment]
@alixunderplatz Brilliant I will implement your suggestions for both.

**Comment by systemcatch** [comment]
Seems like the load url (http://power.kpx.or.kr/powerinfo_en.php) is no longer working.

**Comment by alixunderplatz** [comment]
@systemcatch There also is some load/forecast data on this page:
http://epsis.kpx.or.kr/epsisnew/#
The continuous values in the graph seem to come from:
http://epsis.kpx.or.kr/epsisnew/selectMainEpsMep.ajax (URL was posted in the second comment of this issue)
The figure behind each *"Value2":*  is the load of the 5 min period.
Not sure if it's worth the effort to scrape it. We better just stick with the "most recent" data of any of these pages.

By the way: there also is load data for the island Jeju, 100 km south of the mainland. 
http://www.kpx.or.kr/www/contents.do?key=357 
It's connected via 2 HVDC cables, but I think we don't have any transmission data to seperate it from the mainland.

**Comment by systemcatch** [comment]
Closing this for now as there is nothing else to do.
