### ISSUE TITLE
Import intensity could fallback on yearly averages when missing/unknown

### ISSUE THREAD

**Issue by eimose** [tmrowco/electricitymap-contrib#1576]
When a country, or area, is importing electricity from another country and the exporting country's production sources are unknown, it seems as if the intensity of the imported electricity is set to be equal to the intensity of the importing country. But this is hardly meaningful. Would it be possible to set the unknown intensity of imported electricity to an average or mean value from a historical period? E.g. the last month or the same month last year. Or to the last available dataset (depending on how old that is).

I can see that it happens quite often for Norway, that "Data [is] temporarily unavailable". The intensity of the electricity exported to Sweden is low, while it is medium high when exported to West Denmark.

**Comment by corradio** [comment]
That's a very good idea, which I also wanted to implement. I think it should be quite easy to do on our side. I'll add it on our backlog so we discuss it internally.

**Comment by corradio** [comment]
@brunolajoie any take on this?

**Comment by brunolajoie** [comment]
I think it's a very good idea too! 
It requires to compute a fixed default GHG intensity for all zone of electricityMap, I guess, right?

**Comment by corradio** [comment]
that's right

**Comment by eimose** [comment]
You forecast the co2 intensity for all areas. Couldn't you just use that when actual values are missing?

**Comment by corradio** [comment]
Indeed @eimose but it poses certain threats as people might scrape the results and not pay for our API :(

**Comment by eimose** [comment]
That makes sense. However, I would think the forecast is only valuable if it is for the following 48 hours and not if it is only for the current hour. In other words, you could make the carbon intensity forecast for the current hour available instead of the full forecast and then use this value for a country, if the data source fails for a period. This would also challenge you on speed, as you would need to make it for all countries.
