### ISSUE TITLE
The enrgy balance (export - import) per country is missing

### ISSUE THREAD

**Issue by stadelma** [tmrowco/electricitymap-contrib#1579]
It should be easy to do. on a per country base, sum up all exports in MW and then sum up all imports in MW. Then calculate export minus import and give the number including the sign. A positive number indicates the country exports more then it imports. A negatve sign means the country imports more then it exports. And if you can draw a graph for this balance over a period at a to be selected time scale and period that would help to understand when a country mainly exports and when it mainly imports energy. It could further help when this graphs would be shown how much PV Wind Water Cole and Nuclear amounts are in the game.

**Comment by jarek** [comment]
Hello,

A similar subject was previously discussed in https://github.com/tmrowco/electricitymap-contrib/issues/1030. Would that provide the information you're looking for?

**Comment by jarek** [comment]
Hello, I'm going to close this in favour of issue #1030 which seems to be about a substantially similar idea. Please reopen if this is not correct.
