### ISSUE TITLE
Publish parsers as a separate package on pypi

### ISSUE THREAD

**Issue by danielsjf** [tmrowco/electricitymap-contrib#1581]
I want to integrate electricity prices and CO2 emissions in Home Assistant. HA is a platform for home automation and has many components to 'speak' to other services. 

I was thinking about using Python packages to integrate with ENTSO-e, but in that case there would be some custom work in converting that to CO2 emission rates. Some [attempts](https://community.home-assistant.io/t/any-good-ideas-are-welcome-nordpool-energy-price-per-hour/34646/12) were already made for prices specifically, but nothing for CO2 as far as I know. Also these attempts only focus on one zone (e.g. ENTSO-e or Nordpool). After I saw all the parsers in this project, it seemed easier to build upon that work.

Since HA is written in Python, it would be quite easy to use the parsers. They are already standardised and work for many countries around the world. The rules for HA are that the bulk of the code has to be in a Python package on Pypi. This to encourage work that can also be used elsewhere.

Therefore I was wondering if you have ever considered to package the parsers into a separate Python packages and publish it on pypi? I would be willing to help. Preferably in such a way that it is easy to update changes to any of them to the package code.

Let me know what you think.

**Comment by corradio** [comment]
Hi @danielsjf, 

Why not use api.electricitymap.org?

Olivier

**Comment by danielsjf** [comment]
Well I checked that but it was quite expensive for some home automation queries. It was €50/month which is a lot for scheduling for instance your dishwasher when it is cheap or when the CO2 emissions are low :-) Therefore I was hoping to integrate directly with the parsers. There is no need for a history.

**Comment by danielsjf** [comment]
Well I checked that but it was quite expensive for some home automation queries. It was €50/month which is a lot for scheduling for instance your dishwasher when it is cheap or when the CO2 emissions are low :-) Therefore I was hoping to integrate directly with the parsers. There is no need for a history.

**Comment by danielsjf** [comment]
Cool. Didn't find that one. Yes it is certainly for personal use. However, if I build the integration and release it, is that allowed. In that case other people might also start to use it for personal use. In any case, I have no ambition to sell that data directly or use it in any way to make a profit. 

Does the API also supports price signals or only CO2? Optimally I would like to cover both.

**Comment by danielsjf** [comment]
I also have again the same question. Can I make a python package to interact with the API and publish it on pypi?

**Comment by corradio** [comment]
Hi @danielsjf,
Yes sure go ahead with the integration. Just let us know what you build, so we can advertise it! Our only limitation is that you're not allowed to make a profit from it (else we should talk, and we should share the earnings).
The API unfortunately doesn't support price signals.
For the pypi co2 signal package, I think you can go ahead. I'd be nice to be kept in the loop, and possibly even this package should be done by us. We have limited resources so if you can do it and keep us in the loop that'd be great!

Olivier

**Comment by corradio** [comment]
Closing this as there's nothing we can do. Feel free to re-open if you think otherwise!
