### ISSUE TITLE
Decoding error in JP price parser

### ISSUE THREAD

**Issue by lorrieq** [tmrowco/electricitymap-contrib#1585]
`JP.fetch_price` is failing due to a `UnicodeDecodeError` in `pandas.read_csv`, the CSV file contains Japanese characters. I don't get this issue locally and saw it for the first time on the Kibana logs. 

Maybe it's as simple as passing an `encoding` parameter to `pandas.read_csv`. But I'm using the same version of `pandas` that's specified in the `requirements.txt` file, so maybe that's not it. I can't replicate the issue locally. Any ideas?

**Comment by corradio** [comment]
Hmm maybe. @maxbellec any ideas?

**Comment by jarek** [comment]
I was able to replicate the UnicodeDecodeError on my other Debian installation. Giving `read_csv` `encoding='shift-jis'` seemed to have fixed it. Sorry, I can't debug the locale/encoding settings more right now.
