### ISSUE TITLE
Arrows are slowing down the map

### ISSUE THREAD

**Issue by corradio** [tmrowco/electricitymap-contrib#1590]
I've noticed that removing arrows speed up the map significantly, especially when the wind is present.
Maybe we should consider drawing them in canvas, or in webgl

**Comment by systemcatch** [comment]
This includes the import/export arrows right? Maybe removing the animation could help?

**Comment by corradio** [comment]
It would, but it would also make me sad :(

**Comment by corradio** [comment]
Every arrow is a different GIF. Arrows are hidden/shown on zoom/drag. I
don't know of other formats that are universally supported.
We tried with SVG but that was slower due to CPU-bound animations.
I think an alternative could be to animate in canvas.

**Comment by systemcatch** [comment]
Maybe we could reduce it to one object that just gets properties (rotation, colour, pulse), or possibly use CSS sprites in some way (sorry if I'm going over stuff you've already thought of, I'm just throwing out random ideas).

By canvas you mean the way countries are drawn?

**Comment by corradio** [comment]
Countries are drawn using WebGL, but the wind animation is actually drawn
using canvas. We could do the same with arrows.
I don't know about CSS sprites or about how we would just have on object.
Are you able to investigate? That could be good ideas.

Olivier

**Comment by systemcatch** [comment]
@corradio I've thought about this again.

Using [this article](https://moz.com/blog/how-to-improve-site-performance-using-gifs) as a reference I converted all of the arrows from gifs to html5 videos (mp4) with the following command.

```shell
for i in *.gif; do ffmpeg -i "$i" -movflags faststart -pix_fmt yuv420p -vf "scale=trunc(iw/2)*2:trunc(ih/2)*2" "${i%.*}.mp4"; done
```

Total size of all arrows dropped from 653KB to 185KB. There's likely some performance gains in the browser as well.

**Comment by corradio** [comment]
That's pretty cool! Do you see any differences in perf in the browser? I'm
not sure the size changes a lot, but it shouldn't hurt!
The way I'm testing it is that I activate the wind layer, and see how
smooth it runs. Without arrows it runs very smooth on my laptop, and with
arrows it lags.

**Comment by systemcatch** [comment]
I haven't had a chance to run it yet, it'll need some modification of the html tags I guess (any pointers for where to do that?).

I'll try testing with the wind layer once I get it working.

**Comment by corradio** [comment]
I think there's a map layer called exchangelayer.js or something like that.
If you search for `img` or `gif` you should be able to see where it
generates the tag.

**Comment by corradio** [comment]
This could maybe be used: https://github.com/antimatter15/jsgif

**Comment by corradio** [comment]
Seems like mp4 in img src is not supported in Chrome

**Comment by corradio** [comment]
Seems like playing gif on canvas could help:
https://codepen.io/corradio/pen/PXzqwO?editors=0010
using
https://github.com/blindman67/GIFGroover

Will try to integrate into the map to test

**Comment by corradio** [comment]
I've created a branch here to try it out:
https://github.com/tmrowco/electricitymap-contrib/tree/olc/canvas-arrows

**Comment by ChrisLoer** [comment]
One option to consider would be representing the arrows as lines in a GeoJSON source, and then adding a line layer to the map. You can use the `line-gradient` property to change the colors (and the `line-gradient` property is quick to update, so it should be reasonable to drive this kind of animation with it). See the "animate a route line" example at https://blog.mapbox.com/map-pride-2018-with-our-new-design-tools-32b886f7db1b

If you want to have an arrow head as well as a line, you might have to get clever with making arrow shapes in the geojson, or alternatively you could use a _separate_ line layer using `line-pattern` to pull in some image as an SDF (which can also be rendered very quickly by GL JS)

**Comment by corradio** [comment]
Hi @ChrisLoer ,

from looking at the code it seems that the animation is driven by the JS thread, every 20ms:

![image](https://user-images.githubusercontent.com/1655848/54865460-3f914a00-4d66-11e9-9011-0f243e908821.png)

This seems to be very expensive if we have ~ 20arrows that we animate using JS.

**Comment by corradio** [comment]
@ChrisLoer have you seen this?
https://github.com/mapbox/mapbox-gl-js/pull/7999

**Comment by scriptator** [comment]
Just played around a bit with CSS animations, but unfortunately this is expensive as well. See https://codepen.io/nidhinobinu/pen/RWaYGb

**Comment by corradio** [comment]
> @ChrisLoer have you seen this?
> [mapbox/mapbox-gl-js#7999](https://github.com/mapbox/mapbox-gl-js/pull/7999)

There's a sample here:
https://docs.mapbox.com/mapbox-gl-js/example/add-image-animated/
and more docs here:
https://docs.mapbox.com/mapbox-gl-js/api/#customlayerinterface

**Comment by Kongkille** [comment]
We've made a few improvements. If anyone wishes to try to improve it further, feel free to reopen!
