### ISSUE TITLE
Switch to lokalise.co for translations

### ISSUE THREAD

**Issue by jld3103** [tmrowco/electricitymap-contrib#1592]
[lokalise.co](lokalise.co) is and online translation platform. It would be very easy to integrate this in the project.  
Everyone could see how far the translations for their language are.  
[Here](https://docs.lokalise.co/integrations/github) you can see that it is easy to integrate and automate with Github.  
I think it would help the people who want to translate the map in their language a lot.

**Comment by magol** [comment]
Transifex.com is another greate service to make translations.

**Comment by fbarl** [comment]
Related to #1838.
