### ISSUE TITLE
Incomplete data being reported for Great Britain

### ISSUE THREAD

**Issue by bmckinlay** [tmrowco/electricitymap-contrib#1596]
As much as I would like the UK's grid to be 90% renewable, this doesn't seem correct. Data for gas & nuclear production missing?

<img width="478" alt="screen shot 2018-09-11 at 12 21 20" src="https://user-images.githubusercontent.com/13368547/45357241-a4046d00-b5bd-11e8-8c25-317b0f9ba7c4.png">

**Comment by systemcatch** [comment]
Yes this is clearly wrong, unfortunately it looks like the quality filters haven't caught it so far.
![gb_drop](https://user-images.githubusercontent.com/30196510/45357599-9dc2c080-b5be-11e8-9270-bf2fd09f53b8.png)

**Comment by corradio** [comment]
It seems like the validation code from the ENTSOE parser (https://github.com/tmrowco/electricitymap-contrib/blob/master/parsers/ENTSOE.py#L293) hasn't been ported to the ELEXON parser:
https://github.com/tmrowco/electricitymap-contrib/blob/master/parsers/ELEXON.py#L210
Someone fancy adding that check?

**Comment by corradio** [comment]
This shouldn't happen anymore after the PR we merged.
