### ISSUE TITLE
GB-NIR fetch historical data available with 15-min 

### ISSUE THREAD

**Issue by brunolajoie** [tmrowco/electricitymap-contrib#1600]
Using the same sources than current parser for live data.

http://ws.soni.ltd.uk/DownloadCentre/aspx/FuelMix.aspx
http://ws.soni.ltd.uk/DownloadCentre/aspx/SystemOutput.aspx
http://ws.soni.ltd.uk/DownloadCentre/aspx/MoyleTie.aspx

Quite interesting as current database is 80% empty for NIR
![image-2](https://user-images.githubusercontent.com/22095643/45501672-22117100-b782-11e8-89d1-b8d489bdb5fe.png)

**Comment by systemcatch** [comment]
I'll do this one.
