### ISSUE TITLE
DE-AT-LU Split

### ISSUE THREAD

**Issue by corradio** [tmrowco/electricitymap-contrib#1605]
Seen on the ENTSOE TP:

> Dear Users,
> 
>
> Please be informed, that we will start preparation of the platform for DE-AT-LU bidding zone split on the 23rd of August. BZN|DE-AT-LU will be separated into 2 new bidding zones BZN|DE-LU and BZN|AT.
> 
> New bidding zones will be active from the 1st of October, however, first data submissions, like month ahead forecasts, are expected from the 1st of September. 
> 
> Validity end date for BZN|DE-AT-LU is the end of September 2018. 
> EIC codes for new bidding zones:
> BZN|DE-LU - 10Y1001A1001A82H 
> BZN|AT - 10YAT-APG------L (same as control area or country)
> Thanks for your patience and understanding.
> Best Regards
> Transparency Platform Team.

Does this affect us? cc @brunolajoie @alixunderplatz

**Comment by alixunderplatz** [comment]
I totally missed this development o.O

I think this will only affect the electricity price for the zones, no influence on generation mix in the countries whatsoever, as it's split by country already.

It will lead to higher electricity prices in Austria, I assume...

**Comment by brunolajoie** [comment]
It might be interesting to monitor if this improves the quality of data per control area for germany (to allow us to split in 3 areas as per #1216)

**Comment by lorrieq** [comment]
To fix the prices for these three countries on the map and close this issue:

`ENTSOE_DOMAIN_MAPPINGS`: 
- Add key `DE-LU` with value `10Y1001A1001A82H` 

`ENTSOE_PRICE_DOMAIN_OVERRIDE `:
- Remove key for `AT`
- Change value of keys `DE` and `LU` to `ENTSOE_DOMAIN_MAPPINGS['DE-LU']`

If nobody has time beforehand, I can get to this tomorrow evening.

**Comment by lorrieq** [comment]
[Sample output](https://github.com/tmrowco/electricitymap-contrib/files/2438815/de_at_lu_prices.txt)
