### ISSUE TITLE
Repository link is http, not https

### ISSUE THREAD

**Issue by Neamar** [tmrowco/electricitymap-contrib#1608]
This is a very simple issue:

![image](https://user-images.githubusercontent.com/536844/45750154-f967fc00-bc05-11e8-94a4-93be5bc5d757.png)

The link to electricitymap is still using the http:// version. There is a redirect in place already, but with the push from Chrome to have everything under https, it's probably worth updating there too.

Keep up the good work :)

**Comment by corradio** [comment]
Good point. Done :)
