### ISSUE TITLE
Map navigation using arrow keys should not focus search box

### ISSUE THREAD

**Issue by corradio** [tmrowco/electricitymap-contrib#1610]

**Comment by oielbanna** [comment]
Hey. First timer here and I was wondering if I can take on this bug?

**Comment by corradio** [comment]
go ahead! Thanks :)

**Comment by ShahneRodgers** [comment]
I assume something else came up @oielbanna so do you mind if I take this on for Hacktoberfest?

**Comment by oielbanna** [comment]
@ShahneRodgers  yup, sorry about that. All yours!
