### ISSUE TITLE
Refine Italy regions "unknown" fuel source

### ISSUE THREAD

**Issue by brunolajoie** [tmrowco/electricitymap-contrib#1612]
"Unknown" fuel type is pretty important for Italy, especially in the North.
This issue is about investigating, on average over a year, what type of fuel mix "unknown" comprises of, in order to upgrade its related carbon intensity on the electricityMap.
![image](https://user-images.githubusercontent.com/22095643/45890682-db47fa80-bdc3-11e8-9896-b274900367b4.png)

**Comment by tmslaine** [comment]
ENTSO-E transparency platform has a lot of large units in Italian bidding zones listed with fuel type 'Other'.
A data-driven solution to this issue could be something like:
A) Check if 'Other' generation from data view 'Actual generation by Type' can be mimicked by summing generation from units of category 'Other' from data view 'Actual generation by Unit' in the transparency platform
B) If A) is positive, find sources for main fuels of generating units listed as 'Other' in the transparency platform and refine CO2 intensity based on unit-level generation statistics
