### ISSUE TITLE
Investigate non-ENTSOE data source for Portugal Production mix

### ISSUE THREAD

**Issue by brunolajoie** [tmrowco/electricitymap-contrib#1618]
ENTSOE TP data for PT has been returning "N/A" for more than 2 weeks now.
It might be good to start looking at other data sources for production mix, if it exists

**Comment by alixunderplatz** [comment]
I already had a look last week and here is what I could find:

![image](https://user-images.githubusercontent.com/25743609/46367083-09a7be80-c67d-11e8-8ad7-26a0106b1ec9.png)



http://www.mercado.ren.pt/EN/Electr/MarketInfo/Gen/Pages/Actual.aspx

This is the link for downloading the .xls files:
http://www.mercado.ren.pt/UserPagesFase2/Dados_download.aspx?Dia1=2018-10-02&Dia2=2018-10-02&Nome=ProdVerificadaElectr

Should be fairly easy to implement :)

For the electricity wholesale price:
http://www.mercado.ren.pt/EN/Electr/MarketInfo/MarketResults/OMIE/Pages/Prices.aspx
"Daily" is the column to go for on the site (day-ahead auction) or "PRECO_PT" in the .xls-file

Price download link:
http://www.mercado.ren.pt/UserPages/Dados_download.aspx?Dia1=2018-10-02&Dia2=2018-10-02&Nome=PrecoMerc

Load data and forecast for solar, wind and other are also available, if you need it.
Kind regards, Alex

**Comment by Dalius-ENTSO-E** [comment]
Hi, 
Yes, we see that data submissions stopped from REN. REN is informed and I will update you as soon as I will get some news from them.

**Comment by Dalius-ENTSO-E** [comment]
Hi, 
The issue happened with REN communication system on the 27th of September, ~23:00 (not 2-3 weeks). Good news - issue has been resolved and data submissions are renewed. All  missing data should be delivered during today or during tomorrow at the latest. 
Best regards,
Dalius

**Comment by Dalius-ENTSO-E** [comment]
Actual generation per production type data for PT are already uploaded for the current day and previous days.

**Comment by lorrieq** [comment]
Hey guys, are we looking to implement the other source that @alixunderplatz has found or are we ok to stay with the current source and close this issue?
If the former, I can take on the implementation.

**Comment by brunolajoie** [comment]
Thanks @lorrieq, but I'll close this issue as it seems that ENTSOE data is striclty similar (no better granularity directly from REN), and PT seems back on the map. I've implemented a tracker to see if/how often our current parser fails, and will re-open if that value is too low! Thanks for your proposed help!

**Comment by maximecrml** [comment]
> I already had a look last week and here is what I could find:
> 
> ![image](https://user-images.githubusercontent.com/25743609/46367083-09a7be80-c67d-11e8-8ad7-26a0106b1ec9.png)
> 
> http://www.mercado.ren.pt/EN/Electr/MarketInfo/Gen/Pages/Actual.aspx
> 
> This is the link for downloading the .xls files:
> http://www.mercado.ren.pt/UserPagesFase2/Dados_download.aspx?Dia1=2018-10-02&Dia2=2018-10-02&Nome=ProdVerificadaElectr
> 
> Should be fairly easy to implement :)
> 
> For the electricity wholesale price:
> http://www.mercado.ren.pt/EN/Electr/MarketInfo/MarketResults/OMIE/Pages/Prices.aspx
> "Daily" is the column to go for on the site (day-ahead auction) or "PRECO_PT" in the .xls-file
> 
> Price download link:
> http://www.mercado.ren.pt/UserPages/Dados_download.aspx?Dia1=2018-10-02&Dia2=2018-10-02&Nome=PrecoMerc
> 
> Load data and forecast for solar, wind and other are also available, if you need it.
> Kind regards, Alex

Dear Alex, Dear all,

Thanks for your previous sharing, I actually discover your post by looking for the link to download wind and solar forecast on REN (there is no download button as for actual production date, or spot prices). You said last year that data were available: do you know the link to access the data? More exactly, do you know what is the suffix at the end of the link (quoted as SUFFIX)?

http://www.mercado.ren.pt/UserPages/Dados_download.aspx?Dia1=2018-10-02&Dia2=2018-10-02&Nome=SUFFIX

I've tried several ones randomly like "PrevistaProd", "ProdPrevistaElec", etc. without success.
It would be of very great help if you know the answer (or if you have these data nearby and that you could share them) :)

I thank you very much in advance for your answer if you see that (or anyone else having the answer/solution).

Kind regards,
Maxime
