### ISSUE TITLE
Create parser for India as a whole

### ISSUE THREAD

**Issue by alixunderplatz** [tmrowco/electricitymap-contrib#1623]
Hey everyone,
it's been a while since I brought up that source for India's electricity generation in #304:
http://meritindia.in/

We have all categories broken down as needed, except for the "renewables" (mainly wind+solar), which could be simply mapped to "unknown". Thermal category = coal.
Everything else is quite self-explanatory and should be easy to code.
For further details and some sample data, take a look at #304

It should be worth having and collecting these data and not let them fly by anymore, even if it won't be displayed on the map in the end. Maybe there will be a "change data source"-option one day on the map to view it? ^^
This source seems more reliable in comparison to the other Indian per-state sources.

**Comment by brunolajoie** [comment]
Yeah, i see...i'm really hesistant here, cause in a way we loose the pressure to add data state by state ...and its nice to have a bit of wind vs. solar variability, as we see them currently for Gujarat and Kernataka. What do you think @corradio ?

**Comment by alixunderplatz** [comment]
@brunolajoie just to make it clear: it is not my intention to replace the other per-state-data with the new IN-parser. It's just that somebody has to record the data (and if not you guys, who else will :) The visualization of that data is secondary right now).

I see potential here because there is no chance of transparently viewing any electricity data *timeseries* for IN as a whole (1/6 of world's population!).
This could be a good niche/chance for electricitymap. There are just these numbers on http://meritindia.in which update like every 2 minutes, but then they disappear forever. 
There is no website yet where the data is visualized as a graph for a longer period of time (actually none of the IN source websites do that, I think, so the visualization on electricitymap is the no1 timeseries source for the respective Indian states). 

And since meritindia by far is the cleanest looking Indian source of them all, I think there is no hope for any further improvements on that particular website in the near future (breakdown wind+solar, graphs, transmission). (Except somebody contacts the ministry of power of India who is running this website and begs for more precise data.)

India's electricity sector is developing rapidly: Strongly increasing electricity demand, many many proposed renewables projects, coal unfortunately running @ >100 GW constantly and probably doubling to cover the ever growing demand,... there are things to show to the world, that's the point of opening this issue :)

**Comment by brunolajoie** [comment]
I share your opinion, but our current backend cannot be disconnected from the front end. Basically, we store what we display on the electricityMap......tough decision!

**Comment by corradio** [comment]
I'm actually quite sure we can add a IN parser that is run by the backend
and that is not shown on the map.
We just have to make sure no interconnector is configured to avoid messing
up with the flow-tracing models.

**Comment by jarek** [comment]
Could this also be done for USA as a whole? Our regional breakdowns there are imperfect due to their complex geography and reporting and especially lack of exchange data (e.g. seasonal changes to imports to California or my favourite hobby horse, missing 2 GW of coal in Washington state).

**Comment by corradio** [comment]
Yes but the problem is that we don't have a reliable parser for the total
of the US AFAIK.

**Comment by brunolajoie** [comment]
According to this [source](http://terienvis.nic.in/index3.aspx?sslid=5295&subsublinkid=1560&langid=1&mid=1), 

Wind Power capacity installed is 32.5 GW and Solar Power 13.6 GW.
So, at first approximation, "new-renewable" consists of 70% Wind and 30% solar.

This mix could be used in PR #1664 in order to compute the CO2 intensity of the "unknown" category and add it to the text that jsutifies this computed carbon intensity!

**Comment by alixunderplatz** [comment]
Produced energy in 2016 according to [IEA](https://www.iea.org/statistics/?country=INDIA&year=2016&category=Key%20indicators&indicator=ElecGenByFuel&mode=chart&categoryBrowse=false&dataTable=ELECTRICITYANDHEAT&showDataTable=true):
solar: 14 130 GWh | 24%
wind: 44 856 GWh | 76%

Installed capacity 07/2017 according to Bruno's source:
solar: 13.6 GW | 30% 
wind: 32.5 GW | 70%

Figures for installed capacity 12/2017 in India according to [IRENA](http://resourceirena.irena.org/gateway/countrySearch/?countryCode=IND):
solar: 17.64 GW | 35%
wind: 32.84 GW |  65%

I think solar is literally going through the roof in India, while wind is not really expanding that fast anymore:

Installed capacity as of 07/2018 according to [Ministery of New and Renewable Energy](https://mnre.gov.in/physical-progress-achievements):
solar: 23.11 GW | 40% (of which 22 GW are ground-mounted!)
wind: 34.40 GW | 60%

Installed capacity as of 09/2018 according to this [news article](https://mercomindia.com/solar-indias-installed-power-capacity/):

solar: 26.00 GW | 43%
wind: 34.61 GW | 57%

We should make sure to check these shares regularly ;)
Around **26 g/kWh** for "unknown" category consisting of solar and wind using the weighted emission factors.

_____
India's targets for 2022:

https://mnre.gov.in/sites/default/files/uploads/Tentative-State-wise-break-up-of-Renewable-Power-by-2022.pdf
solar: 99.5 GW | 62%
wind: 60 GW | 38 %
