### ISSUE TITLE
FR: key coal has negative value -9.0

### ISSUE THREAD

**Issue by corradio** [tmrowco/electricitymap-contrib#1630]
```
invalid point: {'zoneKey': 'FR', 'datetime': datetime.datetime(2018, 10, 9, 11, 15, tzinfo=tzoffset(None, 7200)), 'production': {'nuclear': 41740.0, 'coal': -9.0, 'gas': 4057.0, 'oil': 188.0, 'wind': 1158.0, 'solar': 2762.0, 'biomass': 861.0, 'hydro': 3366.0}, 'storage': {'hydro': -1024.0}, 'source': 'opendata.reseaux-energies.fr', 'schemaVersion': 1}, reason:FR: key coal has negative value -9.0
```

Probably a good idea to set small negative values to 0

**Comment by jarek** [comment]
ENTSOE parser does this https://github.com/tmrowco/electricitymap-contrib/blob/27d9f7e8f1641b3b536e9bdb1bf9c1a1c1520041/parsers/ENTSOE.py#L887

Probably makes sense to adapt https://github.com/tmrowco/electricitymap-contrib/blob/926ee622abb0c22cd15a26044c6b218183aa7a52/parsers/lib/quality.py#L79

Using 50 MW or less than 0.1% of total production or something
