### ISSUE TITLE
Fix AT->IT-NO exchange on ENTSOE

### ISSUE THREAD

**Issue by lorrieq** [tmrowco/electricitymap-contrib#1634]
Since the DE-AT-LU bidding zone split, the zone codes for this exchange have changed.

My current assumption is that the correct request is to simply use the codes for AT and IT-NO but that ENTSOE haven't sorted this out on their side.

**Comment by systemcatch** [comment]
This can be closed now due to #1636 ?

**Comment by lorrieq** [comment]
Yes, thanks!
