### ISSUE TITLE
Production by source - suggestion

### ISSUE THREAD

**Issue by pierremmm** [tmrowco/electricitymap-contrib#1642]
It’d be great to have graphs on “who is producing how much” of electricity from à to be selected source.
Would show wind production by country in a graph, same for PV production in another graph, coal production, etc

**Comment by jarek** [comment]
Will this really work with our world data being substantially incomplete? A chart of per-country coal production without China... or for that matter a chart of per-country wind production without China?

**Comment by brunolajoie** [comment]
Closing as this does not fit with current electricitymap front end. Thanks for suggesting though!
Non-map based graphs will be part of a "dashboard" view of historical time series based on eMap data  that we are hoping to build in the future
