### ISSUE TITLE
Tooltip says "? $/MWh" when price is 0

### ISSUE THREAD

**Issue by jarek** [tmrowco/electricitymap-contrib#1644]
Money for nothing and wind for free...

![image](https://user-images.githubusercontent.com/47415/47143139-c9734d80-d2c4-11e8-9203-8b5ea7584564.png)

Price is actually 0:

![image](https://user-images.githubusercontent.com/47415/47143182-e0b23b00-d2c4-11e8-89b4-1723b06116c8.png)

Parser returns:

```
...
{'zoneKey': 'CA-ON', 'price': 0.0, 'source': 'ieso.ca', 'datetime': datetime.datetime(2018, 10, 18, 2, 0, tzinfo=tzfile('/usr/share/zoneinfo/Canada/Eastern')), 'currency': 'CAD'},
{'zoneKey': 'CA-ON', 'price': 0.0, 'source': 'ieso.ca', 'datetime': datetime.datetime(2018, 10, 18, 3, 0, tzinfo=tzfile('/usr/share/zoneinfo/Canada/Eastern')), 'currency': 'CAD'}
]
```

https://api.electricitymap.org/v3/history?countryCode=CA-ON returns:

![image](https://user-images.githubusercontent.com/47415/47143370-456d9580-d2c5-11e8-9c1b-ab3d26d02920.png)

So it looks like only the tooltip is wrong.

**Comment by jarek** [comment]
I'm not expert on frontend, but looks like it's here: https://github.com/tmrowco/electricitymap-contrib/blob/8acf8b381dac9643ba19dc10d0ac47ccab8aec63/web/src/main.js#L965

**Comment by corradio** [comment]
ha! Nice reference. I'll fix this now.
