### ISSUE TITLE
Punjab (India) data format has changed

### ISSUE THREAD

**Issue by systemcatch** [tmrowco/electricitymap-contrib#1647]
http://www.punjabsldc.org/pungenrealw.asp?pg=pbGenReal

These changes are resulting in the datetime, solar & thermal regexs no longer matching. @blackleg do you want to correct them?

**Comment by lorrieq** [comment]
At the moment it looks like everything is ok again except there is no solar value provided. We can either:
- remove lines 41-43 in [`IN_PB.py`](https://github.com/tmrowco/electricitymap-contrib/blob/master/parsers/IN_PB.py) and set solar production to 0. 
- keep the regex for solar but catch the exception that occurs if there's no match and set `solar_value` to 0. Not sure if solar is gone for good from that source but this would still record intermittent values.

**Comment by systemcatch** [comment]
I believe the solar generation is now available at http://www.punjabsldc.org/solarppW.asp?pg=solarppW

**Comment by lorrieq** [comment]
Nice!

**Comment by systemcatch** [comment]
@alixunderplatz good spot on the biomass, they'll need to be specifically mapped to type.. We should be able to use the "SUSPECT" status quite easily.

**Comment by lorrieq** [comment]
closed by #1652
