### ISSUE TITLE
Double check Australia data

### ISSUE THREAD

**Issue by brunolajoie** [tmrowco/electricitymap-contrib#1665]
Our current Australian parsers are doing a bottom-up, powerplant by powerplant reconstruction of total power produced in Australia's zones.

I'd like to check if we are not missing any significant part of the mix.

Below is the annual averages below derived from our parsers, over the 2017-09-01 to 2018-09-01 (we don't have one full calendar year yet)

**If anyone have access to official annual statistics and could compare them with our data, it would be very helpfull.** 

Australia yearly averaged parser data, over 2017-09-01 to 2018-09-01 period
AUS-NSW
total prod:  7578.092178468341
total cons:  8291.357400978186
power_production_biomass_avg          0.000000
power_production_coal_avg          6480.123535
power_production_gas_avg            235.815503
power_production_hydro_avg          560.896090
power_production_nuclear_avg          0.000000
power_production_oil_avg              0.352964
power_production_solar_avg          236.639316
power_production_wind_avg           230.012939
power_production_geothermal_avg       0.000000
power_production_unknown_avg               NaN
dtype: float64

AUS-QLD
total prod:  7005.367820185346
total cons:  6440.892967959951
power_production_biomass_avg         13.988632
power_production_coal_avg          6061.043256
power_production_gas_avg            762.733629
power_production_hydro_avg           73.301963
power_production_nuclear_avg          0.000000
power_production_oil_avg              1.229900
power_production_solar_avg          242.275823
power_production_wind_avg             0.000000
power_production_geothermal_avg       0.000000
power_production_unknown_avg               NaN
dtype: float64

AUS-SA
total prod:  1423.662556722825
total cons:  1402.3065002574597
power_production_biomass_avg         0.000000
power_production_coal_avg            0.000000
power_production_gas_avg           794.539167
power_production_hydro_avg           0.000000
power_production_nuclear_avg         0.000000
power_production_oil_avg             1.410829
power_production_solar_avg         152.583262
power_production_wind_avg          570.821099
power_production_geothermal_avg      0.000000
power_production_unknown_avg              NaN
dtype: float64

AUS-TAS
total prod:  1336.5786412750265
total cons:  1251.4574258478533
power_production_biomass_avg          0.000000
power_production_coal_avg             0.000000
power_production_gas_avg             99.469240
power_production_hydro_avg         1120.852511
power_production_nuclear_avg          0.000000
power_production_oil_avg                   NaN
power_production_solar_avg           25.562607
power_production_wind_avg           133.510208
power_production_geothermal_avg       0.000000
power_production_unknown_avg               NaN
dtype: float64

AUS-VIC
total prod:  4970.1384402451395
total cons:  4927.828486028211
power_production_biomass_avg          0.000000
power_production_coal_avg          4167.698394
power_production_gas_avg            290.403089
power_production_hydro_avg           73.008990
power_production_nuclear_avg          0.000000
power_production_oil_avg                   NaN
power_production_solar_avg          216.492448
power_production_wind_avg           421.977322
power_production_geothermal_avg       0.000000
power_production_unknown_avg               NaN
dtype: float64

AUS-WA
total prod:  2046.771756790737
total cons:  2046.771756790737
power_production_biomass_avg               NaN
power_production_coal_avg          1002.120397
power_production_gas_avg            843.247028
power_production_hydro_avg                 NaN
power_production_nuclear_avg               NaN
power_production_oil_avg              0.082894
power_production_solar_avg            3.181348
power_production_wind_avg           182.533145
power_production_geothermal_avg            NaN
power_production_unknown_avg         15.665177
dtype: float64

**Comment by alixunderplatz** [comment]
@brunolajoie for shorter periods, cross-check the live data for the market areas with with https://opennem.org.au
I'm quite sure no significant part should be missing.
