### ISSUE TITLE
Northern Ireland data quality issues

### ISSUE THREAD

**Issue by jarek** [tmrowco/electricitymap-contrib#1668]
Right now we show (timezone of screenshots UTC-5):

![image](https://user-images.githubusercontent.com/47415/48109856-1b015f00-e217-11e8-8e55-eeaa9187d19d.png)

Link from GB (Scotland) is the "Moyle" link - SONI show it a large part of the _supply_:

![image](https://user-images.githubusercontent.com/47415/48109901-52700b80-e217-11e8-991d-e7ea8b675cf0.png)

Our data shows it as export, and at over 100% of the available supply at that:

![image](https://user-images.githubusercontent.com/47415/48109911-6156be00-e217-11e8-838b-7acf8db3aba2.png)

Something is wrong. Is it just Moyle being flipped, or is there more problems? If someone has some time to investigate, it would be super.

**Comment by alixunderplatz** [comment]
ENTSO-E data for the exchanges of Ireland and GB were irregular or NA today, so it really seems like there are some data issues.

![image](https://user-images.githubusercontent.com/25743609/48158242-4d23c700-e2d2-11e8-83b3-60a2b318cd29.png)

![image](https://user-images.githubusercontent.com/25743609/48158400-b4da1200-e2d2-11e8-8d7c-7cd5c1f99e85.png)

**Comment by brunolajoie** [comment]
I've renamed the issue

If I understand well, data fro ENTSOE TP for GB-NIR has been seen incorrect many times:
- GB-NIR reported "production per plant type" seen insufficient, leading to sometimes negative computed consumption (prod - net export) values.

- GN-NIR to GB power exchanges are sometime missing (N/A)

Pinging @Dalius-ENTSO-E for his information

**Comment by jarek** [comment]
Our parser https://github.com/tmrowco/electricitymap-contrib/blob/master/parsers/GB_NIR.py uses SONI data, not ENTSOE, for both exchanges and production. Per https://github.com/tmrowco/electricitymap-contrib/blob/master/config/zones.json#L1446 ENTSOE is used for consumption, price, and forecasts.

**Comment by brunolajoie** [comment]
Ah, apology I did not read carefully your issue! It might well be that we coded the NIR import in reverse. Did you check absolute values in your previous screenshot to see if they match?

**Comment by brunolajoie** [comment]
Hey @systemcatch, looking at your code [here](https://github.com/tmrowco/electricitymap-contrib/blob/86781b197595764d4cbc3bf00501db7ff9328272/parsers/GB_NIR.py#L177), if have two questions:

- Why do we only use 'Total_Moyle_Load_MW' and not the sum of all 4 columns on the CSV?
![image](https://user-images.githubusercontent.com/22095643/48206055-d0462b00-e36d-11e8-86a9-4ba181d590f5.png)


- I believe we should put a minus sign because we seem to report exchanges in the wrong way

**Comment by brunolajoie** [comment]
Looking pretty good now (17:56 Paris Time)

![image](https://user-images.githubusercontent.com/22095643/48362545-2be12300-e6a4-11e8-860e-aa817718fd12.png)

![image](https://user-images.githubusercontent.com/22095643/48362559-34d1f480-e6a4-11e8-9f25-856207f45c89.png)
