### ISSUE TITLE
Tooltip values don't change for import/export bars

### ISSUE THREAD

**Issue by alixunderplatz** [tmrowco/electricitymap-contrib#1671]
Minor bug observed on android and PC. For reproduction:
- Select a country
- select one of the import/export bars below the generation bars
- use the slider to select different times
-> the values in the tooltip won't change at all (opposed to the values for generation type bars)

**Comment by corradio** [comment]
Indeed I can reproduce

**Comment by corradio** [comment]
Fixed!

**Comment by brunolajoie** [comment]
You rock!
The impossible-to-see bug of the year!
