### ISSUE TITLE
Bar chart X&Y axis title/units missing for zones with long names

### ISSUE THREAD

**Issue by brunolajoie** [tmrowco/electricitymap-contrib#1682]
This zone for instance displays correctly
![image](https://user-images.githubusercontent.com/22095643/48842555-dd631100-ed94-11e8-83ae-65e5a7b42170.png)

All US zone, like this one, displays missing X axis unis "GW" and Y axis title "by source" 
![image](https://user-images.githubusercontent.com/22095643/48842577-e653e280-ed94-11e8-8e51-f59d271f8275.png)

**Comment by corradio** [comment]
It's actually not US zones but all zones where the name takes two lines right?

**Comment by jarek** [comment]
Right:

![image](https://user-images.githubusercontent.com/47415/48848352-b515eb00-ed71-11e8-9aa2-6a4723dc7751.png)

**Comment by corradio** [comment]
@ovbm are you able to help on that one?

**Comment by jarek** [comment]
As seen in #1704, this can also be caused by longer labels for carbon intensity fields:

![image](https://user-images.githubusercontent.com/47415/49699049-13c4cc80-fb9a-11e8-99a6-0d082e998db7.png)
