### ISSUE TITLE
CL-SIC real-time data missing

### ISSUE THREAD

**Issue by brunolajoie** [tmrowco/electricitymap-contrib#1683]
Data for SL-SIC seems to be irregular, being present about 60% of the time only over the last 6 months (see picture below, since April 2018)
![image](https://user-images.githubusercontent.com/22095643/48847496-fa521100-eda1-11e8-8755-7829cfe6c8fe.png)

We need

1. To understand if its related to our parser not handling response correctly, or if its due to the source of data that breaks downs regularily. Calling parser returns
```
min returned datetime: 2018-11-06 01:00:00-03:00
max returned datetime: 2018-11-07T03:00:00+00:00 UTC  :( >2h from now !!!
```
2. To allow historical refetch to fix the missing datapoints. @systemcatch, You have kindly written a parser to fetch SL-SING historical data (#1394). Would you know if its possible to do the same with SL-SIC?

linked to #655 #1108 #1394

**Comment by systemcatch** [comment]
Hey Bruno, I've taken a look at the parser response. All of the data comes from https://sic.coordinador.cl/informes-y-documentos/fichas/operacion-real/

1. The parser is working fine, data seems to be regularly delayed by a number of days (this is the same as when I wrote this parser). Never saw it 2 weeks behind though.

2. Looking at the parser it would be simple to modify to enable backfilling with historical data.

**Comment by brunolajoie** [comment]
All right, so it's good news if I understand well, data is there, but just sometimes with more than 24h delay, therefore not visible on the electricityMap history graphs. 

Historical data seems to dates back several years. So, I guess we just need to add a fetch_history feature - cool! We'll just have to make it robust to potential change in power plant fleets

**Comment by systemcatch** [comment]
Yes it has always been a delayed data source, we've never found a real time one.

I can add a target_datetime parameter to the fetch production function.

**Comment by brunolajoie** [comment]
Very interesting. I'm sending them an email right now to decide what to do next. 

For now, lets keep it split in two regions (because we have the gas vs. coal breakdown on the sub zones, while here it's only solar/Wind vs. other) and add historical datasets for both.

We'll merge both regions when we'll get a better breakdown.
Meanwhile: have you seen a way to get power exchanges between SIC and SING from our current sources?

**Comment by brunolajoie** [comment]
Also, how well interconnected are they, in terms of %of load being exchanged?

**Comment by systemcatch** [comment]
@alixunderplatz I got creative with Wireshark and was able to glean where the app is getting it's data from.

http://panelapp.coordinadorelectrico.cl/api/chart/demanda
http://panelapp.coordinadorelectrico.cl/api/chart/ernc
http://panelapp.coordinadorelectrico.cl/api/chart/produccion

**Comment by alixunderplatz** [comment]
@systemcatch great you could find these urls!
@brunolajoie afaik, the exchange of sic and sing is not really included anywhere except for that one source I mentioned somewhere in the main issue. let's see what they'll reply to your mail. Chile can be very proud of the upcoming achievements (many renewable GWs under development), I think they'd agree to share their live data with the world ;)

**Comment by brunolajoie** [comment]
I've got this kind answer from SIC
>Dear Bruno,  Along with thank you your kindly congratulation, we let you know that currently we do not have real time data in our web site, nevertheless you can access to our public information system where we held all the statistics of the system, in particular the MW production is updated once a day with the total production of the previous day, you can find that information in the following link: https://www.coordinador.cl/sistema-informacion-publica/portal-de-operaciones/operacion-real/generacion-real-de-las-centrales/
We are working in some projects to let available for our customers the real time data coming from our scada system, we hope to have some news during the next few months so please be aware of our website news.
Kind Regards,

So, trying to summarize:
- Right now, the only real-time (<1h) data we have found is total generation, wind, and PV.
We don't have yet the breakdown between thermal vs. hydro in real-time, which prevents us from using these real-time data for the eMap. Am I missing somehting?

- In few months, we should have better real-time data according to the above mentioned email

- Until then, I believe should keep using the current parser, add a fetch_history option, and fetch history to train nowcasts that can replace missing real-time data

**Comment by brunolajoie** [comment]
Current parser fetch xlsx from 
https://sic.coordinador.cl/informes-y-documentos/fichas/operacion-real/
which has stopped updating new xls files since November 6th.

It seems to have been deprecated and replaced by  
https://www.coordinador.cl/sistema-informacion-publica/portal-de-operaciones/operacion-real/generacion-real-de-las-centrales/

cc @systemcatch

**Comment by systemcatch** [comment]
Hey @brunolajoie I'm working on updating the parser to fetch past data. It'd be annoying if they've stopped producing xls files as that would require a whole new parser.

**Comment by brunolajoie** [comment]
@systemcatch Actually, I found the most recent excels
https://sic.coordinador.cl/wp-content/uploads/estadisticas/operdiar/18/OP181127.xls
It's just the a html tag that is not updated!
No need to write a whole new parser

**Comment by systemcatch** [comment]
The source for this parser no longer works, I'm writing a new historical parser for the whole of Chile in #1939
