### ISSUE TITLE
Use yearly average carbon intensity for hydro discharge emission factor

### ISSUE THREAD

**Issue by brunolajoie** [tmrowco/electricitymap-contrib#1690]
Potentially, using a round-trip efficiency loss factor.

Fallback on "world-average carbon intensity" factor if country-specific yearly country average is unknown.

Step 1:  Input annual average emission factor for each eMap zones when possible, in `defaultExportCo2eqFootprint` (using eMap historical database)
Step 2:  code the link between hydro_discharge CO2 intensity factor and `defaultExportCo2eqFoorprint` values
Step 3: add a world average default fallback

**Comment by corradio** [comment]
Could potentially be done together with https://github.com/tmrowco/electricitymap-contrib/issues/1576
