### ISSUE TITLE
Statnett choppy exchange values

### ISSUE THREAD

**Issue by brunolajoie** [tmrowco/electricitymap-contrib#1701]
SE is currently greyed on the map.

Testing parser returns nothing
![image](https://user-images.githubusercontent.com/22095643/49368454-07022d80-f6ef-11e8-8059-19a260d3bbc3.png)

**Comment by corradio** [comment]
The kibana error you're pointing at is the exchange data, so it's not related. However it's weird indeed.

**Comment by brunolajoie** [comment]
Could not find any other kibana issue with SE!

**Comment by corradio** [comment]
![image](https://user-images.githubusercontent.com/1655848/49368661-914a9180-f6ef-11e8-8989-6793444a3c84.png)

The ENTSOE parser is not used for SE. SE.py is used (svk.se)

**Comment by brunolajoie** [comment]
Ah correct! sry! indeed svk.se is down. Let's wait 
![image](https://user-images.githubusercontent.com/22095643/49368784-ef777480-f6ef-11e8-9740-c531a0ac9516.png)

**Comment by jarek** [comment]
Exchanges and some production appear to be back in SVK data, but hydro production is currently missing

**Comment by jarek** [comment]
Hydro production still missing. Exchanges with Lithuania and Poland are reported as 0 in past 24 hours, not sure if that's accurate or missing data.

**Comment by jarek** [comment]
Hydro production still missing. Do we have a contact at SVK we can ask for it? Or switch back to ENTSOE for a while? (Initially switched in #872)

**Comment by jarek** [comment]
Sweden is currently offline.

Exchange data also appears unreliable. The green band are Finland's imports from Sweden:

![image](https://user-images.githubusercontent.com/47415/49650475-45069680-f9fa-11e8-9bf8-6e4d3d633508.png)

**Comment by systemcatch** [comment]
Looks like it's back online again, Finland's imports still look choppy though.
![screenshot from 2018-12-07 20-52-41](https://user-images.githubusercontent.com/30196510/49672319-98acca80-fa62-11e8-8997-03dc654ba056.png)

**Comment by jarek** [comment]
Still problematic today. Also apparently some of the exchanges are (currently?) reported the wrong way, see #1707

![image](https://user-images.githubusercontent.com/47415/49878589-f12eef80-fdf5-11e8-8d50-53bac49aa1f7.png)

**Comment by jarek** [comment]
![image](https://user-images.githubusercontent.com/47415/50125409-bf26ee80-0236-11e9-910a-c4a69d38742a.png)

**Comment by jarek** [comment]
This has been obsoleted/resolved by switching away from Stattnet data in #1739
