### ISSUE TITLE
Add new interconnector "Nemo Link" between GB <-> Belgium

### ISSUE THREAD

**Issue by alixunderplatz** [tmrowco/electricitymap-contrib#1703]
Nemo Link has been inaugurated this week! :)
Capacity is 1.000 MW in both directions.
https://eandt.theiet.org/content/articles/2018/12/uk-belgium-nemo-link-electricity-interconnector-ready-for-use/

The new interconnector was previously mentioned in #1662 #1663, but not yet implemented in exchanges.json.

Some sample data from ENTSO-E (with only small amounts transferred between the zones for testing, I assume):

![image](https://user-images.githubusercontent.com/25743609/49684134-de53ac80-facf-11e8-824d-22284f295e40.png)

:)

**Comment by corradio** [comment]
say no more!
