### ISSUE TITLE
List of energy sources is not fully shown in Firefox

### ISSUE THREAD

**Issue by freefess** [tmrowco/electricitymap-contrib#1704]
It works with CO2 emission also.
![issue](https://user-images.githubusercontent.com/4992394/49695112-c1d67380-fba6-11e8-86aa-f5c1be8f98d8.JPG)

**Comment by jarek** [comment]
It's because the label text for carbon intensity is too long:

![image](https://user-images.githubusercontent.com/47415/49699049-13c4cc80-fb9a-11e8-99a6-0d082e998db7.png)

Actually that's the same issue as #1682. I'll close this in favour of that one. Thanks for noticing and reporting.
