### ISSUE TITLE
DK1-DK2 seems to go in the wrong direction

### ISSUE THREAD

**Issue by nikobh** [tmrowco/electricitymap-contrib#1707]
Looking at the link between West Denmark and East Denmark it seems that the direction of energy flow is opposite of what is displayed on https://energinet.dk/
It has been like that for a week or so.

**Comment by nikobh** [comment]
The same seems to be the case between East Denmark and Sweden.

**Comment by corradio** [comment]
Indeed it's confirmed:
on energinet it shows DK1 -> DK2, as well as on ENTSOE:
![image](https://user-images.githubusercontent.com/1655848/49873422-19c9e000-fe1c-11e8-9f0c-bc5ce297466d.png)

Statnett however (from which we pull the data) are reporting it wrong:
![image](https://user-images.githubusercontent.com/1655848/49873610-9a88dc00-fe1c-11e8-9012-36a991302917.png)
The other exchanges from statnett seem good.
Can someone reach out to them?

**Comment by jarek** [comment]
See also #1701 for other problems with Statnett exchange data

**Comment by nikobh** [comment]
It looks like we are back on track with DK1 - DK2. But the direction is still wrong between DK2 and Sweden

**Comment by brunolajoie** [comment]
Do you have any clue about historical values as well? Have they been corrected on ENTSOE TP, or are they still wrong? (I hope they are corrected !!)

**Comment by corradio** [comment]
Seems like DK - SE also are in the wrong direction :o

**Comment by brunolajoie** [comment]
Confirmed discrepancy on DK2->SE4 export direction
- Energinet.dk and ENTSOE agree
- Statnett reports opposite

eMap currently sources its exchange from Statnett

I suggest to change back to ENTSOE (easy we already have the parser, but houlry granularity only), and contact Statnett to inform them.

Or we code a new parser using energinet data directly (probably the most robust solution on the long run, as they are primary data owner)

**Comment by corradio** [comment]
Energinet publishes this dataset:
https://www.energidataservice.dk/dataset/transmissionlines/resource_extract/d22ec918-fa2e-4aa0-a6dd-0658500b876e

But it's hourly so might as well use ENTSOE if we want to revert.
Just to be sure, did you check on the Statnett website or in our parser?
There could be an implementation problem in our parser.

**Comment by brunolajoie** [comment]
It seems to be a stattnett problem!

**Comment by brunolajoie** [comment]
if anyone has a contact at [Stattnet](https://www.statnett.no/en/for-stakeholders-in-the-power-industry/data-from-the-power-system/), do not hesitate to inform them. Thank you
