### ISSUE TITLE
UK capacity outdated

### ISSUE THREAD

**Issue by brunolajoie** [tmrowco/electricitymap-contrib#1708]
email recieved:
>For the Uk for Solar why is the capacity stated as 8.56GW when it is :
The U.K.’s installed solar PV capacity has reached 12.8 GW across 939,872 installations as of the end of January 2018, according to the latest provisional statistics released by the U.K. Department for Business, Energy and Industrial Strategy (BEIS).

**Comment by systemcatch** [comment]
I guess https://www.gov.uk/government/statistics/solar-photovoltaics-deployment is the source they are referring to. We currently use ENTSOE which has now been updated to 12.4GW installed.

Maybe we could create a method to update capacities automatically from ENTSOE's api?

**Comment by brunolajoie** [comment]
Yes, that could make sense to write such script, which could be appied for all countries where we currently use ENTSOE as a datasource for capacity installed. There are few exceptions, as per README.md, where we don't use ENTSOE in Europe, which would have to be dealt with on a case by case.
