### ISSUE TITLE
NO zones are most often "grey" on live electricityMap

### ISSUE THREAD

**Issue by brunolajoie** [tmrowco/electricitymap-contrib#1714]
How is it that NO zones are most often "greyed" on live electricityMap while historical data is present with no gaps in our historical database?

Is NO parser providing good data, but with a delay? Could we try to fix that?

Details below

1. Most of the time I check, NO bidding zones are greyed out
![image](https://user-images.githubusercontent.com/22095643/50150893-a9114080-02bf-11e9-8e47-cb816c1d770b.png)

2....due to apparently missing hydro generation data
![image](https://user-images.githubusercontent.com/22095643/50151157-58e6ae00-02c0-11e9-92f1-81601a3f7dc4.png)

3. While at the same time, having no  gap in our historical dataset
![image](https://user-images.githubusercontent.com/22095643/50150874-9ac32480-02bf-11e9-853e-9052bd4b8255.png)

**Comment by corradio** [comment]
It's probably due to a delay from ENTSOE? Probably the hydro part is only
filled with some delay.

**Comment by jarek** [comment]
I haven't seen this being an issue recently, maybe the operator has improved their data submission timeliness?

**Comment by corradio** [comment]
Seems like that indeed. Closing
