### ISSUE TITLE
Rewrite ENTE.py to parse all Central American exchanges

### ISSUE THREAD

**Issue by alixunderplatz** [tmrowco/electricitymap-contrib#1719]
The way the recent [ENTE.py parser](https://github.com/tmrowco/electricitymap-contrib/blob/master/parsers/ENTE.py) calculates the exchanges is really complicated and not complete for all exchanges due to mathematical uncertainties.
From what I observed, there is an easier way to do this, taking the same values from the .csv plus an extra little detail! 😃

Here is the map:
http://www.enteoperador.org/newsite/flash/SER.html
![image](https://user-images.githubusercontent.com/25743609/50530807-8b36ad80-0b01-11e9-8f66-0b9122c973c2.png)

Here is the according exchange data from the .csv:
http://www.enteoperador.org/newsite/flash/data.csv

MX<->GU | MXGUN | GU<->ES | GUESN | ES<->HO | ESHON | HO<->NI | HONIN | NI<->CR | NICRN | CR<->PA | CRPAN
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
51,8 | 0 | 207,8 | 1 | 31,3 | 1 | 31 | 1 | 33,5 | 1 | 6,4 | 1

There always is a "logical value" column right behind the exchange value indicating either "1" or "0". This will flip the arrow in the network image, so it indicates the correct direction of flow.
This could help to make the parser shorter and to implement the currently missing exchange flows! :)

______________

Here is the proof for the exchange MX<->GU and CR<->PA, which changed directions:

![image](https://user-images.githubusercontent.com/25743609/50531023-4eb88100-0b04-11e9-9aae-df085772b5bd.png)

.csv data (new):

flow | MX<->GU | MXGUN | GU<->ES | GUESN | ES<->HO | ESHON | HO<->NI | HONIN | NI<->CR | NICRN | CR<->PA | CRPAN
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
old | 51,8 | 0 | 207,8 | 1 | 31,3 | 1 | 31 | 1 | 33,5 | 1 | 6,4 | 1
new | 13,1 | 1 | 242,5 | 1 | 3,6 | 1 | 11,1 | 2 | 6,9 | 1 | 1,5 | 0

Mx<->GU is now 1 and CR<->PA is 0 and the arrow direction has changed.
_____________

Note there is a "bug" 🐛 for the exchange HO<->NI, where the direction is indicated as "2" and the arrow disappears on that second map. I assume it is an issue on the data provider side and "1" means "0" and "2" means "1". 
I think it is not problematic to skip this exchange for the beginning, since we dont have any data for Honduras (besides total load and generation, if you'd like to implement this for now! ;) ).
______________

Based on the first image, all indicated flow directions are "1". Just MX<-GU has 0 there.
Not sure which is the correct arrow direction for HO<->NI (maybe it's flipped).

There probably needs to be something like this in the code to obtain the directions which we can use to determine the direction of all flows:

```
def flowdirection(df):
    """
    Gets values for each flow direction.
    Returns a dictionary.
    """

    directions = {'GT->MX': df.iloc[0]['MXGUN'],
                        'GT->SV': df.iloc[0]['GUESN'],
                        'GT->HN': df.iloc[0]['GUHON'],
                        'HN->SV': df.iloc[0]['ESHON'],
                        'HN->NI': df.iloc[0]['HONIN'],
                        'CR->NI': df.iloc[0]['NICRN'],
                        'CR->PA': df.iloc[0]['CRPAN']}

    return directions
```
__________

Any thoughts on the new assumption for the flow direction? Was the "direction indicator" in the .csv discussed in the past and have I missed it?

@systemcatch Do you want to rewrite the parser?

**Comment by systemcatch** [comment]
Hey @alixunderplatz, looks like you've solved the mystery of how the ENTE map gets flow arrow directions! I think when I looked at this ages ago the logical values weren't changing which led me to discount them, but clearly they are determining direction.

I can rewrite the parser easily based on this information.

**Comment by alixunderplatz** [comment]
@systemcatch that would be great! :)
Yeah I was lucky enough to observe these numbers changing at the right time ;)

One more info on the Honduras<->Nicaragua interconnection for you:
I saw 'HONIN' have the direction values:
- 1 with arrow pointing towards HN
- 2 without any arrow
and today I just saw
- 0 (arrow pointing towards NI)

![image](https://user-images.githubusercontent.com/25743609/50540950-f03ee180-0b9b-11e9-8de2-8d42c941e5db.png)
