### ISSUE TITLE
NO capacity outdated

### ISSUE THREAD

**Issue by Gazer75** [tmrowco/electricitymap-contrib#1729]
No idea where the data comes from, but ENSTOE is not to be trusted on this.

At any point you can get a csv file from here for hydro:
https://www.nve.no/energiforsyning-og-konsesjon/vannkraft/vannkraftdatabase
This can then be filtered to get the pure pumps out (Pumpe).
Can also filter for each of the five areas (Elspotområde).

File for wind can be found at:
https://www.nve.no/energiforsyning-og-konsesjon/vindkraft/utbygde-vindkraftverk/

As of today I summed ~32440MW total hydro power capacity in Norway.
NO1 = ~3592MW
NO2 = ~11317MW
NO3 = ~4571MW
NO4 = ~5088MW
NO5 = ~7873MW

Total wind capacity is ~1664MW, but the table do not show what area each windfarm is in.

**Comment by jarek** [comment]
Note that the website currently does not display capacities in Norway because regional capacities were not added so far after the split into the five regions.

**Comment by Gazer75** [comment]
Those regions have existed for at least 16 years. I found the history of the reservoir status back to 2002 divided by these areas.

Some strange values can be found at ENTSOE site here:
https://transparency.entsoe.eu/generation/r2/installedGenerationCapacityAggregation/show

Only explanation is grid limitation or that a large portion of the generators are offline for maintenance. 

Either way the values are there.

**Comment by Gazer75** [comment]
Closing this issue for now then. I'll try to update capacities later when more of the wind farms under construction start producing later this year. NVE expects almost 2000MW worth of wind to be finished in 2019 according to the 2018 3rd quarter report.
