### ISSUE TITLE
WIP: Sweden's electricity prices

### ISSUE THREAD

**Issue by consideRatio** [tmrowco/electricitymap-contrib#1730]
# About
I'd like to learn about this project in order to potentially contribute to it. This project has huge impact to the climate change discussion and I'd be so happy to have supported it in some way. But first things first, I need to learn more about it and avoid spending your time in vain. I hope to learn while working with a concrete goal. 

@corradio @brunolajoie could you give me some feedback on the following:
1. What else would you say is useful to learn about this project?
2. Is my goal of relevance to the project? Should I for example abandon it, focus on another goal first, adjust it somehow, or go with it?

# Goal
I'd like to add a data source to provide the electricity prices in Sweden, if that is alright?

# My learning tasks
- [ ] Inspect the codebase and learn the tech involved
- [ ] Read through all documentation
- [ ] Read [this text](https://www.svk.se/drift-av-stamnatet/drift-och-marknad/) about the Swedish grid

# Question reference
I write them down some thoughts and questions for reference, I should focus on getting a solid understanding of this project first and then it makes better sense for you to trouble yourself with helping me further.

- There are four electric regions in Sweden, but electricitymap classifies them as one single currently. Norway is split in parts though. What are the drawbacks and benefits of splitting the country in zones? Is this appreciated or not? One may say it adds to the complexity. On the other hand, one could piece together Sweden as a whole in a presentation mode with ease I think, by using a simple resolution switch.
- Should I perhaps instead focus on add resolution to Sweden's electricity generation to match the four zones?

# Technical research
[This webpage](https://www.vattenfall.se/elavtal/elpriser/rorligt-elpris/timpris-pa-elborsen/) displays a forcast of the electricityprices. I identified an API that the webpage relies on.

There are four electrical zones, and these are four different request to get the information about the four zones electrical prices.

**Region**|**API URL**
-|-
SE1 (Luleå) / Norra Sverige|https://www.vattenfall.se/api/price/spot/pricearea/2019-01-07/2019-01-07/SN1
SE2 (Sundsvall) / Norra mellansverige|https://www.vattenfall.se/api/price/spot/pricearea/2019-01-07/2019-01-07/SN2
SE3 (Stockholm) / Södra mellansverige|https://www.vattenfall.se/api/price/spot/pricearea/2019-01-07/2019-01-07/SN3
SE4 (Malmö) / Södra Sverige|https://www.vattenfall.se/api/price/spot/pricearea/2019-01-07/2019-01-07/SN4

These zones are also geographically shown at this page: http://natomraden.se/ and at this page: https://elomraden.se/om

**Response example**
```json
[
  {
    "TimeStamp": "2019-01-07T00:00:00",
    "TimeStampDay": "2019-01-07",
    "TimeStampHour": "00:00",
    "Value": 49.67,
    "PriceArea": "SN1",
    "Unit": "öre/kWh"
  },
  ...
]
```

# About Sweden's grid

![image](https://user-images.githubusercontent.com/3837114/50791242-8f14bd80-12c1-11e9-9562-02aa0b8bda0d.png)

# My tech background

I've done some hobby projects with React, tried react-native, taken ML courses and is working Kubernetes / Helm / clouds. If you would need help with anything in the Kubernetes domain I'd be happy to help you out.

**Comment by jarek** [comment]
Please see #1397 for notes about splitting Sweden. The status currently seems to be on hold as complete generation split by fuel is not available in real time for the regions. As the different regions have different prices, lack of region split is likely why the prices aren't included right now.

**Comment by consideRatio** [comment]
@jarek ah thanks for the guidance!

**Comment by brunolajoie** [comment]
Thanks a lot @consideRatio for your support!

We would like to split Sweden into 4 bidding zone indeed. If you were to find a reliable real-time production mix per main power plant type for each SE bidding zone, let us know! Our comments in #1397 might be outdated, who knows! I haven't checked for few months if things have improved! Or maybe there are other sources of data existing that we're missing.

Best

**Comment by systemcatch** [comment]
@consideRatio any help is appreciated. There's lots of open issues that need fixing so as long as an issue isn't assigned to anyone feel free to start working on it.
