### ISSUE TITLE
Emissions from oil shale

### ISSUE THREAD

**Issue by 4nd3r** [tmrowco/electricitymap-contrib#1737]
Estonia produces electricity from oil shale.

This is a solid fossil fuel that is in the same statistical group with coal.

It would be correct to dislpay the emissions from oil shale under "coal" (solid) not "oil" (liquid).

Source: https://ec.europa.eu/eurostat/statistics-explained/index.php?title=Glossary:Fossil_fuel&oldid=120658

**Comment by brunolajoie** [comment]
Thanks for notifying. Your source seems uncontroversial, I'll make the change!
