### ISSUE TITLE
ENTSOE parser cleanup

### ISSUE THREAD

**Issue by corradio** [tmrowco/electricitymap-contrib#1742]
EE oil shale fix by @brunolajoie didn't work because the mapping
https://github.com/tmrowco/electricitymap-contrib/blob/master/parsers/ENTSOE.py#L52-L64

is not used.

We should make sure those lines use the mapping directly, instead of using functions that do not depend on the mapping:

https://github.com/tmrowco/electricitymap-contrib/blob/master/parsers/ENTSOE.py#L863-L875

Good catch @alixunderplatz !

**Comment by brunolajoie** [comment]
- EE oil shale quick fix in PR #1743.
- Refacto as suggested above is still needed
