### ISSUE TITLE
Hydro storage reserves

### ISSUE THREAD

**Issue by sebastien-bartoli** [tmrowco/electricitymap-contrib#1753]
I have an idea for contribution, and want to add hydro storage capacity on the left panel for each country. 

Source of the data : 
- https://www.services-rte.com/fr/visualisez-les-donnees-publiees-par-rte/stock-hydraulique.html (visualisation and max capacity)
- https://data.rte-france.com/catalog/-/api/user_guide/226953#_Toc506996014 (actual API endpoint with current storage)

My idea is to add on the left panel, under the electricity price graph, a visualisation of the current water reserve in storage versus maximum. Those data are expressed in GWh, as opposed to GW for the actual generation, so it makes sense to segregate this viz from the consumption graph by source. 

However I have several interrogations and would like your feedback, especially on the time scale appropriate to display this. The capacity is updated once a week by RTE, so in my mind, it would make sense to show a bit of evolution, and go back at least one month, maybe 2-3 to have an idea as if the water reserves are increasing or decreasing. The API also allows to get data from past years, so it would make sense, in order to get an idea of the possible future, to show expected variance in the next couple months. 

What do you think about the placement ? About how to show this data ?

Thanks

**Comment by brunolajoie** [comment]
Hello Sebastien, thanks a lot for that idea.

Unfortunately, I haven't seen such data available for a lot of regions beyond France. 
it seems a bit early to add to the electricityMap, but I hope in the future when more data is openly accessible we could add such information to the system. It will require a change in the backend though.

If we were to do so, we could simply start by just having it as text in the tooltip when hovering over "hydro storage".  That would remove the need to have 3 months-back.

Closing until more country have this data available to justify the upgrade
