### ISSUE TITLE
Great Britain: wind power being under-reported

### ISSUE THREAD

**Issue by bmckinlay** [tmrowco/electricitymap-contrib#1755]
Both wind and total generation for Great Britain seems to be consistently under-reported.

Comparing wind generation reported by electricitymap.org to other sources (such as gridwatch.co.uk) at 20:00 GMT on Jan 28th, electricitymap.org reports 1.29GW wind of 43.5GW total, while gridwatch.co.uk reports 5.55GW wind of 45.05GW total. 

This disparity has been consistent for the past week or so and seems particularly large, particularly for the wind generation.

Is electricitymap.org making an error with the way it calculates wind generation for Great Britain?

**Comment by jarek** [comment]
Thanks for noticing and reporting. Please see #1754 for more details on this issue.
