### ISSUE TITLE
electricityMap app not available in F-Droid Android software repository

### ISSUE THREAD

**Issue by strassburger** [tmrowco/electricitymap-contrib#1759]
Can not find  electricityMap APP in F-Droid.
I try to work without google app store.
Is it a problem to put it there?

**Comment by jarek** [comment]
Hm, mobile Firefox does show the "add to home screen" button ("house with plus inside" icon in address bar) but this is just a nice shortcut icon on your desktop that launches a whole Firefox with electricitymap.org loading in it from scratch. I don't know if installing the app caches more things or something.

This is the button:

![image](https://user-images.githubusercontent.com/47415/52182267-88e30580-27c9-11e9-93db-fe0b76df3df9.png)

The icon on home screen then looks like this:

![image](https://user-images.githubusercontent.com/47415/52182249-589b6700-27c9-11e9-93d0-c9d09f410f4e.png)

**Comment by strassburger** [comment]
@jarek,
thanks for your effort.
I understand that the result is like a desktop icon with a link to open just the website of electricitymap with firefox.
Nearly like i use it now with a firefox bookmark.
Think an app is some more or isnt it?

**Comment by jarek** [comment]
I'm actually not sure what the app is, as I don't have it installed (nor do I have the Play Store), maybe someone else can confirm

**Comment by corradio** [comment]
The app is a thin wrapper around the website that makes it start faster (because it doesn't have to load the web application itself).
@strassburger else you can always find the apk on the internet (I think there are some apk scrappers somewhere) and install it?
I'm not sure I see a simple way to add an app to F-Droid else.

**Comment by strassburger** [comment]
@corradio 
As long there is no easy way to put a app of electricitymap to the F-Droid reposito:
I can live with just al firefox bookmark.
