### ISSUE TITLE
Coal emissions too low for Germany

### ISSUE THREAD

**Issue by erdmark** [tmrowco/electricitymap-contrib#1765]
On your site coal has a carbon intensity of 820g/kWh in Germany.
I think it is a bit higher. In Germany there are two types of coal burned, normal hard coal with ~870 and lignite coal with ~1130g.
The data is from energy-charts.de for 2016. I divided CO2 emissions by generated power over the whole year. The weighted average of both types 1020, much higher than what electricitymap calculates with.
Climate impact could be even worse, because this is only co2 without methane emissions.
You can see the calculation, data source and data from 2007 to 2016 in the attachment.

[CO2GrammKohle.xlsx](https://github.com/tmrowco/electricitymap-contrib/files/2849261/CO2GrammKohle.xlsx)

**Comment by jarek** [comment]
Please see issue #738 for ongoing efforts to systematically get more accurate emission intensities for several countries

**Comment by jarek** [comment]
Please follow-up in issue #738 - I will close this issue to clean up duplicates.
