### ISSUE TITLE
UK www.bmreports.com

### ISSUE THREAD

**Issue by GedEssex** [tmrowco/electricitymap-contrib#1766]
Why does...
https://www.bmreports.com/bmrs/?q=eds/main
disagree so much with...
https://www.electricitymap.org/?wind=false&solar=false&page=country&remote=true&countryCode=GB
for the UK?

**Comment by jarek** [comment]
Hello, apparently this is because of reporting problems somewhere in BM or National Grid. We're trying to workaround it by using a different report. Please see issue #1754 for details.
