### ISSUE TITLE
Taiwan real-time data has stopped working

### ISSUE THREAD

**Issue by brunolajoie** [tmrowco/electricitymap-contrib#1772]
Taiwain seems to have been offline recently
It used to work correctly, something may have changed in the data source?

Kibana error description [here](https://kibana.electricitymap.org/app/kibana#/discover/10af54f0-0c4a-11e9-85c1-1d63df8c862c?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:now-24h,mode:quick,to:now))&_a=(columns:!(message,extra.key,level),filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!f,index:'96f67170-0c49-11e9-85c1-1d63df8c862c',key:level,negate:!f,params:(query:ERROR,type:phrase),type:phrase,value:ERROR),query:(match:(level:(query:ERROR,type:phrase)))),('$state':(store:appState),meta:(alias:!n,disabled:!f,index:'96f67170-0c49-11e9-85c1-1d63df8c862c',key:'@timestamp',negate:!f,params:(query:'2019-02-13T09:56:26.971Z',type:phrase),type:phrase,value:'February%2013th%202019,%2010:56:26.971'),query:(match:('@timestamp':(query:'2019-02-13T09:56:26.971Z',type:phrase))))),index:'96f67170-0c49-11e9-85c1-1d63df8c862c',interval:auto,query:(language:lucene,query:''),sort:!('@timestamp',asc)))

**Comment by systemcatch** [comment]
This is the error that is being raised.
```shell
Traceback (most recent call last):
  File "/home/feeder/lib/fetch_data.py", line 181, in launch_parsers
    objs = res.get(timeout)
  File "/usr/local/lib/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value
  File "/usr/local/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/home/feeder/lib/fetch_data.py", line 179, in <lambda>
    **parser_kwargs))
  File "/home/contrib/parsers/TW.py", line 28, in fetch_production
    objData['fueltype'] = objData.fueltype.str.split(')').str[0]
  File "/usr/local/lib/python3.6/site-packages/pandas/core/generic.py", line 3610, in __getattr__
    return object.__getattribute__(self, name)
  File "/usr/local/lib/python3.6/site-packages/pandas/core/accessor.py", line 54, in __get__
    return self.construct_accessor(instance)
  File "/usr/local/lib/python3.6/site-packages/pandas/core/strings.py", line 1910, in _make_accessor
    raise AttributeError("Can only use .str accessor with string "
AttributeError: Can only use .str accessor with string values, which use np.object_ dtype in pandas
```

**Comment by systemcatch** [comment]
Looking at the listed [source](http://www.taipower.com.tw/d006/loadGraph/loadGraph/genshx_.html) in the readme it seems the data is supplied from http://www.taipower.com.tw/d006/loadGraph/loadGraph/data/genary.txt, which is different to the source in the parser (http://data.taipower.com.tw/opendata01/apply/file/d006001/001.txt)

**Comment by brunolajoie** [comment]
Good catch! Let us know if you see it as quickly fixeable or if it need a entire rewrite

**Comment by systemcatch** [comment]
Actually looking closely at http://www.taipower.com.tw/tc/page.aspx?mid=206&cid=404&cchk=8ccc1918-8cae-4f40-a2d0-b43454f4f218, there's a request to http://www.taipower.com.tw/d006/loadGraph/loadGraph/data/loadfueltype.csv for the underlying graph data.

That csv contains data for the entire day so it could provide us with way to return a list of datapoints rather than just one.

**Comment by brunolajoie** [comment]
Oh cool, swapping the URL to http://www.taipower.com.tw/d006/loadGraph/loadGraph/data/genary.txt indeed fix the problem easily. I'll do it right now to stop the bleeding.

Now, to chose between http://www.taipower.com.tw/d006/loadGraph/loadGraph/data/genary.txt  and http://www.taipower.com.tw/d006/loadGraph/loadGraph/data/loadfueltype.csv, a good argument could be if one could fetch historical data. Else, I'm not sure it's usefull to spend time coding a new parser

**Comment by systemcatch** [comment]
As far as I can tell there is currently no historical data available at the granularity we require.
