### ISSUE TITLE
Norways largest windpark, Roan, opened (256MW)

### ISSUE THREAD

**Issue by Gazer75** [tmrowco/electricitymap-contrib#1785]
Another 256MW worth of wind capacity has to be added to NO and NO3 for Norway.
If you look at logs you might see a production for NO3 that is over current set capacity :)
As of writing this on the morning of 24. February 2019 there is pretty high wind in the area so it might show significant production.
The windpark consists of 71 Vestas V117 3.6MW turbines.

**Comment by systemcatch** [comment]
Hi @Gazer75 thanks for pointing that out, do you want to submit a PR updating the capacity?

**Comment by Gazer75** [comment]
Hoped someone with write permission could just update the two lines in the file affected by this directly :)
