### ISSUE TITLE
Add US-MISO day ahead wind & solar forecasts

### ISSUE THREAD

**Issue by brunolajoie** [tmrowco/electricitymap-contrib#1788]
Both Wind Production and Total Load seem available with a day-head forecast from the following webpage https://www.misoenergy.org/markets-and-operations/real-time-displays/

These forecasts could be added to the MISO parser

**Comment by systemcatch** [comment]
API's for both of those are available at https://www.misoenergy.org/markets-and-operations/RTDataAPIs/
