### ISSUE TITLE
Most of Australia is down

### ISSUE THREAD

**Issue by corradio** [tmrowco/electricitymap-contrib#1794]
Parsers indicate "HTTP Error 503: Service Unavailable: Back-end server is at capacity".

**Comment by brunolajoie** [comment]
it might be time to switch to OpenNEM now? (as discussed in #1196, using  
a neat API that returns JSON: https://data.opennem.org.au/power/qld1.json )

**Comment by jarek** [comment]
... down under? >_>

**Comment by corradio** [comment]
wrote to data@digital.gov.au

**Comment by corradio** [comment]
got an answer. New URL: https://services.aremi.data61.io/aemo/v6/csv/all
