### ISSUE TITLE
Suggest delay time to optimize CO2 footprint for dishwasher, etc.

### ISSUE THREAD

**Issue by rodwalker** [tmrowco/electricitymap-contrib#1797]
I would like to suggest a new functionality for your app. It would enable people about to start the dishwasher to easily set a delay time, in order to minimize the CO2 footprint.

Upon opening the new entry-point, or new app, the user would see a configurable set of icon-buttons for dishwasher, washer, drier. Pushing one instantly shows a number of hours to set the delay. The optimization would use standard consumption profiles for each appliance type, together with the local intensity forecast. The profiles do not need to be very refined to start with, e.g. 10mins heating@2kW, followed by 2hrs@50W. Minimizing the footprint against start times will not stress your AI!

That is it, but there could be bells and whistles such as
- graph with forecast intensity, with optimal runtime overlaid
- projected % saving on this wash
- user registration for
-- model and program specs, with accurate consumption profile and kWh total
-- cumulative saving
-- include local PV, in optimization
-- optimize on money for variable tariff (effectively variable for local PV)

Almost all new dishwashers, washing machines and driers have a delay function. I think it would be a good way to weaponize your nice plots, and increase visibility. It is a step towards the automation possible with networked appliances, and a lever to encourage cooperation from manufacturers.

Cheers,
Rod.

**Comment by corradio** [comment]
cc @martincollignon @tth4vb @sorensvejstrup for the idea.
Closing as we will take this internally.
