### ISSUE TITLE
Check import/export directions for Northern Ireland

### ISSUE THREAD

**Issue by alixunderplatz** [tmrowco/electricitymap-contrib#1806]
We had a PR #1669 that dealt with the direction of exchanges with Northern Ireland (GB-NIR).
Today's graph for NIR looks very suspicious to me:
![image](https://user-images.githubusercontent.com/25743609/54869982-b9dec000-4da0-11e9-8fb8-f1704b2e56b7.png)
Simultaneous imports towards NIR should result in a smooth load curve or in a reaction of the production, not in a weird up and down.

Here is an overlay of the forecasted load over production:
![image](https://user-images.githubusercontent.com/25743609/54870328-3ecbd880-4da5-11e9-8fff-ac6e7e5c8f7a.png)

Another evidence for the issue is the production mix for Ireland:
![image](https://user-images.githubusercontent.com/25743609/54870335-6d49b380-4da5-11e9-9003-82066e17ed00.png)

The sum of all sources is too low to cover the load according to the data on ENTSOE:
![image](https://user-images.githubusercontent.com/25743609/54870316-2956ae80-4da5-11e9-97e7-4c0388e32838.png)

Clearly, there are a few hundred megawatts missing. I assume these should come from UK to NIR, are transferred through NIR and are passed on to IR.

Please have another look at the directions!
Kind regards, Alex

**Comment by alixunderplatz** [comment]
So I had another look at the related data and I think I found the main bug :)

1.) The data for the moyle-interconnector in fetch_exchange is problematic. 
The csv behind the data (get it at http://ws.soni.ltd.uk/DownloadCentre/aspx/MoyleTie.aspx) is either showing a negative value (=import to NIR) or 0 for Moyle, but never (!) a positive value.
This means, on the map, the power flow is only coming from GB, there are no exports from NIR to GB, which is clearly wrong.
However, the complete data for Moyle, including the positive export values, are found in the "wind_url" accessed by the parser for wind production: http://ws.soni.ltd.uk/DownloadCentre/aspx/SystemOutput.aspx

The red data from "Moyle and TieLines" shouldn't be used anymore (0 or negativ). We should stick to the Moyle data coming from the ["SystemOutput" csv](http://ws.soni.ltd.uk/DownloadCentre/aspx/SystemOutput.aspx) (covering both directions! ;) ). Please note, the direction of the values is inversed, this needs to be adressed correctly in the parser. Positive means import to NIR from GB through Moyle. Negative means export to GB from NIR.
![image](https://user-images.githubusercontent.com/25743609/56204088-e657c600-6046-11e9-9195-20bb3236b2dd.png)

2.) Actually, between NIR and IR, there are 3 interconnectors.
The main interconnector is Tandragee(NIR)-Louth(IR) on the 275kV level (2 parallel systems). 
There are 2 more 110 kV lines between the west of NIR and IR. These two interconnectors Enniskillen(NIR)-Corraclassy(IR) and Strabane(NIR)-Letterkenny(IR) "support the grid on a local level".
https://issuu.com/designtactics/docs/soni_north_south_interconnector_-_a/5
The parser is accessing the ["Moyle and TieLines"-url](http://ws.soni.ltd.uk/DownloadCentre/aspx/MoyleTie.aspx) and correctly takes the sum of all three interconnections. However, from what I have observed, that data is lacking the two 110kV-tie-lines (data for them is empty in the csv right now). 
There is another column in the "SystemOutput" csv, which is named "Tie_Lines_MW". This one sums the data for all three NIR<->IR interconnectors, and not only the 275kV line (unlike the "Moyle and Tie Lines" csv).
Here you can see that there is a small difference between the 275kV-data and the total tie-line value:
![image](https://user-images.githubusercontent.com/25743609/56205448-194f8900-604a-11e9-94ed-2cfddbaf4498.png)
So I suggest we should stick with the "Tie_Lines_MW" from SystemOutput.csv instead of what is used in fetch_exchange now.

3.) I assumed there is a wrong direction for one of the interconnectors. I haven't yet looked into the parser to find the line which may cause it, but I'll try to figure it out. I still assume it's the direction for the tie lines between NIR<->IR which is inversed.
____________________________

To get an idea of the correct direction of flows from my assumptions:

![image](https://user-images.githubusercontent.com/25743609/56205562-73504e80-604a-11e9-80a7-68ff0d47777e.png)
- "Total_NI_Generated_MW" = Load, green surface.
- "Tie_Lines_MW" = exchange NIR<->IR, with negative = "export from NIR to IR" and positive "import to NIR from IR"
- "Total_Moyle_Load_MW" = exchange NIR<->GB, with negative = "export from NIR to GB" and positive "import to NIR from GB" (I cross-checked with ENTSOE data)
-  surplusses (everything above green surface) are exported to IR (dark red in negative area) or GB (yellow in negative area)

I'll try to implement the suggested improvements ;)

**Comment by corradio** [comment]
@alixunderplatz PR has been deployed - does it look better?

**Comment by alixunderplatz** [comment]
@corradio the exchange of NIR with Ireland looks good and smoothly fills the top of IR's load curve
![image](https://user-images.githubusercontent.com/25743609/56364189-40df5680-61ee-11e9-9cc7-210026bf6f48.png)

NIR however has a load of ~1000 MW at the moment, but it's only producing 800 MW while at the same time exporting 200 MW to GB. So now I have messed up the direction for that exchange^^ I'm sorry!
Will fix this!
