### ISSUE TITLE
Fix exchanges of RU-zones

### ISSUE THREAD

**Issue by alixunderplatz** [tmrowco/electricitymap-contrib#1817]
The RU parser needs another small tweak. Exchanges with all eastern countries don't seem to work on the map.
When fetching the recent hour, the exchanges show "0.0 MW" because the data is not yet available.
`fetch_exchange(CN, RU-AS) ->
{'sortedZoneKeys': 'CN->RU-AS', 'datetime': datetime.datetime(2019, 4, 6, 8, 48, 10, 810991, tzinfo=tzfile('W-SU')), 'netFlow': 0.0, 'source': 'so-ups.ru'}
fetch_exchange(MN, RU) ->
{'sortedZoneKeys': 'MN->RU', 'datetime': datetime.datetime(2019, 4, 6, 8, 48, 11, 435945, tzinfo=tzfile('W-SU')), 'netFlow': 0.0, 'source': 'so-ups.ru'}
fetch_exchange(MN, RU-2) ->
{'sortedZoneKeys': 'MN->RU-2', 'datetime': datetime.datetime(2019, 4, 6, 8, 48, 12, 14033, tzinfo=tzfile('W-SU')), 'netFlow': 0.0, 'source': 'so-ups.ru'}`

Going back 1 hour in the exchanges-URL solves this:
`fetch_exchange(CN, RU-AS) ->
{'sortedZoneKeys': 'CN->RU-AS', 'datetime': datetime.datetime(2019, 4, 6, 8, 53, 40, 83369, tzinfo=tzfile('W-SU')), 'netFlow': 771.6650390625, 'source': 'so-ups.ru'}
fetch_exchange(MN, RU) ->
{'sortedZoneKeys': 'MN->RU', 'datetime': datetime.datetime(2019, 4, 6, 8, 53, 40, 723144, tzinfo=tzfile('W-SU')), 'netFlow': 56.64677810668945, 'source': 'so-ups.ru'}
fetch_exchange(MN, RU-2) ->
{'sortedZoneKeys': 'MN->RU-2', 'datetime': datetime.datetime(2019, 4, 6, 8, 53, 41, 370206, tzinfo=tzfile('W-SU')), 'netFlow': 56.64677810668945, 'source': 'so-ups.ru'}
`

The timestamp of the exchange data needs a fix as well. It should not be the timestamp of the machine, but of the dataset. So in my example, not  'datetime': datetime.datetime(2019, 4, 6, 8, 53, 40, 83369, ...) but datetime.datetime(2019, 4, 6, 7, 0, ...) for the 7th hour.

@denplis Maybe you can have a look?

**Comment by systemcatch** [comment]
Hey @alixunderplatz I tried your fix but had to go 2 hours back (hour=20 instead of hour=22 that the parser was requesting).

Maybe we could check the json response for each ID that is mapped to an exchange. If all of them are zero we could request the hour before and keep going (within reason) until we hit good data?

**Comment by systemcatch** [comment]
@alixunderplatz actually the easier solution could be to modify the parser to return exchange data for the entire day. That would also let us fetch historical data.
