### ISSUE TITLE
Implement offshore-interconnector geometries

### ISSUE THREAD

**Issue by alixunderplatz** [tmrowco/electricitymap-contrib#1818]
The link to the awesome project openinframap.org was posted recently on Slack:
https://openinframap.org/
There also is a github repo:
https://github.com/openinframap/

It includes many of the world's transmission and distribution high-voltage grids and other infrastructure-grids.
Maybe there is a way to use the line geometries of the offshore-cables between the zones for electricityMap one day?

![image](https://user-images.githubusercontent.com/25743609/55665766-23e97180-5845-11e9-8c86-51314dd8b422.png)

Some ideas:
- Cable color could represent carbon intensity like the arrows do now
- Moving dashes could represent the direction of flow. Maybe just one dash moving down the line (like [in the King island dashboard](http://www.kingislandrenewableenergy.com.au/)) is enough
- speed / line thickness / dash color could vary based on the carbon intensity or load factor
- the "interconnector layer" could be activated based on the zoom stage

Not sure how this will affect the performance (#1590) and how difficult implementing that idea is at all.  😬

**Comment by corradio** [comment]
Such a good idea but unfortunately we won't have time to work on this :/
