### ISSUE TITLE
Not able to start web container

### ISSUE THREAD

**Issue by jld3103** [tmrowco/electricitymap-contrib#1821]
I'm running this command:
```
docker-compose run --rm web npm run watch
```
And I'm always getting the same error:
```
Creating electricitymap-contrib_mockserver_1 ... error

ERROR: for electricitymap-contrib_mockserver_1  Cannot start service mockserver: OCI runtime create failed: container_linux.go:345: starting container process caused "process_linux.go:424: container init caused \"rootfs_linux.go:58: mounting \\\"/home/jld3103/Desktop/electricitymap-contrib/mockserver/server.py\\\" to rootfs \\\"/mnt/sda1/var/lib/docker/overlay2/45d634b40ca922bbb2f1a1ded4edef2779aa1ab897284d702ac42798b844c086/merged\\\" at \\\"/mnt/sda1/var/lib/docker/overlay2/45d634b40ca922bbb2f1a1ded4edef2779aa1ab897284d702ac42798b844c086/merged/home/server.py\\\" caused \\\"not a directory\\\"\"": unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type

ERROR: for mockserver  Cannot start service mockserver: OCI runtime create failed: container_linux.go:345: starting container process caused "process_linux.go:424: container init caused \"rootfs_linux.go:58: mounting \\\"/home/jld3103/Desktop/electricitymap-contrib/mockserver/server.py\\\" to rootfs \\\"/mnt/sda1/var/lib/docker/overlay2/45d634b40ca922bbb2f1a1ded4edef2779aa1ab897284d702ac42798b844c086/merged\\\" at \\\"/mnt/sda1/var/lib/docker/overlay2/45d634b40ca922bbb2f1a1ded4edef2779aa1ab897284d702ac42798b844c086/merged/home/server.py\\\" caused \\\"not a directory\\\"\"": unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type
ERROR: Encountered errors while bringing up the project.
```

I already tried rebuild the container, removing everything (containers, volumes, networks), but the error doesn't go away.

I'm using Docker 18.09.4, Dockercompose 1.23.2 and Dockermachine 0.16.0.

**Comment by corradio** [comment]
Hi @jld3103,
The error `Are you trying to mount a directory onto a file` seems to suggest that `server.py` might be a directory on your machine. Can you check?
Also, are you on windows? Have you tried looking at https://github.com/tmrowco/electricitymap-contrib#troubleshooting?

**Comment by jld3103** [comment]
I'm on Linux and I already tried to troubleshoot.
Before I tried to troubleshoot I couldn't reach the frontend, but I could reach the mockserver.
Then I installed Dockermachine and I got this error.

Using dir -al I got this:
```
-rw-rw-r--  1 jld3103 jld3103  764 Jan 30 22:04 server.py
```

**Comment by corradio** [comment]
As an easy fix, you can delete that line from docker-compose.yml:

![image](https://user-images.githubusercontent.com/1655848/55942088-f08f5400-5c43-11e9-9e6e-a290f26fa3d4.png)

You don't need to have server.py mounted

**Comment by jld3103** [comment]
Now I got another error:
```
Error response from daemon: OCI runtime create failed: container_linux.go:345: starting container process caused "process_linux.go:424: container init caused \"rootfs_linux.go:58: mounting \\\"/home/jld3103/Desktop/electricitymap-contrib/web/server.js\\\" to rootfs \\\"/mnt/sda1/var/lib/docker/overlay2/6f3884530f6811d48ac17abb3011badca079fb7ae50c4d5f946c754061f38654/merged\\\" at \\\"/mnt/sda1/var/lib/docker/overlay2/6f3884530f6811d48ac17abb3011badca079fb7ae50c4d5f946c754061f38654/merged/home/web/server.js\\\" caused \\\"not a directory\\\"\"": unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type
```

I'll try to remove that file, too.

**Comment by jld3103** [comment]
I had to remove all files (not directories) from the volumes, but then I got this error:
```
[./node_modules/webpack/buildin/global.js] (webpack)/buildin/global.js 489 bytes {vendor} [built]
[0] multi babel-polyfill ./src/main.js 40 bytes {bundle} [built]
    + 326 hidden modules

ERROR in Entry module not found: Error: Can't resolve './src/styles.css' in '/home/web'

ERROR in multi babel-polyfill ./src/main.js
Module not found: Error: Can't resolve './src/main.js' in '/home/web'
 @ multi babel-polyfill ./src/main.js bundle[1]
```

**Comment by corradio** [comment]
Unfortunately it won't work if you remove all volume mounts because the watch command will create files that needs to be access by the mockserver.
You should be able to mount files as volumes in linux. Unfortunately I don't know enough about your docker installation to know why there's an issue there.
https://github.com/moby/moby/issues/27010#issuecomment-250437911 seems to be a good place to start? It could be that you're trying to mount files in a folder that isn't accessible.
Also see https://github.com/codekitchen/dinghy/issues/241

**Comment by jld3103** [comment]
I have an older setup on my laptop from November 2018. I'll try it there and then update to the current version and check if it's working.

**Comment by jld3103** [comment]
So I look into the VM and found (as the error and reports you send said) all files mounted as empty directories.

**Comment by jld3103** [comment]
So somehow it fixed it self. I reset my computer and now it works! I Really don't know why it didn't work before.

**Comment by rolanddosa** [comment]
I had the same issue, then I recloned the project in a folder in C/Users/me/ and it started fine. Seems like the location in `C:/Users/` allows it to start fine
