### ISSUE TITLE
Update capacities for BE

### ISSUE THREAD

**Issue by corradio** [tmrowco/electricitymap-contrib#1824]
I just received this email, which hints at BE capacities:

> Hello!
> 
> I found the most recent numbers for the installed capacity in Belgium in Elia’s 2018 sustainability report. 
> Attached is a screenshot of the data, you can find the full report online: https://www.eliagroup.eu/en/publications  

![image](https://user-images.githubusercontent.com/1655848/56215109-6558f880-605f-11e9-9882-60c37dac4ed9.png)

**Comment by alixunderplatz** [comment]
Nice! I'll update this :)
