### ISSUE TITLE
Check/fix parsers of "lost" areas

### ISSUE THREAD

**Issue by alixunderplatz** [tmrowco/electricitymap-contrib#1833]
In the last couple of weeks, some areas on the map went grey.
Here's a list with regions that need a parser fix / investigation of the source:

- [x] **US-BPA** is grey (Washington (state))
 
- [x] **US-IPC** is grey (Idaho)
  - data url was changed, I think this data source could no more be available in real-time
  - see #1803 for latest commit

- [x] **IT-South** is grey + IT<->GR is missing (ENTSOE.py)
  - check if the ENTSOE-ID of the bidding zone has been changed
  - see #1770 and #1776 for latest commit
 
- [x] **CA-AB**
  - see @jarek's comment below

- [x] **GT**
  - pandas error seen repeatedly

- [x] **JP-HKD/JP-SK**
  - storage is wrong format

- [x] **DO**
  - source website does not respond
  - there's a note on the [website](http://www.sie.gob.do/) about server-issues for the market participants

- [x] **KR**
  - source for Korea not available at the moment
  - switching to another data source is discussed in #1563

**Comment by jarek** [comment]
Alberta, too. I've been meaning to check on it, page http://ets.aeso.ca/ets_web/ip/Market/Reports/CSDReportServlet still loads...

**Comment by systemcatch** [comment]
US-BPA data link seems to be working fine (https://transmission.bpa.gov/business/operations/Wind/baltwg.txt)

Logger is showing an error that's related to pandas.

```python
Traceback (most recent call last):
  File "/home/feeder/lib/fetch_data.py", line 171, in launch_parsers
    objs = res.get(timeout)
  File "/usr/local/lib/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value
  File "/usr/local/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/home/feeder/lib/fetch_data.py", line 169, in <lambda>
    **parser_kwargs))
  File "/home/contrib/parsers/US_BPA.py", line 114, in fetch_production
    processed_data = data_processor(raw_data, logger)
  File "/home/contrib/parsers/US_BPA.py", line 71, in data_processor
    dt = dt.to_datetime()
AttributeError: 'Timestamp' object has no attribute 'to_datetime'
```

**Comment by systemcatch** [comment]
Seems like to_datetime() is being replaced by to_pydatetime(). This warning isn't captured by the logger but I don't see why the parser is breaking since this is just a warning on 0.22.0

```shell
(EM-env) chris@ThinkPad:~/electricitymap$ python parsers/US_BPA.py 
fetch_production() ->
parsers/US_BPA.py:114: FutureWarning: to_datetime is deprecated. Use self.to_pydatetime()
```

**Comment by corradio** [comment]
Actually we're using 0.24.2 internally, and it has overridden the version here, so that explains the error.

**Comment by systemcatch** [comment]
Ah ok well regardless the fix is easy.

**Comment by systemcatch** [comment]
GT error that keeps happening.

```python
Traceback (most recent call last):
  File "/home/feeder/lib/fetch_data.py", line 171, in launch_parsers
    objs = res.get(timeout)
  File "/usr/local/lib/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value
  File "/usr/local/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/home/feeder/lib/fetch_data.py", line 169, in <lambda>
    **parser_kwargs))
  File "/home/contrib/parsers/GT.py", line 75, in fetch_production
    data_temp = fetch_hourly_production(zone_key, obj_h, 0, formatted_date)
  File "/home/contrib/parsers/GT.py", line 39, in fetch_hourly_production
    data['production']['biomass'] = max(obj[obj['tipo'] == 'Biomasa'].potencia.iloc[0], 0) + max(obj[obj['tipo'] == 'Biogas'].potencia.iloc[0], 0)
  File "/usr/local/lib/python3.6/site-packages/pandas/core/indexing.py", line 1500, in __getitem__
    return self._getitem_axis(maybe_callable, axis=axis)
  File "/usr/local/lib/python3.6/site-packages/pandas/core/indexing.py", line 2230, in _getitem_axis
    self._validate_integer(key, axis)
  File "/usr/local/lib/python3.6/site-packages/pandas/core/indexing.py", line 2139, in _validate_integer
    raise IndexError("single positional indexer is out-of-bounds")
IndexError: single positional indexer is out-of-bounds
```

JP parsers failing quality test

```python
invalid point: {'zoneKey': 'JP-HKD', 'datetime': datetime.datetime(2019, 4, 28, 0, 20, tzinfo=tzfile('/usr/share/zoneinfo/Asia/Tokyo')), 'production': {'biomass': None, 'coal': None, 'gas': None, 'hydro': None, 'nuclear': None, 'oil': None, 'solar': None, 'wind': None, 'geothermal': None, 'unknown': 2791.0}, 'storage': None, 'source': 'occtonet.or.jp, denkiyoho.hepco.co.jp', 'schemaVersion': 3}, reason:storage value must be a dict, was None
```

**Comment by systemcatch** [comment]
I think I've found where the data source for DO has moved to!

http://190.122.102.21:8084/reportesgraficos/reportepostdespacho.aspx

**Comment by systemcatch** [comment]
@alixunderplatz looks like IT-South is working again, but the interconnecter with Greece is still down.

**Comment by systemcatch** [comment]
With CA-AB now working again I think this issue can be closed.
