### ISSUE TITLE
Wrong (?) price

### ISSUE THREAD

**Issue by jld3103** [tmrowco/electricitymap-contrib#1839]
I found this:
![electricitMap_wrong_price](https://user-images.githubusercontent.com/26026535/57035548-9ede5600-6c52-11e9-81a0-0479321f6629.png)
It looks like the price is not correct.
If it isn't wrong you have to explain me why :)

**Comment by jarek** [comment]
Electricity prices do go negative:
https://www.cleanenergywire.org/factsheets/why-power-prices-turn-negative
https://www.bloomberg.com/news/articles/2018-08-06/negative-prices-in-power-market-as-wind-solar-cut-electricity

I'm not finding an article about today's prices, but consider that today is a holiday in Germany, and evidently there was a fair bit of sun and wind. Probably complicating matters is that the holiday is mid-week, so energy was needed yesterday and will be needed tomorrow. Unlike during a weekend, spinning down coal plants with long spin-up cycles might not actually happen.

**Comment by jarek** [comment]
You can see that the same negative price is shown on https://www.energy-charts.de/price.htm?auction=1h&year=2019&month=5

Electricity Map's German data, including prices, ultimately comes from ENTSO-E Transparency Platform, in particular it looks like the -2.82 EUR value comes from https://transparency.entsoe.eu/transmission-domain/r2/dayAheadPrices/show?name=&defaultValue=false&viewType=TABLE&areaType=BZN&atch=false&dateTime.dateTime=01.05.2019+00:00|CET|DAY&biddingZone.values=CTY|10Y1001A1001A83F!BZN|10Y1001A1001A82H&dateTime.timezone=CET_CEST&dateTime.timezone_input=CET+(UTC+1)+/+CEST+(UTC+2)

**Comment by alixunderplatz** [comment]
@jld3103 negative prices happen from time to time. the electricity price is mainly based on the amount of required fossil/conventional power. the more renewables feed in electricity, the cheaper the market price will be. 
today was a holiday in Germany, so a day with low electricity demand, but high renewable share, especially in the afternoon. when fossil power plants are not shut down in the required amount to prevent the overproduction in periods with low demand, negative prices occur and consumers even get paid when they purchase electricity.
"merit order" is the term you can check for further info on how the market price is determined; or just ping me on slack ;)
https://de.m.wikipedia.org/wiki/Merit-Order
I close this issue
