### ISSUE TITLE
Add the African continent

### ISSUE THREAD

**Issue by jld3103** [tmrowco/electricitymap-contrib#1850]
I've found [this](https://www.africa-energy.com/live-data) provider which seems to cover the whole continent.
This would be perfect, because we have almost the whole continent not covered.
I wrote an email to ask some questions about the data they provide and if it's possible to get free access to it.
I'm going to update this issue when I get a response.

**Comment by jarek** [comment]
Let us know if they do indeed have hourly generation data per plant or per fuel. I am a bit skeptical but I'm prepared to be pleasantly surprised.

**Comment by alixunderplatz** [comment]
Nice catch, @jld3103! This is from where I once took the numbers for Namibia's solar & wind capacity. They have a large database with all larger generators and also smaller projects in the Kilowatts range, which is great! 
I'm also sceptical that "live data" referrs to real-time elctricity generation, and I think it's more like tracking a status of planned/realized renewable projects. https://www.africa-energy.com/live-data/about-live-data
Anyways, they could be a catalyst to providing live data, as they may have the crucial contacts to the national TSOs. Fingers crossed that you'll get a response! 🤞 :)

**Comment by jld3103** [comment]
Got no response yet :(

**Comment by alixunderplatz** [comment]
@jld3103 No worries! If you like, you can take a look at the websites mentioned in #1218 (African Power Pools). Maybe there have been some updates for some African regions. You can also check these power pool pages for the names of the respective national transmission system operators.

**Comment by matteodefelice** [comment]
Already contacted them, they have indeed a very high-quality and updated list of power-plants projects (built, planned and under-construction) but they do not have any real-time generation information.

**Comment by jld3103** [comment]
That's sad :(
Closing this issue, because it's not relevant anymore.
Please reopen if something has changed.
