### ISSUE TITLE
Split Azerbaijan and Nagorno-Karabakh Republic networks

### ISSUE THREAD

**Issue by Varmin123** [tmrowco/electricitymap-contrib#1860]
Hi everyone,

First of all, I wanted to thank you for adding recently Armenia. However, it seems that there is a little detail lacking in the CO2 emissions.

Indeed, electricity imports from OHTL Artsakh and OHTL Shinuhayr are counted as imports from Azerbaijan. In practice, those imports come from Nagorno-Karabakh Republic (NKR), a de facto independant state. The networks of AZ and NKR have been separated (the transmission lines have been cut), and no electricity is exchanged between both.

I would suggest splitting AZ in half (following the Wikipedia map: https://commons.wikimedia.org/wiki/File:Republic_of_Artsakh_location_map_(dotted_de-facto)_(-NKR_provinces)_(%2BAzerbaijan).svg ), as there are actually two independent networks operating in the same country (hereafter the AZ network and the NKR network). 

The CO2 emissions of 490g/kWh given in co2eq_parameters.json are only for the AZ network, while the NKR network is made only of hydroelectric power plants (Sarsang HPP 50 MW, + other small HPP: Trghi-1 3MW, Trghi-2 6 MW, Mataghis-1 and -2 7,8 MW, Trghi-3 5 MW, Trghi-4 - 0.8 MW and Lev-1 - 7 MW + other HPP being built). The carbon content of the NKR network is assumed to be 24g/kWh (100% hydro).

After splitting the AZ network into two (AZ + NKR), the other networks would be modified as follows: 
- Armenia imports from NKR network
- Everybody else imports from AZ network
- No connection between AZ and NKR networks

I could submit the pull request from the last part, but I do not know how to do the changes on the map. If I could get some help, I would be really glad.

Thank you very much.

**Comment by jarek** [comment]
Thanks for the great description of the system in place! That'll be really helpful.

**Comment by Varmin123** [comment]
#1866

**Comment by Varmin123** [comment]
Done.
