### ISSUE TITLE
List of supported languages is duplicated across the code

### ISSUE THREAD

**Issue by fbarl** [tmrowco/electricitymap-contrib#1862]
The locales array is currently being independently defined in 4 different places in the code:

* https://github.com/tmrowco/electricitymap-contrib/blob/40d3a1eaff42f13645fac86893a495cbdc7ef6c3/mobileapp/www/index.html#L5
* https://github.com/tmrowco/electricitymap-contrib/blob/40d3a1eaff42f13645fac86893a495cbdc7ef6c3/mobileapp/generate-index.js#L29
* https://github.com/tmrowco/electricitymap-contrib/blob/40d3a1eaff42f13645fac86893a495cbdc7ef6c3/web/server.js#L33
* https://github.com/tmrowco/electricitymap-contrib/blob/40d3a1eaff42f13645fac86893a495cbdc7ef6c3/web/src/helpers/translation.js#L5

This makes maintaining the list of translations a pain (e.g. adding a language requires changes in all the files above). Instead, the list should be defined at only _one_ place in the code and imported everywhere else where it's needed.

**Comment by jld3103** [comment]
Maybe we should even generate the list from the json files.

**Comment by corradio** [comment]
Still needs to be done for the mobile app

**Comment by systemcatch** [comment]
Quoting from #1897 
> 
> 
> The problems comes from this line:
> https://github.com/jld3103/electricitymap-contrib/blob/8ab390672ead5e92a4108c29fd811f98c8ed4703/web/src/helpers/locales-list.js#L3
> `readdirSync` is not available on the browser.
> I didn't test it but somehow it should have failed when you tested it?
> The ideal solution is to create a webpack transform that injects (i.e. hard codes) the locale list into the source code.
> Else we can also make a script that simply creates a json with the list of locales. That script would have to be run as part of the build process.
