### ISSUE TITLE
Data for Iran

### ISSUE THREAD

**Issue by jzlcdh** [tmrowco/electricitymap-contrib#1864]
Not sure if this is useful for you but there are some [reports here](https://www.igmc.ir/Electronic-Services/Power-Market-Deputy/Reports) and some twice daily data
[here](https://www.igmc.ir/Power-grid-status-report)

If it looks promising but you need translation help let me know and I can ask an Iranian friend.

**Comment by systemcatch** [comment]
@jzlcdh Maybe your friend could scour the site to see if they have anything historical or real time?

**Comment by jzlcdh** [comment]
I hoped I might have missed something but he checked and unfortunately that is all there is.

**Comment by systemcatch** [comment]
Fair enough let's close this for now and reopen if we find anything better in the future.
