### ISSUE TITLE
Problem with excanges.json transfer direction NO1->NO5 vs displayed on web

### ISSUE THREAD

**Issue by Gazer75** [tmrowco/electricitymap-contrib#1869]
In https://github.com/tmrowco/electricitymap-contrib/blob/062c700bf535d31941f264aab3fd864135bc10a9/config/exchanges.json#L1948 it clearly says NO1 to NO5, but on the website capacity seem to be reversed.
This made me confused and I might have messed up the numbers for the other capacities in my last PR.

The data used for the one above is the peak found here:
https://transparency.entsoe.eu/transmission-domain/ntcWeek/show?name=&defaultValue=false&viewType=TABLE&areaType=BORDER_BZN&atch=false&dateTime.dateTime=31.12.2018+00:00|UTC|WEEK&border.values=CTY|10YNO-0--------C!BZN_BZN|10YNO-1--------2_BZN_BZN|10Y1001A1001A48H&direction.values=Export&direction.values=Import

**Comment by systemcatch** [comment]
From a quick glance only one or two look the wrong way round.

**Comment by corradio** [comment]
@Gazer75 is this still happening?

**Comment by Gazer75** [comment]
Yep this is still a problem. At the moment it looks like NO5 to NO1 is reversed. That is West to Southeast.
The lines for the zone transfers also do not list the zones properly and simply say like "NO-NO1" where it should say NO5-NO1 if I have West zone selected.

**Comment by corradio** [comment]
I've looked at it and it seems like exchanges.json should showcase [600, -3900] instead of [-600, 3900].

**Comment by Gazer75** [comment]
If that's the case then the description line above has to be reversed as it is 3900MW from NO5 to NO1 and only 600MW the other way. Same goes for line for NO1->NO2.
https://github.com/tmrowco/electricitymap-contrib/blob/fc85e871cf17735ab6c4451ed574d29666e9c0cd/config/exchanges.json#L1923

**Comment by corradio** [comment]
Sorry I just dug into the code and the two numbers represent the min and max of the net flow.
Therefore, the first number represents the NO5->NO1 capacity (needs to be negative), and the second the NO1->NO5 capacity (needs to be positive).
Therefore, the value should be [-3900, 600]. Let's try this one out and if it works we do the others?

**Comment by Gazer75** [comment]
Exactly, and thus the description for them should be reversed so that it says "NO-NO5->NO-NO1". That to me indicate you send from 5 to 1 and thus first positive number has to be the higher one as that's the one with most capacity. Sending something is taking something away which is negative right?

**Comment by corradio** [comment]
right! The only thing is that the description is always ordered alphabetically (for performance reasons) so we can't change it. Instead, we should change the values that currently describe NO5->NO1 such that they describe NO1->NO5

**Comment by Gazer75** [comment]
Very unintuitive to type the values in reverse though and this is very easy to get wrong.

**Comment by corradio** [comment]
I hear you. To be fair this only applies to zones that are listed in a given order (NO1,NO2...). Most other zones do not have an order associated.
@Gazer75 would you be able to make the changes? That would be appreciated 🙏

**Comment by Gazer75** [comment]
I am a bit confused about this so if you understand it please do the corrections. There should probably be a note in there that these values has to be reversed?

**Comment by Gazer75** [comment]
Best thing would be to grab these values directly from ENTSO-E
For Norway there seem to be a weekly forecast on capacity.
