### ISSUE TITLE
Unknown defaults to Non Renewable Type

### ISSUE THREAD

**Issue by zuron7** [tmrowco/electricitymap-contrib#1875]
Any energy source that is unknown defaults to a non renewable type. Even if there is a mix of renewable in the unknown part. It is suggested that the ratio of renewable to non-renewable be exposed as a parameter which may be configured through the co2eq_parameters file.

As I have been made aware, the code to modify this is closed source, and will require changes by devs on the server side.

This issue was caused due to the Pull Request #1868

**Comment by corradio** [comment]
I added the code here:
https://github.com/tmrowco/electricitymap-contrib/commit/ceb42b01f82f41a2d031c0c59278e2666b849fc5
We can now customise them ;-)
