### ISSUE TITLE
Production / consumption toggle fixed width

### ISSUE THREAD

**Issue by petrpulc** [tmrowco/electricitymap-contrib#1878]
As my update to Czech locale was accepted a while ago (thanks!), this happened:

![obrazek](https://user-images.githubusercontent.com/5113566/58633776-d7bd2980-82e9-11e9-9c7e-423ed5e0a86b.png)

The toggle (`.production-toggle-active-overlay`) is of a fixed width (110px, defined in `styles.css`).

But the text under it (`.production-toggle-item`) is allowed to be flexible.

I provide no fix as this should be properly discussed with UI/UX people from here and as there are two possible solutions:

1) Should the toggle be allowed to change size based on the underlying item?

2) Should the items have fixed width? What if some languages have their string longer than 110px?

**Comment by corradio** [comment]
@ovbm do you have any suggestion?

**Comment by ovbm** [comment]
I'll fix it

**Comment by corradio** [comment]
@Kongkille are you able to help here?

**Comment by corradio** [comment]
@ovbm are you able to take this?

**Comment by corradio** [comment]
@ovbm are you able to take this?
