### ISSUE TITLE
New England flag

### ISSUE THREAD

**Issue by NewEnglandSeparatist** [tmrowco/electricitymap-contrib#1880]
This is almost irrelevant, and really not a big issue, but for consistency's sake, it'd be nice to add New England's flag.
![2000px-New_England_pine_flag svg](https://user-images.githubusercontent.com/32886774/58679319-f7c40b80-8330-11e9-9608-34ad0cb4a538.png)

**Comment by systemcatch** [comment]
We generally use the main country flag for sub areas to identify which country they're a part of. I don't see a need to change it in this case.
