### ISSUE TITLE
Some countries listed twice in sidebar list (div .zone-list)

### ISSUE THREAD

**Issue by JulianNF** [tmrowco/electricitymap-contrib#1890]
Lovely viz!

I spotted that some countries/regions are appearing twice in the sidebar list (e.g. Poland, Queensland AUS).

Not sure what might be causing this, but thought I'd mention it as a new issue.

(Firefox 67).

**Comment by jld3103** [comment]
Cannot confirm on Firefox 67.0.4

**Comment by jld3103** [comment]
Can you send a screenshot?

**Comment by JulianNF** [comment]
I just had a look and it seems that I too can no longer replicate the issue. Perhaps it was somehow linked with issue #1891 which I reported at the same time.

Marking as closed.
