### ISSUE TITLE
Wind and solar overlays not working in Firefox

### ISSUE THREAD

**Issue by JulianNF** [tmrowco/electricitymap-contrib#1891]
Solar and wind overlays don't appear to be working at all for me (Firefox 67).

Perhaps this console error report might be related:

```
Error: WebGL warning: texImage2D: Alpha-premult and y-flip are deprecated for non-DOM-Element uploads.
```

**Comment by systemcatch** [comment]
The overlays also don't work for me on FireFox 67.0.2, I see the same console error as @JulianNF

**Comment by systemcatch** [comment]
The overlays also don't work for me on FireFox 67.0.2, I see the same console error as @JulianNF

**Comment by systemcatch** [comment]
The overlays also don't work for me on FireFox 67.0.2, I see the same console error as @JulianNF

**Comment by corradio** [comment]
This issue also happens on Chrome. Network console shows a 404 when fetching wind data.

**Comment by corradio** [comment]
The GFS servers changed their URL :/ It's now fixed! Thanks for raising the issue
