### ISSUE TITLE
Language selection doesn't work on mobile app

### ISSUE THREAD

**Issue by corradio** [tmrowco/electricitymap-contrib#1892]
There's an issue with languages in the mobile app, as the mobile app doesn't respond to ?lang= querystring, but instead has to be redirected to /index_<locale>.html as one can see here:
https://github.com/tmrowco/electricitymap-contrib/blob/master/mobileapp/www/index.html#L10-L13
This means that the language selector doesn't currently work in the mobile app, which is unfortunate.
The fix is to redirect to /index_<locale>.html if we're using the mobile app, and to ?lang=<locale> else.

**Comment by jld3103** [comment]
Also needs to fix #1841 at the same time
