### ISSUE TITLE
electricityMap locale problem

### ISSUE THREAD

**Issue by corradio** [tmrowco/electricitymap-contrib#1897]
Seems to be introduced by https://github.com/tmrowco/electricitymap-contrib/pull/1888

I reverted that PR

cc @jld3103

![image](https://user-images.githubusercontent.com/1655848/60433082-3258e680-9c04-11e9-9479-4a500332313e.png)

**Comment by jld3103** [comment]
But how did it work before?
The solution would be my first attempt generating a js file with the locales list.

**Comment by corradio** [comment]
The problems comes from this line:
https://github.com/jld3103/electricitymap-contrib/blob/8ab390672ead5e92a4108c29fd811f98c8ed4703/web/src/helpers/locales-list.js#L3
`readdirSync` is not available on the browser.
I didn't test it but somehow it should have failed when you tested it?

**Comment by jld3103** [comment]
I did test it on web and it worked.
In the first commit you can see, that my first attempt was generating a js file.

**Comment by systemcatch** [comment]
closing for #1862
