### ISSUE TITLE
Split Hawaii geometries

### ISSUE THREAD

**Issue by kepiej** [tmrowco/electricitymap-contrib#1901]
I'm opening a new issue following @corradio 's suggestion in https://github.com/tmrowco/electricitymap-contrib/pull/1900#issuecomment-512240405.

Following the discussion in #814 , the Hawaii parser PR #1900 fetches data only for the Oahu Island of Hawaii (2/3 of population of Hawaii according to Wikipedia). Before merging #1900 , the Oahu Island needs to be split from the other Hawaii islands.
I don't know how to do that, so any guidance/help is appreciated! Maybe @systemcatch can help?

**Comment by systemcatch** [comment]
I'll take a look at this and try to remember how I did it before in qgis.
