### ISSUE TITLE
Alternative indicator CO2/inhabitant

### ISSUE THREAD

**Issue by BodiPim** [tmrowco/electricitymap-contrib#1907]
What about proposing an indicator showing the CO2 per person per hour due to electricty production?

Should be not to complicated as there is already total kwh and avg CO2 so multiplying both and dividing by the population of the country would give the figure...

Thanks!

**Comment by jarek** [comment]
Hi, thanks for the comment! See https://github.com/tmrowco/electricitymap-contrib/issues?utf8=%E2%9C%93&q=per+capita for past discussion of per capita emissions.
