### ISSUE TITLE
Create a third column "Consumption"

### ISSUE THREAD

**Issue by lars974** [tmrowco/electricitymap-contrib#1921]
Next to "Production" and "Emission" you could create a column showing the electrical consumption of a region in order to easily compare what's been produced with what's been used.

**Comment by jarek** [comment]
Hi Lars, does the toggle in top left corner of the screen do what you mean? It also switches the country details view between "Electricity production" and "Electricity consumption"

![image](https://user-images.githubusercontent.com/47415/62468738-c6b6eb80-b764-11e9-9aa4-725d044b25bb.png)

![image](https://user-images.githubusercontent.com/47415/62469283-ed295680-b765-11e9-9d5a-1593a85c62dc.png) ![image](https://user-images.githubusercontent.com/47415/62469309-fa464580-b765-11e9-97bc-26bfe06c779c.png)

**Comment by lars974** [comment]
OK,

you've split it into two areas of selection.

Thanks !
