### ISSUE TITLE
ENTE exchanges no longer work

### ISSUE THREAD

**Issue by systemcatch** [tmrowco/electricitymap-contrib#1930]
The enteoperador site has undergone a big refresh and the old url from which we scraped data no longer works (http://www.enteoperador.org/newsite/flash/data.csv)

New site + map
https://www.enteoperador.org/flujos-regionales-en-tiempo-real/

The map above is populated by data from the url below
https://mapa.enteoperador.org/WebServiceScadaEORRest/webresources/generic

Looks like they've moved from csv to json and also added a load more data to the graphic. This likely means rewriting some of the ENTE parser.

**Comment by scriptator** [comment]
Unless somebody different can do it earlier, I will approach this in about two weeks from now.

**Comment by systemcatch** [comment]
@scriptator I will make a start on this one.

**Comment by S3rbane** [comment]
Does anyone have a copy of the old .CSV file for reference out of curiosity?

**Comment by alixunderplatz** [comment]
@S3rbane I'll see if I can find it in my files.
