### ISSUE TITLE
Add total CO2 by country/región (GWh*CO2)

### ISSUE THREAD

**Issue by pangusion** [tmrowco/electricitymap-contrib#1933]
Hell

First of all, congratulations for your webpage. You are doing a great great job.

My sugestion concerns following topic.

There are some country/regions with high carbon intensity like Bolivia. They look horrible in dark Brown color (500 CO2eq/KWh). Other countries like Germany or Spain look much better because they generate less CO2 by KWh (250gr). However, electricity map doesn't take into account total power generated by country.

Germany generates 60 GWh.
Bolivia only 2 GWh.

That means total CO2 generated is:
Bolivia generates 500gr * 2GWh= 1.000.000.000 gr (1k ton/hour).
Germany generates 250gr * 60GWh = 15.000.000.000 gr (15k ton/hour).

Germany generates more CO2 bit looks better.

Sugestion:

Add new layer to show total CO2 generated by country/region. Fórmula: CO2eq/KWh * KWh generated. Results would be normally hundreds or thousands of CO2 tons/hour.

Alternatively, just show how many GWh generates each country. Germany or California would look brighter than Bolivia or new England.

Thank you in advance,

Diego Pangusión

**Comment by jarek** [comment]
Hi Diego, thanks for the comment. Please see some of the issues in https://github.com/tmrowco/electricitymap-contrib/issues?utf8=%E2%9C%93&q=sort%3Aupdated-desc+per+capita for some past discussion of total emissions and per-capita emissions.

Also note that while it's not on a map, you can see a region's total emissions per minute with the "Carbon emissions" switch:

![image](https://user-images.githubusercontent.com/47415/62989412-ce862800-be15-11e9-8048-03e57c280a72.png)

**Comment by pangusion** [comment]
Hi

Thank you for this information. 
I didn't know that total emissions was already available.

After checking discussion about "carbón per capita / carbón per country": (https://github.com/tmrowco/electricitymap-contrib/issues?utf8=%E2%9C%93&q=per+capita).

I also think that carbón by population is a good idea  (better than mine). 
You can close this topic.

Note: I have the feeling that electricitymap Project could have exceded its original goal (like "where to plug my electrical car"). I understand that a new map with "carbon by population" could have political implications and be out of the scope, but "veritas liberat nobis" :-) 
It will depend on electricity map decission.
