### ISSUE TITLE
US-PJM has SSL certificate issues

### ISSUE THREAD

**Issue by systemcatch** [tmrowco/electricitymap-contrib#1936]
I keep seeing this error for any parsers attempting to contact the pjm.com domain, but can't reproduce it locally is the EM server using a different version of requests to the one specified in requirements (2.20.1)?

Logger
```shell
HTTPSConnectionPool(host='www.pjm.com', port=443): Max retries exceeded with url: /markets-and-operations.aspx (Caused by SSLError(SSLError(1, '[SSL: DH_KEY_TOO_SMALL] dh key too small (_ssl.c:852)'),))
```

curl
```shell
(EM) chris@ThinkPad:~/electricitymap$ curl -v https://www.pjm.com/markets-and-operations.aspx*   Trying 192.251.13.151...* Connected to www.pjm.com (192.251.13.151) port 443 (#0)* found 148 certificates in /etc/ssl/certs/ca-certificates.crt* found 604 certificates in /etc/ssl/certs* ALPN, offering http/1.1* SSL connection using TLS1.2 / DHE_RSA_AES_256_GCM_SHA384*      server certificate verification OK*      server certificate status verification SKIPPED*      common name: *.pjm.com (matched)*      server certificate expiration date OK*      server certificate activation date OK*      certificate public key: RSA*      certificate version: #3*      subject: C=US,ST=Pennsylvania,L=Norristown,O=PJM Interconnection LLC,OU=Networking and Telecommunications,CN=*.pjm.com*      start date: Wed, 23 May 2018 00:00:00 GMT*      expire date: Sun, 26 Jan 2020 12:00:00 GMT*      issuer: C=US,O=DigiCert Inc,OU=www.digicert.com,CN=GeoTrust RSA CA 2018*      compression: NULL
```

Looks like the `DHE_RSA_AES_256_GCM_SHA384` cipher is considered weak, we'll have to manually allow it in urllib3, setting `verify=False` won't fix this.

**Comment by corradio** [comment]
It also happens with US-SPP.

**Comment by corradio** [comment]
Can't reproduce locally using `python3 test_parser.py 'US-PJM' production`
I have Python 3.7.2 and requests==2.18.4
I suspect it has something to do with our containerised environment. Maybe the OpenSSL version is wrong.

**Comment by corradio** [comment]
Found the problem. Apparently we needed to lower our security requirements. See https://github.com/home-assistant/home-assistant/issues/19683#issuecomment-451132346
and https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=907807

**Comment by corradio** [comment]
Works!
