### ISSUE TITLE
UK battery storage

### ISSUE THREAD

**Issue by aarbur** [tmrowco/electricitymap-contrib#1937]
Hi,

Why does UK battery storage show simply as a question mark?

The following link claims that "as of June 2019, there is currently 700MW of large scale battery storage installed in the UK" but I don't know where they got that information.
https://www.solarpowerportal.co.uk/blogs/uk_battery_storage_capacity_could_reach_70_growth_in_2019_as_business_model

It'd be fascinating to have the battery storage contribution shown here.

On a slight tangent it's curious that it's split specifically into "hydro storage" and "battery storage" when clearly there are many possible technologies to "store" electricity. Is this limited by how the official data sources break things down?

Regards,
Aaron.

**Comment by systemcatch** [comment]
Hello @aarbur, you can see in https://github.com/tmrowco/electricitymap-contrib/blob/master/parsers/ELEXON.py#L44 how we do the mapping for the UK. There's no specific category for battery storage in the data so I imagine it is part of the the  `Other` category which is currently being mapped to unknown.

**Comment by systemcatch** [comment]
Not really ideal that storage is going to unknown but until a better data source is found not much is going to happen here.
