### ISSUE TITLE
USA hourly generation by fuel type is now available

### ISSUE THREAD

**Issue by systemcatch** [tmrowco/electricitymap-contrib#1941]
The EIA have just released a new visualization for the USA Electric Operating System. One of the graphs is hourly generation by fuel type for the lower 48 states! From a quick glance it appears to lag behind by about a day but it's still hugely useful! :tada: 

https://www.eia.gov/beta/electricity/gridmonitor/dashboard/electric_overview/US48/US48

It also seems like you can drill down into individual balancing authorities and get the exact same data (hourly by type D-1), for instance checkout [Tennessee Valley Authority](https://www.eia.gov/beta/electricity/gridmonitor/dashboard/electric_overview/balancing_authority/TVA)

API Guide (https://www.eia.gov/realtime_grid/docs/userguide-knownissues.pdf)

**Comment by PETILLON-Sebastien** [comment]
That's really interesting !
Which precision do we want in zones ? Do we need to redefine the zones ?
I'd be OK to work on this on my spare time with one of you.

**Comment by systemcatch** [comment]
@PETILLON-Sebastien I think the zones as drawn are currently ok, since this data is lagging behind by 5-10 hours it won't show up on the map. It's more for filling in the database.

Happy to work on this with you.

**Comment by PETILLON-Sebastien** [comment]
Fine for the zones !
Oh too bad the lag is big. Do you know if it will be improved ?
Tell me if you fork the project, this way I'll join it. Hope I'll have enough time to contribute significantly.

**Comment by systemcatch** [comment]
I'll create a branch on the main repo, that way it's easily accessible.

**Comment by systemcatch** [comment]
Closing this for now as everything has been done I think?

@robertahunt might be useful for the big scrape you guys are planning.
