### ISSUE TITLE
where is Swedish 37 g from?; using different emission levels

### ISSUE THREAD

**Issue by rzm1** [tmrowco/electricitymap-contrib#1947]
Sweden is supposed to have emission of 37 g but practically all her sources are below that level of emission. I could find only 95% of sources. Maybe because of rounding. The sum of nuclear, wind, water, NO1, NO2, NO3 is:
.31*12 + .11*11 + .45*24  + .05*28 + 0.02*39 + 0.01*53 = 18.4 g
The missing 5% would have to have 380 g of emission to raise the sum to 37 g.

Another strange thing is import of 0% from Germany with… 37 g emission while Germany has 306 g now. Anyway it should not count as it is 0.00 W.

Those emission levels are not always realistic anyway. E.g. 230 g for biomass is overly optimistic. Also wind compensating gas may have higher emission than gas burned steadily. I have an idea to introduce switches for such variants or private profiles with possibility of using own data on emission.

**Comment by jarek** [comment]
Take a look at the "carbon emissions" view - 51% of emissions come from the 5% "unknown" source:

![image](https://user-images.githubusercontent.com/47415/64127328-2530b300-cd7f-11e9-9692-0c088f9c8cc3.png)

Import from Germany is 2.08 MW as I write this. Possibly it was something like 0.004 MW when you were looking, rounded down.

The CO2 intensity values are median values from IPCC, see second paragraph in https://github.com/tmrowco/electricitymap-contrib#carbon-intensity-calculation-and-data-source

See #738 for ongoing preparation for using better region- or country-specific CO2 intensities

**Comment by rzm1** [comment]
Thanks. I have overlooked this "unknown" factor.

I know that standard intensities are from IPCC 2014 but they are not always realistic when whole hectares of woods are cut to be transported overseas and burned.

**Comment by jarek** [comment]
For what it's worth, per the table in https://github.com/tmrowco/electricitymap-contrib/issues/738#issuecomment-499397532 (data ultimately comes from [Ecoinvent](https://www.ecoinvent.org/)) SE's biomass intensity should actually be 53.8 g/kWh, so a fair bit _lower_

**Comment by jarek** [comment]
I'm closing this issue as it seems like it's best addressed by using Ecoinvent's data in #738. Please reopen if you have further questions!
