### ISSUE TITLE
Add DK-DK1->NL new interconnector

### ISSUE THREAD

**Issue by corradio** [tmrowco/electricitymap-contrib#1949]
It is available from ENTSOE (although it shows no data obviously as it hasn't been put in operation).
It'd be great to have it ready when it opens!
cc @martincollignon

**Comment by PaulCornelissen** [comment]
I think this one can be closed:
<img width="700" alt="image" src="https://user-images.githubusercontent.com/5185181/64697361-fadaa600-d4a0-11e9-87ef-1eb7a1fc6cea.png">

**Comment by corradio** [comment]
Great!
