### ISSUE TITLE
Slovenia lacks amount of installed MW for hydro storage also wind is too low.

### ISSUE THREAD

**Issue by seba1337** [tmrowco/electricitymap-contrib#1956]
The capacity for the only hydro storage plant of Slovenia is 185 MW when consuming and 180 MW when emitting energy. Source: https://www.seng.si/en/hydropower-plants/pumped-storage-hydropower-plant/

Wind should be at least 3,5 MW (source: https://www.delo.si/gospodarstvo/infrastruktura/zakaj-slovenci-ne-marajo-vetrnih-elektrarn.html), or even 4,93 MW according to the latest official statistics: https://pxweb.stat.si/SiStatDb/pxweb/sl/30_Okolje/30_Okolje__18_energetika__03_18176_elektricna_energija/1817604S.px/. There are two main ones, 2,3 MW and 0,91 MW, that's 3,21 MW in total, but a lot of smaller ones (~50 kW) were added over time (e.g. on petrol stations, power transformers buildings) and it adds up.

Nuclear is 688 MW and not 690 MW anymore (they had to remove 4 fuel rods and replace them with metal ones due to turbulence). Source: gov statistics, same as for wind before (+news articles in my head from few years ago).

There are no geothermal plants, so that should be 0 MW. Geothermal energy is used, but for now only for heat. (source: https://www.i-energija.si/ienergija/energetika-v-sloveniji-in-svetu-statistika/, http://www.geologija-revija.si/dokument.aspx?id=1152).

Also there's no battery storage or oil fired power plants, so that's 0 MW as well, but I find no good source for that. There were some that could fire fuel oil in the past, but that's all gas now (or a few biomass).

**Comment by jarek** [comment]
Thanks for the report! Partial response:

690 MW for nuclear is currently reported to ENTSO-E. Maybe they are overclocking?

In https://github.com/tmrowco/electricitymap-contrib/blob/master/config/zones.json#L3447 it says that hydro capacity includes 180 MW of pumped storage. Perhaps this is because pumped consumption/production is not reported separately to ENTSO-E? We would have to double check.

3-5 megawatt of wind unfortunately won't really show up, currently biomass is 11 MW and it's this tiny tiny sliver:

![image](https://user-images.githubusercontent.com/47415/64574605-1e391000-d33e-11e9-9d26-fee21ea12ac5.png)

3 MW of wind is actually specified in https://github.com/tmrowco/electricitymap-contrib/blob/master/config/zones.json#L3467 but it's so small it doesn't show up on the webpage.

**Comment by seba1337** [comment]
I'm aware that wind power is too little to show on the linear graph. I was just reffering to the 3.00 MW which you can see if you hover over wind. According to the latest gov. data it should be 4,9 MW, although even if I sum the main two power plants and add a few smaller ones that I know they exist it could sum maybe to 3,5 MW, so 4,9 MW is a bit of a stretch, so I started to wonder...

I'm starting to think that the government's data isn't true, so maybe ENTSO-E's 3 MW is closer to reality. Also I went from wind turbine to wind turbine and a lot of these smaller ones (~50 kW) were removed. No idea where they get the data from. 

So I went googling and I've found a good source though, https://www.borzen.si/sl/Domov/menu2/Center-za-podpore-proizvodnji-zelene-energije/Poro%C4%8Dila-in-podatki/Podatki

But then again this source is just about, who is getting subsidy money and for how much kW. Seems that the total amount of windpower in Slovenia is at least 3283 kW.

I don't know anymore what's true or not, but I do know now, that there isn't any good source on this data and that the people here hate wind power. Not sure why. For solar there are way better sources.

Also I've double checked on other sources for the nuclear plant and it is seems to be 696 MW on the web page of the plant, weird. Maybe for that let's stick with what it's now.

![slika](https://user-images.githubusercontent.com/37665002/64593912-43b23200-d3af-11e9-942a-2d584d68d991.png)
(veterne = wind, sončne = solar, jedrske = nuclear)

**Comment by seba1337** [comment]
Anyway, this is my proposal:

https://github.com/tmrowco/electricitymap-contrib/compare/master...seba1337:patch-2

**Comment by systemcatch** [comment]
@seba1337 feel free to open a pull request with your changes.
