### ISSUE TITLE
Croatia daily solar generation forecast available

### ISSUE THREAD

**Issue by seba1337** [tmrowco/electricitymap-contrib#1966]
Croatia has publicly available data (in excel :cry:) about the forecast of daily solar power generation.
https://www.hrote.hr/planning-electricity-production-for-the-eco-balance-group (at the bottom)

We could use this data and further refine the Croatia's unknown.

On ENTSOE for example Slovenia most likely reports similar data i.e. forecast. If I check the data generated for today I can see the solar MW for whole day even though it's only 9 AM, but not for other power sources.

**Comment by systemcatch** [comment]
We might be able to bypass the excel by using the json url (https://files.hrote.hr/files/EKO_BG/FORECAST/SOLAR/FTP/TEST_DRIVE/22.9.2019.json) which supplies data for the graphs.

**Comment by zilefaith** [comment]
Great and very informative post. I really appreciate your effort in this post. I got it what you have tried to explain about [Solar panels ](https://estimate.solar)devices.

**Comment by OlgaCh** [comment]
Hello
I have large experience in web-scraping/data parsing.
Would love to work on this issue during `hacktoberfest`.
If you're ok with it could you please assign an issue to me? Thanks a lot!

**Comment by martincollignon** [comment]
Hi Olga - sounds great! Would you start working on it now? Otherwise let me know when you start working on it and I'll assign it to you then :-)

**Comment by OlgaCh** [comment]
@martincollignon I was planning to start working on it this weekend but should submit PR in October to stay compliant with the rules.

**Comment by martincollignon** [comment]
I'll assign it to you then. I'll remove it on October 1st if not PR'ed/heard from you to let others help out :)

**Comment by OlgaCh** [comment]
@martincollignon writing just to let you know that work is on track. Will submit PR tomorrow :)
