### ISSUE TITLE
Costa Rica data, official source

### ISSUE THREAD

**Issue by Mario500X** [tmrowco/electricitymap-contrib#1972]
Hello Guys, 
Just want to point out theres an official source for data from Costa Rica at 

https://apps.grupoice.com/CenceWeb/CencePosdespachoNacional.jsf

where data is published daily.  Its from our electricity dispatch center and lists all the generation plants operating in Costa Rica, daily. 

I downloaded it to excel and attached plant type (hydro, wind, etc. ) and on "emission factors" tab, put the emission factors from last year.  So country emission factor can be programmed easily.  Hope that works for you. Daily generation information can be reached at the link above. 

There's a few cases where one reservoir serves to cascading plants. I point it out in the excel where appropriate. 

[2019-09-26 Generacion_Real_MWh.xlsx](https://github.com/tmrowco/electricitymap-contrib/files/3663546/2019-09-26.Generacion_Real_MWh.xlsx)

We plant to publish this online later next year making it even easier for you to compare Costa Rica with others in your map.  electricitymap, btw,  is very handy for comparisons. 

Best regards, 

Mario Montero

**Comment by martincollignon** [comment]
Nice @Mario500X! Do you work for the Costa Rican government? If yes, do you have contacts in other countries? Feel free to DM me on our slack (slack.tmrow.com)

**Comment by jarek** [comment]
We actually have a Costa Rica parser https://github.com/tmrowco/electricitymap-contrib/blob/master/parsers/CR.py which uses that very page, however it seems to be out of date right now - possibly a new power plant has been added that needs handling on our side

**Comment by madsnedergaard** [comment]
The parser for Costa Rica is running and should be fine, so closing this issue - feel free to reopen if anyone finds it can be improved further :)
