### ISSUE TITLE
Create Alexa skills for ElectricityMap

### ISSUE THREAD

**Issue by martincollignon** [tmrowco/electricitymap-contrib#1976]
ElectricityMap could become an action on Alexa.

https://developer.amazon.com/docs/ask-overviews/build-skills-with-the-alexa-skills-kit.html

We do not know a lot about it, so any pointers and help would be great. DM me on [Slack](slack.tmrow.com)!

**Comment by kenseii** [comment]
Hey, i am interested on contributing on this, do you mind sharing more details about it? thanks

**Comment by corradio** [comment]
Closing as we won't be able to support it. Asks us on Slack if you're interested in building this!
