### ISSUE TITLE
Dashboard for Aruba displaying 0 MW - contact data provider

### ISSUE THREAD

**Issue by alixunderplatz** [tmrowco/electricitymap-contrib#1984]
The dashboard displays "0.0 MW" for any of the production types of the island of Aruba:
https://www.webaruba.com/renewable-energy-dashboard/aruba

@martincollignon Would you drop them a message and ask for a fix of the dashboard? Or should somebody else do it?

**Comment by martincollignon** [comment]
Sent them an email.

**Comment by martincollignon** [comment]
For the interested, this is the email I sent:

> 
> Hello xxx
> 
> I'm reaching out on behalf of the [electricityMap project](electricitymap.org), a website visited by millions of visitors every year that helps people understand the carbon intensity (CO2 emissions) derived from electricity around the world.
> 
> We used to be able to get some data from source (link to the source), but it doesn't seem to work anymore.
> Would you mind helping us or telling me who I should contact?
> 
> Kind regards,

**Comment by S3rbane** [comment]
https://www.webaruba.com/renewable-energy-dashboard/app/rest/results.json

This is where the data is pulled from, seems there's a error server side.

**Comment by alixunderplatz** [comment]
Data is back and so is Aruba on the map.
Closing.
