### ISSUE TITLE
Add source for thermal energy

### ISSUE THREAD

**Issue by timrodz** [tmrowco/electricitymap-contrib#1986]
I have noticed quite a few countries (Mainly Latin America) use thermal as their sources of energy. Instead of it being parsed to `unknown`, this energy type could be added to the source dictionary.

Unless the best way to go about this is to assign it another source type, e.g. `geothermal`?

Currently:
```python
MAP_GENERATION = {
    'Hídrica': 'hydro',
    'Eólica': 'wind',
    'Solar': 'solar',
    'Biogas': 'gas',
    'Térmica': 'unknown'
}
```

Could become:
```python
MAP_GENERATION = {
    'Hídrica': 'hydro',
    'Eólica': 'wind',
    'Solar': 'solar',
    'Biogas': 'gas',
    'Térmica': 'thermal'
}
```

**Comment by corradio** [comment]
Hi @timrodz (cc @martincollignon )
It's a good idea. However, we've made the choice I long time ago that we'd like to differentiate the source of fuel (coal/gas/biomass/geothermal..) as thermal sources have different emissions based on what fuel is used.
This is why it makes sense to resort to "unknown" when the actual fuel is not known (even though we know it is thermal).

Note that it is possible to have specific emission factors for the "unknown" category, that assume a given breakdown of fuel sources.
