### ISSUE TITLE
[UI Issue] "color blind mode" checkbox text misalignment

### ISSUE THREAD

**Issue by Chopinsky** [tmrowco/electricitymap-contrib#2009]
It seems that the "color blind mode" checkbox's text is slightly misaligned with the box. This should be fixable with some CSS. 

- Chrome
![image](https://user-images.githubusercontent.com/5376280/66142465-0bc39680-e5cb-11e9-93a5-0ff03ecc899e.png)

- Firefox
![image](https://user-images.githubusercontent.com/5376280/66142813-c489d580-e5cb-11e9-9d34-967a5a31eb21.png)

- Edge
![image](https://user-images.githubusercontent.com/5376280/66142870-d9666900-e5cb-11e9-8899-0a20881d50e0.png)

In addition, it seems that the checkbox is quit buried in the lower right corner of the sidebar, making it less accessibility-friendly. 

Ideally, we probably should make it into a toggle button along with right side toggle buttons (e.g. right below the dark-mode button), but at least we can make the checkbox larger and right beneath the country selection list.

**Comment by lanpai** [comment]
Could I handle this?

**Comment by ystanwar** [comment]
Hi cab I take this issue

**Comment by fbarl** [comment]
It seems that #2010 addressed this issue for the desktop mode:

![image](https://user-images.githubusercontent.com/5376280/66222550-0a5fa000-e697-11e9-8a7c-8c233a69472c.png)

So the only piece of work left is to update the mobile view with the same styles:

![image](https://user-images.githubusercontent.com/1216874/72525941-90c67900-3865-11ea-98ea-e0d9bfc9c831.png)

**Comment by corradio** [comment]
OK. Closing this issue. feel free to re-open if the issue reappears
