### ISSUE TITLE
Hydro Storage Emissions

### ISSUE THREAD

**Issue by cmikovits** [tmrowco/electricitymap-contrib#2012]
Regarding Hydro Storage Emissions:
- why are hydro storages emitting CO2equ? Even if in the case of pumped hydro storages the water was pumped with e.g. energy from coal, this was already emitted and is not emitted again
- in e.g. Austria the pumping capacity is much lower than the production capacity, as most storages are fed by natural water inflow.

So these numbers are afaik not correct.

Keep up the good work. C

**Comment by jarek** [comment]
Hello,

See #1883 for details on how storage emissions are accounted, and about Austria's "storage".

**Comment by cmikovits** [comment]
Thanks, this explains the issue.

**Comment by jarek** [comment]
Great, thanks for dropping by and asking!

**Comment by cmikovits** [comment]
As for the hydro pumped storage accounting: entso-e lists also the amount of energy used for pumping. Maybe this could be considered instead?
