### ISSUE TITLE
Two taps on tab bar button are required

### ISSUE THREAD

**Issue by corradio** [tmrowco/electricitymap-contrib#2029]
To reproduce:
1. open the mobile app
2. drag the map
3. press on "Areas" or "About" tab bar button
4. the button changes color, but is not "clicked" before a second tap is done. Expected behavior: one tap should be enough.

Tested on my iPhone 8 in the mobile app. Doesn't seem to happen on the web though (tested through Chrome).
Question: does it also happen on Android in the app/on the web?

cc @FelixDQ FYI

**Comment by sventropy** [comment]
Verified on IPhone 8 Plus in the app, not in Safari

**Comment by corradio** [comment]
I'm re-opening as two related bugs appeared:
- on the app, nothing happens when I press "Area"
- on the web on a phone, the bug described in this issue happens for "Area" only.
@FelixDQ maybe you know what happened?

**Comment by FelixDQ** [comment]
Ah damn, I see my mistake. I copied "touchend" into the wrong place on the area button 😬https://github.com/tmrowco/electricitymap-contrib/pull/2040/files#diff-42c3276bc26032ecad9d7061dd401cd4R972

I will make a new PR
