### ISSUE TITLE
Data for Nepal 

### ISSUE THREAD

**Issue by Subarna578** [tmrowco/electricitymap-contrib#2041]
Nepal hasn't have real-data power transmission system online yet. Nepal produces most of the energy from Hydropower projects and some from the boarder area of India.
The given link provides the hydropower projects that are in use in Nepal.
https://www.doed.gov.np/download/GIS-map-of-reservoir-projects.pdf

The below link provides the electricity production projects between Nepal and India..
https://www.cptcindia.com/nepal/projects/

So, are these two documents sufficient to add Nepal in the electricitymap? Note that, it still hasn't real time tracking power transmission system.

**Comment by systemcatch** [comment]
> So, are these two documents sufficient to add Nepal in the electricitymap? Note that, it still hasn't real time tracking power transmission system.
No but you can add capcity data for Nepal if you like?

**Comment by Subarna578** [comment]
Yes, it still hasn't real time tracking power transmission system.
Can you help me how I can add capacity data for Nepal?

**Comment by systemcatch** [comment]
Capacities go in https://github.com/tmrowco/electricitymap-contrib/blob/master/config/zones.json, you might need to add the Nepal zone first.

**Comment by Subarna578** [comment]
Can you please tell me the values in the bounding box at zones.json?

**Comment by systemcatch** [comment]
80, 25.767 and 88.183, 30.45 using https://data.humdata.org/dataset/bounding-boxes-for-countries
