### ISSUE TITLE
CO2 emission factors for power production from cogeneration powerplants

### ISSUE THREAD

**Issue by nielsanso** [tmrowco/electricitymap-contrib#2044]
I have some questions about the CO2 emission factors used for thermal power production.

Why doesn´t Electricitymap consider whether the power is produced with or without heat utilization from thermal power plants? Eg. cogeneration is widely used in Denmark, where the waste heat is utilization in connection with approx. 75% of electricity generation from thermal power plants. That means, that the energy in the fuel is utilized approx. twice as much, resulting in halving CO2 emissions per kWh.

And besides, why does Electricitymap use the same emission factor for biomass, 230g/kWh, no matter where in the world electricity is produced from biomass and whatever type of biomass is used? There is a very large difference in CO2 emissions from biomass as a primary resource, for example. wood pellets and wood chips are very low compared to the ICCP 2014 median of 230 g CO2 / kWh. Eg. the direct net CO2 emission from Ørsted's biomass fired power plants was in 2017 just 44.2 g CO2 / kWh, weighted average at 75% share of cogeneration, and 25% pure electricity generation. That´s around one 5th of the number used in Electricitymap.

If you consider here that much biomass is residual products, e.g. from timber production, straw or manure, one can argue that net CO2 emissions are even lower.

How does Electricitymap recognize CO2 emissions from cogeneration from biogas (bio methane), either as pure biogas or upgraded biogas fed into the natural gas network?

I would suggest that the emission factors would be differentiated and adjusted in terms of total efficiency from thermal power plants, as well as for biomass, differentiated according to the actual type of biomass used.

Best regards
Niels Ansø

**Comment by corradio** [comment]
Related to https://github.com/tmrowco/electricitymap-contrib/issues/738

**Comment by robertahunt** [comment]
Hi Niels, just to follow up on this, we try to adjust the country-specific CO2 emissions where we can find data for it. You can see those adjustments in https://github.com/tmrowco/electricitymap-contrib/blob/master/config/co2eq_parameters.json . Biomass is a case where we have not made any country-specific adjustments. If you can provide a new source of biomass emissions factors for a specific country, we would be happy to update it and improve our numbers! For now, I am closing this as I think it is covered by #738, which we are continuing to look into.
