### ISSUE TITLE
Denmark's installed capacity of coal is too high

### ISSUE THREAD

**Issue by nikBeier** [tmrowco/electricitymap-contrib#2050]
The area "West Denmark (Denmark)" (a.k.a. DK1 in Nordpool energy trading market) is shown at electricitymap.org to have a coal capacity of 2.3 GW installed capacity.
Likewise the area "East Denmark (Denmark)" (a.k.a. DK2 in Nordpool energy trading market) is shown at electricitymap.org to have 2.07 GW installed capacity of coal.
Where are the values taken from?

In West Denmark, there is Esbjerg, Aalborg, Odense still left burning coal of 407+411+362=1180 MW (Studstrup that potentially could switch back to coal was 760 MW before its rebuild) Studstrup is now listed as 730 MW by ENTSOE

In East Denmark, there is Amager 3 and Asnæs of 263+(147+270+640)=1320 MW.

A good secondary source of installed capacity is https://beyond-coal.eu/wp-content/uploads/2019/07/2019-07-22_Europe_Beyond_Coal-European_Coal_Database_hc.xlsx . The values from ENTSOE are slightly lower for “fossil hard coal” (as Nordjyllandsværket unit 3 is listed as 411 and 407 MW respectively. 
ENTSOE data found on https://transparency.entsoe.eu/generation/r2/installedGenerationCapacityAggregation/show 
 for DK1:
https://transparency.entsoe.eu/generation/r2/installedGenerationCapacityAggregation/show?name=&defaultValue=false&viewType=TABLE&areaType=BZN&atch=false&dateTime.dateTime=01.01.2019+00:00|UTC|YEAR&dateTime.endDateTime=01.01.2020+00:00|UTC|YEAR&area.values=CTY|10Y1001A1001A65H!BZN|10YDK-1--------W&productionType.values=B01&productionType.values=B02&productionType.values=B03&productionType.values=B04&productionType.values=B05&productionType.values=B06&productionType.values=B07&productionType.values=B08&productionType.values=B09&productionType.values=B10&productionType.values=B11&productionType.values=B12&productionType.values=B13&productionType.values=B14&productionType.values=B20&productionType.values=B15&productionType.values=B16&productionType.values=B17&productionType.values=B18&productionType.values=B19 

Is it correctly understood that the capacity values are manually updated and written into the file https://github.com/tmrowco/electricitymap-contrib/blob/master/config/zones.json ?

From ENTSOE database:
- DK-DK1 coal 2019: 1915 MW
 https://github.com/tmrowco/electricitymap-contrib/blob/0cb0c438172890003a63b6e0ca0dccea994d3061/config/zones.json#L1042 
- DK-DK2 coal 2019: 1741 MW
 https://github.com/tmrowco/electricitymap-contrib/blob/0cb0c438172890003a63b6e0ca0dccea994d3061/config/zones.json#L1081 
- Total coal in whole Denmark, 2019-10-20: 3656 MW hard coal
 https://github.com/tmrowco/electricitymap-contrib/blob/0cb0c438172890003a63b6e0ca0dccea994d3061/config/zones.json#L980 

These values align with other publicly information available at the web sites maintained by the operators and the database at beyond-coal.eu .

Next update: Around January 2020 another coal fired unit in Copenhagen will be decommissioned.

**Comment by nikBeier** [comment]
In the file zone.json it seems there still is a section and zone for Denmark as a whole. Is it still used?

**Comment by nikBeier** [comment]
How about adding a comment after relevant values, containing the source reference, like 
“# Source: ENTSOE 2019” or the longer
”# source: https://transparency.entsoe.eu/generation/r2/installedGenerationCapacityAggregation/show 
 2019” ?

I did not find anywhere that mentions which values are sourced/copied/cited/referenced from where? Maybe the current figures for Denmark  are from ENTSOE year 2017? But how about the biomass capacity, as there clearly are power plants using biomass as fuel, but not counted as such in the figures from ENTSOE (I guess the values given to ENTSOE database is chosen so no capacity is counted twice, even for plants and units that are capable of burning more than one fuel, for example both wood chips and coal.)

**Comment by corradio** [comment]
Hi @nikBeier ,

The capacity sources are listed at https://github.com/tmrowco/electricitymap-contrib#production-capacity-data-sources
For this case, it's ENTSOE. Are you able to update those capacities and maybe have a better reference so we also add the year?

Thanks!

Olivier

**Comment by systemcatch** [comment]
@nikBeier for reference we show all the capacity sources in https://github.com/tmrowco/electricitymap-contrib#production-capacity-data-sources

**Comment by nikBeier** [comment]
Related pull request, that updates existing values, but still omits waste and other renewables (and Bornholm):  https://github.com/tmrowco/electricitymap-contrib/pull/2093

**Comment by systemcatch** [comment]
Now that the capacities have been updated this can be closed.
