### ISSUE TITLE
Czech data source is stuck

### ISSUE THREAD

**Issue by alixunderplatz** [tmrowco/electricitymap-contrib#2053]
Data for the Czech Republic has been absolutely constant in the last days on data provider entsoe.

Should we implement some sort of check to prevent parsing such data (like "if 3 hours in a row for a zone are exactly the same, then dismiss all of it and report warning")

![image](https://user-images.githubusercontent.com/25743609/67239835-658fe180-f450-11e9-81ce-e30904f25dfc.png)

![image](https://user-images.githubusercontent.com/25743609/67239687-0df17600-f450-11e9-9348-f03c72850a59.png)

**Comment by systemcatch** [comment]
I think Max created a function to check if the diff was too big a while this a while back. Maybe we could add one for static checking as well.

**Comment by scriptator** [comment]
The source at #1899 does not appear to be stuck. Maybe it's the right time to switch data source?
