### ISSUE TITLE
Historical Data for region Kazakhstan (KZ, KAZ) 2016, 2017, 2018

### ISSUE THREAD

**Issue by steppefox** [tmrowco/electricitymap-contrib#2057]
## Country

Kazakhstan

## KZ Gov Agency and Power company

![image](https://user-images.githubusercontent.com/4667275/67295843-f8c82600-f4e7-11e9-9dc7-d8f1dcf18691.png)

JSC "Samruk Energy"

Links: 
https://www.samruk-energy.kz/en/
https://www.facebook.com/samrukenergy/
https://twitter.com/SamrukEnergy

Contacts Page:

https://www.samruk-energy.kz/en/company/contact

## Description

Here are two Government agency reports for 2017 and 2018:
http://eenergy.media/wp-content/uploads/2018/02/analiz-rynka-elektroenergii-kazakhstana-za-2017.pdf - 2017
http://ar2018.samruk-energy.kz/ru/015.html - 2018

## Screenshots

Production 2016-2017, millions kWh

![image](https://user-images.githubusercontent.com/4667275/67294721-78ed8c00-f4e6-11e9-8516-6895ba6340f4.png)

Consumption by region 2016-2017, millions kWh

![image](https://user-images.githubusercontent.com/4667275/67294900-bc47fa80-f4e6-11e9-834b-59984231313a.png)

Country Production/Consumption by type of energy 2016-2018:

![image](https://user-images.githubusercontent.com/4667275/67295281-34162500-f4e7-11e9-8bda-a0f22265af7d.png)

## Proper translated Text representation

TBD

**Comment by systemcatch** [comment]
Hello @steppefox, we need hourly data or better for a country to show up on the map. This kind of yearly average would only be useful for estimating the CO2 intensity of a country where we have net generation only.

**Comment by robertahunt** [comment]
Closing this as we need hourly data :(
