### ISSUE TITLE
"Select language" menu has inconsistent capitalisation

### ISSUE THREAD

**Issue by Ogaday** [tmrowco/electricitymap-contrib#2062]
The names of some languages are capitalised and others are not. This looks inconsistent:

![image](https://user-images.githubusercontent.com/6689770/67429679-91d66a00-f5d8-11e9-95ce-70bda3ca1b6e.png)

I suggest that they should all be capitalised - this also matches how Wikipedia handles language names, for instance:

![image](https://user-images.githubusercontent.com/6689770/67429869-f42f6a80-f5d8-11e9-85f1-3e6c79d66c3f.png)

**Comment by leternoz** [comment]
Hi, may I take this one ?

**Comment by Ogaday** [comment]
Sorry @leternoz, I already made a PR but I messed up the commit message so the PR wasn't linked to this issue.

**Comment by leternoz** [comment]
ok fine

**Comment by jarek** [comment]
This has now been merged in #2063, closing issue
