### ISSUE TITLE
Data for Macedonia (24 h sum)

### ISSUE THREAD

**Issue by seba1337** [tmrowco/electricitymap-contrib#2082]
I've found this: http://www.elem.com.mk/?1/&lang=en
Related to this: https://github.com/tmrowco/electricitymap-contrib/issues/1059

They generate each day how much MWh they generated by thermal, wind and hydro plants. The data is stored in HTML as such:
`<div class="wen-skill-charts-wrap">
              
    <div class="wen-skill-circle" id="wsc-474-5dbb51a852106">
                      <div class="skill-wrap">
                    <div class="skill-title">THERMAL POWER PLANTS</div>
                              <div class="skill-circle-wrap" data-percent="72" data-barcolor="#e41920">
                          <span class="skill-percentage" style="color:#003d7e;"></span>
                      </div>
                              <div class="skill-description">7566 MWh</div>
          
        </div>
                      <div class="skill-wrap">
                    <div class="skill-title">HYDRO POWER PLANTS</div>
                              <div class="skill-circle-wrap" data-percent="26" data-barcolor="#0397d9">
                          <span class="skill-percentage" style="color:#003d7e;"></span>
                      </div>
                              <div class="skill-description">2755 MWh</div>
          
        </div>
                      <div class="skill-wrap">
                    <div class="skill-title">windmill</div>
                              <div class="skill-circle-wrap" data-percent="2" data-barcolor="#96c137">
                          <span class="skill-percentage" style="color:#003d7e;"></span>
                      </div>
                              <div class="skill-description">250 MWh</div>
          
        </div>`

**Comment by systemcatch** [comment]
To be able to use this we need a way of storing cumulative values throughout the day for use in calculating the current generation.

**Comment by seba1337** [comment]
> 
> 
> To be able to use this we need a way of storing cumulative values throughout the day for use in calculating the current generation.

Yes. I think the data is parsable. Harder than json/xml/csv, but not that hard. I guess I could do it, just tell me the format it has to spit out.

**Comment by jarek** [comment]
Would be good to note how frequently the data updates. Currently at 13:15:53 UTC the values are the same as provided in the initial post 16 hours ago. Let's keep an eye on it.

**Comment by jarek** [comment]
Numbers still the same now, 7566 / 2755 / 250, 00:06 UTC Nov 2.

**Comment by seba1337** [comment]
Still same. I guess they don't update it. :'(

**Comment by jarek** [comment]
Still exactly the same now, so I guess I'll close the issue. Sorry about that, thanks for the thought and the report!

**Comment by seba1337** [comment]
It changed now!

7519 MWh, 1588 MWh, 200 MWh, 5 nov 2019 @ 12:26 (UTC+1).

**Comment by jarek** [comment]
still the same at 02:52 UTC+1 - so it doesn't seem to be updated with much regularity, no daily cycles can be observed at least so far

**Comment by jarek** [comment]
Currently 7340/2317/85. So it updates, but so far we have not seen a regularity or frequency of updates that would allow adding to electricitymap

**Comment by seba1337** [comment]
> 
> 
> Currently 7340/2317/85. So it updates, but so far we have not seen a regularity or frequency of updates that would allow adding to electricitymap
> 
> edit: Almost 49 hours later, it's still 7340/2317/85 - so no weekend data updates.

There's data for N. Macedonia now on Entsoe, https://transparency.entsoe.eu/generation/r2/actualGenerationPerProductionType/show?name=&defaultValue=false&viewType=GRAPH&areaType=BZN&atch=false&datepicker-day-offset-select-dv-date-from_input=D&dateTime.dateTime=03.09.2019+00:00|CET|DAYTIMERANGE&dateTime.endDateTime=03.09.2019+00:00|CET|DAYTIMERANGE&area.values=CTY|10YMK-MEPSO----8!BZN|10YMK-MEPSO----8&productionType.values=B01&productionType.values=B02&productionType.values=B03&productionType.values=B04&productionType.values=B05&productionType.values=B06&productionType.values=B07&productionType.values=B08&productionType.values=B09&productionType.values=B10&productionType.values=B11&productionType.values=B12&productionType.values=B13&productionType.values=B14&productionType.values=B20&productionType.values=B15&productionType.values=B16&productionType.values=B17&productionType.values=B18&productionType.values=B19&dateTime.timezone=CET_CEST&dateTime.timezone_input=CET+(UTC+1)+/+CEST+(UTC+2)

**Comment by jarek** [comment]
Oh that's good to know! Right now the latest data I'm seeing is from November 13th, so a fair bit delayed. However it might be useful for importing historical data - Electricity Map team, do you want to configure the ENTSO-E parser to read BZN|MK?

**Comment by alixunderplatz** [comment]
@jarek @seba1337 I just had a look at the ENTSOE parser. 
It seems like the N. Macedonian zone (10YMK-MEPSO----8) is included in the ENTSOE parser already, so I guess the historical data for this zone is collected whenever a target_datetime is set?
If so, we could close this issue.

**Comment by corradio** [comment]
Yes indeed. Thanks
