### ISSUE TITLE
Data for region king island (australia)

### ISSUE THREAD

**Issue by gappypirate** [tmrowco/electricitymap-contrib#2097]
Hey just in case you guys can use this to add data for king island there is areal time graph at this link.

https://www.hydro.com.au/clean-energy/hybrid-energy-solutions/success-stories/king-island

Love the map keep up the good work.Cheers

**Comment by jarek** [comment]
Hi, thanks for the note! Please see https://github.com/tmrowco/electricitymap-contrib/issues/636 for details on King Island and difficulties adding its data to the map.
