### ISSUE TITLE
Data for region Canaries Islands

### ISSUE THREAD

**Issue by legrosdede** [tmrowco/electricitymap-contrib#2105]
Hello, I had a look at  https://www.electricitymap.org/ , it is quite interesting and a very good job ! But there is a mistake for canarias islands : you indicate generation from gas, but the LNG terminals have not been built and commissioned yet ! The mistakes comes probablyfrom bad understanding of datas published by Red Electrica de España : the amount indicated by them as "turbina de gas" and "ciclo combinado" refers to amount produced by combined cycle and open cycle gas turbine, but these plants are still operated on liquidfuel, awaiting for natural gas availability !

**Comment by alixunderplatz** [comment]
@legrosdede thank you for clarifying this! :)
there always is a risk of "misinterpreting" the fuel for gas turbines, since they can be operated on both fuel's as you said. Guess we have to change the fuel type in the respective parser.
By the way: Do you happen to know if the situation on the balearic islands is the same (oil instead of gas) or do they actually have some sort of gas supply?

**Comment by legrosdede** [comment]
It seems the situation on the Balearic Islands is different as they are much closer from the spanish mainland, a pipeline connecting them to the spanish gas grid has been built.
(https://magazin.mannesmann-linepipe.com/en/04-2016/projects/mallorca/)
By the way the power station in Palma de Maillorca is exaclty the same that the one I have been working in a couple of years ago in Tenerife, only the fuel is different.
There is a project to build a LNG terminal in Tenerife, but it seems to be stopped at the moment.

**Comment by systemcatch** [comment]
I guess we need to change the designation in the parser from `gas` to `oil` with note to recheck this every 6 months or so.

**Comment by alixunderplatz** [comment]
@systemcatch or we could assign the oil carbon intensity to gas for Canary Islands ;)
We really have to check which technologies of the ree website are assigned to which production type in our parser.

**Comment by systemcatch** [comment]
@alixunderplatz here is the current mapping.

```python
    if zone_key == 'ES-CN-HI':
        for response in island_data:
            if response.production() > 0:
                response_data = {
                    'zoneKey': zone_key,
                    'datetime': get(response.timestamp).datetime,
                    'production': {
                        'coal': 0.0,
                        'gas': round(response.gas + response.combined, 2),
                        'solar': round(response.solar, 2),
                        'oil': round(response.vapor + response.diesel, 2),
                        'wind': round(response.wind, 2),
                        'hydro': 0.0,
                        'biomass': 0.0,
                        'nuclear': 0.0,
                        'geothermal': 0.0
                    },
                    'storage': {
                        'hydro': round(-response.hydraulic, 2),
                        'battery': 0.0
                    },
                    'source': 'demanda.ree.es',
                }
                response_data = validate(response_data, logger,
                                         floor=FLOORS[zone_key])

                if response_data:
                    # append if valid
                    data.append(response_data)

    else:
        for response in island_data:
            if response.production() > 0:
                response_data = {
                    'zoneKey': zone_key,
                    'datetime': get(response.timestamp).datetime,
                    'production': {
                        'coal': 0.0,
                        'gas': round(response.gas + response.combined, 2),
                        'solar': round(response.solar, 2),
                        'oil': round(response.vapor + response.diesel, 2),
                        'wind': round(response.wind, 2),
                        'hydro': round(response.hydraulic, 2),
                        'biomass': 0.0,
                        'nuclear': 0.0,
                        'geothermal': 0.0
                    },
                    'storage': {
                        'hydro': 0.0,
                        'battery': 0.0
                    },
                    'source': 'demanda.ree.es',
                }
```
