### ISSUE TITLE
Potential data for India / Tamil Nadu

### ISSUE THREAD

**Issue by SIVAH-AKASH** [tmrowco/electricitymap-contrib#2107]
Hey,

I am not sure how too add it, but I think this data will be useful for the state of Tamil Nadu in India.
http://meritindia.in/state-data/tamil-nadu

**Comment by alixunderplatz** [comment]
Hey @SIVAH-AKASH ! 
Thank you for your message.
The data on http://meritindia.in/state-data/tamil-nadu for the states of India is not detailed enough, unfortunately.
We can only use the data from the main page with the breakdown for "thermal", "gas", "nuclear," "hydro", and "renewables".  http://http://meritindia.in/

At least, we need an hourly breakdown of the generation of a state per production type (wind, solar, coal, hydro, nuclear, gas, others...) and all of the exports or imports to the neighbouring regions. All that information must be near real-time (up to +2 hours).
The data on meritindia are updated every few minutes, but the only facts given for a state on meritindia are: 
"demand met" = load, 
"own generation" but without a proper breakdown per type,
"import" but without a proper breakdown from which regions the imports are coming or where possible exports are going.

I believe Tamil Nadu is the Indian state with the highest wind and solar generation? So it would be really helpful to contact the local "State Load Despatch Centre Chennai" and to ask them if they could disclose that data in real-time/near real-time on their website in a table. 

Are you living in India? And if so, could you please send them a mail and ask for data? :)

**Comment by SIVAH-AKASH** [comment]
Hi,
Sorry for the late reply.
I am currently in the US for my Education but am from India, so I just sent them an email. I will let you know as soon as they reply.
Thank You,S.Akash
Get Outlook for Android

**Comment by alixunderplatz** [comment]
Hi @SIVAH-AKASH :)
Did you receive any reply?

**Comment by SIVAH-AKASH** [comment]
Hi,
Sadly I didn't :(
Sorry I'm not sure what else I can do.
Get Outlook for Android



On Wed, Dec 25, 2019 at 4:27 AM -0500, "Alex" <notifications@github.com> wrote:












Hi @SIVAH-AKASH :)

Did you receive any reply?

**Comment by robertahunt** [comment]
Closing this as no data found
