### ISSUE TITLE
electricity-map, CO2 map 

### ISSUE THREAD

**Issue by brigo69** [tmrowco/electricitymap-contrib#2110]
Hi,

I am just wondering about your CO2 map, and not really understand how Hungary can have 15% renewable value while Hydro +Wind+Biomass+Solar is hardly 4% on 29/Nov/2019 at 10:45. Is this 15% is an annual average or how do you calculate while other figures seems to be changing in real time?

Thanks,

gabor

**Comment by brunolajoie** [comment]
By default, figures are computed with a "consumption" point of view, which takes into account electricity imported from neighbors in real-time (you can change to production point of view on the top right corner). That may explain your 15% figure! Feel free to close this issue if your question has been answered

**Comment by corradio** [comment]
Thanks @brunolajoie !
@brigo69 feel free to re-open this issue if you have more questions
