### ISSUE TITLE
Data for Kosovo

### ISSUE THREAD

**Issue by seba1337** [tmrowco/electricitymap-contrib#2120]
I've found production data for Kosovo that is updated hourly.
https://kostt.com/WebFiles/Realizimi.xlsx

They have also some extra data under "Transparenca" which doesn't work.

**Comment by systemcatch** [comment]
Hey @seba1337 nice find. Currently we don't show Kosovo on the map due to it not being included in our shapefiles.

We have an older issue (#1458) about Kosovo which could be reopened if you post the new information there.

**Comment by jarek** [comment]
Going to reopen older issue and close this one, thank you!
