### ISSUE TITLE
Data for Luxembourg

### ISSUE THREAD

**Issue by seba1337** [tmrowco/electricitymap-contrib#2121]
There is data on Entsoe for Luxembourg, but you have to change the zones.

Check it yourself:

https://transparency.entsoe.eu/generation/r2/actualGenerationPerProductionType/show?name=&defaultValue=false&viewType=TABLE&areaType=BZN&atch=false&datepicker-day-offset-select-dv-date-from_input=D&dateTime.dateTime=03.09.2019+00:00|CET|DAYTIMERANGE&dateTime.endDateTime=03.09.2019+00:00|CET|DAYTIMERANGE&area.values=CTY|10YLU-CEGEDEL-NQ!BZN|10Y1001A1001A63L&productionType.values=B01&productionType.values=B02&productionType.values=B03&productionType.values=B04&productionType.values=B05&productionType.values=B06&productionType.values=B07&productionType.values=B08&productionType.values=B09&productionType.values=B10&productionType.values=B11&productionType.values=B12&productionType.values=B13&productionType.values=B14&productionType.values=B20&productionType.values=B15&productionType.values=B16&productionType.values=B17&productionType.values=B18&productionType.values=B19&dateTime.timezone=CET_CEST&dateTime.timezone_input=CET+(UTC+1)+/+CEST+(UTC+2)

https://transparency.entsoe.eu/generation/r2/actualGenerationPerProductionType/show?name=&defaultValue=false&viewType=TABLE&areaType=BZN&atch=false&datepicker-day-offset-select-dv-date-from_input=D&dateTime.dateTime=03.09.2019+00:00|CET|DAYTIMERANGE&dateTime.endDateTime=03.09.2019+00:00|CET|DAYTIMERANGE&area.values=CTY|10YLU-CEGEDEL-NQ!BZN|10Y1001A1001A82H&productionType.values=B01&productionType.values=B02&productionType.values=B03&productionType.values=B04&productionType.values=B05&productionType.values=B06&productionType.values=B07&productionType.values=B08&productionType.values=B09&productionType.values=B10&productionType.values=B11&productionType.values=B12&productionType.values=B13&productionType.values=B14&productionType.values=B20&productionType.values=B15&productionType.values=B16&productionType.values=B17&productionType.values=B18&productionType.values=B19&dateTime.timezone=CET_CEST&dateTime.timezone_input=CET+(UTC+1)+/+CEST+(UTC+2)

I think it's related to #1605.

**Comment by alixunderplatz** [comment]
hi @seba1337, thank you for looking into the data!
That data actually is for the market/ bidding zone "Luxembourg + Germany", which **only** features data for Germany as far as I know. The magnitude of that data definitely is not for Luxembourg
![image](https://user-images.githubusercontent.com/25743609/71313030-7b5f5a00-2433-11ea-9f65-5098e096f34a.png)

There is no data for the country Luxembourg so far, which is what we actually need:
![image](https://user-images.githubusercontent.com/25743609/71313057-aea1e900-2433-11ea-9cc5-32fabcf8ea2c.png)

**Comment by seba1337** [comment]
What if you do DE-LU - DE?

**Comment by alixunderplatz** [comment]
@seba1337 it will return 0 as the data is exactly the same.

**Comment by alixunderplatz** [comment]
@seba1337 I will close this issue for the moment, since there is no value-added regarding Luxembourg.
Let's open a new issue next year regarding data for other European zones without data (Luxembourg, Malta, North Macedonia, Albania...) , where we try to contact the system operators of the respective countries and beg for their data. ;)

**Comment by seba1337** [comment]
> 
> 
> @seba1337 I will close this issue for the moment, since there is no value-added regarding Luxembourg.
> Let's open a new issue next year regarding data for other European zones without data (Luxembourg, Malta, North Macedonia, Albania...) , where we try to contact the system operators of the respective countries and beg for their data. ;)

Agreed. Unrelated, but similar problem: I've found Kosovo's data #2120, but you should check if the coal plants are already included in Serbia's published data or not.
