### ISSUE TITLE
Missing Caribbean islands

### ISSUE THREAD

**Issue by woutertP1** [tmrowco/electricitymap-contrib#2127]
I'm not seeing all Caribbean islands on the electricityMap. Missing are at least the following:

- Curaçao
- Bonaire
- St. Maarten (Dutch & French part)
- British Virgin Islands

Once available I can add some country info.

**Comment by alixunderplatz** [comment]
Hi @woutertP1 ,
the country geometries were simplified for the map. This is why these small islands are missing at the moment. What exactly do you have in mind adding for these islands?

**Comment by woutertP1** [comment]
For the moment just adding them for completeness sake. It will add insight in the performance of CO2 emissions for SIDS-countries (Small Island Developing States) on an annual timeline. Most of these countries are similar in some aspects and vastly different in others.

**Comment by jarek** [comment]
As far as I know we do not have any data for these islands. They would only appear greyed out, as e.g. Jamaica.

(Part of the reason small islands and shapes are currently excluded is because the map is loaded in one resolution only, with no refinement on zooming, so including small shapes makes the page slower to load.)

**Comment by woutertP1** [comment]
Jarek, data for these islands can be retrieved from the website of the respective utilities. Most of these islands have just one utility, so it can be easily found. Only drawback is that this data is on an annual basis, although some do have some sort of realtime feed (like Aruba).

**Comment by jarek** [comment]
To be included on live Electricity Map, a region needs a carbon intensity of the energy sources, as well as current (<24 hours) electricity production/consumption in the region. From annual averages we can get the former. If any of the islands have a dashboard with current consumption or production updated at least several times a day, feel free to open an issue with a link to that page :)

**Comment by robertahunt** [comment]
Closing this until we find data for said islands.
