### ISSUE TITLE
Interconnectors IT-GR and IT-ME

### ISSUE THREAD

**Issue by Juma7C9** [tmrowco/electricitymap-contrib#2131]
The two interconnectors are available on the ENTSO-E transparency portal, but not on the map.

The IT-GR one, unlike the rest of the Greece data, seems to have a <2h delay, so it should be realtime enough, while the recently added IT-ME one started to return data just today [2019-12-28] (for now it sits at '0', but before it was N/A or n/e), so it may be operative soon.

The IT-ME interconnector, if added, should have a capacity of 600MW on both directions, as per https://www.terna.it/en/media/news-events/italy-montenegro-invisible-electrical-bridge

**Comment by Juma7C9** [comment]
The Montenegro interconnector have started to report real time data today [2020-10-07], while until yesterday it seemed to have a 1-day delay.

**Comment by robertahunt** [comment]
Hi @Juma7C9 thanks for bringing this to our attention! Is this something you are comfortable trying to adjust yourself in the codebase? Would you need any pointers from us? If you cannot / don't have time, no worries! We will pick this up when we get a chance.
Cheers,
Roberta

**Comment by robertahunt** [comment]
Another potential data source: http://cges.me/en/system-live/web-scada
