### ISSUE TITLE
Timezone

### ISSUE THREAD

**Issue by coogor** [tmrowco/electricitymap-contrib#2133]
Hi, I was just looking at https://www.electricitymap.org/?page=country&solar=false&remote=true&wind=false&countryCode=DE
and notice 11,3 GW solar power at 12:00PM
Is there an issue with the timezone? 12:00PM is equal to 24:00h, and middle of the night there is no solar power....

**Comment by alixunderplatz** [comment]
Hi @coogor 
the am/pm notation indeed has high potential for possible confusion when it comes to noon & midnight. 
https://en.wikipedia.org/wiki/12-hour_clock#Confusion_at_noon_and_midnight

> The American Heritage Dictionary of the English Language states "By convention, 12 AM denotes midnight and 12 PM denotes noon. Because of the potential for confusion, it is advisable to use 12 noon and 12 midnight."

So everything is fine with the time displayed on the map.

**Comment by coogor** [comment]
Dear @alixunderplatz, thanks for the clarification - and the confirmation that this am/pm stuff is nonsense. Anywhere else, esp. in science , 24h format is used to avoid misunderstandings. Would be great if you switch as well
