### ISSUE TITLE
Truly high art (with one minor flaw ~;-)

### ISSUE THREAD

**Issue by cowcreekgeek** [tmrowco/electricitymap-contrib#2144]
You've raised code to the level of high art;
Truly a thing of beauty, save for one flaw...

Android / Chrome and Firefox, all views.

`This project is Open Source (see data sources). Contribute by <a href="https://github.com/tmrowco/electricitymap-contrib#adding-a-new-country" target="_blank">adding your territory</a>.`

![Screenshot_20200108-123410](https://user-images.githubusercontent.com/22483123/72001667-eb335a00-3213-11ea-9bb2-a6f18c0feb4f.png)

**Comment by corradio** [comment]
Thank you for reporting the issue!
@fbarl are you able to help here?
It seems like we just need to wrap the localisation function in a <span> with the dangerouslySetInnerHTML attribute to make sure the localisation string puts the HTML code in.
The relevant file is mobileinfotab.js and the localisation string "panel-initial-text.contribute"

**Comment by fbarl** [comment]
Good catch @cowcreekgeek!

Thanks for the very precise hint @corradio, I fixed it in #2146.
