### ISSUE TITLE
Power capacity data for Spain (updated to November 2019)

### ISSUE THREAD

**Issue by JosepRey** [tmrowco/electricitymap-contrib#2149]
Data for the spanish electricity system is starting to get outdated, I would consider updating power capacities for each fuel, with the ones I attach in this post with the latest data available (November 2019).

Hydroelectric (conventional): 17087 MW
Pumped Hydro Storage: 3329 MW
Nuclear: 7117 MW
Coal: 9683 MW
Fuel + Gas (open cycle, I suggest adding it as "Oil". Barely ever used): 2447 MW
Gas fired Combined Cycle: 26284 MW
Wind: 25223 MW
Solar (PV + Thermal): 10125 MW
Biomass: 981 MW

![Power capacity November 2019](https://user-images.githubusercontent.com/59806177/72242586-1b9b3f80-35ea-11ea-8e2e-ebb3a5c6a44b.JPG)

**Comment by robertahunt** [comment]
solved by #2150 and #2154
