### ISSUE TITLE
Disable "follow-me" viewport

### ISSUE THREAD

**Issue by baerbock** [tmrowco/electricitymap-contrib#2156]
Recently electricitymap started to change the viewport when selecting a country.

In my opinion it feels awkward when a web app overzealously wants to help the user, so this should be disabled again.

**Comment by corradio** [comment]
@fbarl I think this is a side effect of re-centering when clicking on a country. Can you help revert the behavior?

**Comment by fbarl** [comment]
Thanks for reporting the issue @baerbock !

> I think this is a side effect of re-centering when clicking on a country. Can you help revert the behavior?

It's very possible #2145 caused an accidental change in the behaviour. However, I'm not really sure how the app was behaving before :thinking:

There are two ways one can select the zone that I'm aware of:

a) By clicking on the zones list in the sidebar
![image](https://user-images.githubusercontent.com/1216874/72368610-b84f0180-36fe-11ea-9ec6-bad94a96dc51.png)

b) By clicking on the zone directly in the map
![image](https://user-images.githubusercontent.com/1216874/72368636-c6048700-36fe-11ea-8125-164bfaec19df.png)

1) Right now the viewport changes in **both** cases
2) If I removed the observer mentioned in https://github.com/tmrowco/electricitymap-contrib/pull/2145#issuecomment-572530852, the viewport doesn't change in **neither** case
3) We could make the viewport change **only** when clicking on the zones list
4) We could make the viewport change **only** when clicking on the map

@corradio Was (3) what we had before? If we don't want (1), I'd personally like to see us go with either (2) or (3) - there are arguments to be made for both, but I don't have a strong stand and I think both would be fine, so you can make the call :)

**Comment by corradio** [comment]
Thanks for the write-up. Let's go with (3).
Let's also make sure that the viewpoint is centered on the country when a country is linked to (i.e. when the URL already points to a country)
Thanks!
