### ISSUE TITLE
Add color blind version of electricity sources color spectrum

### ISSUE THREAD

**Issue by fbarl** [tmrowco/electricitymap-contrib#2158]
`modeColor` spectrum has hardcoded values per energy source which don't play well with the color blind mode. That is maybe less of a problem in the bar chart where the source names are written explicitly:

![image](https://user-images.githubusercontent.com/1216874/72388113-5ce43a00-3725-11ea-809d-8e08efdee3b4.png)

But it probably has a bigger effect on the area graph:

![image](https://user-images.githubusercontent.com/1216874/72387861-d891b700-3724-11ea-8779-160e889581f0.png)

**Comment by fbarl** [comment]
I was thinking how we could use the same carbon intensity scale that is currently used for painting map zones in the color blind mode.

![image](https://user-images.githubusercontent.com/1216874/75585294-0717e700-5a72-11ea-88bf-fa728f3d918d.png)

So for each electricity source, use the color that we'd get by mapping either the zone's specific or the world's average carbon intensity of the resource onto that scale.

**Comment by corradio** [comment]
I think this is a good idea, but I will close it due to inactivity, unless someone sees a clear way forward and wants to dedicate time here.
