### ISSUE TITLE
FAQ section doesn't scroll to linked answers on desktop

### ISSUE THREAD

**Issue by fbarl** [tmrowco/electricitymap-contrib#2162]
While working on #2160, I discovered that the FAQ answers linked from other answers only get into focus in mobile views - on full desktop views, the answers open up but they are not brought into the viewport if they were outside of it.

**Comment by robertahunt** [comment]
Hey Filip, Can this also be closed now?

**Comment by fbarl** [comment]
> Hey Filip, Can this also be closed now?

Hey @robertahunt, I discovered this issue while working on #2160, but didn't address it there - I also just checked and the issue is still present on wider screens so I'd keep it open :)

**Comment by robertahunt** [comment]
No worries!! Sorry about this. Just trying to clean up a bit.

**Comment by madsnedergaard** [comment]
Seems like it's working correctly now :)
