### ISSUE TITLE
US-SPP historical parser captures too much as 'Unknown'

### ISSUE THREAD

**Issue by robertahunt** [tmrowco/electricitymap-contrib#2166]
Because SPP named their columns 'Natural Gas Market' and 'Gas Self' instead of 'Natural Gas Self', the 'Gas Self' column is mistakenly added to Unknown.

**Comment by fbarl** [comment]
@corradio @robertahunt can we close this now that #2168 has been merged?

**Comment by robertahunt** [comment]
Yes!
