### ISSUE TITLE
Capacities for Italian BZNs

### ISSUE THREAD

**Issue by Juma7C9** [tmrowco/electricitymap-contrib#2173]
Hi,
I found that Terna, the Italian TSO publishes the production capacities divided by region and type (link: [1]), so it is possible to add them to the map simply summing them together for each bidding zone.

This is the, albeit partial, result:

![immagine](https://user-images.githubusercontent.com/5333677/72853076-aba74c00-3cb0-11ea-95c8-3c54d6be3852.png)

[Update 2: Added Rossano BZN data to South BZN]
[Update 3: Manually checked first ~250 entries (sorted by installed capacity) in the ENTSO-E data, casting entries incorrectly classified as _Other_ into the correct categories. Data and changes made in the attached .zip file]

Unfortunately the classification is slightly different than that used by the ENTSO-E, in particular concerning hydro and pumped storage, and thermal sources.

For hydro, and in particular pumped storage, the data distinguishes "pure storage" and "mixed storage", the former having <5% of the energy generated from natural inflows, the latter >5%.
As I don't know where the 'intermediate' case falls into the ENTSO-E data, I added in the table both values, so it is possible to choose from them.

Apart from this, the main issue remains the thermal capacity, as the detail per region does not distinguish the fuel used, while the fuel detail is not divided by region/macro area.

I also cross-checked the data with those available on the 'Installed capacity per production unit', summing all the units under the same BZN.
The result is that the ENTSO-E data underestimates, from slightly (e.g. for Wind) to severely (for Solar) the data reported by Terna, and it is consistent with missing all production units < ~10MW (e.g. for Hydro+Storage, Terna reports a total of 22.9GW, while ENTSO-E reports 19.0GW. The difference is consistent within ~400MW with the capacity of all the units below 10MW [3.5GW, Terna page 68]).

This unfortunately means that the aggregated capacities for thermal/fossil units from the ENTSO-E data are quite inaccurate, as almost 20% of the capacity is missing (only 51.1GW of the 62.3GW total are accounted for), assuming that the ENTSO-E 'Other' units (~9.3GW) are all thermal.
One way I see to solve this discrepancy is to suppose that the missing capacity is due to smaller units, and make an educated guess of their main fuel source(s) (e.g. by comparing ~for each BZN~ which type is mostly missing) -- or simply to add them to the 'Other/Unknown data'.

Additional data:

[Capacities.zip](https://github.com/tmrowco/electricitymap-contrib/files/4094461/Capacities.zip)

[1]: https://download.terna.it/terna/0000/1230/97.PDF

**Comment by robertahunt** [comment]
Hi @Juma7C9 ! Thanks so much for gathering all of this together :D, and sorry about not replying earlier, this week has been a bit busy. 

First, is this something you feel comfortable trying to update the numbers in the code yourself? (in https://github.com/tmrowco/electricitymap-contrib/blob/master/config/zones.json ). If not, no worries, I'll tag this as help-wanted then.

For the hydro problem, unfortunately I cannot find CO2 equivalent emissions values that distinguish between pure hydro storage, mixed hydro storage, and run-of-river, so I would classify pure + mixed as 'hydro storage', and the rest as 'hydro'. 

For the thermal problem I see two solutions, One: we could use the Tema numbers and just put thermal under 'unknown', then adjust the unknown emission factor to represent the capacity mix. Or, the second option which I prefer is what you suggested, using the ENTSO-E numbers and adding the difference to 'unknown'. We should probably also check that the emission factor for unknown is appropriate for thermal generation. 

Did I miss anything?

**Comment by Juma7C9** [comment]
No problem, this should be easier than the other one, as it seems to be well documented.

The only thing I think may be worth checking before is to compare these capacities with the historical data to verify that there is no missing capacity, i.e. capacity > production always, for each zone and for each type.

Also, it may be useful to compare the overall yearly energy mix as calculated from ENTSO-E data, and compare it with the latest one reported by Terna ([1]), to get a better idea of the 'Other' source emission factor. But this is a different and anyway minor issue, as the largest source of uncertainty are the imports from Switzerland, that (if I recall correctly) cover roughly the 10% of IT-North energy demands, and which emission factor is probably quite overestimated.

[1]: https://download.terna.it/terna/PRODUZIONE-5_8d714f74ef6f6b8.pdf

**Comment by robertahunt** [comment]
Good point. I'm attaching a csv with the maximum production for each fuel type from our historic database. At first glance the numbers look good to me. 
[IT_max_production_by_fuel.txt](https://github.com/tmrowco/electricitymap-contrib/files/4118923/IT_max_production_by_fuel.txt).

For the yearly energy mixes, I leave it up to you if you want to go that deep. I am not so familiar with the Italian/Swiss energy systems, what makes you say the emission factor there is probably overestimated?

**Comment by Juma7C9** [comment]
Looking at the data, they seem mostly fine, except for Hydro for IT-SIC and IT-SAR, and Oil in IT-NO. For the first two, it is possible that the reporting changed over the years, or that some hydro storage is instead reported as run-of-the-river or similar. For the latter I imagine that some capacity was removed over time or that the data is inaccurate, but its value is negligible enough that its capacity may be safely omitted.

The major issue actually lies in the 'Unknown' row, as it is consistently and significantly larger than the sum calculated above. That may mean that there was some reporting issue or change in the past, or that data are binned differently at the ENTSO-E level.

I think it may be useful to check the maxima against the 2018 data (the year the Terna report refers to), and if those issue persist the 'Other/Unknown' row may better be omitted.

As for Switzerland, the sources cited in #892 (in particular [1], tables T24 and T07) report for 2018 a net production of ~63TWh, of which ~90% come from Hydro and Nuclear, and an import of ~32TWh, mainly from France, Germany and Austria.
As the emission intensity for Switzerland is not available, the intensity used is the one of the importing zone, and in case of IT-NO it probably is quite an overestimate as it generates ~2/3 of the energy from thermal sources (see [2]), and so has a significantly higher carbon intensity.

[1]: https://opendata.swiss/fr/dataset/schweizerische-gesamtenergiestatistik
[2]: https://download.terna.it/terna/PRODUZIONE-5_8d714f74ef6f6b8.pdf

**Comment by erdmark** [comment]
For Switzerland only nuclear data seems to be outdatet for 2 or 3 hours. If you assume nuclear generation is the same as 3 hours ago you could calculate the emission factor.
The other sources (Import from Germany and France, export to Italy, hydro and a bit from Austria) seem to be actual. Also nuclear production changes only rare times.

**Comment by pierresegonne** [comment]
Hey @Juma7C9 Thanks for the work you put into this :) 

Is there anything you need on our side to proceed, or did you just not find time to keep on going?

**Comment by KabelWlan** [comment]
This could be closed since it is covered with #3228.
