### ISSUE TITLE
US-CA going offline overnight

### ISSUE THREAD

**Issue by typicalTYLER** [tmrowco/electricitymap-contrib#2183]
It seems like similar to the [US-TX issue](https://github.com/tmrowco/electricitymap-contrib/issues/2178) I posted recently, US-CA is going offline overnight as well, seemingly due to the same problem, negative solar overnight. Here is a [log](https://kibana.electricitymap.org/app/kibana#/doc/96f67170-0c49-11e9-85c1-1d63df8c862c/logstash-2020.01.23/doc?id=wyBc028BX-fmul22TGRZ&_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:now-24h,mode:quick,to:now))) of one of the errors. Maybe this should be clamped and throw a warning as well?

**Comment by robertahunt** [comment]
Hey! Yes, that makes sense. Is this something you want to/are able to take on fixing? Do you need anything from us?

**Comment by typicalTYLER** [comment]
Just took a stab at it! Don't have an environment set up though so wasn't able to test, hopefully CI would catch any problems though
