### ISSUE TITLE
Widget and notification

### ISSUE THREAD

**Issue by Hedaja** [tmrowco/electricitymap-contrib#2187]
I think a nice feature to have would be the ability to create widget. This way you can easily see what the current CO2 emissions and share of renewable are. 

On the other hand you could also activate a notification when the emissions drop below or raise above a threshold you have set. 

This way you can easily adjust some of your daily behaviors to the current state of the power gird more easily. For example turn on your washing machine when emissions are low.

**Comment by corradio** [comment]
Hi @Hedaja ,

Thanks for the suggestion, it's something we're considering for our app https://north-app.com.
I'll close this here but rest assured we're thinking about it ;-)
