### ISSUE TITLE
Negative Hydro values (in EIA, US) cause parser to fail

### ISSUE THREAD

**Issue by robertahunt** [tmrowco/electricitymap-contrib#2192]
When scraping historic data, I've noticed that negative hydro values are sometimes returned by EIA. For example, for US-TN 2018-09-23 6am local time, there was hydro production reported of -144.

I am not sure if this means we should just always move negative hydro production values over to storage, or if for each BA we should decide if the hydro production should be 'storage' hydro or run-of-river. What you think? @systemcatch I guess you are closest to the EIA data.

**Comment by systemcatch** [comment]
Hi @robertahunt, the EIA have a useful information section about their data at https://www.eia.gov/beta/electricity/gridmonitor/about

Quoting from that page;

> Net generation

> EIA imputes for anomalous values for total net generation and net generation by energy source if the value is missing or reported as negative, zero, or at least 1.5 times greater than the maximum of past total net generation values reported by that BA with the following exceptions. Small negative net generation and zero net generation values are accepted for generation-only balancing authorities (See the Generation-only balancing authorities section above) and for City of Homestead (HST), Duke Energy Progress West (CPLW), and the Utilities Commission of New Smyrna Beach (NSB) since they may not be running their generators during all hours. Hydro net generation may also have negative values due to pumped storage, although EIA has asked balancing authorities to count pumped storage negative net generation as demand instead.

I think you're safe to assume that negative hydro values are pumped, given how many BA's there are trying to determine output type for each sounds like a nightmare.
