### ISSUE TITLE
Add installed capacity for Uruguay

### ISSUE THREAD

**Issue by alixunderplatz** [tmrowco/electricitymap-contrib#2197]
Seems like there still is no capacity data in zones.json for Uruguay / UY yet.
Finding & adding recent data (2018/2019) for the installed power of each type is appreciated :)

**Comment by brandongalbraith** [comment]
I've sent an email to UTE inquiring for capacity data, and will update when I hear back.

Is it possible for EM to infer total capacity based on historical generation "high water marks"?

**Comment by brandongalbraith** [comment]
I think https://github.com/tmrowco/electricitymap-contrib/pull/2217 closes this?

**Comment by robertahunt** [comment]
Yup! :D
