### ISSUE TITLE
Many Countries not showing live data

### ISSUE THREAD

**Issue by Kevindeving** [tmrowco/electricitymap-contrib#2212]
Many countries like Germany, Austria, Norway and sometimes Great Britain are not showing data since at least today on electricitymap.org

This might be due to entsoe data being out of sync? I don't know.

Edit: Confirmed some entsoe data is out of sync. Historical data from 1-2 hours is available though. This could have been shown on electricitymap with a warning that current data is not available as a better solution.

**Comment by jarek** [comment]
This doesn't seem related to ENTSO-E per se, as some countries on ENTSO-E are showing up (like Czechia); meanwhile we get British data (currently missing) from bmreports

**Comment by Kevindeving** [comment]
I see this now. Seems like it is normal on countries like Germany who have smaller data ranges than 1 hour that they are not perfectly aligned on all energy resources.
It must be something different then of course.

**Comment by Kevindeving** [comment]
Seems to be fixed.
