### ISSUE TITLE
App uses a lot of disk space

### ISSUE THREAD

**Issue by corradio** [tmrowco/electricitymap-contrib#2216]
> The website is great, but the app uses over 600 MB of system memory for its data after a single start.

I suspect it must come from cordova-code-push

- https://play.google.com/apps/publish?account=7105597502658203364#ReviewDetailsPlace:p=com.tmrow.electricitymap&reviewid=gp:AOqpTOEINqDJaK5usTyfTG7n_x2-6m3KHI5M8yBQqfwxmxYOchi0a5TVaZcKFDAG_Dc2qPNXJL9cc5O6NJaxTw
- https://play.google.com/apps/publish?account=7105597502658203364#ReviewDetailsPlace:p=com.tmrow.electricitymap&reviewid=gp:AOqpTOF4ZdjFGx3yw5F4pxDNyueepJcshjvF0wXW_qbsJyXmLW1B9t2cVPQHFZzO0lYCRDwmf6bpiCH4mC6umQ
- https://play.google.com/apps/publish/?account=7105597502658203364#ReviewDetailsPlace:p=com.tmrow.electricitymap&reviewid=gp:AOqpTOFaJeWz5Fxph9uNWFVfM7bCOrdDwe6qhKfCLYntmVTkmlQfIZo9cKUjqNfzg4DP1bsVyvwHN0wRXm8Vrw

**Comment by arganoid** [comment]
I just came here after noticing the app is taking up over 1GB of storage on my phone.

**Comment by corradio** [comment]
We just released a new version of the app, which should fix this. I suggest uninstalling and reinstalling the last version.
