### ISSUE TITLE
Nuclear installed capacity for region Sweden too high.

### ISSUE THREAD

**Issue by augustekman** [tmrowco/electricitymap-contrib#2224]
The installed capacity of nuclear (9.1 GW) in Sweden is too high. Reactor Ringhals 2 was permanently shut down around new years, and the remaining reactors' effects are:

Ringhals 1: 881 MW
Ringhals 3: 1 063 MW
Ringhals 4: 1 130 MW
(source: https://group.vattenfall.com/se/var-verksamhet/ringhals/produktion )

Oskarshamn 3: 1 450 MW or 1 400 MW ( https://www.okg.se/sv/Produktionsinformation/ and https://www.okg.se/sv/Om-OKG/ or https://sv.wikipedia.org/wiki/Oskarshamns_kärnkraftverk#Oskarshamn_3 )

Forsmark 1: 990 MW
Forsmark 2: 1 120 MW
Forsmark 3:  1 167 MW
( https://group.vattenfall.com/se/var-verksamhet/forsmark/produktion )

That totals 7 751 MW or 7 801 MW depending on which number of O3 is correct. A fair bit less than 9.1 GW.

(Also wind installed effect for Sweden is too low, but I don't have any source for a correct number there. Just that production has been far above 6.12 GW a couple of times the last windy weeks. Example: 16 Feb 2020)

**Comment by nessie2013** [comment]
I found more up to date numbers for Swedens capacities on the source page (nuclear = 8586 MW from data source) and more up to date wind data, I will push a fix to the file for it.

**Comment by nessie2013** [comment]
I included your updated sources / Data in my update of Swedens Capacities.
