### ISSUE TITLE
Wind installed capacity for Sweden too low

### ISSUE THREAD

**Issue by augustekman** [tmrowco/electricitymap-contrib#2225]
The wind installed capacity (6.12 GW) for Sweden is too low.

The previous weeks, that installed capacity has been surpassed by a lot several times, 16 February we've seen numbers over 7,500 MW.

I've found one source of wind installed power, not sure about the exact credibility of the source, though:

https://svenskvindenergi.org/wp-content/uploads/2020/02/Statistics-and-forecast-Svensk-Vindenergi-feb-2020-FINAL.pdf

On slide 3, capacity in the end of 2019 is listed as 8,984 MW.

**Comment by nessie2013** [comment]
I included your updated sources / Data in my update of Swedens Capacities.

**Comment by robertahunt** [comment]
Fixed by #2284
