### ISSUE TITLE
Data for region Sweden

### ISSUE THREAD

**Issue by Henrik575** [tmrowco/electricitymap-contrib#2245]
Installed capacity, production and price available on https://transparency.entsoe.eu/

Data available under Country or Control Area (no data available under Bidding Zone yet)

Brgds,
Henrik

**Comment by nessie2013** [comment]
I already put in a pull request for updating Sweden with even more up to date data from new sources.

**Comment by Henrik575** [comment]
Thank You

**Comment by jarek** [comment]
Sweden is currently online with live production data. What is possible to add?

Please also check https://github.com/tmrowco/electricitymap-contrib/issues/1397 for an attempt to split Sweden into smaller bidding zones, at the time it failed due to insufficiently detailed production data.

**Comment by Henrik575** [comment]
Price and installed capacity

**Comment by robertahunt** [comment]
Hi @Henrik575 , Unless I am missing something, EntsoE only reports price by bidding zone, so unfortunately until we can split SE into bidding zones, I don't think we can do much here. 

Unless there are some actions I am missing, I will close this for now as I think the rest is covered by #1397.
