### ISSUE TITLE
Estonia (EE) Coal/Oil data wrong

### ISSUE THREAD

**Issue by nessie2013** [tmrowco/electricitymap-contrib#2248]
The data for Estonia shows that it is getting quite a lot of power from coal. In fact, both Wikipedia and ENTSOE say that Estonia has no coal generation facilities, so I suspect Oil generation has been wrongly marked as coal generation. I'm unsure how to fix this so I made this issue.

**Comment by alixunderplatz** [comment]
@nessie2013 we are aware that part of production comes from shale oil. it is a coal-like rock containing mineral oil. it used to be labeled as "oil" in the beginning on EM, but was moved it to the coal category later. Look up "Estonia" in the search bar here on github if you want to know more about this ;) closing

**Comment by brandongalbraith** [comment]
@nessie2013 additional context can be found at https://github.com/tmrowco/electricitymap-contrib/issues/2118
