### ISSUE TITLE
Time slider doesn't account for gaps in data

### ISSUE THREAD

**Issue by fbarl** [tmrowco/electricitymap-contrib#2253]
This is a problem not only for data missing from the beginning or the end of the time scale (for the same reasons as in #2250), but also if the data is missing from the middlef the slider value will not map in a linear fashion to the timestamp, so the tick values below the slider will be incorrect.

I can't find a good live example to demonstrate this at the moment, but the current code suggests this would be the case.

![image](https://user-images.githubusercontent.com/1216874/75397723-dad85b00-58f7-11ea-8fb9-c9bd9ff7d6b1.png)

**Comment by pierresegonne** [comment]
This seems fixed by #2231 (and I tested it and couldn't replicate) so I'll close it

**Comment by fbarl** [comment]
Thanks for looking into this @pierresegonne!

It's been a while since I opened this issue but I think that at the time my concern was about the gaps caused by server being down - I assumed that in that case we'd have a gap in the timestamps which graph components would know how to render (since they're passed to a time scale when generating the time axis), but the time slider would assume they are uniformly distributed and would thus render them wrongly.

For illustration, assume that the server returns datapoints at these times: 10:00, 10:15, 11:00 (missing 10:30 and 10:45). The graphs would render time axis like `x-x-----x` while the slider would distribute the timestamps like this `x---x---x`.

Of course, this is only a problem if the server could ever return non-uniformly distributed timestamps for historical data, which I'm not sure ever happens (maybe @robertahunt would know more).

I never actually ran into this case, so it might be very marginal - I agree we can keep the issue closed and reopen it if we ever come across it in reality :wink:
