### ISSUE TITLE
No data for most countries

### ISSUE THREAD

**Issue by StefanAO** [tmrowco/electricitymap-contrib#2257]
For the last couple of days, there is no data for most countries on my device and when I open the website.

![Screenshot_20200302-065151](https://user-images.githubusercontent.com/4057678/75649074-5157be80-5c52-11ea-92f9-3bf0e78aa793.jpg)

**Comment by torbjornvatn** [comment]
I think it's related to this https://tmrow-team.slack.com/archives/C2DQPTHA6/p1582957262012400

**Comment by robertahunt** [comment]
@StefanAO and @torbjornvatn Indeed, this is because we currently cannot get data for these countries through the entsoe api. I have contacted them, and we are working to get this fixed.

**Comment by fbarl** [comment]
@robertahunt The [production](https://www.electricitymap.org/?page=map&solar=false&remote=true&wind=false) looks good to me now, I guess this issue can be considered resolved then?

**Comment by robertahunt** [comment]
I am locally scraping the data and uploading it ... for our users it should be mostly resolved... until I have to bike to work :P #hacky resolved.

But I think we can indeed close this.
