### ISSUE TITLE
unknown attribute: "minutes", ETSOE parser

### ISSUE THREAD

**Issue by Mk-arc** [tmrowco/electricitymap-contrib#2259]
Hi there,

I am having a problem getting the ENTSOE.py parser to work.

Im running the test_parser.py script as follows, from within a venv:

ENTSOE_TOKEN=<my_entsoe_token> ./python3 ../../test_parser.py DE price

Then im getting following error:

```Traceback (most recent call last):
  File "../..//test_parser.py", line 86, in <module>
    print(test_parser())
  File "/home/kisle/git/electricitymap-contrib/parser_env/lib/python3.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/kisle/git/electricitymap-contrib/parser_env/lib/python3.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/kisle/git/electricitymap-contrib/parser_env/lib/python3.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/kisle/git/electricitymap-contrib/parser_env/lib/python3.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "../..//test_parser.py", line 49, in test_parser
    res = parser(*args, target_datetime=target_datetime)
  File "/home/kisle/git/electricitymap-contrib/parsers/ENTSOE.py", line 1059, in fetch_price
    parsed = parse_price(query_price(domain, session, target_datetime=target_datetime))
  File "/home/kisle/git/electricitymap-contrib/parsers/ENTSOE.py", line 721, in parse_price
    datetime = datetime_from_position(datetime_start, position, resolution)
  File "/home/kisle/git/electricitymap-contrib/parsers/ENTSOE.py", line 571, in datetime_from_position
    return start.replace(minutes=(position - 1) * digits)
  File "/home/kisle/git/electricitymap-contrib/parser_env/lib/python3.7/site-packages/arrow/arrow.py", line 612, in replace
    raise AttributeError('unknown attribute: "{}"'.format(key))
AttributeError: unknown attribute: "minutes"
```

**Comment by corradio** [comment]
It seems like you're using a wrong version of arrow.
Could you try with arrow==0.15.4 as specified in the requirements.txt?

**Comment by systemcatch** [comment]
This is an older version of arrow, the newer versions use `shift` to alter attributes relatively.

**Comment by Mk-arc** [comment]
Hmm. But somehow when i run a pip install with the requirements file I get the following:

~/git/electricitymap-contrib$ pip3 install -r parsers/requirements.txt 
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: arrow==0.15.4 in /home/kisle/.local/lib/python3.7/site-packages (from -r parsers/requirements.txt (line 1)) (0.15.4)

So the correct version seems to be installed?

**Comment by Mk-arc** [comment]
Also when inside the test_parsers script I put: 
    print(arrow.__version__)
It returns "0.15.4"

**Comment by Mk-arc** [comment]
Just tested it again in a fresh virtual env. All I did was creating the env. Installing wheel via pip (Its not included in the requirements.txt, but its needed). And then installing all modules via the requirements.txt.

Still not working.

**Comment by jarek** [comment]
Source code in question (with comment and whitespace trimmed):

https://github.com/crsmithdev/arrow/blob/0.15.4/arrow/arrow.py#L582-L622

```python
    def replace(self, **kwargs):
        absolute_kwargs = {}
        for key, value in kwargs.items():
            if key in self._ATTRS:
                absolute_kwargs[key] = value
            elif key in ["week", "quarter"]:
                raise AttributeError("setting absolute {} is not supported".format(key))
            elif key != "tzinfo":
                raise AttributeError('unknown attribute: "{}"'.format(key))

        current = self._datetime.replace(**absolute_kwargs)

        tzinfo = kwargs.get("tzinfo")

        if tzinfo is not None:
            tzinfo = self._get_tzinfo(tzinfo)
            current = current.replace(tzinfo=tzinfo)

        return self.fromdatetime(current)
```

So it's raising because `minutes` is not in `self._ATTRS`, where `_ATTRS = ["year", "month", "day", "hour", "minute", "second", "microsecond"]` in https://github.com/crsmithdev/arrow/blob/0.15.4/arrow/arrow.py#L56

So it really does seem like it shouldn't work.

The code in question in ENTSOE.py is from April 2018 so possibly it broke along the way but we didn't notice.

What is the code in `arrow.py` on the backend server?

**Comment by systemcatch** [comment]
We would have seen the error before now surely? The `datetime_from_position` function is used in 6 places in the ENTSOE parser, it raising an error would mean the parser fails and a blank zone.

Is there an older version of arrow running on the backend? I know that the backend pandas version is different to the requirements.

**Comment by jarek** [comment]
> Is there an older version of arrow running on the backend?

Yeah that's my guess. If an update is not possible (or too likely to break other things), I'm wondering if that version could handle `minute` param, then we could update ENTSOE.py and have it work for others too.

**Comment by Mk-arc** [comment]
I tested changing the minutes= inside replace() to minute=.
Results in a new error:

Traceback (most recent call last):
  File "./test_parser.py", line 86, in <module>
    print(test_parser())
  File "/home/kisle/.local/lib/python3.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/kisle/.local/lib/python3.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/kisle/.local/lib/python3.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/kisle/.local/lib/python3.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "./test_parser.py", line 49, in test_parser
    res = parser(*args, target_datetime=target_datetime)
  File "/home/kisle/git/electricitymap-contrib/parsers/ENTSOE.py", line 809, in fetch_production
    target_datetime=target_datetime))
  File "/home/kisle/git/electricitymap-contrib/parsers/ENTSOE.py", line 619, in parse_production
    datetime = datetime_from_position(datetime_start, position, resolution)
  File "/home/kisle/git/electricitymap-contrib/parsers/ENTSOE.py", line 571, in datetime_from_position
    return start.replace(minute=(position - 1) * digits)
  File "/home/kisle/.local/lib/python3.7/site-packages/arrow/arrow.py", line 614, in replace
    current = self._datetime.replace(**absolute_kwargs)
ValueError: minute must be in 0..59

**Comment by systemcatch** [comment]
I'm in the process of getting an ENTSOE token and will be able to debug locally soon.

**Comment by robertahunt** [comment]
Sorry about the late update on this. You are correct, we actually run arrow 0.10.0 on the backend/feeder at the moment. I am not sure how much trouble it would be to update to the newer version - we have about 10 files that use it.

**Comment by robertahunt** [comment]
@systemcatch do you how much difference there is between the two. Is it worth it to spend some time porting our backend to arrow 0.15.4 now, or should we change the requirements in the contrib to 0.10.0?

**Comment by corradio** [comment]
I would recommend setting the contrib requirements to 0.10.0 for consistency.
This would also avoid creating additional work in the short-term.

**Comment by systemcatch** [comment]
@robertahunt, @corradio, it is worth the time to upgrade. There's been substantial improvements to arrow over the past year and the work needed is minimal.

Since I'm a maintainer for arrow I can easily help with modernizing the backend, you can provide code snippets instead of the full files if you'd rather keep the backend closed.

Also I don't get why there's requirements version differences between the frontend and backend, since this creates a whole set of problems that are hard to debug. If that has to be the case the requirements file should be updated to use the backend versions.

**Comment by corradio** [comment]
Got it. Here's what I suggest as a plan:
1. immediately set currently used arrow version (https://github.com/tmrowco/electricitymap-contrib/pull/2329)
2. make sure our backend uses the version of arrow set here
3. upgrade this repo to last version of arrow (https://github.com/tmrowco/electricitymap-contrib/issues/2330)

**Comment by robertahunt** [comment]
> Also, how come our linter didn't fail with the current setup?

Do linters normally notice that? The problem is that for the feeder we have the feeder-specific requirements file and the contrib requirements file.

**Comment by corradio** [comment]
Yes indeed you're right. If linters don't check that, then it would explain why tests pass on https://github.com/tmrowco/electricitymap-contrib/pull/2329
