### ISSUE TITLE
Data for Aruba

### ISSUE THREAD

**Issue by q--** [tmrowco/electricitymap-contrib#2266]
>Aruba is an island and a constituent country of the Kingdom of the Netherlands in the southern Caribbean Sea

Installed capacity: https://www.webaruba.com/energy-production/power-production-figures ([fossil generation appears to be fuel oil](https://www.webaruba.com/energy-production/technologies-used))
Real-time stats: https://www.webaruba.com/renewable-energy-dashboard/aruba

@woutertP1 mentioned in #2127 that Aruba had a real-time feed available, so I went looking

**Comment by Manu1400** [comment]
@q-- Real-time stats in already in Electricitymap : https://www.electricitymap.org/?page=country&solar=false&remote=true&wind=false&countryCode=AW

**Comment by jarek** [comment]
Yes, it's already there, just really small! You can find it via the country list too!
