### ISSUE TITLE
Add more realtime information about electricity importation/exportation in Finland

### ISSUE THREAD

**Issue by Manu1400** [tmrowco/electricitymap-contrib#2267]
Real time map, contain data about electricity transmission : 
* https://www.fingrid.fi/sahkomarkkinat/sahkojarjestelman-tila/
* https://www.fingrid.fi/-/custom/sahkojarjestelman-tila-169/

GET https://www.fingrid.fi/api/graph/power-system-state?language=fi return JSON data in MW :
```json
{
  "PowerTransferMap": {
    "conn-1": -41.264,
    "conn-2": -758.43,
    "conn-3": 1030.5,
    "conn-4": -37.6,
    "conn-5": -1191.2,
    "conn-6": -984.44
  },
```

**Comment by Manu1400** [comment]
Dataset : 
* https://data.fingrid.fi/en/dataset/commercial-flow-fi-ee Commercial electricity flow between Finland and Estonia (FI-EE)

**Comment by jarek** [comment]
Electricity Map currently has five connections: to Aland, Estonia, Norway, Russia, and Sweden. Looks like the Fingrid data splits the Sweden connections into two, is that right?

Do you know the difference between "commercial flow" with Estonia and data we now get from ENTSOE?

**Comment by corradio** [comment]
Could we merge this issue with #1307 ?

**Comment by robertahunt** [comment]
@Manu1400 I have added your datasets to our other open issue about Finland, but am closing this issue as I think the datasets should be considered together.
