### ISSUE TITLE
Production and consumption swapped on the map?

### ISSUE THREAD

**Issue by GitMatze** [tmrowco/electricitymap-contrib#2269]
Am I missing something here?
Take Iceland for example: the parser only supports production: 

```
>python test_parser.py IS production
parser result:
{'zoneKey': 'IS', 'production': {'hydro': 1551.3561, 'geothermal': 539.698, 'oil': 0.0}, 'storage': {}, 'source': 'amper.landsnet.is', 'datetime': datetime.datetime(2020, 3, 7, 8, 8, 20, 398331, tzinfo=tzutc())}

```
If I go to the map, I see those values showing up on the consumption side (Stromverbrauch): 

![grafik](https://user-images.githubusercontent.com/45139485/76139729-67e78680-6053-11ea-8963-e3ccbf183e8b.png)

The same goes for other countries too.

**Comment by jarek** [comment]
Electricity Map calculations include losses within consumption/Verbrauch. No distinction is made between production and consumption

production + imports - exports = consumption

**Comment by GitMatze** [comment]
Got it, thanks for explaining!
