### ISSUE TITLE
Proposal: new information, the electric frequency

### ISSUE THREAD

**Issue by Manu1400** [tmrowco/electricitymap-contrib#2270]
In Europe, the electricity network value is circa 50 Hz.

The real value in real-time is important: The electric frequency is an indicator of network balance.

More information from RTE about this indicator : https://lemag.rte-et-vous.com/actualites/la-frequence-electrique-un-indicateur-dequilibre-du-reseau

Dataset DAY-1, from RTE 🇫🇷 : https://clients.rte-france.com/lang/fr/visiteurs/vie/vie_frequence.jsp

**Comment by Manu1400** [comment]
A great example of a long time variation in Europe : https://arstechnica.com/tech-policy/2018/04/european-grid-dispute-resolved-lost-6-minutes-returned-to-oven-clocks/

**Comment by Manu1400** [comment]
electric frequency in Georgia: http://www.gse.com.ge/for-customers/data-from-the-power-system/power-balance

**Comment by Manu1400** [comment]
https://ua.energy/activity/dispatch-information/ues-operation/ give a graph about average frequency deviation in Ukraine

**Comment by Manu1400** [comment]
India (Uttar Pradesh): [upsldc](http://www.upsldc.org/real-time-data) give realtime Frequency (Hz)

**Comment by Manu1400** [comment]
Switzerland: https://www.swissgrid.ch/en/home/operation/regulation/grid-stability.html


> Current frequency | 50.034 Hz
> -- | --
> Current grid time deviation | 1.522 s

**Comment by Manu1400** [comment]
G.B. National Grid Status: https://www.gridwatch.templar.co.uk/

> Frequency 50.030Hz

**Comment by Manu1400** [comment]
https://gridwatch.co.uk/frequency give value and graphs

> 50.045 HZ

**Comment by Manu1400** [comment]
http://www.moldelectrica.md/ro/activity/system_state give frequency in realtime in Moldova

Frecvența: | 49.97 | Hz
-- | -- | --

**Comment by corradio** [comment]
Hi @Manu1400 ,

Thanks for the idea! Indeed this is something we thought about but we decided not to include it as our focus is exclusively on carbon emissions.
