### ISSUE TITLE
Add Malta capacity

### ISSUE THREAD

**Issue by Manu1400** [tmrowco/electricitymap-contrib#2271]
> Malta has four electricity plants operational and the total combined nominal installed capacity is 537.8 MW

https://en.wikipedia.org/wiki/Energy_in_Malta#Energy_generation

**Comment by jarek** [comment]
Thanks for the link! However, Electricity Map frontend does not currently display installed capacities if no real-time data is available. As Electricity Map is really focused on real-time generation and climate impact information, this seems like rather low priority?

**Comment by corradio** [comment]
As @jarek mentions, we don't support showing it when data is not available yet. Feel free to submit a PR with the capacity though, in case you want them to be ready for the future!
