### ISSUE TITLE
Data Available for Exchange RU-1->GE

### ISSUE THREAD

**Issue by Manu1400** [tmrowco/electricitymap-contrib#2273]
more data about Power flow than actual map https://www.electricitymap.org/ on http://www.gse.com.ge/for-customers/data-from-the-power-system/power-flow

**Comment by jarek** [comment]
See original discussion in https://github.com/tmrowco/electricitymap-contrib/issues/1212

What are we missing? The separate imports from Russia?

**Comment by robertahunt** [comment]
Looks like we don't account for any imports from Russia to Georgia at the moment. That could be nice to add. @Manu1400 please flag it if I am missing something. I'll change the name of this.

**Comment by jarek** [comment]
Back in 2018 we did have data for RU-GE exchange, see screenshot in https://github.com/tmrowco/electricitymap-contrib/issues/1212#issuecomment-373950581

Currently we use the RU parser for this exchange, evidently RU is no longer working as a data source here

https://github.com/tmrowco/electricitymap-contrib/blob/1657b32d115db6f1c9027fae28f22febb423277f/config/exchanges.json#L1201-L1210

Regarding using the Georgian data for this, during implementation the comments in #1212 were:

> Looks like the exchange with Russia is stuck at 23 MW on that site? It kind of never changes. The "0 MW" exchanges in the upper left corner might be due to the political conflict in Abchasia (since 2008)."

> I agree it is questionable if the exchanges with Russia can be trusted.
One or two of them lead to Abkhazia, the third one is located in South Ossetia.
Both Abkhazia and South Ossetia have claimed independence of Georgia so GSE possibly has no access to the GE->RU flows.

Maybe the GSE data is better now. The numbers as I'm writing this are 64 MW / 0 / 18 MW. We should check back to see if they change:

![Screenshot_2020-03-13_19-14-27](https://user-images.githubusercontent.com/47415/76665856-e9ad4780-655e-11ea-8f3a-28724d97eb7d.png)

**Comment by corradio** [comment]
Any news here?

**Comment by jarek** [comment]
Well, the numbers change at least, so we could try adding them. This is the screenshot right now:

![ge](https://user-images.githubusercontent.com/47415/84213974-10144d80-aa90-11ea-9c1f-7ac39afc5379.png)

Might be as easy as switching from RU.py to GE.py for this exchange? I've not checked what GE.py implements right now.

**Comment by pierresegonne** [comment]
Hey @jarek the `GE.py` already accounts for exchanges with Russia, see

```python
elif exch == 'GE->RU':
  netFlow = -obj['areaSum']['russiaSum']-obj['areaSum']['russiaJavaSum']-obj['areaSum']['russiaSalkhinoSum']
  data['netFlow'] = netFlow
```

So I guess it is just a question of putting the exchanges with from georgia to russia forwards rather than russia to georgia in `exchanges.json`. It's a quick fix so I'll push it myself. Thanks for the investigation!
