### ISSUE TITLE
Contact Energydata to access the EnerdyDataDK data plateform

### ISSUE THREAD

**Issue by Manu1400** [tmrowco/electricitymap-contrib#2274]
List of some datasets of EnerdyDataDK: https://energydata.dk/

Please, contact `info@energydata.dk`

The Electricitymap parser `DK_BHM` use already some data from this company:
https://github.com/tmrowco/electricitymap-contrib/blob/master/parsers/DK_BHM.py

**Comment by Manu1400** [comment]
Documentation of the realtime datahub: http://www.powerlab.dk/Facilities/DigitalEnergyLab

**Comment by robertahunt** [comment]
Hi @Manu1400 Could you give some indication of what data in particular you think the DigitalEnergyLab could provide us that we do not already have, and how it may be an improvement on our current data sources? It is always great to have new contact points, but I know we have the digital energy lab on our radar and am not seeing an immediate need to collaborate with them.

**Comment by robertahunt** [comment]
I am closing this for now, but @Manu1400 please feel free to comment and if there is some immediate need for data from them, we can reopen this, or open an more specific issue.
