### ISSUE TITLE
New RESOURCE_TYPE : photovoltaic AND solar thermal

### ISSUE THREAD

**Issue by Manu1400** [tmrowco/electricitymap-contrib#2277]
https://demanda.ree.es/visiona/peninsula/demanda/total give realtime information about photovoltaic and solar thermal in continental Spain.

Pro 👍:
- Spain produce massive energy (X GW) with solar energy

Possible solution :
Split 'solar' to 'solar.photovoltaic', 'solar.thermal' and 'solar.unknown' (for historical data)

Similar issue: #2272

**Comment by robertahunt** [comment]
Hi @Manu1400. Thanks for bringing this up, it would be nice to make our datasets more accurate! 

However, since our primary focus is on increasing awareness around climate change, could you give any indication of if these technologies have a significantly different carbon footprint?

**Comment by corradio** [comment]
Hi @Manu1400 ,

We won't be able to split the mix (it would clutter the UI up too much), but the carbon intensity could be improved. This is currently covered by https://github.com/tmrowco/electricitymap-contrib/issues/738
