### ISSUE TITLE
Remove URL search params from Redux

### ISSUE THREAD

**Issue by fbarl** [tmrowco/electricitymap-contrib#2296]
After we introduce React Router (#2161), we should consider not maintaining a copy of the URL state in Redux. As [React Router guides](https://reacttraining.com/react-router/web/guides/redux-integration) mention:

> Our recommendation is not to keep your routes in your Redux store at all

There are a few reasons why that might not be desirable, but to single out a generic one - it's always good to have a single source of truth instead of keeping the data in sync between places :)

The only difficulty in making that transition right now is that it might be slightly harder to read and update the URL outside of React components, e.g. from within `main.js`.

**Comment by corradio** [comment]
Absolutely!
