### ISSUE TITLE
Convert 'page' URL param values into separate routes

### ISSUE THREAD

**Issue by fbarl** [tmrowco/electricitymap-contrib#2297]
This naturally extends on #2161 and it's probably a good idea to unload some of the URL search param state onto different routes. I'm suggesting the following routes:

* `/map`
* `/zone/:zoneId`
* `/faq`
* `/info`
* ~`/highscore`~ `/ranking` (only existing in mobile mode)

This would enable us to get rid of the `page` and `countryCode` search params.

**Comment by corradio** [comment]
LGTM. I would just rename `highscore` to `ranking`
