### ISSUE TITLE
Is German gas production always required?

### ISSUE THREAD

**Issue by robertahunt** [tmrowco/electricitymap-contrib#2302]
Hey guys,

This is more of a general question. The German parser has been failing for the past couple days because ENTSOE is not reporting any gas production, and we have set gas production as a required value in our parser.

Does anyone know/have time to check if this rule is still valid? (Ie, should there always be some gas production in Germany? Is the fact that it is reported as N/A now mean that it is actually 0, or is this an error?)

kibana warning log:
https://kibana.electricitymap.org/app/kibana#/discover?_g=()&_a=(columns:!(level,message),filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!f,index:'96f67170-0c49-11e9-85c1-1d63df8c862c',key:extra.key,negate:!f,params:(query:DE,type:phrase),type:phrase,value:DE),query:(match:(extra.key:(query:DE,type:phrase))))),index:'96f67170-0c49-11e9-85c1-1d63df8c862c',interval:auto,query:(language:lucene,query:''),sort:!('@timestamp',desc))

**Comment by Kevindeving** [comment]
Yes. It is needed all the time and not only gas is missing but many other production types too. I assume there is an issue at at least one of the four German energy suppliers and atm most data is missing on entsoe energy production. Maybe someone needs to email them or they will fix it by themselves.

**Comment by robertahunt** [comment]
Alright, thanks! I'll close this. If it isn't fixed soon I'll ping them.
