### ISSUE TITLE
Add dev / staging server

### ISSUE THREAD

**Issue by fbarl** [tmrowco/electricitymap-contrib#2307]
It would be nice if [electricityMap](https://www.electricitymap.org/) had a public dev / staging server which would always reflect the state of the `master` branch in a production-like environment.

Having a staging server would minimize the risk of things going wrong in production releases.

**Comment by corradio** [comment]
absolutely!

**Comment by corradio** [comment]
Hi @fbarl , I'm closing this as it will be considered internally. Stay tuned.
