### ISSUE TITLE
Mobile electricityMap starts empty

### ISSUE THREAD

**Issue by corradio** [tmrowco/electricitymap-contrib#2323]
cc @fbarl 
To reproduce:
1. set browser in mobile mode (or browse from phone)
2. browse to electricitymap.org
Screen is empty:

![image](https://user-images.githubusercontent.com/1655848/77817933-d48ff700-70ce-11ea-989c-374dd980e32e.png)

**Comment by fbarl** [comment]
Ouch, quite embarrassing that I missed that :man_facepalming: 

I managed to reproduce both on prod and `master` - I will try to have a hotfix PR soon.
