### ISSUE TITLE
Turn prodconstoggle.js into a re-usable component

### ISSUE THREAD

**Issue by corradio** [tmrowco/electricitymap-contrib#2325]
Create a re-usable component that can take a redux key alongside a list of (key, labels) and a tooltip description.

**Comment by fbarl** [comment]
> alongside a list of (key, labels)

Can we assume this list would always consist of exactly 2 entries or is there already a use case for a _multi toggle_ on the horizon?

**Comment by corradio** [comment]
Yep there's already a use case for a multi-toggle
