### ISSUE TITLE
CircleCI failing when running tests

### ISSUE THREAD

**Issue by fbarl** [tmrowco/electricitymap-contrib#2331]
![image](https://user-images.githubusercontent.com/1216874/77897902-95060e00-727a-11ea-8e02-fad03ad6e84c.png)

Perhaps a timeout longer than 20 seconds is needed to ensure everything boots up properly?

![image](https://user-images.githubusercontent.com/1216874/77897974-b36c0980-727a-11ea-8b4d-8778ef696667.png)

I hit this twice in a row on https://github.com/tmrowco/electricitymap-contrib/pull/2324 and I also noticed https://github.com/tmrowco/electricitymap-contrib/pull/2328 was failing because of it.

cc @corradio @robertahunt

**Comment by corradio** [comment]
I'm on it
