### ISSUE TITLE
onboarding modal front-end bug on "CO2" subs

### ISSUE THREAD

**Issue by brunolajoie** [tmrowco/electricitymap-contrib#2332]
![image](https://user-images.githubusercontent.com/22095643/77901883-a4885580-7280-11ea-8095-609008b2134d.png)

**Comment by fbarl** [comment]
Good catch @brunolajoie!

That one's probably on me as I suspect it was introduced in https://github.com/tmrowco/electricitymap-contrib/pull/2298.

Looking into it now..
