### ISSUE TITLE
New exchanges for US are still not appearing in the country panels

### ISSUE THREAD

**Issue by robertahunt** [tmrowco/electricitymap-contrib#2340]
![image](https://user-images.githubusercontent.com/13189214/78024792-42e7ea00-7359-11ea-8eb8-d8f56d18c5cc.png)

despite the fact that kibana seems to have no trouble grabbing the exchanges now:
https://kibana.electricitymap.org/app/kibana#/discover?_g=()&_a=(columns:!(_source),filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!f,index:'96f67170-0c49-11e9-85c1-1d63df8c862c',key:extra.key,negate:!f,params:(query:US-MIDA-PJM-%3EUS-MIDW-MISO,type:phrase),type:phrase,value:US-MIDA-PJM-%3EUS-MIDW-MISO),query:(match:(extra.key:(query:US-MIDA-PJM-%3EUS-MIDW-MISO,type:phrase))))),index:'96f67170-0c49-11e9-85c1-1d63df8c862c',interval:auto,query:(language:lucene,query:''),sort:!('@timestamp',desc))

**Comment by fbarl** [comment]
Related to #2319.

**Comment by robertahunt** [comment]
Looks like it fixed itself... maybe I just hadn't waited long enough for the map to update. I love bugs that fix themselves <3
