### ISSUE TITLE
New data source for the US?

### ISSUE THREAD

**Issue by GitMatze** [tmrowco/electricitymap-contrib#2344]
https://www.eia.gov/beta/electricity/gridmonitor/expanded-view/electric_overview/US48/US48/GenerationByEnergySource-4/edit

Note the select-region button on the right.

**Comment by robertahunt** [comment]
This is actually the data we are currently using :D -  we get it through their api per balancing authority - https://www.eia.gov/opendata/qb.php?category=3390101

**Comment by robertahunt** [comment]
It isn't live data though, it has an 8-24 hours lag, which is why most of the zones still appear grey

**Comment by robertahunt** [comment]
So I am going to close this - message me if there is some new data there I am not seeing.
