### ISSUE TITLE
Data for Gulf countries (United Arab Emirates, Bahrain, Saudi Arabia, Oman, Qatar, and Kuwait)

### ISSUE THREAD

**Issue by q--** [tmrowco/electricitymap-contrib#2357]
I did some digging and found https://www.gccia.com.sa/, which has a map with "Demand Now" data for Gulf Cooperation Council countries, which are United Arab Emirates, Bahrain, Saudi Arabia, Oman, Qatar, and Kuwait.

Comparing the value on the map for Kuwait with the [data source](https://www.mew.gov.kw/en) ElectricityMap currently uses for that country, the value on the GCCIA site is only slightly different, possibly due to latency or the fact that I didn't load both sites at the exact same time.

They also have [an app](https://www.gccia.com.sa/gcciamobile.html), with screenshots implying it has historical data graphs.

Edit: forgot to mention - a few countries show an `-` instead of electricity demand right now (Oman, Saudi  Arabia). This might just be temporary.

**Comment by alixunderplatz** [comment]
@q-- i'm so happy to see a new source for the data of a whole geohraphical region :) well done! :+1: :+1: :+1:
