### ISSUE TITLE
KW production is actually consumption

### ISSUE THREAD

**Issue by robertahunt** [tmrowco/electricitymap-contrib#2362]
As pointed out by @q-- the fetch_production in KW.py parser is actually fetching consumption. We should modify our script to treat this as consumption

Two things need to happen:
- [ ] parser KW.py should be changed to consumption
- [ ] historic data in database needs to be corrected (I will do this)

**Comment by alixunderplatz** [comment]
@robertahunt Hi! I knew this, but I added it as production, because it must be equal to consumption due to no cross border links and therefore no exchanges with the neigbours.

**Comment by alixunderplatz** [comment]
edit: at least that was what I knew back then. maybe things have changed, hadn't yet looked at the new data. but I'm sure it's still like this.

**Comment by q--** [comment]
@alixunderplatz https://www.gccia.com.sa/Data/PressRelease/Press_43.pdf  page 37 (38th page in the PDF, page number in document is 37) says there's an interconnection between Kuwait and Saudi Arabia

**Comment by alixunderplatz** [comment]
@q-- you're right, there is an interconnector. but is there any info if it is in use? can you look for any figures for import/export? The IEA data didnt show any exchanges back then.
https://openinframap.org/#6.49/29.136/47.699

**Comment by q--** [comment]
Some googling gave me [this]() report

>The Gulf Cooperation Council established a regional power grid to support high voltage networks in member countries in 2001. The intended purpose of the grid was to provide backup  electricity  during  emergencies  caused  by  power  system  outages,  especially during the summer, and to share spinning reserves, optimize capital investments in electricity and reduce fuel costs.<sup>11</sup> The system to date, however, has been underutilized, but the GCC Interconnection Authority (GCCIA), the grid system’s operator, sees potential in expanding electricity trading among countries. The Northern System of the grid was completed in 2009, connecting the Az-Zour complex in Kuwait to grids in Saudi Arabia, Bahrain  and  Qatar.  The  GCCIA  manages  the  interconnection,  and  the  transmission capacity of the interconnector is 1.2 GW. According to the GCCIA, electricity trading by member states has increased over the past decade. Since it commenced trading, Kuwait has imported slightly more electricity than it has exported, but overall trade has generally been unchanged, at around 550 GWh for both imports and exports.<sup>12</sup> Kuwait imports power in an emergency and only for a few hours at a time. Since 2016, Kuwait has exported as much as 750 MW during the summer peak period to Bahrain and the UAE. In return, Kuwait has imported “in-kind” power during winter months.

They cite GCCIA data, so one of the reports on the GCCIA website might also have it. [Probably this one](https://www.gccia.com.sa/Data/Downloads/Reports/FILE_24.pdf), but the PDF consists of images so I can't search the text. Also, the first half is in Arabic  (but the part starting from page 75 appears to be an English translation).
