### ISSUE TITLE
Hourly power demand for India

### ISSUE THREAD

**Issue by yzhong12** [tmrowco/electricitymap-contrib#2375]
Where to find hourly power demand for entire India and each state?

**Comment by alixunderplatz** [comment]
@yzhong12 try http://meritindia.in and select a state to see its load. real time afaik.

**Comment by yzhong12** [comment]
Cannot download the data

**Comment by alixunderplatz** [comment]
@yzhong12 you'd have to scrape it from the website with some python-code.
