### ISSUE TITLE
Data for country Cyprus

### ISSUE THREAD

**Issue by alexaristotelous** [tmrowco/electricitymap-contrib#2376]
Cyprus doesn't seem to be showing data anymore. 
When checking the "List of sources" Cyprus has:
<http://www.dsm.org.cy/en/daily-system-generation-on-the-transmission-system-mw>

A link that returns HTTP 404. 

The new link is here:
<https://tsoc.org.cy/total-daily-system-generation-on-the-transmission-system/>

It's a shame but they seem to have removed pages in English.
If you need assistance translating anything from Greek please let me know.

**Comment by jarek** [comment]
Thank you!

Looks like the data format has changed, but it should be possible for us to use the new one.

As you might have local knowledge, can you take a look at the page and confirm the following:
- which timezone do the hours seem to be in?
- is the blue line total load? green line wind production? purple line thermal/fossil fuel/conventional production? 
- Google translates the label for the yellow line as "Photovoltaics and Biomass". Do you happen to know or can you find how much is solar and how much is biomass? Currently in the middle of the night it appears to show a constant 5 MW yellow line - does that mean 5 MW is biomass?
- is it still the case that all non-solar and non-wind generation is fuelled by oil?

The chart is drawn based on values included in the HTML source, which look to be generated automatically. The HTML source has several parts like this:

```
        			var dateStr = "2020-04-16";
			var hourStr = "03";
			var minutesStr = "45";
			var dateStrFormat = new Date(dateStr);
			dateStrFormat.setHours(hourStr, minutesStr);
						if (synchronizedGenerationView) {
				forecastValues.push(
				[dateStrFormat, 265, 19, 5, 265, 241]
			);
			} else {
				forecastValues.push(
				[dateStrFormat, 19, 5, 265, 241]
			);
			}
        			var dateStr = "2020-04-16";
			var hourStr = "04";
			var minutesStr = "00";
			var dateStrFormat = new Date(dateStr);
			dateStrFormat.setHours(hourStr, minutesStr);
							tempDate = dateStrFormat;
				if (counter % 2 == 0) { 
					ticksString.push(dateStrFormat);
				}
				counter = counter + 1;
						if (synchronizedGenerationView) {
				forecastValues.push(
				[dateStrFormat, 265, null, null, null, null]
			);
			} else {
				forecastValues.push(
				[dateStrFormat, null, null, null, null]
			);
			}
```

where `265, 19, 5, 265, 241` appears to be forecast (?), wind, solar/biomass, and total load, and the `265, null, null, null, null` appears to be for future times and forecasted loads.

**Comment by alexaristotelous** [comment]
Hey @jarek ,
- Time displayed is local time, which is EEST. Time follows the daylight saving shift, so it is otherwise in EET timezone. 

**Colour-codes**
- Blue: Total load
- Purple: Conventional production
- Yellow: Solar *energy excluding wind* production - this currently includes: PV, Solar thermal (relatively big solar thermal plants are underway), and Biomass. 
- Green: Wind production

**Biomass**
Biomass seems to be less transparent in terms of data. 
I guess the most accurate representation would be to show it combined with other solar production. 
According to the Electricity Authority of Cyprus (EAC), there is 9.7MWe of installed biomass capacity. 

Looking at the past 7 days of RES generation (https://tsoc.org.cy/archive-total-daily-wind-and-solar-farm-generation/?startdt=-6days&enddt=today), there is always a flat 5MW of solar & biomass overnight. 
I am willing to question that number, I suspect that's incorrect and simplified by the EAC. 
More than happy to send them an email and ask. 
If 5MW is correct, it is one of the below:
1) Biomass
2) Solar thermal
3) Combination of above

And sadly yes, Cyprus still relies on just heavy-fuel oil for its conventional generation. 
They have been converting their older-generation steam turbines to combined-cycle gas turbines in transitioning to gas, but that hasn't materialised yet. 

Total conventional capacity is published here:
https://www.eac.com.cy/EN/RegulatedActivities/Generation/powerstationcapacity/Pages/default.aspx


I hope that helps :) 
I am a huge fan of Tomorrow and its work! Let me know if I can help in other ways.

**Comment by systemcatch** [comment]
I'm taking a look at this and the new data layout will require rewriting most of the the parser. Luckily I should be able to use `fetch_solar_production_estimation` as a template to start.

**Comment by q--** [comment]
I think this can be closed now

**Comment by FelixDQ** [comment]
👍 Thank you
