### ISSUE TITLE
Update Capacity Data for Austria (AT)

### ISSUE THREAD

**Issue by brandongalbraith** [tmrowco/electricitymap-contrib#2389]
Austria recently decommissioned their last two coal plants [[1]](https://noe.orf.at/stories/3007102/) [[2]](https://abcnews.go.com/International/wireStory/austria-shuts-coal-fired-power-plant-70221689). [There was a commit to zones.json to reflect this](https://github.com/brandongalbraith/electricitymap-contrib/commit/0307da4d10bb84b0af1f2cfe9ce1c541f0d33148), [but then a more recent commit where capacity data from ENTSO was deferred to](https://github.com/brandongalbraith/electricitymap-contrib/commit/590eb4e3d0fe6dfecef922514769b6bc9db5721d#diff-acbebc28f4bcde4ea895a29977d81628) (ENTSO currently shows 246MW of coal fired electrical generation capacity for Austria). I have emailed ENTSO (transparency@entsoe.eu) [regarding the inaccurate generation capacity data they are reporting for Austria](https://transparency.entsoe.eu/generation/r2/installedGenerationCapacityAggregation/show?name=&defaultValue=false&viewType=TABLE&areaType=BZN&atch=false&dateTime.dateTime=01.01.2020+00:00%7CUTC%7CYEAR&dateTime.endDateTime=01.01.2020+00:00%7CUTC%7CYEAR&area.values=CTY%7C10YAT-APG------L!BZN%7C10YAT-APG------L&productionType.values=B01&productionType.values=B02&productionType.values=B03&productionType.values=B04&productionType.values=B05&productionType.values=B06&productionType.values=B07&productionType.values=B08&productionType.values=B09&productionType.values=B10&productionType.values=B11&productionType.values=B12&productionType.values=B13&productionType.values=B14&productionType.values=B20&productionType.values=B15&productionType.values=B16&productionType.values=B17&productionType.values=B18&productionType.values=B19).

@robertahunt Would it be reasonable for me to submit a PR reducing Austria coal capacity to zero?

[1] https://noe.orf.at/stories/3007102/

[2] https://abcnews.go.com/International/wireStory/austria-shuts-coal-fired-power-plant-70221689

**Comment by robertahunt** [comment]
Yes, I think that is reasonable. Thanks for keeping track of this!

**Comment by brandongalbraith** [comment]
@robertahunt @alixunderplatz mentioned that the shuttered coal generator I referred to is to remain as backup generation capacity, closing this and will revert the coal capacity change in my PR (but intend to retain capacity changes for other generation types).
