### ISSUE TITLE
Wrong import co2eq values

### ISSUE THREAD

**Issue by Kevindeving** [tmrowco/electricitymap-contrib#2391]
See: https://tmrow-team.slack.com/archives/C2DQPTHA6/p1586621359085900

Imports from other countries where there is no current information had estimated (yearly) co2eq value before this issue. Now imports are assumed same co2eq as the countries average whose importing from another country.

**Comment by q--** [comment]
I also noted this on [April 4](https://tmrow-team.slack.com/archives/C2DQPTHA6/p1585930631061200), which resulted in  #2358 being filed. But I think this issue gets to the root of the problem,  #2358 e.g. wouldn't explain why import co2eq from RU-1 was wrong despite the fact it was still listed in co2eq_parameters.json
