### ISSUE TITLE
Update coal capacity of DK2?

### ISSUE THREAD

**Issue by madsnedergaard** [tmrowco/electricitymap-contrib#2392]
The Danish "Amagerværket" has (finally) closed down Block 3 for good, and the plant (and therefore also East Denmark) is now only running on biomass.

But [according to entsoe](https://transparency.entsoe.eu/generation/r2/actualGenerationPerProductionType/show?name=&defaultValue=true&viewType=TABLE&areaType=BZN&atch=false&datepicker-day-offset-select-dv-date-from_input=D&dateTime.dateTime=20.04.2020+00:00|CET|DAYTIMERANGE&dateTime.endDateTime=20.04.2020+00:00|CET|DAYTIMERANGE&area.values=CTY|10Y1001A1001A65H!BZN|10YDK-2--------M&productionType.values=B01&productionType.values=B02&productionType.values=B03&productionType.values=B04&productionType.values=B05&productionType.values=B06&productionType.values=B07&productionType.values=B08&productionType.values=B09&productionType.values=B10&productionType.values=B11&productionType.values=B12&productionType.values=B13&productionType.values=B14&productionType.values=B20&productionType.values=B15&productionType.values=B16&productionType.values=B17&productionType.values=B18&productionType.values=B19&dateTime.timezone=CET_CEST&dateTime.timezone_input=CET+(UTC+1)+/+CEST+(UTC+2)
), there is still an ongoing generation based on "fossil hard coal" 🤔 

Am I missing something? 

Source:
[danskenergi.dk/nyheder/kullet-braendte-ud-paa-amager](https://www.danskenergi.dk/nyheder/kullet-braendte-ud-paa-amager) ([Google translated version](https://translate.google.com/translate?sl=auto&tl=en&u=https%3A%2F%2Fwww.danskenergi.dk%2Fnyheder%2Fkullet-braendte-ud-paa-amager))

**Comment by alixunderplatz** [comment]
@madsnedergaard I remember I used to investigate on this topic for Denmark back in 2018. See issue #1161 for details. Sometimes it takes a while for generation of a unit to be reported in the appropiate category. in guess energinet.dk would be in charge of changing it in this case

**Comment by madsnedergaard** [comment]
Thanks for the explanation and link @alixunderplatz , seems like it's pretty much the same situation of Entsoe either being a bit behind on updating numbers or them knowing something I don't :)

**Comment by corradio** [comment]
@madsnedergaard I believe we can close this as there's nothing we can do?
It might be worth reporting this to ENTSOE though?

**Comment by madsnedergaard** [comment]
Yes, closing it :)
