### ISSUE TITLE
Should Sweden's unknown co2eq be recalculated with no coal power?

### ISSUE THREAD

**Issue by VIKTORVAV99** [tmrowco/electricitymap-contrib#2407]
Sweden recently closed it's last coal power plant. But when I was going to edit it I noticed that Sweden did not have a entry for coal power so I added it.
So now I wonder if I should just change the coal co2eq entry with 0 too?
Does unknown co2eq need to be recalculated?

Source: https://ieefa.org/sweden-becomes-third-european-country-to-complete-coal-plant-phaseout/ 

EDIT: To be clear I mean the co2eq equivalent of coal and unknown.

**Comment by robertahunt** [comment]
It is a good question - We currently assume 72% biomass, 28% conventional thermal for the unknown makeup. As far as I understand Sweden has quite a few combined heat and power plants (which I think are mainly gas/waste powered) - you can see more info here https://pxexternal.energimyndigheten.se/pxweb/sv/%c3%85rlig%20energibalans/%c3%85rlig%20energibalans__El-%20och%20fj%c3%a4rrv%c3%a4rmeproduktion/EN0202_25.px/table/tableViewLayout2/?loadedQueryId=17d13f92-2720-46c9-9727-463aa7d01cfa&timeType=from&timeValue=0.

And I don't think the coal plant they shut down has been in operation much in the past couple years, so I doubt it's capacity change would effect much. But if you/anyone else has time to do some more digging and find a better approximation for the unknown co2 factor, that would be great!

**Comment by VIKTORVAV99** [comment]
I found pretty detailed statistics for the power production of 2018 on Eurostat.
Here is a link to the zip containing the excel tables: [Energy Balances in the MS Excel file format (2020 edition)](https://ec.europa.eu/eurostat/documents/38154/4956218/Energy-Balances-April-2020-edition.zip/69da6e9f-bf8f-cd8e-f4ad-50b52f8ce616)

If I understand this data correct the ratio for 2018 should be:

- Coal: 2.15%
- Manufactured gases: 4.93%
- Peat: 1.95%
- Oil and Petroleum: 1.97%
- Natural gas: 2.41%
- Biofuel: 65.48%
- Biogas: 0.07% (This one can probably be skipped)
- Liquid biofuel: 0.34% (Possibly this one too)
- Renewable Municipal Waste: 9.66%
-  Non-renewable Waste: 10.08%

Now I don't yet have co2eq values for these sources and there might be required to merge some like the waste but it should be a good start. Since this is 2018 data it will be out of date and it still says Sweden used coal but it should still be fairly accurate if we just remove the coal source.

If anyone want to crunch the co2eq value or point me in the right direction to where I might find such data that would be greatly appreciated.

Oh and it got kind of late when doing this so there might be some inaccuracies so if anyone want to double check be my guest.

**Comment by VIKTORVAV99** [comment]
![image](https://user-images.githubusercontent.com/30777521/80491640-46c05980-8963-11ea-8b30-56bb59b923fb.png)
@robertahunt how do these numbers look?
Sources are grouped by category:

- Black: Oil, Petroleum and Non-renewable waste.
- Red: Gas
- Yellow: Biomass
- Green: Solar

Things of note:
- _I had to guess the CO2eq values for Renewable Waste and Non-Renewable Waste._
- _Coal was removed from the data_
- _Solar output is possibly outdated by a big margin_

**Comment by alixunderplatz** [comment]
Hi @VIKTORVAV99 
great chart for the unknown part! :+1: 
just one remark from me: in your chart, you assigned the intensity of biomass to peat. Peat is grouped with the coal production on the electricitymap (compare Finland, Ireland and Estonia), as it is considered to be "not really renewable". even if it has a small share only, can you recalculate with 820g/kWh for peat? Thanks :)
I think your guessings for non-renewable waste are ok (plastic=oil based /renewable waste=biomass based).

**Comment by VIKTORVAV99** [comment]
Ah okay will do, shouldn't make that much of a difference but let's strive for accuracy.

**Comment by robertahunt** [comment]
Fixed by #2435
