### ISSUE TITLE
Coal in Austria

### ISSUE THREAD

**Issue by LeoH67** [tmrowco/electricitymap-contrib#2421]
Mellach, Austria’s last coal fired power plant was retired on April 17th 2020. So Austria got out of coal.
You can do the grey potential graph away.

Source
https://www.zeit.de/wissen/umwelt/2020-04/kohleausstieg-oesterreich-kohlekraftwerk-abgeschalten-fossile-energie

BR
Leo

**Comment by q--** [comment]
https://github.com/tmrowco/electricitymap-contrib/pull/2390#pullrequestreview-395993489 apparently the plant is mothballed but kept as an emergency backup (that'll hopefully never be needed)

**Comment by LeoH67** [comment]
Great! Thank you.
