### ISSUE TITLE
France data offline?

### ISSUE THREAD

**Issue by Kevindeving** [tmrowco/electricitymap-contrib#2444]
France not having any data for more than 24hours now. I can't verify source of: https://opendata.reseaux-energies.fr/

Edit: At least RTE and entsoe data seems to be allright.

**Comment by steinwinde** [comment]
I've provided a tentative bug fix, see #2451 .

**Comment by ajoga** [comment]
The public dataset[2] for production used[1] seems to not be updated anymore. 

No data for 2020-05 are available. I tried to request them via API and via a download of the excel dataset, and they are absent as well. 

The first line of the dataset description says that the feed is supposed to be updated every hour. 

As suggested in the similar #1761 of last year, I shot them a message via their [contact form](https://opendata.reseaux-energies.fr/pages/contact/), referencing this issue. 
I'm also going to reference electricitymap as a project that reuses that data ! :) 

[1] https://github.com/tmrowco/electricitymap-contrib/blob/master/parsers/FR.py#L53 
[2] https://opendata.reseaux-energies.fr/explore/dataset/eco2mix-national-tr/information/?disjunctive.nature&sort=-date_heure

**Comment by peterhughgriffin** [comment]
Is there a reason we don’t use ENTSOE for France? I’m assuming it’s there.

**Comment by robertahunt** [comment]
@ajoga Any response from them? - I found a new area to download the data outside the API, if this isn't fixed soon, we should consider using that instead - https://www.rte-france.com/fr/eco2mix/eco2mix-telechargement 

@peterhughgriffin I don't know the history on this one, but usually we only add a new European parser if there are data quality issues regarding the data we get from ENTSOE. But this data has been unavailable for too long now, so I made a PR to switch to ENTSOE( #2464 )

**Comment by ajoga** [comment]
> @ajoga Any response from them? - I found a new area to download the data outside the API, if this isn't fixed soon, we should consider using that instead - https://www.rte-france.com/fr/eco2mix/eco2mix-telechargement

Nothing so far. Bear in mind that friday may 1st was a public holiday here :-) 

I quickly checked your link, and it is up-to-date indeed. The license terms are however much restrictive on the reuse of that data...

**Comment by robertahunt** [comment]
@ajoga - Good point. I guess we have to hope opendata is updated then, or we just keep using ENTSOE, but I was really excited about using the regional data.

**Comment by robertahunt** [comment]
It is back now with ENTSOE - I'll open another issue regarding switching it back to RTE once data is available
