### ISSUE TITLE
Carbon Intensity for Japan zones not calculated

### ISSUE THREAD

**Issue by robertahunt** [tmrowco/electricitymap-contrib#2448]
Currently carbon intensity for only JP-KY is being calculated, even though we have production data for the other zones. The red thread seems to be that JP-KY has an entry in co2eq_parameteres.json, and the others do not - Although the US zones currently don't have entries there, and yet they are calculated properly

**Comment by robertahunt** [comment]
The plot thickens:
screenshot of JP-CB - it looks like carbon intensity is being shown in the power production graph
![image](https://user-images.githubusercontent.com/13189214/80797469-33e79800-8ba2-11ea-8815-6832fdd4f89e.png)

**Comment by alixunderplatz** [comment]
@robertahunt we used to see carbon intensity in the very first days of the JP parser. Calculation was manually deactivated due to a lacking breakdown of generation.
https://github.com/tmrowco/electricitymap-contrib/issues/541#issuecomment-413620557
and ref #1562

**Comment by robertahunt** [comment]
Thanks! This was really troubling me yesterday!
