### ISSUE TITLE
IN-MH: nuclear is ramping

### ISSUE THREAD

**Issue by alixunderplatz** [tmrowco/electricitymap-contrib#2460]
@GitMatze one question regarding Maharashtra:
it seems like electrcity output from nuclear is ramping up during the day and down during nighttimes. This is quite unusual behaviour for a region with a mix of several fuel sources. Do you still have any of the data from testing the parser back then? Would be great to have a comparison to the recently displayed data.
![grafik](https://user-images.githubusercontent.com/25743609/80909295-51923a00-8d27-11ea-8d51-cac9a976caa3.png)

@robertahunt Is the "India as a whole"-parser IN.py running in the background? If so can you please compare the nuclear output of IN.py vs IN-MH.py  from the database to see if we have any significant ups and downs there as well? thanks :)

**Comment by GitMatze** [comment]
Unfortunately I don't have presentable data right now but I could generate some if you want. However, there will be no difference. I run both parsers in parallel for half a day and checked for any discepancies. Apart from one or two misreadings the results were the exact same. 

If you look at https://github.com/tmrowco/electricitymap-contrib/issues/1443#issuecomment-591862355  I think you see a slight increase during daytime as well.

**Comment by GitMatze** [comment]
Ok, I think I found the issue. As the nuclear plants are part of Central State production, they are scaled down by CS EXCH/CS TOTAL (see https://github.com/tmrowco/electricitymap-contrib/issues/1443#issuecomment-590799851). Nuclear production as displayed on the dashboard is actually pretty much constant, what changes is the factor. This once again goes back to the problem that the dashboard does not provide the breakdown we need.

Here are two dashboards, one for night and one for daytime.

![grafik](https://user-images.githubusercontent.com/45139485/80912152-5365f880-8d3b-11ea-9259-a7ce9e65daaa.png)
![grafik](https://user-images.githubusercontent.com/45139485/80912162-5c56ca00-8d3b-11ea-88c1-12fc3d8648bb.png)

**Comment by robertahunt** [comment]
@alixunderplatz 
It does look like they report some variation in the nuclear for the IN parser as well:
Here is all of April 1, 2020 - present, nuclear generation:
![image](https://user-images.githubusercontent.com/13189214/80966091-1ae61d80-8e14-11ea-96e8-0ad96b7930a1.png)

And just looking at the last couple days:
![image](https://user-images.githubusercontent.com/13189214/80966132-2f2a1a80-8e14-11ea-8b2d-da097dbf53c8.png)

**Comment by robertahunt** [comment]
@alixunderplatz Do you still think this is an issue? Although I agree it is weird that it appears to ramp up and down, that fluctuation also seems to be reported on the national data. What do you think?

**Comment by tth4vb** [comment]
Circling back to this issue - given the ramping is also reflected in national data and that there is precedent for nuclear plants ramping in other parts of the world, right now I don't see a reason to distrust this data right now. A bit of research of the nuclear situation in IN didn't shed any further light on the possibility of ramping or not.

Right now, the larger issue I see is that this parser is only getting values coming in a couple hours out of every 24, making it not very useful when looking at the last 24h on eMap. Going to check if there are any existing issues about this and if not, open up an issue.
