### ISSUE TITLE
Solar layer not showing up

### ISSUE THREAD

**Issue by fbarl** [tmrowco/electricitymap-contrib#2466]
When I tried turning on [solar forecast](https://www.electricitymap.org/map?solar=true) at 9:50am UTC, the following happens:

1. Two API calls are made, both of them failing with `Forecast was not found`:
  * `/v3/gfs/solar?refTime=2020-05-04T06:00:00.000Z&targetTime=2020-05-04T09:00:00.000Z`
  * `/v3/gfs/solar?refTime=2020-05-04T06:00:00.000Z&targetTime=2020-05-04T10:00:00.000Z`
2. After that, fallback requests are successfully made with `refTime` being pushed 6 hours behind and `targetTime`s staying the same:
  * `/v3/gfs/solar?refTime=2020-05-04T00:00:00.000Z&targetTime=2020-05-04T09:00:00.000Z`
  * `/v3/gfs/solar?refTime=2020-05-04T00:00:00.000Z&targetTime=2020-05-04T10:00:00.000Z`
3. However, both requests in (2) actually return a JSON with a header `{refTime: "2020-05-04T00:00:00+00:00", forecastTime: 6, …}`, meaning they target the 6:00am UTC time which neither corresponds to the `targetTime` values nor actually provides a time interval to interpolate in (since both timestamps are the same). As a consequence, we hit `Error while interpolating solar because current time is out of bounds` and the solar layer doesn't get rendered.

I've been noticing this bug during the last couple of weeks, but I wasn't sure how to interpret it until recently as I was working on #2395. It seems that the API just responds with the wrong data in (2) although it's also not clear to me why (1) regularly fails :thinking:

**Comment by FelixDQ** [comment]
Should be fixed now
