### ISSUE TITLE
Switch data source for France back to RTE

### ISSUE THREAD

**Issue by robertahunt** [tmrowco/electricitymap-contrib#2469]
See #2444 and #2464  - Because RTE data was unavailable for 4 days straight, we temporarily switched to ENTSOE. Assuming RTE data becomes available again we should probably switch back and rescrape historic data.

**Comment by ajoga** [comment]
In https://github.com/tmrowco/electricitymap-contrib/issues/2444#issuecomment-622565942 I wrote an email to the data provider. I'll follow-up here when the answers shows up.

**Comment by robertahunt** [comment]
Looks like the data is back 

https://opendata.reseaux-energies.fr/explore/dataset/eco2mix-national-tr/table/?disjunctive.nature&q.from_date.date_heure=date_heure%3E%3D%222020-05-03T22:00:00Z%22&sort=-date_heure

**Comment by ajoga** [comment]
Yep, I got an answer few hours ago in that direction too
