### ISSUE TITLE
Remove outdated survey link

### ISSUE THREAD

**Issue by q--** [tmrowco/electricitymap-contrib#2471]
https://tmrow-team.slack.com/archives/C2DQPTHA6/p1588511290309900

**Comment by robertahunt** [comment]
@q-- The link you are sending doesn't work for me. Could you expand on this a bit? (maybe put a screenshot?)

**Comment by steinwinde** [comment]
This refers to a comment I posted over the weekend:
Has anyone ever done the little survey behind "Like the visualization (Google Forms)? We'd love your feedback!" at the bottom left corner? It doesn't look like anyone took an interest in its results: Columns and lines of the question "How much would you be willing to donate to.." appear to be inverted. In addition to that I would suggest not to offer users to do the same questionnaire again in the end - it's meaningless.

**Comment by robertahunt** [comment]
I see what you mean. @martincollignon @fbarl Do either of you know who maintains the survey? 
![image](https://user-images.githubusercontent.com/13189214/81666849-daedee80-9442-11ea-9e75-cc65970f5df5.png)

**Comment by fbarl** [comment]
> @martincollignon @fbarl Do either of you know who maintains the survey?

I don't, I actually just clicked through the survey the other day and was surprised how nice and detailed it was!

**Comment by corradio** [comment]
Should we just remove the survey? We don't use it anymore.

**Comment by fbarl** [comment]
> Should we just remove the link to the survey? We don't use it anymore.

I think it should be removed if it's not being used anymore, but I wonder what are the main feedback channels right now if this survey is not used? :slightly_smiling_face:

**Comment by corradio** [comment]
> > Should we just remove the link to the survey? We don't use it anymore.
> 
> I think it should be removed if it's not being used anymore, but I wonder what are the main feedback channels right now if this survey is not used? 🙂

Well our email and the slack channel are good feedback channels (and we regularly get feedback there!)

**Comment by fbarl** [comment]
> Well our email and the slack channel are good feedback channels (and we regularly get feedback there!)

Ok I agree, there is still "Found bugs or have ideas? Report them here." + social media buttons as the CTAs from the app :+1:
