### ISSUE TITLE
Running locally

### ISSUE THREAD

**Issue by rolanddosa** [tmrowco/electricitymap-contrib#2475]
Hi all, I am trying to do 'docker-compose build' on the master branch, but I have this issue: 

**FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory:**
     I tried increasing the space with     `"build-release": "export NODE_ENV=production && NODE_OPTIONS=--max-old-space-size=8192 && webpack --bail --mode production",`   but still failing..

Anyone else had this issue? Let me know any suggestions please, thank you

**Comment by fbarl** [comment]
Hi @rolanddosa, thanks for reporting the issue!

Could you please tell us which OS you're using and share the output of the following commands to try to reproduce your problem:

```
node --version
docker --version
docker-compose --version
```

My bet is that upgrading your node [might fix it](https://github.com/webpack/webpack-sources/issues/66#issuecomment-531862216), that's what I'd try next!

**Comment by rolanddosa** [comment]
Hi just upgraded my node, but still no luck..

I'm running on Windows. 
$ node --version
v12.16.3
$ docker --version
Docker version 19.03.1, build 74b1e89e8a
$ docker-compose --version
docker-compose version 1.24.1, build 4667896b

Also I had to get Docker Tools as I have Windows 10 Home, would that be an issue?

**Comment by rolanddosa** [comment]
Fixed it, the syntax was wrong, it worked with     `"build-release": "export NODE_OPTIONS=--max-old-space-size=4096 NODE_ENV=production && webpack --bail --mode production",`

The other issue I'm facing now is  my node is stuck on starting:
```
web-watch_1   | <s> [webpack.Progress] 98% after emitting
web-watch_1   | <s> [webpack.Progress] 100%
web_1         | [nodemon] starting `node server.js`
web-watch_1   |
web_1         | [nodemon] restarting due to changes...
web_1         | [nodemon] starting `node server.js`



```

**Comment by rolanddosa** [comment]
Fixed now, I was checking localhost instead of the Docker's IP address. Will close this issue now.

**Comment by fbarl** [comment]
Glad it all worked out for you in the end @rolanddosa, and thanks for sharing all the bumps you experienced along the road :wink:
