### ISSUE TITLE
Most of europe missing

### ISSUE THREAD

**Issue by DonatelloXX** [tmrowco/electricitymap-contrib#2478]
Most european countries are missing since yesterday (5th May).

**Comment by Kevindeving** [comment]
This is due to a data publication failure on entsoe tp: https://m-transparency.entsoe.eu/news/widget?id=5eb1508d5092e76bcbdd44d1

**Comment by alixunderplatz** [comment]
If anybody is up to writing alternative/backup parsers, have a look on #1015 (no guarantee the links still work, it's been a while since I started that collection^^)

**Comment by martincollignon** [comment]
Fixed by ENTSOE - would be great if people can help on #1015 (pinned it!)

**Comment by Kevindeving** [comment]
seems like we are having problems again for the moment....

**Comment by DonatelloXX** [comment]
@martincollignon We miss most of europe again. Reopen this issue or create another?
