### ISSUE TITLE
Ibiza, Formentera & Montenegro deactivated without production

### ISSUE THREAD

**Issue by alixunderplatz** [tmrowco/electricitymap-contrib#2483]
When there is no production on Ibiza or Formentera, the carbon intensity of the islands will not be calculated. We need an exception here, because this is a regular and valid scenario.
Ibiza mostly imports from Mallorca. Formentera mostly imports from Ibiza.
That carbon-chain is often interrupted when one of the zones has no own generation.

For Formentera, when solar returns, the carbon intensity is calculated and displayed on the map.
At night times when importing the entire electricity from Ibiza, the island is grey. But it seems like the default databse value for the imports from Ibiza is used when Ibiza has no production.

![image](https://user-images.githubusercontent.com/25743609/81383723-09e12900-9100-11ea-8cc4-013bfa4e2422.png)

Ibiza seems to have no own production at the moment, because the load is so low (no tourism as usual = low demand). So instead of greying-it-out, it should get the carbon intensity of the imports from Mallorca. This should also be passed on to the imports of Formentera.

https://demanda.ree.es/visiona/baleares/ibiza/acumulada/2020-05-07
https://demanda.ree.es/visiona/baleares/formentera/acumulada/2020-05-07

![image](https://user-images.githubusercontent.com/25743609/81385352-bde3b380-9102-11ea-9e21-e6e87af31851.png)

By the way: The same exception should be included for Menorca<->Mallorac, just in case. 
The interconnector cable between these islands is undergoing reconstruction, after it was damaged back in 2018 or 19. When it'll be back online, it's possible that Menorca's demand will also be covered temporarily by imports from Mallorca.

**EDIT:** Same issue for Montenegro accordIng to the next comment:

![grafik](https://user-images.githubusercontent.com/25743609/81503166-71ef6500-92e2-11ea-85a8-f99abb6ddec3.png)

**Comment by Fred-3000** [comment]
Montenegro has the same issue.

**Comment by robertahunt** [comment]
@alixunderplatz Could this be because the current Ibiza parser returns no data instead of reporting the production as 0?

https://github.com/tmrowco/electricitymap-contrib/blob/db85902207871b01409054cd3eb2b7737b59316f/parsers/ES_IB.py#L99-L101

I am not 100% sure, but I suspect that if we let the parser return 0 production instead of giving an error, the carbon intensity will be calculated, and the imports would be properly included, then we don't need to maintain an exception.

**Comment by alixunderplatz** [comment]
@robertahunt thanks for looking into this issue! 
I tried ">=" instead of ">" and got the desired zeros returned for production. :) let's try this!
I'll submit that micro-PR for the ES-IB.py

I guess for Montenegro, the exception is required though?

**Comment by robertahunt** [comment]
Maybe - Montenegro seems like a more complicated region though. I haven't had time to dig into the issues that might arise there. If someone else does we can tackle that. I suspect the same trick might work?

**Comment by alixunderplatz** [comment]
Montenegro seems to have 400kV+220kV interconnectors to Albania, which may disrupt the carbon intensity, as most of Albanian energy comes from hydro. https://www.entsoe.eu/data/map/ 
But that power flow data hasn't been reported to entsoe for a while already.
In general, it is totally okay for montenegro to no have any production because of the new interconnector with Italy

**Comment by robertahunt** [comment]
@alixunderplatz just to update you, Seems like I was wrong on this one - we have merged the changes that you made, but still looks like Formentera is not using the correct carbon intensity for imports from Ibiza/Mallorca. Guess we will need to find another fix.
