### ISSUE TITLE
Refine colors or range of wind speed bar

### ISSUE THREAD

**Issue by alixunderplatz** [tmrowco/electricitymap-contrib#2491]
@fbarl and I had a brief conversation about the colors and range of the wind speed bar.
With some of the latest changes it became a bit harder to distinguish speed areas by their color, especially when screenshotting the map. This is due to the bars new maximum of 30 m/s (=108 km/h, which rarely happens in most places).

Let's use these power curves for very common turbiens from a publication on [resarchgate](https://www.researchgate.net/publication/257748412_Using_machine_learning_to_predict_wind_turbine_power_output) to illustrate the issue:

![grafik](https://www.researchgate.net/profile/Paul_Fleming8/publication/257748412/figure/fig5/AS:668293715218439@1536345046255/Power-curves-for-several-different-utility-scale-wind-turbines-Data-are-from-the.png)

The speed range between 5-15 m/s (measured at hub height, which mostly is around 80-120m) usually is the one with the most crucial change in output power of a wind turbine, as power corresponds to v^3. Beyond this range, blades are pitched and Pmax is constant till the cut-out speed is reached (like 25-30 m/s, beyond that forces on the structures are getting too high etc.).

So my suggestion is to readjust the colors: white-grey up to 5, blue-purple up to 15 m/s, fading to pink until 25 m/s and maybe even to red above that, as red isn't used for anything yet?

What do you think?

![grafik](https://user-images.githubusercontent.com/25743609/81503320-43be5500-92e3-11ea-9a98-4736f13cfb23.png)

**Comment by fbarl** [comment]
Thanks for summing this up @alixunderplatz, the graphs specifically I find very useful!

> So my suggestion is to readjust the colors: white-grey up to 5, blue-purple up to 15 m/s, fading to pink until 25 m/s and maybe even to red above that, as red isn't used for anything yet?

I have an alternative idea here - how about we use a monocolor scale which starts transparent at 0 m/s, climbs up to a full color (let's say cyan) at 15 m/s, stays there till 25 m/s and then has a sharp decline back to transparent where it stays till 30 m/s. In other words, what I'm suggesting is to use a cyan color for the scale and make its opacity a direct function of turbine efficiency based on the graph above.

My thinking is that the main thing we want to show here is how usable the wind is at a certain area and since 30 m/s winds would be as good as 0 m/s, there is no reason why it should have a different color from the power potential perspective - WDYT @alixunderplatz @corradio ?

**Comment by corradio** [comment]
Not against it - screenshots would help us decide!
In case of doubt, I would probably tend to revert to original behavior.

**Comment by pierresegonne** [comment]
Could be nice to group with #1157

**Comment by corradio** [comment]
@alixunderplatz @fbarl any preferences?
Would love to close this one :)

**Comment by fbarl** [comment]
I don't have a strong preference here but if we go down the line of tweaking the colour palette, I'd like us to also address my suggestion in https://github.com/tmrowco/electricitymap-contrib/issues/2491#issuecomment-626714655:

> what I'm suggesting is to [...] make its opacity a direct function of turbine efficiency based on the graph above

Not sure if that makes sense and if there's a more standard way of visualizing wind speeds, I'm fine dropping this idea :slightly_smiling_face:

**Comment by corradio** [comment]
@fbarl can you help me pinpoint where the change occurred? I can't seem to find the commit that changed `scales.js` - did we modify another file that ended up making the change that @alixunderplatz mentions in the first comment of this issue?

**Comment by fbarl** [comment]
> @fbarl can you help me pinpoint where the change occurred?

Sure, took me a while too to locate the change, but I managed to dig it up: https://github.com/tmrowco/electricitymap-contrib/pull/2299/files#diff-c4e69b5da3e11a4363b05a005d3d4cc0a32947880cf3f8134653a85b5dbc5665L14-L16
