### ISSUE TITLE
Don't show arrows when zoomed out

### ISSUE THREAD

**Issue by GitMatze** [tmrowco/electricitymap-contrib#2497]
At low zoom levels, including the default one, the import/export arrows are unrecognizable but take up a lot of resources.

**Comment by fbarl** [comment]
Thanks for the suggestion @GitMatze, I'm fully on board with you here!

I've actually already tackled this [here](https://github.com/tmrowco/electricitymap-contrib/pull/2481/files#diff-31d196d1ca900b0fc47407db518f2b1aR75), in case we decide not to go with CSS arrow animations for now, I'll pull that change out to address this issue specifically :slightly_smiling_face:

**Comment by GitMatze** [comment]
@fbarl Ok!

**Comment by fbarl** [comment]
Let's still keep this issue open, we might want to postpone merging of #2481 and address this separately.

**Comment by corradio** [comment]
@fbarl is that still applicable?

**Comment by fbarl** [comment]
> is that still applicable?

It seems that my reply didn't get through :thinking: Yes, this is still something to be addressed - I did it in #2481 but that PR might not end up getting merged so I think I should do it separately to be able to close this earlier.

**Comment by corradio** [comment]
> > is that still applicable?
> 
> It seems that my reply didn't get through 🤔 Yes, this is still something to be addressed - I did it in #2481 but that PR might not end up getting merged so I think I should do it separately to be able to close this earlier.

I think it'd be great if you could extract that indeed!
