### ISSUE TITLE
Allow contribution via email

### ISSUE THREAD

**Issue by GitMatze** [tmrowco/electricitymap-contrib#2499]
Currently, clicking on a blank region prompts users to participate via GitHub. This is probably too big a hurdle for non-programmers (i.e. 98% of the people). Simply providing an email address or a contact form would make it a lot easier for users to leave valuable hints and sources.

Sorry if this has been discussed before.

**Comment by fbarl** [comment]
I like your idea @GitMatze!

The closest thing in the app right now to my knowledge is the feedback form (which also nudges users to reach out via email):

![image](https://user-images.githubusercontent.com/1216874/81567539-b8a19580-939c-11ea-9d55-ca8bf180e257.png)

Perhaps we can extend on this and provide something similar also when clicking on a blank region?

![image](https://user-images.githubusercontent.com/1216874/81567685-ed155180-939c-11ea-8589-d4edbe70abfe.png)

**Comment by GitMatze** [comment]
To avoid getting the same hints from different people over and over again we could show a little info message for each region briefly summarizing the current status on available and missing data plus the link to the relevant Github issues for those who want to know more. This will get people started right away and I feel like people might  also be intrigued to see if they can find out more.

**Comment by robertahunt** [comment]
@GitMatze I really like the idea of giving people a summary of the current status of the region. I am more skeptical of e-mail feedback as we already receive a lot of e-mails on a daily basis and sorting through them is already quite a chore, so redirecting everyone to github where the eMap community can help direct and shape ideas and feedback is much preferred from my perspective. However, I think we could do a lot to make the github community more accessible for people - add more information to the readme, give a better introduction as to how we work, and what questions should be directed where, and like you said, point to relevant issues for each region.

**Comment by GitMatze** [comment]
I totally get you @robertahunt. 
Seems like there is a GitHub API. So maybe a pretty neat alternative to email would be to provide a contact form that automatically posts a  message in a collective issue on GitHub? For further inquiries they could also leave their email address privately to the tomorrow team.

**Comment by robertahunt** [comment]
That sounds like a good idea. If there is a way to auto-generate a github issue that would be really nice.

**Comment by GitMatze** [comment]
There is a way, indeed. The GitHub API is, in fact, super extensive.
I created a little demo and it works like a charm. https://github.com/GitMatze/githubAPI

**Comment by robertahunt** [comment]
Nice!! Unfortunately we have some other higher priority things to do before this. If you have time to try implementing this, that would be great. Otherwise, we, or perhaps someone else in the community, will pick this up later.

**Comment by GitMatze** [comment]
I'll try to implement this the next couple of days.

**Comment by corradio** [comment]
@GitMatze any luck?

**Comment by pierresegonne** [comment]
Hey @GitMatze thanks for the contribution, 

It would be a nice addition to eMap, there are a few safety considerations we need to discuss internally (e.g how we can restrict this access to only add a new issue and not be used to maliciously delete other issues as well), and a bit of thinking of how to handle and label new issues generated that way (which would potentially be less specific and harder to act on). 

We'll give an update as soon as we can :)

**Comment by tth4vb** [comment]
Closing this issue as the associated PR is closed for now. Hopefully we'll be able to revisit this in the future :)
