### ISSUE TITLE
EU power consumption / CO2 intensity is missing for EU

### ISSUE THREAD

**Issue by smiley0455** [tmrowco/electricitymap-contrib#2503]
Hi,

Many thanks for the ElectricityMap project. I noticed that live data for electricity consumption and carbon intensity is missing for most of the EU. Can you please look into this?

Thank you.

**Comment by Kevindeving** [comment]
This is again unfortunately a problem of entsoe transparency plattform data provider as you can see on their newspage: https://m-transparency.entsoe.eu/news/widget?id=5eba90db5092e76384320590

**Comment by smiley0455** [comment]
Many thanks for the prompt reply!

**Comment by robertahunt** [comment]
Closing this as it is back now.
