### ISSUE TITLE
Current Québec ( Canada ) export intensity impossible

### ISSUE THREAD

**Issue by Alain-Ivadolabs-Ext** [tmrowco/electricitymap-contrib#2507]
Hi,
While we don't have yet the live data from province of Québec in Canada, the value of its carbone intensity is **301 gCO₂eq/kWh** shown currently on electricitymap.org is simply not possible, the vast majority of the generation of electricity there is hydro and some wind.
We should see more a number like **20** or **25 gCO₂eq/kWh**. Maybe 30.
But 301, it's simply impossible with all the installations of large hydro, and very little biomass and thermal.

**Comment by jarek** [comment]
Hi, thanks for the note! It is indeed the case, we are tracking this problem in issue #2358.

Before it went missing, we were estimating the intensity as 30 gCO₂eq/kWh based on Statcan data from CANSIM Table 127-0002 for 2011-2015... it might be lower now. I see that Statcan has data up to 2020 now so it might be possible to update it, I'll take a look at some point.

**Comment by corradio** [comment]
Closing in favor of https://github.com/tmrowco/electricitymap-contrib/issues/2358

**Comment by corradio** [comment]
Re-opening as I believe the simplest to do is to add a fallback value for the mix https://github.com/tmrowco/electricitymap-contrib/blob/master/config/co2eq_parameters.json#L796

**Comment by pierresegonne** [comment]
Used https://www150.statcan.gc.ca/t1/tbl1/en/cv.action?pid=2510001501#timeframe to obtain production data (as well as https://www.cer-rec.gc.ca/nrg/ntgrtd/mrkt/nrgsstmprfls/qc-eng.html to see that "combustible fuels" is actually ~90% biomass)
