### ISSUE TITLE
Coal CO2 eq for Estonia

### ISSUE THREAD

**Issue by Spyder2000** [tmrowco/electricitymap-contrib#2514]
Just to question, why all coal CO2 eq is set to 820, while for Estonia it is set to 1515 gCO2eq/kWh

**Comment by nessie2013** [comment]
"part of production comes from shale oil. it is a coal-like rock containing mineral oil. it used to be labeled as "oil" in the beginning on EM, but was moved it to the coal category later." relates to one of my old closed issues here #2248 

additional context for CO2 eq can be found at #2118
