### ISSUE TITLE
Electricity sources in the power graph could be rearranged

### ISSUE THREAD

**Issue by RRyyas** [tmrowco/electricitymap-contrib#2522]
So i experience when using this website that the graphs are a bit misleading in that they don't reflect a "duck curve", typically in California and Germany, because it places solar power in the middle of the graph. Baseload energy sources, such as nuclear, geothermal, coal and biomass should be placed at the bottom of the graph, just like what it is right now, and the dispatchable energy sources, such as gas, oil and hydropower should be placed in the middle and the intermittent energy sources, such as solar and wind, should be placed at the top of the graph. That would show how much the dispatchable energy sources would need to quickly ramp up production when the sun goes down or when the wind stops blowing.

**Comment by jarek** [comment]
For some history, previous discussions or changes of the order were:
* https://github.com/tmrowco/electricitymap-contrib/commit/de4064461615cfee7010c810b462ebdaa71469d8
* https://github.com/tmrowco/electricitymap-contrib/pull/1538
* https://github.com/tmrowco/electricitymap-contrib/pull/1800
* https://github.com/tmrowco/electricitymap-contrib/issues/1745 idea to add a switch to support different orderings

**Comment by RRyyas** [comment]
Those discussions are for the baseload sources, which is already done. None of them discusses the dispatchable and intermittent sources, which are completely out of order.

**Comment by corradio** [comment]
The reason why oil, gas and hydro are on top of wind & solar is that oil, gas and hydro are/can be used for balancing the grid, and as such, they can "fill" the void left by renewable in order to match total consumption.
This is the rationale for having dispatchable sources on top of intermittent.

**Comment by RRyyas** [comment]
> The reason why oil, gas and hydro are on top of wind & solar is that oil, gas and hydro are/can be used for balancing the grid, and as such, they can "fill" the void left by renewable in order to match total consumption.
> This is the rationale for having dispatchable sources on top of intermittent.

This can help you understand the situation about highlighting the issue i was talking about: 
https://seekingalpha.com/article/4262588-californias-mid-day-solar-power-glut-become-obvious

**Comment by tth4vb** [comment]
Closing this issue for now as it doesn't look like we'll be making a change in the foreseeable future. Feel free to contribute any other specific suggestions on ordering in the future :)
