### ISSUE TITLE
Graph goes wrong with -ve prices

### ISSUE THREAD

**Issue by andy-dinger** [tmrowco/electricitymap-contrib#2523]
![96C7698C-0415-4B8A-8454-D840C7564003](https://user-images.githubusercontent.com/61416039/82748622-88de8e80-9d9b-11ea-8ea8-cf87f87e7f68.jpeg)
The electricity prices graph gets pretty messy when the values go negative. And the price box doesn’t show the value

**Comment by Kevindeving** [comment]
I don't have this problem anymore. Has been fixed in the past weeks for me.
![Screenshot_20200524_095437_com android chrome](https://user-images.githubusercontent.com/4691618/82748749-aa904380-9da4-11ea-8b18-16fd1ec36efa.jpg)

**Comment by andy-dinger** [comment]
> I don't have this problem anymore. Has been fixed in the past weeks for me.

Oh yes, should have said I’m using the iOS version 1.2.2
Which version are you using?

**Comment by Kevindeving** [comment]
Mobile Web version. I think this should be fixed in the next application update for iOS version.

**Comment by fbarl** [comment]
> I think this should be fixed in the next application update for iOS version.

Yup, I expect so as well - we've been waiting to make sure the app is stable enough on the web after all the React transitions we did before bumping the mobile app versions. The resulting performance degradation https://github.com/tmrowco/electricitymap-contrib/issues/2304 is probably one of the things that'd be nice to address before cutting a new mobile release.

**Comment by corradio** [comment]
Should be done now with the iOS/Android release
