### ISSUE TITLE
Austria coal capacity

### ISSUE THREAD

**Issue by moinmoin2** [tmrowco/electricitymap-contrib#2524]
#The Region Austria has shutdown his last coal fired power plant a few weeks ago for ever. So you can remove coal from the chart

**Comment by nessie2013** [comment]
the plant has been mothballed, but could still be used for backup generation in an emergency, thus is still counted as capacity. relates to this PR #2390 and Issue #2513

**Comment by jarek** [comment]
@alixunderplatz Could you double-check if Austria's Mellach coal plant is going to be kept as backup with coal as fuel?

I looked briefly and found references, but only to gas (e.g. "Der Verbund wird die Kraftwerksanlage in Mellach für die Anforderungen der sogenannten Engpassvermeidung auf der Brennstoffbasis Erdgas betriebsbereit halten" https://hlk.co.at/a/keine-kohle-mehr-in-oesterreich or "... Fernheizkraftwerk Mellach, das kurzzeitig auch mit Gas betrieben werden kann.“ https://steiermark.orf.at/v2/news/stories/2984926/)

But you're better informed in the industry. (Is it that everyone is telling people that it's off, but there is still a contract for it to run on coal if found needed?)

**Comment by jarek** [comment]
Another quote https://www.meinbezirk.at/graz-umgebung/c-wirtschaft/oesterreichs-letztes-kohlekraftwerk-hat-den-betrieb-eingestellt_a4043238 "Das letzte Kohlekraftwerk ... kann künftig bei Bedarf kurzzeitig mit dem Brennstoff Erdgas für die überregionale Stromnetzstützung eingesetzt werden." saying it can be used for backup with natural gas

**Comment by FelixDQ** [comment]
Hi guys, I'm going to close this issue for now due to staleness and I'm not quite sure what the actionable step is. Let me know if I'm missing something.
