### ISSUE TITLE
data being used by people claiming we need gas and nuclear

### ISSUE THREAD

**Issue by PatrickMerlevede** [tmrowco/electricitymap-contrib#2528]
On FB I saw a screenshot from the data for Belgium (27 May 2020) taken at 23h30 - according to the person posting, it gives the impression that the full capacity of Solar was "not used" yesterday (while it's clear that on a day like this, solar is at 100% capacity) - for my own solar panels, it was the second best day of the month ... I know that the argument of "Tomorrow" is that this is caused by excess electricity being generated (e.g. by gas and nuclear)... 
However, from looking at the data/graphs, you get no idea where the excess electricity went and thus people can use te graph to claim that more gas and nuclear are needed... and that we certainly can't do without... how can the data been used/explained to counter that interpretation ?

link to the post/picture https://www.facebook.com/photo.php?fbid=3233287013389107

**Comment by DragosPetria** [comment]
I am not associated with Tomorrow.

ElectricityMap gives real-time data. As such, of course, no sun was shining at 23:30. 

That's leaving the political stuff aside, but if you're looking for proof that renewables alone work, real-world data from electricityMap won't support that, sorry.

**Comment by corradio** [comment]
Hi @PatrickMerlevede and @DragosPetria ,
Unfortunately there's not much we can do here. Our goal is simply to provide transparency.
