### ISSUE TITLE
Separate Flinders Island from Tasmania

### ISSUE THREAD

**Issue by chuqtas** [tmrowco/electricitymap-contrib#2533]
(first submission, please be nice if I've done it wrong!)

This request is similar to the King Island request:  https://github.com/tmrowco/electricitymap-contrib/issues/636 "split Australia (Tasmania) to show King island off grid system"

Basically it relates to another island with many similarities = it is in the same area of the world, also with it's own off-grid power system, also built and operated by Hydro Tasmania, also with a web & app dashboard for live info.

However - it's dashboard is a totally different design and therefore parsing the data might be easier (or maybe no different - no idea).

There are two parts to this issue:

1) Re-arranging regions:
- Remove Flinders Island and nearby island from the "Tasmania" region
- Create new "Flinders Island (Australia)" region with just the large one
- Leave the small one blank - if it needs a name, call it "Cape Barren Island (Australia)".
- The island at the bottom of Tasmania should stay as part of the "Tasmania" region, no changes needed

![image](https://user-images.githubusercontent.com/51102336/83344283-f1071480-a347-11ea-99b3-6417e5ecc770.png)

2) Attempt to extract data from the dashboard to apply to this region.

The website is - https://www.hydro.com.au/clean-energy/hybrid-energy-solutions/success-stories/flinders-island for anyone who is able to make sense on whether this data can be extracted or not.

Hope I've provided enough info - can't be of much use with the data extraction/coding though :(

**Comment by q--** [comment]
I'm seeing requests to `data.ajenti.com.au/live/signalr/` on that page in my browser console, which is also present in https://github.com/tmrowco/electricitymap-contrib/pull/2456/files#diff-c3b7bb94e70c63d689a577143fcab2a9R12

So the user interface might look different, but under the hood they're probably very similar. Might even make sense to try to combine the parser for this and King Island

**Comment by pierresegonne** [comment]
Hey @chuqtas! Thanks for the thorough investigation and breakdown of the tasks. This would be a good place to start contributing! 

1.  

This should be a first PR, few elements to help you

- _Remove Flinders Island and nearby island from the "Tasmania" region_ -> look into https://github.com/tmrowco/electricitymap-contrib/blob/master/web/README.md to understand how the geometries of the zones are generated
- _Create new "Flinders Island (Australia)" region with just the large one_ -> This needs creating a new zone in `zones.json` and add its geometry accordingly



2. 

This should be a second PR, or could be embedded in #2534 for example


Let me know if you need more details :)

**Comment by ajoga** [comment]
I played with it a bit, to be more specific, a change [here](https://github.com/ajoga/electricitymap-contrib/blob/83e937fb6ebbd6ef4f86eada892732051c9de935/parsers/AUS_TAS_KI.py#L61 ) fetches some data 

`TagHub` -> `flindershub` | `HogsHub` (hello #2534 :)) 
`Dashboard` -> `SendDashboard`

It seems that SendDashboard is a method to get more data than for KI's parser (I don't remember also getting capacities in the payload). Maybe this is a newer version of the backend than King's island ? I tried to get KI's data through this method but it didn't work.

**Comment by chuqtas** [comment]
> Hey @chuqtas! Thanks for the thorough investigation and breakdown of the tasks. This would be a good place to start contributing!
> 

I really had no idea what I was doing hence leaving this alone for a while.  However I have some time off at the moment so thought I'd take a look!  (Bear in mind this is my first time attempting to use pull requests, or editing geojson files, so apologies for any issues)..

I have created a modified version of AUS-TAS.geojson, and created new files AUS-TAS-FI.geojson and AUS-TAS-CBI.geojson for Flinders Island and Cape Barren Island.

I presume I need to edit generate-geometries.js at rows 41 and 241 to reference these two new files.

I had an issue trying to create a new branch but it appears I need to be added as a collaborator for the project first?

**Comment by chuqtas** [comment]
After another look I've found I had to fork the project into my own workspace and create the branch there.  I've done that and it seems to have worked.  I noticed pull request #2925 has been automatically linked above.  I'm new at this so please let me know if I need to do anything else!

**Comment by chuqtas** [comment]
The first part of this is done via merged pull request: https://github.com/tmrowco/electricitymap-contrib/pull/2925
The second part is generally the same as, or broadly overlaps with, open pull request: https://github.com/tmrowco/electricitymap-contrib/pull/2867

**Comment by ajoga** [comment]
@chuqtas hello :) yes our efforts are going to the same goal ! I just pushed the geometry data for the last island handled by the parser in #2867 that also handles data feeding for Flinders Island! :)

As for the github function, each time you mention an issue or a PR via their numbers, github will link both as "mentioned" to ease navigation back and forth related PR/issues.

**Comment by FelixDQ** [comment]
Great work everyone! This issue seems to be resolved now. Let me know if missed something
