### ISSUE TITLE
Data for Rottnest Island (Western Australia)

### ISSUE THREAD

**Issue by q--** [tmrowco/electricitymap-contrib#2534]
After another energy dashboard was found in  #2533, I decided to have a [look](https://www.hydro.com.au/clean-energy/hybrid-energy-solutions/success-stories/) at Hydro Tasmania's website to see what else I could find.

Turns out there's also a [dashboard](https://www.hydro.com.au/clean-energy/hybrid-energy-solutions/success-stories/rottnest-island) for Rottnest island, [off the coast of Western Australia](https://www.google.nl/maps/place/Rottnest+Island+WA+6161,+Australia)

Judging by the browser console logs, this one [also](https://github.com/tmrowco/electricitymap-contrib/pull/2456/files#diff-c3b7bb94e70c63d689a577143fcab2a9R12) uses Ajenti and a SignalR WebSocket connection under the hood. It will likely be possible to make this work with the parser from #2456

To Do

- [ ] Add Rottnest island to the map (I don't know how to do this. It's off the coast of Perth and not currently on the map)
- [ ] See if we can adapt the King Island parser to also work for this island

**Comment by q--** [comment]
Changing "taghub" to "hogshub" (with different capitalization?)  should do

Found in a request setting up the connection:

    GET | https://data.ajenti.com.au/live/signalr/negotiate?clientProtocol=1.5&connectionData=[{"name":"hogshub"}]&_=1603470672758

**Comment by madsnedergaard** [comment]
Closing this as it's been done in #2977 and #2867
