### ISSUE TITLE
Arrow for imports from US-MIDW-MISO to CA-ON facing the wrong direction on the app

### ISSUE THREAD

**Issue by robertahunt** [tmrowco/electricitymap-contrib#2536]
Thanks to Russ for flagging this in an e-mail. It seems like the arrow on the website is facing the correct direction (as far as I can tell), but it faces the wrong direction on the app.

Screenshot from app:
![Screenshot_20200602-142205](https://user-images.githubusercontent.com/13189214/83519638-a4087700-a4dc-11ea-84ea-2e26c5ae8bde.png)

screenshot from website:
![image](https://user-images.githubusercontent.com/13189214/83519457-50962900-a4dc-11ea-8989-9b078fcff070.png)

**Comment by corradio** [comment]
Should be done now with the iOS/Android release
