### ISSUE TITLE
Live Data for ERCOT no longer showing up after switching to EIA parser

### ISSUE THREAD

**Issue by typicalTYLER** [tmrowco/electricitymap-contrib#2538]
I'm unsure if the eia.gov source is only historical data, but it seems like the live data for ERCOT is no longer available. Previously we had the US_TX.py parser (which still exists) that was getting a decent estimate for the live data (although less accurate due to part of the energy mix being estimated), but now the displayed data seems to be historical only, and every day it looks like maybe it's back-filled at 4am. 
![image](https://user-images.githubusercontent.com/6762150/83654955-69a5e500-a583-11ea-9151-8671a8065541.png)

I checked around to see if there was an existing issue or plans around this (unsure if other US zones are in a similar situation), but nothing seemed obviously associated that I could find.

Is there some way to use the US_TX.py parser's data until EIA.py backfills the more accurate data? It seems like a big loss to never be able to see Texas' live carbon density.

**Comment by systemcatch** [comment]
@typicalTYLER 

I think there has been a fairly significant change in how Tomorrow defines and parses US data but we'd need someone from the team to chime in here.

Data from [eiapy](https://github.com/systemcatch/eiapy) will always lag by at least 8 hours. From the [logs](https://kibana.electricitymap.org/app/kibana#/discover/10af54f0-0c4a-11e9-85c1-1d63df8c862c?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:now%2FM,mode:quick,to:now))&_a=(columns:!(message,extra.key,level),filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!f,index:'96f67170-0c49-11e9-85c1-1d63df8c862c',key:extra.key,negate:!f,params:(query:US-TX,type:phrase),type:phrase,value:US-TX),query:(match:(extra.key:(query:US-TX,type:phrase)))),('$state':(store:appState),meta:(alias:!n,disabled:!f,index:'96f67170-0c49-11e9-85c1-1d63df8c862c',key:level,negate:!f,params:(query:INFO,type:phrase),type:phrase,value:INFO),query:(match:(level:(query:INFO,type:phrase))))),index:'96f67170-0c49-11e9-85c1-1d63df8c862c',interval:auto,query:(language:lucene,query:US-TX),sort:!('@timestamp',desc))) the `US-TX` parser is still running with no errors but not displaying on the map.

**Comment by martincollignon** [comment]
We're currently not able to run two types of parsers at the same time, so we've decided to keep the most accurate source for now.

**Comment by tth4vb** [comment]
Closing for now as we're integrating new data sources for ERCOT. We should have slightly delayed data now for a more granular definition of grids based on balancing authorities, and we'll determine in the future how to visualize this data delay on eMap.org
