### ISSUE TITLE
Remove "we're hiring" link on electricityMap

### ISSUE THREAD

**Issue by corradio** [tmrowco/electricitymap-contrib#2543]

**Comment by fbarl** [comment]
@corradio Is this because Tomorrow is not actively hiring anymore or because the link in the app just gives too much exposure? :slightly_smiling_face: 

I'm asking because I wonder if we should also remove the _Tomorrow is hiring!_ section from the README.

**Comment by corradio** [comment]
It's because we don't want to risk having people land on our jobs page which is currently empty :)

**Comment by brandongalbraith** [comment]
@corradio Any thoughts to having a form of some sort to take input from the user who lands on the empty job page, for people who would be interested in future positions?

**Comment by fbarl** [comment]
@brandongalbraith Thanks for your feedback!

> Any thoughts to having a form of some sort to take input from a user who lands on the empty job page, for people who would be interested in future positions?

I don't know what @corradio thinks about it, but I personally feel the _Get in touch_ section under _Current Job Opportunities_ provides that window for job opportunities outreach:

![image](https://user-images.githubusercontent.com/1216874/84625514-b377bf00-aee3-11ea-8364-d011ed9340bb.png)

Maybe this is a matter of personal taste, but I generally prefer being able to write an open email vs. filling out a specific form 🤔
