### ISSUE TITLE
Denmark-Sweden Interconnection Capacity

### ISSUE THREAD

**Issue by q--** [tmrowco/electricitymap-contrib#2545]
Saw no capacity was known for DK2-SE. DK1-SE on ElectricityMap is lower than listed in this document as well by a small amount.

| SE3>DK1 | SE3<DK1 | SE4>DK2 | SE4<DK2 |
|---------|---------|---------|--------|
| 680     | 740     | 1,300   | 1,700  |

Source: [2019 Nordic Grid Development Plan](https://www.statnett.no/contentassets/61e33bec85804310a0feef41387da2c0/nordic-grid-development-plan-2019-for-web.pdf) page 41

Probably other useful figures in this document as well, haven't looked

**Comment by pierresegonne** [comment]
Hey @q-- Thanks for the investigation, the source you found seems reliable.

**Comment by tgy** [comment]
This can now be closed I think
