### ISSUE TITLE
Inconsistencies historical CL-SEN data

### ISSUE THREAD

**Issue by pierresegonne** [tmrowco/electricitymap-contrib#2556]
The 🇨🇱 CL-SEN 🇨🇱 parser is functional again, see https://github.com/tmrowco/electricitymap-contrib/pull/2552 and https://github.com/tmrowco/electricitymap-contrib/pull/2555. Nevertheless, looking at the re-fetched data since 2015

![CL_2015_2020](https://user-images.githubusercontent.com/32778266/85131152-8e15e880-b236-11ea-888a-77fbd30d2e32.png)

raised some doubts about data quality (especially because of the 2015-2016 data period). I therefore went on to verify if the coordinador electrico nacional had the same data. Looking at https://www.coordinador.cl/reportes-y-estadisticas/ I found the following statistics for electricity production (In estadisticas/Histórico de Generación Horaria Total de Energía) 
[historico_de_generación_horaria_total_de_energía5.xlsx](https://github.com/tmrowco/electricitymap-contrib/files/4804520/historico_de_generacion_horaria_total_de_energia5.xlsx)

Which shows that the data received from the historical API `https://sipub.coordinador.cl/api/v1/recursos/generacion_centrales_tecnologia_horario` displays a substancially lower average daily production (ex: 2017, ~8516MW/h for the xlsx and ~5985MW/h for the API) 

I have requested an API key for https://www.coordinador.cl/api-del-sistema-de-informacion-publica/ but still waiting on them

_Note_: 

[capacidad_y_generación_2020_5 (2).xlsx](https://github.com/tmrowco/electricitymap-contrib/files/4804549/capacidad_y_generacion_2020_5.2.xlsx) found under estadisticas/Capacidad y Generación de Energía 2020 shows an average production in 2019 of 6435MW/h which corresponds pretty much exactly to what the API returns 

![CL_2019](https://user-images.githubusercontent.com/32778266/85131949-22cd1600-b238-11ea-9873-06322a1453e8.png)

And finally, other statistics, such as [generacion_bruta_diaria_por_central_sen2 (3).xlsx](https://github.com/tmrowco/electricitymap-contrib/files/4804574/generacion_bruta_diaria_por_central_sen2.3.xlsx) (found under estadisticas/Generación Bruta Diaria de Energía por Central Generadora/historico SEN) 

And [historico_generacion_anual_por_tecnologia2.xlsx](https://github.com/tmrowco/electricitymap-contrib/files/4804579/historico_generacion_anual_por_tecnologia2.xlsx) (found under estadisticas/Histórico Generación Anual por Tecnología) show different yearly production averages. 

__So if someone from the community has some time to look into what are the most reliable data sources/investigate why there are differences in the different csvs/contact the support to ask them about data inconsistencies that would be awesome! Thanks!__

**Comment by KiSobral** [comment]
Hey, if you guys still want help, I would love to do this ressearch.
Can I take this?

**Comment by skovhus** [comment]
@KiSobral sorry for us not responding here. We have switched to another data source May 2021, which means that the data is more accurate, but unfortunately it is delayed.
