### ISSUE TITLE
Update installed capacity data for Ontario

### ISSUE THREAD

**Issue by FelixVanOost** [tmrowco/electricitymap-contrib#2557]
The latest IESO [Reliability Outlook](http://www.ieso.ca/-/media/Files/IESO/Document-Library/planning-forecasts/reliability-outlook/ReliabilityOutlook2020Mar.pdf?la=en) from March 2020 has updated figures for Ontario's installed power generation capacity.

Although not a major change, the capacity of hydroelectric, gas / oil, and solar has increased since the map was last updated. I've summarised the installed capacity currently displayed on electricityMap vs. the latest official figures:

| Fuel Type | Total Installed Capacity (MW) - electricityMap | Total Installed Capacity (MW) - ISEO March 2020 |
| --- | --- |  --- | 
| Nuclear | 13,009 | 13,009 |
| **Hydroelectric** | **8,480** | **9,065** |
| **Gas / Oil** | **10,300** | **11,270** |
| Wind | 4,486 | 4,486 |
| Biofuel | 295 | 295 |
| **Solar** | **380** | **478** |

**Comment by martincollignon** [comment]
Hi @FelixVanOost!

Great find - would you mind updating the capacities directly?

You can do it by updating the numbers here: https://github.com/tmrowco/electricitymap-contrib/blob/master/config/zones.json

**Comment by FelixVanOost** [comment]
Sounds good, I've opened PR #2558 with the changes.

**Comment by martincollignon** [comment]
Thanks Felix!
