### ISSUE TITLE
Data for Nigeria

### ISSUE THREAD

**Issue by q--** [tmrowco/electricitymap-contrib#2570]
Real-time consumption: https://www.sogrid.org/DisCoLoadProfile

Generation by hour: https://www.sogrid.org/GenerationProfile (includes historical)  
Generation seems quite low compared to consumption for the current time, a brief look through the historical data suggests this might be due to some generation companies being slower with providing data

The dashboard also has some other stuff like grid frequency, [generation/consumption by day for the past seven days et cetera](https://www.sogrid.org/EnergyTrend)

Found via https://nsong.org/

The regulatory commision also has some [data](http://www.nercng.org/index.php/library/industry-statistics), but it looks older/less detailed/broken.

Nigeria has interconnectors to neighbouring countries. According to the graph at http://icc.ecowapp.org/ (scroll down) it exports  a lot. Imports for 2019 were zero.

https://www.nbet.com.ng/ is the electricity trading company. Installed capacity breakdown on the homepage, unclear if it's for all of Nigeria

**Comment by systemcatch** [comment]
Nice find, looks like it uses aspx behind the scenes so we should be able to get the data out but it might end up being painful.

**Comment by Kongkille** [comment]
Hi guys, I just looked at the data briefly but would you say we can set the labels "Parser buildable" and "Help wanted" for this issue? Or do we need further investigation?

**Comment by q--** [comment]
@Kongkille It should be possible to build a parser with the data that's available. Carbon intensity can be calculated from [IEA data](https://www.iea.org/countries/nigeria), the country almost exclusively uses natural gas and hydro

**Comment by sashavor** [comment]
So essentially each of the sources listed at [https://www.sogrid.org/GenerationProfile](https://www.sogrid.org/GenerationProfile) needs to be linked with a type of production (natural gas/hydro) and then the parser can be built?

**Comment by q--** [comment]
@sashavor In theory, yes, but the GenerationProfile seems to be incomplete (compare the lastest generation total and the demand at the DisCoLoadProfile page - older generation profile data appears to be more complete however), so for real-time it might be better to grab the consumption from the DisCoLoadProfile page and calculate a static carbon intensity from IEA data.

**Comment by corradio** [comment]
@q-- if in case you deem the GenerationProfile data of insufficient quality, then I don't think we should qualify this parser as buildable.
I'm not sure that just having the load profile with a static intensity is of great value here?
However it might be good to show the incomplete mix at this stage, as this might motivate Nigerian officials to do something about their data once they see it on the map!

**Comment by madsnedergaard** [comment]
Parser has been build in #2851, so closing this issue - feel free to open it again if you feel like anything is missing :)
