### ISSUE TITLE
Change 'gas' production to 'biomass' in Panama historical data

### ISSUE THREAD

**Issue by q--** [tmrowco/electricitymap-contrib#2577]
See #2576. Biogas got reported as 'gas' instead of 'biomass'.

Since 'biogas' is the only thing the parser stores as 'gas', this could be done by simply moving all the gas production to biomass.

**Comment by corradio** [comment]
@q-- it seems like this was done in https://github.com/tmrowco/electricitymap-contrib/pull/2576/files correct?

**Comment by q--** [comment]
For current production, yes. But as I understand it ElectricityMap also keeps historical data behind its API, and everything logged as "natural gas" before the merging of #2576 was actually biomass. So you might want to update that in your database.

(I've later updated the PA parser and it's now also able to recognize actual natural gas plants, so data logged as "natural gas" after #2642 was merged should not be changed to "biomass".)

**Comment by corradio** [comment]
Great! Thank you so much. ping'in @FelixDQ so we make sure our internal systems are updated.
I'll close this issue as this task seems done
