### ISSUE TITLE
Solar data in Netherlands is gone (equals zero)

### ISSUE THREAD

**Issue by SimonForrez** [tmrowco/electricitymap-contrib#2588]
For the last 24 hours, two sunny days in the Netherlands,
the solar energy production in the Netherlands has been zero.
I suppose this is incorrect.
Other countries are showing solar production just fine.

The total consumption at the moment (13:10 GMT, 12jul2020) in the Netherlands is also very low (6.30GW) so that might be wrong/influenced as well.

**Comment by ivard** [comment]
The data of https://energieopwek.nl/ still seems correct, so the data is still available. Probably there is some issue with the API connection somewhere?

**Comment by FelixDQ** [comment]
Nice catch!
@PaulCornelissen actually tries to address this in https://github.com/tmrowco/electricitymap-contrib/pull/2561

You can also see the discussions here https://github.com/tmrowco/electricitymap-contrib/issues/1871
