### ISSUE TITLE
lowcarbon tooltip is missing

### ISSUE THREAD

**Issue by corradio** [tmrowco/electricitymap-contrib#2592]
We used to have a tooltip when you hover over the low-carbon gauge in the left-panel. It showed some description about what low-carbon meant. I think it got lost in the transition to React.

cc @fbarl

**Comment by fbarl** [comment]
Good catch @corradio!

I don't know how long we've had this bug - the low-carbon tooltip component was never lost, but the mouse triggers that activate it were not passed through correctly which I fixed in #2599.
