### ISSUE TITLE
Wind/solar overlay disappear when clicking a country on the map

### ISSUE THREAD

**Issue by q--** [tmrowco/electricitymap-contrib#2596]
# Steps to reproduce:

1. Enable the wind or solar  layer

2. Click on a country **on the map**

3. The wind/solar layer disappears

(When starting ElectricityMap with wind/solar **enabled** (e.g. https://www.electricitymap.org/map?wind=true), switching it off and then clicking a country on the map **re-enables** that layer again instead)

# What should've happened

1. The wind/solar layer shouldn't disappear

(Oddly, when switching to a (different) country using the _areas list_ at the left, it *does* correctly preserve the wind/solar layer)

# Other stuff

Tested on desktop with Firefox and Chrome

I think this started happening somewhere around #2434

**Comment by fbarl** [comment]
Thanks for opening an issue with such a detailed description @q--! :ok_hand: 

It helped me track down the bug pretty quickly - some mouse handler hooks were missing the URL location dependency.

#2600 should fix all the issues above.

**Comment by q--** [comment]
No problem, thanks for the quick fix
