### ISSUE TITLE
Ukraine is down (ElectricityMap got blocked)

### ISSUE THREAD

**Issue by q--** [tmrowco/electricitymap-contrib#2598]
Ukraine has been down for a couple of days now. When running test-parser UA it shows the server terminated the connection.

I changed the User-Agent header like this:
```
    response = r.post(url, postdata, headers={
    'User-Agent': 'My User Agent 1.0'
	})
```
and it started working again, so apparently it's blocking the parser based on user-agent.

Changing the parser to use a user-agent of e.g. Firefox should be enough to have UA show up again, unless ElectricityMap got IP-banned as well. Might be worth trying to contact them as well to avoid getting blocked again, though

**Comment by FelixDQ** [comment]
Nice catch @q-- ! I just checked and we aren't IP blocked. I will make a PR updating the user agent and try to contact UA to make sure that we don't get blocked again.
