### ISSUE TITLE
Armenia exchange data appears to be inaccurate 

### ISSUE THREAD

**Issue by q--** [tmrowco/electricitymap-contrib#2602]
ElectricityMap [shows](https://www.electricitymap.org/zone/GE) GE consistently importing exactly 376MW from Armenia.
This data is from the Armenia parser. When looking at [the website of the Georgian TSO](http://gse.com.ge/home), imports/exports from Armenia are zero right now.

I suspect the exchange data reported for AM is not being updated.
Exchanges with Iran and Nagorno-Karabakh are exhibiting similar behavior.

AM<->GE could be fixed by getting the exchange data from the Georgian TSO instead. As for the other exchanges, it might be worth trying to contact the Armenian TSO (unless the problem is due to an issue with the parser itself; it used to work before a change to the website broke the parser, but I'm not sure if it's worked correctly since the parser got fixed in #2571)

**Comment by q--** [comment]
The amount of electricity exported to Iran started fluctuating again. Exports to NKR and GE are still stuck.

**Comment by FelixDQ** [comment]
NIce catch @q-- ! I tried to investigate this, but it seems like the Armenia parser went down. I created an issue for it https://github.com/tmrowco/electricitymap-contrib/issues/2611

**Comment by FelixDQ** [comment]
I'm closing this issue for now since the armenia data source is gone. Feel free to reopen if there's any updates.
