### ISSUE TITLE
Armenia parser format changed

### ISSUE THREAD

**Issue by FelixDQ** [tmrowco/electricitymap-contrib#2611]
It was recently fixed in https://github.com/tmrowco/electricitymap-contrib/pull/2571, but it went down again.

From kibana:
```
Traceback (most recent call last):
  File "/home/src/electricitymap/feeder/lib/fetch_data.py", line 175, in launch_parsers
    objs = res.get(timeout)
  File "/usr/local/lib/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value
  File "/usr/local/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/home/src/electricitymap/feeder/lib/fetch_data.py", line 173, in <lambda>
    **parser_kwargs))
  File "/home/src/electricitymap/contrib/parsers/AM.py", line 72, in fetch_production
    gas_total = float(gas_tes[0])
IndexError: list index out of range
```

**Comment by willbeaufoy** [comment]
I'm looking for a parser to fix/add, is there any other info I should be aware of other than what's in this bug? From looking at the parser itself it looks like the data URL (http://epso.am/poweren.htm) returns a blank page currently. Another URL mentioned in the parser (http://epso.am/scada.htm) requires a password to view.

**Comment by FelixDQ** [comment]
Awesome! Unfortunately, I don't think that we have had any previous contact with the data provider.  I found an email on their [website](http://www.energyoperator.am/about.html) if you want to reach out: office@energyoperator.am

Let me know if you need help with something or if I should reach out to them (though data providers often react positively when people from the community reach out)

**Comment by willbeaufoy** [comment]
> Awesome! Unfortunately, I don't think that we have had any previous contact with the data provider. I found an email on their [website](http://www.energyoperator.am/about.html) if you want to reach out: [office@energyoperator.am](mailto:office@energyoperator.am)
> 
> Let me know if you need help with something or if I should reach out to them (though data providers often react positively when people from the community reach out)

Ok thanks, I've emailed them. Will update here with any reply.

**Comment by willbeaufoy** [comment]
> > Awesome! Unfortunately, I don't think that we have had any previous contact with the data provider. I found an email on their [website](http://www.energyoperator.am/about.html) if you want to reach out: [office@energyoperator.am](mailto:office@energyoperator.am)
> > Let me know if you need help with something or if I should reach out to them (though data providers often react positively when people from the community reach out)
> 
> Ok thanks, I've emailed them. Will update here with any reply.

I've emailed twice now but no reply.

**Comment by q--** [comment]
I've looked into the AM parser a week or so ago and the entire website http://epso.am is gone.

I've looked at a few other related Armenian websites like [Armenian Energy Agency](https://energyagency.am/en), [Electric Networks of Armenia](http://www.ena.am/index.aspx?lang=2), [HIGH VOLTAGE ELECTRIC NETWORKS](http://www.hven.am/en/fp/) and http://www.minenergy.am/en/page/539 but none of them have real-time data. 

So the AM parser is unlikely to start working again.

**Comment by FelixDQ** [comment]
Thanks for the investigation work! I'm going to close this issue for now. Feel free to reopen if there's any updates
