### ISSUE TITLE
Please divide Sweden into four electricity areas! Compare with Norway.

### ISSUE THREAD

**Issue by Blixtmannen** [tmrowco/electricitymap-contrib#2616]
Dear Sir,

I like you map BUT: Please divide Sweden into four electricity areas! Compare with Norway.

Best

Magnus

**Comment by magol** [comment]
This is a duplicate of #1397

Unfortunately, the work with #1397 seems to have stopped, but I hope it can start again.

**Comment by martincollignon** [comment]
Closing as it is a duplicate.
