### ISSUE TITLE
Update electricitymap_social_image.jpg

### ISSUE THREAD

**Issue by magol** [tmrowco/electricitymap-contrib#2617]
In https://www.electricitymap.org/images/electricitymap_social_image.jpg, Sweden is gray. I want the image to be updated to reflect the best case when maximal of all countris with data is present.

**Comment by Kongkille** [comment]
I think that makes sense :) Let's see if we can get a picture that represents emap at full capacity

**Comment by corradio** [comment]
Any news here? Seems some easy to do!

**Comment by magol** [comment]
How do you know if all available regions are online? I compare the image to current map, and I see that it is regions present in the image that is gray right now on the map.
