### ISSUE TITLE
Display EU average emissions

### ISSUE THREAD

**Issue by maingoh** [tmrowco/electricitymap-contrib#2622]
It would be nice to display the EU average emissions and maybe other big zones (USA, south america, africa ..) for comparison

**Comment by Kongkille** [comment]
I agree. We are currently working on a "historical" view, which will display an aggregate value for the zone. Not sure how we would be able to include larger zones, but it's definitely an interesting idea. Perhaps OOS for the live map, but perhaps if done right.

**Comment by maingoh** [comment]
There might be also two different averages:
- Average of the average per country inside the zone
- Sum of total emission per country divided by the total population of the zone
