### ISSUE TITLE
Map scrolling juddering

### ISSUE THREAD

**Issue by zeristor** [tmrowco/electricitymap-contrib#2626]
Beta version of iOS 14 version 5, judders when scrolling around the map

**Comment by fbarl** [comment]
Thanks for reporting the issue @zeristor!

Could you please post a recording of this from your iPhone?

I also wonder if this is the only iOS version you've experienced it on - I suspect it's a hardware / performance issue but there must be more to it if the latest version is more problematic :thinking:

**Comment by zeristor** [comment]
I think this is no doubt down to the iOS 14.0 beta versions, the issue has lessened in beta 6.
I did work out how to take a video, but it looks like it is no longer needed.
