### ISSUE TITLE
Slovenian vs. Croatian nuclear not accurate?

### ISSUE THREAD

**Issue by tth4vb** [tmrowco/electricitymap-contrib#2628]
From Jaka Ortar via email:

Slovenian nuclear power plant Krško is actually owned by Croatia as well - 50/50. So in reality half of power is always regarded as Croatian domestic production and the other half as Slovenian. That plant lies in Slovenia but very close to the national border and to Croatian capital city of Zagreb.

**Comment by fbarl** [comment]
> Slovenian nuclear power plant Krško is actually owned by Croatia as well - 50/50. So in reality half of power is always regarded as Croatian domestic production and the other half as Slovenian. That plant lies in Slovenia but very close to the national border and to Croatian capital city of Zagreb.

Sounds right, [Croatian Wikipedia article](https://hr.wikipedia.org/wiki/Nuklearna_elektrana_Kr%C5%A1ko) supports this claim, although the closest quote I found on the [English Wikipedia article](https://en.wikipedia.org/wiki/Kr%C5%A1ko_Nuclear_Power_Plant) is this:

> Croatia also has a contractual obligation to take in one half of the nuclear waste by 2025.

**Comment by tth4vb** [comment]
Given that we're looking at this from the location-based perspective, I guess the question really is where is the power physically produced (I guess Slovenia? but you can make an argument that Croatia is also responsible?)

**Comment by jarek** [comment]
Also, is the power from the plant destined for Croatia sent there directly, or via the Slovenian grid? And is this currently included in exchange values between Croatia and Slovenia? (Looks like at this moment Electricity Map data has Slovenia with 676 MW nuclear production and 666 MW export to Croatia)

**Comment by madsnedergaard** [comment]
We've been discussing this, and we wish to apply the least amount of correction to the data we get from the providers (in this case ENTSO-E and [KOSTT](http://kostt.com/)) as possible.

We're closing this issue, but we recommend that anyone who wants to drive this forward should contact the data providers directly to get this corrected :)
