### ISSUE TITLE
New Zealand SSL Certificate Problems

### ISSUE THREAD

**Issue by dh47** [tmrowco/electricitymap-contrib#2633]
Are you aware theirs an issue with NZ data?  Data was flowing a few weeks ago and now nothing.

**Comment by jarek** [comment]
looks like SSL cert problems...

excerpt from Kibana logs
```
...
  File "/home/src/electricitymap/contrib/parsers/NZ.py", line 59, in fetch_production
    obj = fetch(session)
  File "/home/src/electricitymap/contrib/parsers/NZ.py", line 17, in fetch
    response = r.get(url)
...
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='www.transpower.co.nz', port=443): Max retries exceeded with url: /power-system-live-data (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)'),))
```

URL is https://www.transpower.co.nz/power-system-live-data ... oddly enough Firefox/Linux doesn't mind the cert

**Comment by dh47** [comment]
Would I have to speak with Transpower to sort the SSL issue?

**Comment by q--** [comment]
[SSL Labs says their certificate chain is incomplete](https://www.ssllabs.com/ssltest/analyze.html?d=www.transpower.co.nz), so same issue as with SSEN which I explained in https://github.com/tmrowco/electricitymap-contrib/issues/2462#issuecomment-623393667

![Screenshot of SSL Server Test www.transpower.co.nz (Powered by Qualys SSL Labs))](https://user-images.githubusercontent.com/2470175/91550956-ad617e00-e929-11ea-8241-26c3ee773649.png)

**Comment by q--** [comment]
Transpower has fixed the missing intermediate certificate problem (though their certificate chain is still [a bit messy](https://www.ssllabs.com/ssltest/analyze.html?d=www.transpower.co.nz) and New Zealand is back on the map.

This issue can be closed.

**Comment by jarek** [comment]
Great, thanks for checking!
