### ISSUE TITLE
DK<->SE interconnector capacities not updated in ElectricityMap

### ISSUE THREAD

**Issue by q--** [tmrowco/electricitymap-contrib#2634]
A few months ago, the interconnector capacities between DK1/DK2 and Sweden were updated in #2569, but these changes haven't shown up on the map.

Possibly because the changes were made to e.g. `DK-DK2->SE-SE4` instead of `DK-DK2->SE`?

**Comment by Kongkille** [comment]
Thanks!

Yeah, I would probably agree that is the root cause
