### ISSUE TITLE
Missing solar data in AUS-SA

### ISSUE THREAD

**Issue by tth4vb** [tmrowco/electricitymap-contrib#2655]
We're missing data from solar in AUS-SA, as can be seen in this source: https://opennem.org.au/energy/sa1/

If anyone wants to try and integrate this data source in, that'd be awesome :)

**Comment by q--** [comment]
See also #1985

**Comment by tth4vb** [comment]
Ah thanks for the reminder/link!

**Comment by tth4vb** [comment]
closing as I think this is covered in another issue
