### ISSUE TITLE
Moldova-Romania Interconnector Not In Operation

### ISSUE THREAD

**Issue by nessie2013** [tmrowco/electricitymap-contrib#2685]
The source on interconnection in #2410 states that this connection is "not in operation". However, it's still shown on electricitymap. Should this be removed, put to 0 capacity, or kept as it is (in case it goes back into operation)?

**Comment by q--** [comment]
The footnote on page 14 says Moldova "committed  in  2018  to  its  rehabilitation", so it might return at some point

**Comment by FelixDQ** [comment]
Yes, let's just keep it. It doesn't show up on the map while the netflow is 0, so it shouldn't clutter the UI.

Thanks for noticing :-)
