### ISSUE TITLE
GB regional data

### ISSUE THREAD

**Issue by AilinvandenHonigkuchenpferdlande** [tmrowco/electricitymap-contrib#2696]
14 now also has data for each of the 14 geographical regions via the National Grid’s carbon intensity initiative. Currently GB data is coming from ENTSOE. 

Note: 
- Generation mix API is still in beta version 
- Need to check whether there is minimum 1 year historical data for the generation mix

https://carbon-intensity.github.io/api-definitions/?python#regional

https://www.carbonintensity.org.uk/#:~:text=The%20carbon%20intensity%20of%20electricity,kilowatt%20hour%20of%20electricity%20consumed.&text=Carbon%20intensity%20varies%20by%20hour,%2C%20biomass)%20and%20conventional%20generation

**Comment by jarek** [comment]
Back in 2018 this was only consumption mix, see https://github.com/tmrowco/electricitymap-contrib/issues/596#issuecomment-416668710 - the map example on carbonintensity.org.uk still has these issues (showing nuclear in London...)

Good to know generation is now available. Are flows/exchanges between the regions also available?

**Comment by tth4vb** [comment]
@AilinvandenHonigkuchenpferdlande this is great! We've previously spoken to the folks behind this API and they said regional was still in closed beta and they weren't 100% confident on data quality yet, but now that it's publicly available I think it'd be great to try and implement. Let me know if you want any help with the historical data investigation - if it isn't apparent on their site/docs, I can reach out to them directly

**Comment by willbeaufoy** [comment]
Looks like progress on this has stalled, I'm interested in helping things along.

I have checked and 1 year ago historical data for the generation mix is indeed available (in half hour periods), e.g. `curl -X GET https://api.carbonintensity.org.uk/regional/intensity/2019-10-30T11:30Z/2019-10-30T12:00Z   -H 'Accept: application/json'`

However I cannot see any data on flows between regions.

I've got a few questions that it would be useful to get answers to:

1) The API returns the generation mix by fuel in percentage terms, not in MW. Can percent figures be used or do we have to find the total production by region first and use the percentages to calculate the MW?
2) Should we divide the country into England/Scotland/Wales or the 12 subnational regions also offered by the API? Some of these regions are very small (see the [map](https://carbonintensity.org.uk/)) so I'm not sure this would be the best approach. I think people would find the England/Scotland/Wales version more interesting, though the ideal situation would to be able to switch between views.

**Comment by jarek** [comment]
> Can percent figures be used or do we have to find the total production by region first and use the percentages to calculate the MW?

We do need the actual production per fuel in MW

> the ideal situation would to be able to switch between views.

This would be nice but I can't see how this would be done in current ElectricityMap interface

**Comment by tth4vb** [comment]
@willbeaufoy sorry for the late reply, but I think while the regions are small, I'd advocate that we try and get as high granularity as possible :) We took a similar approach in the US - I think it makes things a bit more actionable. Unfortunately as @jarek said, we can't switch between views in the eMap interface, but I think that unless the 12 regions have dramatically different carbon intensities, then I think the breakdown will be helpful without looking too overwhelming. And if they do have different intensities, the more reason to show that breakdown!

**Comment by tth4vb** [comment]
And to back up what Jarek said, we do need the production per fuel in MW, so I guess in this case it would have to start from total production and then use %s if that's all that's available

**Comment by willbeaufoy** [comment]
Ok great, I looked again and couldn't find any data sources for actual MW values by source by region (on their API or elsewhere), so I emailed one of the contacts asking if this information is available. I also asked about import/export flows. Will update here with any reply.

**Comment by numptie** [comment]
> 
> 
> @willbeaufoy sorry for the late reply, but I think while the regions are small, I'd advocate that we try and get as high granularity as possible :) We took a similar approach in the US - I think it makes things a bit more actionable. Unfortunately as @jarek said, we can't switch between views in the eMap interface, but I think that unless the 12 regions have dramatically different carbon intensities, then I think the breakdown will be helpful without looking too overwhelming. And if they do have different intensities, the more reason to show that breakdown!

@tth4vb - I would agree with your approach on having the regional breakdown.  There is also a significant difference in planning/energy policy between Scotland and England, and seeing energy flows between the two (including within the UK would be beneficial.

**Comment by willbeaufoy** [comment]
So I've emailed the contacts on the page multiple times now since my last update (a.r.w.bruce@gmail.com and lyndon.ruff@nationalgrid.com) but not received any response, does anyone have alternative contact details? In the email I asked two questions:

1. Is there a way to get the actual MW generation values per region from the API, or from another source that the API pulls from?
2. Is there a way for the API to return import/export flows between GB regions?

I can't really move forward without answers to question 1 in particular, and have looked for this data myself too (see my previous comment).

**Comment by corradio** [comment]
I suggest we use https://github.com/tmrowco/electricitymap-contrib/issues/1894 to track this issue
