### ISSUE TITLE
Cross border flow arrow for Netherlands <-> Denmark HVDC is missing

### ISSUE THREAD

**Issue by Gazer75** [tmrowco/electricitymap-contrib#2697]
The data is there in each region, but the arrow is missing on the map.

**Comment by Kongkille** [comment]
One note is that arrows are not displayed if it's extremely low, I must admit I am not sure whether it's when it's 0 or just below a certain threshold

**Comment by Gazer75** [comment]
Suggest having the arrows visible even if there is no flow. I thought there was missing details.

**Comment by PaulCornelissen** [comment]
The interconnector is closed as per message from TenneT:
https://www.tennet.org/bsmailfax/20200928_151936_Cobra_Beperking_transportcapaciteit___Reduction_transport_capacity.html

This issue can be closed I guess.

**Comment by FelixDQ** [comment]
👍 Thank you @PaulCornelissen and @Gazer75
