### ISSUE TITLE
Germany <-> Norway HVDC cable NordLink entering test phase

### ISSUE THREAD

**Issue by Gazer75** [tmrowco/electricitymap-contrib#2698]
NordLink is now in testing phase and should be in full operation by December 2020.

Needs to be added to the parser and visually on map.

**Comment by brandongalbraith** [comment]
Duplicate of https://github.com/tmrowco/electricitymap-contrib/issues/2647, already closed by https://github.com/tmrowco/electricitymap-contrib/pull/2648

**Comment by Kongkille** [comment]
Yes, the reason why it's not showing is likely because it's very low. I'm pretty sure it has been visible a couple of times

cc @FelixDQ

**Comment by Gazer75** [comment]
Still missing the detail in each region. Those should be visible even if 0

**Comment by Gazer75** [comment]
This should be changed IMO. Removing the arrows with no transfer is confusing and leads to reports like this...
