### ISSUE TITLE
Misleading name "hydro storage" for pumped storage

### ISSUE THREAD

**Issue by Gazer75** [tmrowco/electricitymap-contrib#2707]
The line saying "Hydro Storage" is kind of misleading as this is actually pumped hydro storage.
Maybe change the name of this one to clarify this?

ENTSO-E is displaying this as "Hydro Pumped Storage"

**Comment by Kongkille** [comment]
Thanks @Gazer75, I'm closing this issue, you can see our discussion on the linked PR!
