### ISSUE TITLE
ENTSOE fetch_consumption must include consumption by production units

### ISSUE THREAD

**Issue by PaulCornelissen** [tmrowco/electricitymap-contrib#2710]
While fixing a issue with negative values for "unknown" production (#2638) it was found out (#2676) that ENTSOE reports consumption at the site of a generator under production as a negative production. For most power plants the electricity consumption is neglible (a couple of MW at most), but in NL we have a lot of CHP plants at greenhouses and such. They are very large electricity consumer and at times this can be several 100's of MW. This consumption is _probably_ not included in the consumption values we fetch from ENTSOE. So the ENTSOE parser for fetch_consumption needs to also fetch production information from ENTSOE and add the consumption of production plants.

**Comment by willbeaufoy** [comment]
I will take this if no one else has started on it yet.
