### ISSUE TITLE
Divisions of UK

### ISSUE THREAD

**Issue by sblanky** [tmrowco/electricitymap-contrib#2714]
Hi!

I think this project is brilliant. I was wondering if it is possible to determine electricity consumption/production on the island of Great Britain when seperated by sub-nation? I know for example that approximately half of the electricity produced in Wales is exported (mostly to England), and that much of this is renewable. 

I understand it being one unified grid that this might be difficult though!

**Comment by veqtrus** [comment]
See #2696 and #1894

**Comment by Kongkille** [comment]
Thanks @sblanky! 

Hopefully, you can see the current status of separating GB on the issues @veqtrus mentioned, I am going to close this issue for now
