### ISSUE TITLE
Add Germany<->Belgium: Alegro is coming

### ISSUE THREAD

**Issue by thtomate** [tmrowco/electricitymap-contrib#2723]
The first direct interconnection between Germany and Belgium has been constructed: Alegro https://www.elia.be/en/infrastructure-and-projects/infrastructure-projects/alegro
It is currently under testing and be used for the market next month. https://www.amprion.net/Press/Press-Detail-Page_26944.html

May be here are real data for it (wiht 30 minutes delay): https://www.elia.be/en/grid-data/transmission/physical-flows-per-border

**Comment by Kevindeving** [comment]
Unfortunately the interconnector is not yet included on entsoe. Should be coming soon hopefully.

**Comment by thtomate** [comment]
I looked and I found this: https://transparency.entsoe.eu/transmission-domain/physicalFlow/show?name=&defaultValue=false&viewType=TABLE&areaType=BORDER_CTY&atch=false&dateTime.dateTime=08.10.2020+00:00|CET|DAY&border.values=CTY|10Y1001A1001A83F!CTY_CTY|10Y1001A1001A83F_CTY_CTY|10YBE----------2&dateTime.timezone=CET_CEST&dateTime.timezone_input=CET+(UTC+1)+/+CEST+(UTC+2)  
In the end of September, it changed from n/e to some integers.

**Comment by Kevindeving** [comment]
Argh, I only looked at the bidding zones and not border country. Maybe someone can integrate it then. Test connections seem to be made from Monday to Friday at daytime last weeks already. 👍

**Comment by FelixDQ** [comment]
Cool! You can see how PaulCornelissen implemented the DE->NO-NO2 exchange [here](https://github.com/tmrowco/electricitymap-contrib/pull/2648). If you add it, then it will show up on the map when it becomes active.

**Comment by thtomate** [comment]
I have already seen it (we should not use DE-LU here), but I'm afraid of breaking things without an ENTSOE API key.

**Comment by PaulCornelissen** [comment]
I already looked at this when I did the NordLink, but there weren't any integers for this exchange at that point. I do remember this line though:
https://github.com/tmrowco/electricitymap-contrib/blob/master/parsers/ENTSOE.py#L179

Basically the ENTSOE parser currently substitutes DE-LU for DE in every `fetch_*`-call. So I suspect that maybe this exchange will be double counted as a DE<->BE exchange, but also in the DE-LU<->BE exchange. In that case we will require some extra code to untangle that.

**Comment by thtomate** [comment]
This is only used in fetch_price, otherwise would already break DE->LU and BE->LU and previously broke exchanges with common countries of Austria and Germany

**Comment by PaulCornelissen** [comment]
Ok, that sounds logical. You wan't to implement this? Otherwise I can do it.

**Comment by Kongkille** [comment]
Hey guys, does someone want to take this further? :)

cc @PaulCornelissen @thtomate

**Comment by PaulCornelissen** [comment]
I will, but probably not until next week.

**Comment by PaulCornelissen** [comment]
This issue can be closed i think. @FelixDQ
