### ISSUE TITLE
New Zealand: Stewart Island is incorrectly shown as part of the South Island electricity network

### ISSUE THREAD

**Issue by x-cubed** [tmrowco/electricitymap-contrib#2741]
The [electricityMap](https://www.electricitymap.org/zone/NZ-NZS) incorrectly shows New Zealand's Stewart Island as being part of the South Island electricity distribution network.
![image](https://user-images.githubusercontent.com/11729/95926148-0a50bf00-0e18-11eb-8514-8e8d0cc550f1.png)

However, there is no electricity distribution link between the two islands, and Stewart Island has it's own independent diesel generator setup to provide electricity to the community on the island.

A description of Stewart Island's electricity infrastructure can be found at: https://www.southlanddc.govt.nz/my-southland/siesa-2/what-sieasa-does/

**Comment by Kongkille** [comment]
Nice catch! So we need to separate these two and create a new region

**Comment by recursiveElk** [comment]
I'm a frontend dev in NZ, would this be a good first-issue?

**Comment by Kongkille** [comment]
Hi @recursiveElk, I think so, there's not a lot on the wiki regarding updating geographies, so this might also be a good time to write a good section on how to do something like this. So if you're up for it, I'm happy to help :)

**Comment by recursiveElk** [comment]
I might have look at the repo and flick you a msg.

**Comment by madsnedergaard** [comment]
Hey @recursiveElk, did you start any work on this? Otherwise I'd be happy to give it a try :)
