### ISSUE TITLE
Bolivia: calculate static carbon intensity for "unknown"

### ISSUE THREAD

**Issue by q--** [tmrowco/electricitymap-contrib#2747]
According to [2019 IEA data](https://www.iea.org/data-and-statistics?country=BOLIVIA&fuel=Energy%20supply&indicator=ElecGenByFuel), thermal electricity generation in Bolivia is mostly natural gas (and a bit of oil and biomass), so the default carbon intensity ElectricityMap uses for "unknown" generation is too high for the country.

Someone should calculate a static carbon intensity for the unknown part. (Note that `unknown` is only thermal generation.)

**Comment by veqtrus** [comment]
### [2019 data](https://www.iea.org/data-and-statistics/data-tables?country=BOLIVIA&energy=Electricity&year=2019)

  | Production | Carbon Intensity | Percentage
-- | -- | -- | --
Oil | 94 | 650 | 1.41523637458597
Natural gas | 6279 | 490 | 94.5347786811201
Biofuels | 269 | 230 | 4.04998494429389

Average Carbon Intensity: 481.734417344173

### 1% oil, 95% gas, 4% biomass

Average Carbon Intensity: 481.2

**Comment by q--** [comment]
Thank you
