### ISSUE TITLE
Request - Can someone calculate a static carbon intensity based on the generation breakdown for Puerto Rico?

### ISSUE THREAD

**Issue by q--** [tmrowco/electricitymap-contrib#2749]
For #2531, I need a static carbon intensity for the **renewable** generation of Puerto Rico.

I've found [monthly generation data](https://indicadores.pr/dataset/generacion-consumo-costo-ingresos-y-clientes-del-sistema-electrico-de-puerto-rico/resource/fdad4f42-a4be-48bb-9478-a8fb75c000c6). (I'd suggest LibreOffice Calc for the file, as Excel often struggles with CSV files.)

I'd base the carbon intensity on the renewable output of the last twelve months (to account for seasonal fluctuations in wind, solar and hydro output).

The relevant columns appear to be:

|           	| |
|-------------------------------------------------------	|----------	|
| * Generaci�n Bruta con Hidroel�ctrica (mkWh)          	| hydro    	|
| * Generaci�n con energ�a comprada-Fotovoltaica (mkWh) 	| solar PV 	|
| * Generaci�n con energ�a comprada-E�lica (mkWh)       	| wind     	|

The column _Generaci�n con energ�a comprada-Otros (varias tecnolog�as1) (mkWh)_ might also be relevant; I'm missing landfill gas ([mentioned here](https://www.eia.gov/state/analysis.php?sid=RQ
)), so this might be it. However, as the share of landfill gas in the real-time [generation info](https://aeepr.com/es-pr/generacion/Documents/Unidades_renovables.aspx) is quite small, I'd suggest just excluding it.

**Comment by veqtrus** [comment]
_Generación con energía comprada-Otros (varias tecnologías1)_ is about 11 total.

### Using the last 12 months

  | Total Generation | Carbon Intensity
-- | -- | --
Hydro | 53.758 | 24
Solar | 260.18266756 | 45
Wind | 141.421724566 | 11

Average Carbon Intensity: 31.9614690674738

### Using the 12 months of 2019

  | Total Generation | Carbon Intensity
-- | -- | --
Hydro | 40.977807 | 24
Solar | 241.97140922 | 45
Wind | 158.873767086 | 11

Average Carbon Intensity: 30.8263552043718

**Comment by q--** [comment]
Thank you!
