### ISSUE TITLE
Inaccurate

### ISSUE THREAD

**Issue by Shaunovsky** [tmrowco/electricitymap-contrib#2751]
Hi,

Have noticed electricitymap for Australia is pretty inaccurate, particular for states where there is rapid renewables growth. 

Needs to be pulling data from official market operator: https://aemo.com.au/energy-systems/electricity/national-electricity-market-nem/data-nem/data-dashboard-nem

**Comment by jamesy1988** [comment]
Hi Shaunovsky,

This is a live issue and currently being addressed under issue #2580

**Comment by Shaunovsky** [comment]
Ah good to know

On 18 Oct 2020, at 4:15 pm, Andy James <notifications@github.com> wrote:

﻿

Hi Shaunovsky,

This is a live issue and currently being addressed under issue #2580<https://github.com/tmrowco/electricitymap-contrib/issues/2580>
