### ISSUE TITLE
IN-MH parser data is coming in spotty

### ISSUE THREAD

**Issue by tth4vb** [tmrowco/electricitymap-contrib#2758]
Looking at the last few months of data coming into IN-MH, we're seeing very scarce data, a couple of hourly data points every 24 hours, meaning it's not very useful when looking at the recent history graphs on eMap for example:
<img width="444" alt="Screen Shot 2020-10-21 at 10 50 57 AM" src="https://user-images.githubusercontent.com/8129157/96696703-59a06d80-138b-11eb-9924-b73cef71cf02.png">

Here's a chart of the data coming in for 2020:
<img width="677" alt="Screen Shot 2020-10-21 at 10 57 38 AM" src="https://user-images.githubusercontent.com/8129157/96697547-55c11b00-138c-11eb-9e39-ca475f14d4eb.png">

It would be awesome if someone has the chance to dig in a bit here as to why this is happening, particularly @GitMatze who I believe built the original parser. 

If we cannot identify the issue and/or a potential solution, I think this also would bring up a conversation previously started in #1982 by @systemcatch about switching to all of India as a parser instead given some of the challenges with regional parsers. My concern there is that there is still a decent proportion of data coming into that parser as "unknown production" where we're assigning some static values (based on skimming through #304, after which we had concluded on sticking to regional parsers). But let's first see if there's some solution to this problem in IN-MH.

**Comment by GitMatze** [comment]
This is a known issue caused by a timeout. Since the data is parsed from a dashbord image using character recognition this parser is quite computation-heavy. I've already tried to optimize it, but apparently it's still not fast enough. See https://github.com/tmrowco/electricitymap-contrib/issues/2343

**Comment by tth4vb** [comment]
Ah thanks for the clarification @GitMatze! Good to know the limitations here

**Comment by Kongkille** [comment]
@GitMatze just looked at the parser. It seems you've thought of a lot of ways to improve it. Did you try to crop the image to specifically only get the values that are relevant? I'm wondering which aspects of the computation takes a long time, it could also be the original loading of the image as it's a bit heavier than a lot of other images we use tesseract on.

**Comment by GitMatze** [comment]
Just did some profiling. On my system fetching the image accounts for 62% and running tesseract for 32% of the time. However, with the cpu power resctricted  to a minimum, fetching the image takes only 34% and tesseract 70% of the time. Tesseract definitely is the cpu-sensitive process here.

**Comment by ssmssam** [comment]
Hi, this is my first time potentially contributing so apologies if I'm not following standard procedure. I tried to use pytessy https://pypi.org/project/pytessy/ as heard that could be faster than using Tesseract directly. On my machine this provided roughly a 10% speed up on the running tesseract part:


Tesseract:
%timeit pytesseract.image_to_string(imgs_line, lang='digits_comma', config='--psm 7')
521 ms ± 7.66 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

pytessy:
%timeit digit_reader.read(imgs_line.tobytes(), imgs_line.size[0], imgs_line.size[1], 1) 
484 ms ± 20.3 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


and for a file taken at an earler time:
Tesseract:
%timeit pytesseract.image_to_string(imgs_line, lang='digits_comma', config='--psm 7')
1.02 s ± 3.97 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

pytessy:
%timeit digit_reader.read(imgs_line.tobytes(), imgs_line.size[0], imgs_line.size[1], 1) 
939 ms ± 5.3 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


The code can be found here https://github.com/ssmssam/electricitymap-contrib/blob/attempt_to_speedup_iINMH_parser/parsers/IN_MH.py    . I don't know if that is significant enough to stop any timeouts but if it is of use let me know and I can create a pull request.

**Comment by Kongkille** [comment]
Thank you @ssmssam! Maybe you can open a PR and then add @GitMatze as a reviewer? And yeah, not sure if this will stop the timeouts either as the image is quite big, but it is interesting nonetheless as we have several parsers using tesseract, so figuring out the optimal way of using it would be a win regardless I think.

**Comment by skovhus** [comment]
The data is much more stable now after we upgraded our infrastructure. Thanks for everyone helping out here. 👏
