### ISSUE TITLE
Spanish islands down

### ISSUE THREAD

**Issue by q--** [tmrowco/electricitymap-contrib#2765]
The Balearic islands and the Canaries are down. The parser has trouble processing a [timestamp](https://kibana.electricitymap.org/app/kibana#/discover/10af54f0-0c4a-11e9-85c1-1d63df8c862c?_g=(refreshInterval:('$$hashKey':'object:232',display:'5%20minutes',pause:!f,section:2,value:300000),time:(from:now-24h,mode:quick,to:now))&_a=(columns:!(message,extra.key,level),filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!t,index:'96f67170-0c49-11e9-85c1-1d63df8c862c',key:level,negate:!f,params:(query:ERROR,type:phrase),type:phrase,value:ERROR),query:(match:(level:(query:ERROR,type:phrase)))),('$state':(store:appState),meta:(alias:!n,disabled:!f,index:'96f67170-0c49-11e9-85c1-1d63df8c862c',key:extra.key,negate:!f,params:(query:ES-IB-MA,type:phrase),type:phrase,value:ES-IB-MA),query:(match:(extra.key:(query:ES-IB-MA,type:phrase))))),index:'96f67170-0c49-11e9-85c1-1d63df8c862c',interval:auto,query:(language:lucene,query:''),sort:!('@timestamp',desc)))

 

> Failed to match 'YYYY-MM-DD HH:mm ZZZ' when parsing '2020-10-25 2A:00 Europe/Madrid'

**Comment by q--** [comment]
It's up again.

Still might be worth trying to figure out if it was just a problem on their end, or if the parser also needs updating

**Comment by corradio** [comment]
@q-- should we close this one then?

**Comment by q--** [comment]
I haven't seen it happen again for a while (haven't really been paying attention, though), so that's fine
