### ISSUE TITLE
Link "You can contribute by adding area data." broken

### ISSUE THREAD

**Issue by q--** [tmrowco/electricitymap-contrib#2767]
The link on e.g. https://www.electricitymap.org/zone/NE?wind=true doesn't lead to the right place anymore now that instructions have been moved to the wiki.

**Comment by veqtrus** [comment]
The wiki doesn't seem to have an article for adding areas.

**Comment by FelixDQ** [comment]
Ah yea, we organized the wiki a bit different than the old readme. For now i think that we should link to the "getting started" page of the wiki https://github.com/tmrowco/electricitymap-contrib/wiki/Getting-started
