### ISSUE TITLE
Sparse data coming in for Singapore

### ISSUE THREAD

**Issue by tth4vb** [tmrowco/electricitymap-contrib#2779]
We're seeing some really spotty data coming in from the SG parser, similar in pattern to the IM-MH parser (#2758). Wondering if perhaps there's some issue with the OCR timing out and affecting other data as well (though I know this should have been fixed in #1281)? 

Either way, if anyone has time to look into the potential source of this issue, we'd love your help :) 

Tagging potential relevant folks here - @jarek who built the original parser, @systemcatch who set up the OCR, @mickm who helped improve OCR in #2477

**Comment by ssmssam** [comment]
As with issue 2758, I have tried using pytessy instead and did see a considerable speed up, whether or not this is enough to stop timeouts on the server, I do not know. 

On my local machine:

With pytessy: 
%timeit digit_reader.read(black_white.tobytes(), black_white.width, black_white.height, 1)
105 ms ± 2.21 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)

With pytesseract:
%timeit image_to_string(black_white, lang='eng')
302 ms ± 2.11 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

Values read from both methods were the same.  This is now part of a pull request  https://github.com/tmrowco/electricitymap-contrib/pull/2768

**Comment by systemcatch** [comment]
Looking at the [logger](https://kibana.electricitymap.org/app/kibana#/doc/96f67170-0c49-11e9-85c1-1d63df8c862c/logstash-2020.11.01/doc?id=0OEjgXUBflit6ybPgU7X&_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:now%2Fw,mode:quick,to:now%2Fw)))

```shell
Traceback (most recent call last):
  File "/home/src/electricitymap/feeder/lib/fetch_data.py", line 176, in launch_parsers
    objs = res.get(timeout)
  File "/usr/local/lib/python3.6/multiprocessing/pool.py", line 640, in get
    raise TimeoutError
multiprocessing.context.TimeoutError
```
@tth4vb there is an issue in the closed source backend. I can load both urls for the `SG` parser, makes me think electricitymap has been blocked.

**Comment by tth4vb** [comment]
@systemcatch ah ok, thanks for digging in. We will look into it on our side as soon as we have capacity!

**Comment by skovhus** [comment]
This has been fixed.
