### ISSUE TITLE
EIA parser doesn't report 0 production for hydro

### ISSUE THREAD

**Issue by FelixDQ** [tmrowco/electricitymap-contrib#2789]
When generating power from hydro storage, the EIA parser reports nothing for hydro:
![image](https://user-images.githubusercontent.com/12124251/98128771-99ea0a80-1eb8-11eb-87cf-3fb53be7dbf6.png)

This results in a question mark on the map even though that we now that the production is 0:
![image](https://user-images.githubusercontent.com/12124251/98129070-f9e0b100-1eb8-11eb-9ced-e21d0459ac5c.png)

Reproduce with
```
python test_parser.py US-CAR-DUK --target_datetime 2020-01-01
```

Am I interpreting the data correctly in that the hydro production should be set to 0?

**Comment by willbeaufoy** [comment]
To clarify, do you mean that hydro should be 0 in the 5am datetime, rather than being absent completely?

**Comment by FelixDQ** [comment]
Yes, I would say so, but please correct me if I'm misinterpreting the data.

**Comment by FelixDQ** [comment]
Actually, I'm just going to close this as it doesn't matter that much. Though, please go ahead, if someone wants to look deeper into this
