### ISSUE TITLE
Clear definition of "low carbon" and "renewables" to FAQ 

### ISSUE THREAD

**Issue by jaakla** [tmrowco/electricitymap-contrib#2796]
I get that biomass can be classified as kind of "renewable" (but consider that regrowing trees can take 50+ years in higher latitudes), but burning it for energy or electricity produces much more CO₂ per KWh than many fossils, e.g. natural gas. In this sense biomass should be set as "high carbon".  
From the numbers it seems that you simply classify all renewables as low carbon. I know it is a common approach, but still IMHO debatable and greenwashy practise. Please you add to FAQ what exactly you classify as low carbon and renewables

**Comment by chalg** [comment]
Agree, and is transportation, for example, shipping it from the US to Europe included in emissions?

**Comment by jarek** [comment]
> burning it for energy or electricity produces much more CO₂ per KWh than many fossils, e.g. natural gas. In this sense biomass should be set as "high carbon".

According to the IPCC values which we use, the median carbon intensity (gCO2eq/kWh) of electricity generated from biomass is about half of that generated from natural gas. See https://www.ipcc.ch/site/assets/uploads/2018/02/ipcc_wg3_ar5_annex-iii.pdf PDF-page 1335. The mean/median/max values for biomass are 130 / 230 / 420 compared to 410 / 490 / 650 for combined-cycle natural gas. The biomass figure has a note "Direct emissions from biomass combustion at the power plant are positive and significant, but should be seen in connection with the CO2 absorbed by growing plants." Generally the position of Electricity Map has been that they want to use peer-reviewed values for carbon intensity and the IPCC values are used as a widely-reviewed baseline.

> is transportation, for example, shipping it from the US to Europe included in emissions?

IPCC figures we use include lifecycle emissions. E.g. for nuclear this includes uranium mining and concrete embodied in the plants. For biomass, most of the overall carbon intensity value does come from "infrastructure & supply chain emissions".

---

You may also be interested in previous discussions in https://github.com/tmrowco/electricitymap-contrib/issues/738 "Refine GHG emission factors by regions"

---

On this topic, I think that our readme used to have a link the IPCC table that we use for default carbon intensity of the different fuels, but I can't find it now. Has it gone missing? I _think_ the PDF link is https://www.ipcc.ch/site/assets/uploads/2018/02/ipcc_wg3_ar5_annex-iii.pdf ?

**Comment by Kongkille** [comment]
@jarek we added this section in the wiki. Would be happy to expand it if you have any input whatsoever :) 
https://github.com/tmrowco/electricitymap-contrib/wiki/Emission-factors
