### ISSUE TITLE
ENTSO-E Pumped Hydro consumption missing 

### ISSUE THREAD

**Issue by Fred-3000** [tmrowco/electricitymap-contrib#2800]
It seems that consumption values for pumped hydro (storage) are missing for countries based on ENTSO-E data. 
They are reported on their website, so I guess something is wrong in the parser.

**Comment by willbeaufoy** [comment]
Which countries are you looking at? I checked now on the frontend and the UK, France and Germany are all reporting pumped storage values.

**Comment by Fred-3000** [comment]
Belgium, Germany, Portugal, and more...
The positive values (when producing electricity) are shown, but the negative values (when storing electricity) are not.

**Comment by willbeaufoy** [comment]
Ah yes I see what you mean. So for example hydro storage for Austria is reported as -.0.0 at 03:00 UTC this morning:

![Screenshot from 2020-11-13 17-55-12](https://user-images.githubusercontent.com/693233/99104883-81c16c00-25d9-11eb-8ab0-b002e266d09e.png)

However ENTSOE [reports](https://transparency.entsoe.eu/generation/r2/actualGenerationPerProductionType/show?name=&defaultValue=false&viewType=GRAPH&areaType=BZN&atch=false&datepicker-day-offset-select-dv-date-from_input=D&dateTime.dateTime=13.11.2020+03:00|UTC|DAYTIMERANGE&dateTime.endDateTime=13.11.2020+04:00|UTC|DAYTIMERANGE&area.values=CTY|10YAT-APG------L!BZN|10YAT-APG------L&productionType.values=B01&productionType.values=B02&productionType.values=B03&productionType.values=B04&productionType.values=B05&productionType.values=B06&productionType.values=B07&productionType.values=B08&productionType.values=B09&productionType.values=B10&productionType.values=B11&productionType.values=B12&productionType.values=B13&productionType.values=B14&productionType.values=B20&productionType.values=B15&productionType.values=B16&productionType.values=B17&productionType.values=B18&productionType.values=B19&dateTime.timezone=UTC&dateTime.timezone_input=UTC) that at this time hydro storage consumption was -422MW (and there was no hydro storage production at this time).

**Comment by willbeaufoy** [comment]
I've found the cause, it's because of [this commit](https://github.com/tmrowco/electricitymap-contrib/commit/97865b8d33fbfe643aeba2fcff53ecb8b727786c?branch=97865b8d33fbfe643aeba2fcff53ecb8b727786c&diff=unified) from a month ago that ignores consumption values when calculating production. If you revert the code that was changed then we get the pumped storage data again. @FelixDQ @PaulCornelissen (authors of the commit) was this effect intended in your commit?

**Comment by PaulCornelissen** [comment]
Nope, that was certainly not the intended effect. You can read the history here: #2676 and #2638 

In short: In NL there's sometimes significant self consumption at power plants (e.g. CHP plants at large consumers). Sometimes it's more than the production for an entire generation type (mostly for unknown). That would cause the production for unknown to be negative and the parser would fail. 

I suppose that we should add an extra condition to differentiate between consumption for hydro(storage) and other types of generation.

**Comment by willbeaufoy** [comment]
> Nope, that was certainly not the intended effect. You can read the history here: #2676 and #2638
> 
> In short: In NL there's sometimes significant self consumption at power plants (e.g. CHP plants at large consumers). Sometimes it's more than the production for an entire generation type (mostly for unknown). That would cause the production for unknown to be negative and the parser would fail.
> 
> I suppose that we should add an extra condition to differentiate between consumption for hydro(storage) and other types of generation.

Ok I will see if I can fix it.
