### ISSUE TITLE
IFA2 (1 GW France-UK link) has started transferring power

### ISSUE THREAD

**Issue by aarbur** [tmrowco/electricitymap-contrib#2809]
See:
https://www.montelnews.com/en/story/tsos-begin-power-transfers-on-1-gw-france-uk-link/1167828

Time to add it to electricitymap?

**Comment by aarbur** [comment]
Is it normal for ElectricityMap to "merge" parallel interconnectors? Or should cross-chanel and IFA2 show up separately?

@PaulCornelissen am I right in thinking that your change only updates the Capacity (and assumes a merged display of the two interconnectors here on ElectricityMap), and does not automagically add the actual live usage data for IFA2?

**Comment by Kongkille** [comment]
Yes based on the PR that's what's going on. So the capacity is the current one (2k) + 1k from IFA2

**Comment by aarbur** [comment]
Why is this closed? The capacity might be updated but we are not yet parsing/aggregating the data for the new interconnector - unless I misunderstand.

**Comment by Kongkille** [comment]
Yes so the interconnector should be included in the ENTSOE data which we are already parsing, so the data should be automatically be added to the map, we just haven't added the capacity for the interconnector

![image](https://user-images.githubusercontent.com/45588799/99701132-55539700-2a94-11eb-8c29-a3da484a5e7a.png)

So this means the interconnector data should be displayed here as well, just with a new capacity.

Here is the link to entsoe as well :) 
https://transparency.entsoe.eu/transmission-domain/physicalFlow/show?name=&defaultValue=false&viewType=TABLE&areaType=BORDER_CTY&atch=false&dateTime.dateTime=19.11.2020+00:00|CET|DAY&border.values=CTY|10YFR-RTE------C!CTY_CTY|10YFR-RTE------C_CTY_CTY|GB&dateTime.timezone=CET_CEST&dateTime.timezone_input=CET+(UTC+1)+/+CEST+(UTC+2)

**Comment by aarbur** [comment]
I see, thank you! That link you supplied has numbers today (every time I looked before it only showed columns of n/a, or something like that) - highest value I see is 2022MW, which I suppose reflects that IFA2 is not yet in full use.

I still see a capacity of 2GW showing on https://www.electricitymap.org/. How do we know when commits that have been merged into master will/do actually show up on the website?

**Comment by PaulCornelissen** [comment]
It's not asctually using the ENTSOE parser like I said before, but the ELEXON parser. However I already checked the API spec shortly after my commit and ELEXON should also return total FR->GB exchange and not a per interconnector value, so all the same.

2022MW doesn't mean anything. It's probably the difference between reporting the input and output. The difference is line losses. You see this on many interconnectors that they report a couple percent above max capacity. 

IFA2 isn't in use yet. That may take a couple of months. Just like COBRA and AleGro did. Let's be patient please.
