### ISSUE TITLE
Données Suisse

### ISSUE THREAD

**Issue by fcimballi** [tmrowco/electricitymap-contrib#2824]
Bonjour,
Il est souvent noté Données temporairement non disponibles pour la Suisse. Pourquoi ?

**Comment by jarek** [comment]
Sorry, in English: it looks like official data published is significantly incomplete. You might get some information from the past issue: https://github.com/tmrowco/electricitymap-contrib/issues/892

**Comment by corradio** [comment]
Closing as this is a duplicate of #892
