### ISSUE TITLE
Add North Sea Link (GB<->NO-NO2)

### ISSUE THREAD

**Issue by q--** [tmrowco/electricitymap-contrib#2832]
National Grid and Statnett are building an interconnector ([1400MW](https://northsealink.com/)) between Great Britain and [South-West Norway](https://northsealink.com/en/locations/norway/) (should be NO-NO2 based on physical location).

Installation of subsea cables is only [planned](https://northsealink.com/en/the-project/project-timeline/) to be finished in 2021, but apparently the interconnector has already been added to ELEXON and possibly [broken](/tmrowco/electricitymap-contrib/pull/2828) that [parser](/tmrowco/electricitymap-contrib/issues/2829).

So, it seems to be possible to add the exchange to ElectricityMap. I can't find it in ENTSO-E yet though, so if we want to use that one instead of ELEXON we'll have to wait.

**Comment by ilfrich** [comment]
The new exchanges (3 of them, 2 to FR, 1 to NO) haven't been added yet. Probably best to add them via ELEXON, will have a look.

**Comment by ilfrich** [comment]
Not 100% sure, but does the direction of the exchange matter? It looks like ELEXON returns positive and negative values depending on the flow, but the `EXCHANGES` listed in the parser seem to depend on the direction of the exchange and how it is defined.

They've also created 2 more exchanges to France (currently not providing any values yet), so there's probably some need to refactor the parser to support multiple columns per exchange (`FR->GB`). I can extend this, but would need to know if the new link is `NO-NO2->GB` or `GB->NO-NO2` - and the same question for the 2 new French connections.

**Comment by ilfrich** [comment]
Did some more digging. It looks like ELEXON provides all their data under the following convention:

> The convention adopted is that a positive value represents import into the GB Transmission System, whilst a negative value represents an export from GB.

Given that, the ELEXON parser currently handles the `FR->GB` and `BE->GB` exchanges incorrectly (basically inverting the actual power flow).

**Comment by ilfrich** [comment]
Ok, the new link is added. I figured out the "direction" issue eventually. The answer became obvious once I saw the result, given the `sorted_zone_keys` are returned, and not the keys passed in.
