### ISSUE TITLE
Show header when loading

### ISSUE THREAD

**Issue by fbarl** [tmrowco/electricitymap-contrib#2846]
There is no reason to hide the header while the map content is being loaded and having the header visible at all times would make smoother transitions between header links (Live / Open Source / API pages) in the desktop view.

cc @Kongkille

**Comment by Kongkille** [comment]
Yes good idea!

**Comment by corradio** [comment]
cc @madsnedergaard in case this is an easy win

**Comment by kocvrek** [comment]
Can I work on this issue?

**Comment by madsnedergaard** [comment]
Hey @kocvrek, that would be great! Let us know if you have any questions while working on it :)
