### ISSUE TITLE
France <> GB interconnector missing data?

### ISSUE THREAD

**Issue by tth4vb** [tmrowco/electricitymap-contrib#2853]
Note from someone reaching out over email: the UK is still missing some of the interconnectors e.g French etc which were showing prior to loss of data.

**Comment by jarek** [comment]
Could be because https://github.com/tmrowco/electricitymap-contrib/pull/2840 is still open?

**Comment by tth4vb** [comment]
@jarek ah yes, could be! Just wanted to capture this feedback when it came in, but hopefully can be fixed by that PR. Thanks for the heads up :)

**Comment by wizmer** [comment]
This seems to be fixed, no ?
![Screenshot from 2021-01-11 11-22-36](https://user-images.githubusercontent.com/1685078/104169120-5c958200-53ff-11eb-865a-bcc91ec94e7c.png)

**Comment by corradio** [comment]
Seems to have been fixed indeed!
