### ISSUE TITLE
bounding_box documentation

### ISSUE THREAD

**Issue by ajoga** [tmrowco/electricitymap-contrib#2857]
Hello, 

I'm trying to add an island, and [I can't find documentation](https://github.com/tmrowco/electricitymap-contrib/search?q=bounding_box&type=wikis) on what are and how to determine the `bounding_box` dictionary in [zones.json](https://github.com/tmrowco/electricitymap-contrib/blob/master/config/zones.json#L16). 

Could someone help?
Thanks

**Comment by corradio** [comment]
Hi @ajoga ,

This is the script we use: https://github.com/tmrowco/electricitymap-contrib/blob/master/web/generate-zone-bounding-boxes.js
Could be a good idea to write some doc and upgrade the script so it can be run on a single zone (instead of updating all bounding boxes of all zones!)

**Comment by ajoga** [comment]
Alright so I found out that `topogen.sh` calls `generate-zone-bounding-boxes.js` and that this needs no interaction whatsoever and just works. 

For someone googling around, there is informations about all that in [web/README.md](https://github.com/tmrowco/electricitymap-contrib/blob/4cea9b9ddf76954a4bd3f3e931439d5d3f5171cb/web/README.md)
