### ISSUE TITLE
Reduce header size

### ISSUE THREAD

**Issue by Kongkille** [tmrowco/electricitymap-contrib#2876]
Tested on multiple screens. I think we can reduce header height by about 8 px and then reduce font size accordingly. Prob from about 16 to 14. 

- [ ] Reduce header height
- [ ] Reduce header font size

**Comment by Kongkille** [comment]
@madsnedergaard if you want. I think this item could be really cool to finish up?

**Comment by madsnedergaard** [comment]
Aight, spinning up things locally now and then I'll get on it :)
