### ISSUE TITLE
Change Croatia source to ENTSOE

### ISSUE THREAD

**Issue by Lightning-5** [tmrowco/electricitymap-contrib#2885]
Current source for Croatia is lacking information on type of electricity production. Since information on Croatia is also available on ENTSOE I think that ENTSOE should be uses as a source

[ENTSOE Croatia](https://transparency.entsoe.eu/generation/r2/actualGenerationPerProductionType/show?name=&defaultValue=true&viewType=TABLE&areaType=BZN&atch=false&datepicker-day-offset-select-dv-date-from_input=D&dateTime.dateTime=30.12.2020+00:00|CET|DAYTIMERANGE&dateTime.endDateTime=30.12.2020+00:00|CET|DAYTIMERANGE&area.values=CTY|10YHR-HEP------M!BZN|10YHR-HEP------M&productionType.values=B01&productionType.values=B02&productionType.values=B03&productionType.values=B04&productionType.values=B05&productionType.values=B06&productionType.values=B07&productionType.values=B08&productionType.values=B09&productionType.values=B10&productionType.values=B11&productionType.values=B12&productionType.values=B13&productionType.values=B14&productionType.values=B20&productionType.values=B15&productionType.values=B16&productionType.values=B17&productionType.values=B18&productionType.values=B19&dateTime.timezone=CET_CEST&dateTime.timezone_input=CET+(UTC+1)+/+CEST+(UTC+2))

**Comment by PaulCornelissen** [comment]
This is very good news!

However if I look at today, they seem to be >4hrs behind, so no good for live info. At the moment the data is 7hrs behind.

If this turns out to be just a fluke and the data is normally reliable, I'd be happy to do a PR to fix this.

Otherwise we can combine the current parser with the ENTSOE parser for older data and use this data to update the unknown intensity?

**Comment by FelixDQ** [comment]
The ENTSOE data is still lagging with ~4 hours, so I don't think that we should switch data source right now.

I'm going to close this issue for now, and then we can revisit it if the lag on ENTSOE changes in the future.
