### ISSUE TITLE
No transmission reported between NO1 and SE

### ISSUE THREAD

**Issue by VIKTORVAV99** [tmrowco/electricitymap-contrib#2897]
electricityMap show no transmission between NO1 and SE
![image](https://user-images.githubusercontent.com/30777521/103593144-4bc3a880-4ef5-11eb-9f58-16202d24a438.png)
but at the same time SVK shows a transmission of 674 MW from NO1 to SE3
![image](https://user-images.githubusercontent.com/30777521/103593218-80376480-4ef5-11eb-9d30-1767f055f003.png)

**Comment by FelixDQ** [comment]
Thanks for noticing! It seems like the interconnector is back up now.
![image](https://user-images.githubusercontent.com/12124251/112332430-0627a800-8cba-11eb-97c0-bc9bd67da10c.png)
