### ISSUE TITLE
Hovering over mix graph causes tooltip flags to be refetched

### ISSUE THREAD

**Issue by corradio** [tmrowco/electricitymap-contrib#2902]
Hovering over the mix graph causes the tooltip to be recreated, and the flag png to be refetched (see the many requests to se.png)
![image](https://user-images.githubusercontent.com/1655848/103768717-4cf2f380-5023-11eb-9bac-48eda3e2ee1f.png)

**Comment by q--** [comment]
Can't reproduce with Firefox. Perhaps you've got caching disabled in the dev tools?

**Comment by corradio** [comment]
> Can't reproduce with Firefox. Perhaps you've got caching disabled in the dev tools?

you're right!

@fbarl do you think this is a sign that the React component is re-rendering everything? Do you see any potential optimisation? If not, we can close this issue.

**Comment by fbarl** [comment]
I can't reproduce it with my Chrome either so I guess this is only a problem for the users that have caching disabled - is that a significant portion?

It's possible we're doing a complete rerendering (so maybe it's worth looking into that as separate optimisation), but it might also be there's something going on with `flagUri` helper / its `resolvePath` call. It might be worth adding a simple cache there in the `helpers/flags.js` code to make sure no flag is loaded twice in the app. But then again, that's something that should probably be managed by a browser caching policy so not sure if this workaround is a way to go :smile:

**Comment by corradio** [comment]
ok. Checked resolvePath and couldn't see anything. False alert!
