### ISSUE TITLE
Update position of arrow for Corse (Corsica) 🇫🇷 => Sardinia 🇮🇹  link

### ISSUE THREAD

**Issue by Manu1400** [tmrowco/electricitymap-contrib#2910]
Actual map : 
<img width="208" alt="Capture d’écran, le 2021-01-11 à 14 52 29" src="https://user-images.githubusercontent.com/3307236/104190630-a6d92c00-541c-11eb-9a8c-e347a20d47a9.png">

Proposal : 
<img width="208" alt="Capture d’écran, le 2021-01-11 à 14 50 45" src="https://user-images.githubusercontent.com/3307236/104190642-aa6cb300-541c-11eb-806c-3cabdcbf9b8c.png">

Source : 
https://twitter.com/MrBidouille/status/1348598044128899072

**Comment by q--** [comment]
There is an interconnection between Italy and Sardinia as well according to [ENTSO-E](https://www.entsoe.eu/data/map/)

**Comment by alixunderplatz** [comment]
The arrows above show the correct interconnectors and their respective directions and values, so everything is fine with the arrows and the data as they are. 

However there are 2 more paths to consider which are missing on the map: interconnections between Corsica and Sardinia and between Italy-Central-North and Sardinia (from the DC-connection).
I wrote a few lines how to get all of that properly represented a while back in 2019, but it is not implemented so far.
Someone should probably open a separate issue to finally fix/implement this in the ENTSOE parser:
https://github.com/tmrowco/electricitymap-contrib/issues/1029#issuecomment-537910683
and
https://github.com/tmrowco/electricitymap-contrib/issues/1029#issuecomment-537956654

**Comment by corradio** [comment]
Closing in favour of https://github.com/tmrowco/electricitymap-contrib/issues/2991
