### ISSUE TITLE
Missing flag : 🇽🇰 Kosovo (XK)

### ISSUE THREAD

**Issue by Manu1400** [tmrowco/electricitymap-contrib#2914]
Screenshoot: 
<img width="455" alt="Capture d’écran, le 2021-01-11 à 18 27 58" src="https://user-images.githubusercontent.com/3307236/104216751-c4b58980-543a-11eb-8a13-0b8c96a14616.png">

URL : https://static.electricitymap.org/public_web/images/flag-icons/flags_iso/32/xk.png
> "The specified key does not exist."

**Comment by Manu1400** [comment]
missing "flag_file_name": "xk.png" in zones.json ?

**Comment by jarek** [comment]
> missing "flag_file_name": "xk.png" in zones.json ?

No, the flag_file_name defaults to the country code if not specified in zones.json: https://github.com/tmrowco/electricitymap-contrib/blob/8033de5f23b0908e3f9b5e336e1e09b9679c1449/web/src/helpers/flags.js#L12-L13

We don't have the flag image. It should be in https://github.com/tmrowco/electricitymap-contrib/tree/master/web/public/images/flag-icons/flags_iso

**Comment by madsnedergaard** [comment]
I've fixed it in #3005.

For future reference as it took me some time do dig this info out:

The source for the flag icons is http://icondrawer.com/flag-icons.php
