### ISSUE TITLE
Data available for French Polynesia

### ISSUE THREAD

**Issue by autipial** [tmrowco/electricitymap-contrib#2917]
Hi, first issue here, hope I'm not doing it the wrong way!

Real-time production/consumption data for _most_ of the islands of French Polynesia is available here : [https://www.edt.pf/transition-energetique-innovation](url)
Production = consumption since there isn't any exchange with neighboring countries/dependent territories.
Electricity in French Polynesia is only generated by thermal (oil), hydro and solar plants. There used to be wind turbines on a few islands, and there are projects to conduct some other experimentation, but it's not clear if they currently are in operation.

The data above-mentioned covers the electricity generated by EDT/Engie and its subsidiary Marama Nui on the most populated islands (including Tahiti, Moorea, Huahine, Bora Bora) where at least 75-80% of the population lives :
- [https://www.edt.pf/edt-engie](url)
- [https://www.edt.pf/documents/20126/1180028/EDT-chiffres+2018-10.jpg/10e3828d-6eb3-5c82-ab6b-ede4055cfb74?t=1582934078733imagePreview=1](url).

The production on the remaining islands is generated by domestic stations operated by municipalities. I've mapped most of the stations, even on the remote islands using many different sources, don't know if this can prove useful to estimate the total installed capacity for French Polynesia.

There's also historic data available here with a 10-minute update (XLSX files) : [https://www.service-public.pf/sde/documentation-2/production-delectricite-edt-sur-tahiti/](url). Unfortunately it only covers the production on the island of Tahiti (~2/3 of the population).

I've started to write a parser for the data using guidance from the Wiki, but I doubt the method I used is optimal. I have basic knowledge in coding (but am very interested in learning more), so I was wondering if anyone could mentor me on this one.

Cheers :)

**Comment by vakili** [comment]
Hey @autipial, I'd be happy to work together on implementing this parser if you like :)

**Comment by autipial** [comment]
Hey @vakili, thanks for the reply ! I'll reach out to you on Slack.
