### ISSUE TITLE
Update the screenshoot into README

### ISSUE THREAD

**Issue by Manu1400** [tmrowco/electricitymap-contrib#2918]
The screenshoot of the website in README is 3 years old !

sources  : 
* git blame, line 7 : https://github.com/tmrowco/electricitymap-contrib/blame/master/README.md
* diff : https://github.com/tmrowco/electricitymap-contrib/commit/03b5c31f6b05caaaf3917f15d570eb1c113cf21c

More countries is supported now (and the UI have now a "production / consumption" button).

**Comment by veqtrus** [comment]
`<meta property="og:image" content="https://www.electricitymap.org/images/electricitymap_social_image.jpg" />` should also be updated.

**Comment by Manu1400** [comment]
> `<meta property="og:image" content="https://www.electricitymap.org/images/electricitymap_social_image.jpg" />` should also be updated.

It's the same URL

**Comment by corradio** [comment]
duplicate of https://github.com/tmrowco/electricitymap-contrib/issues/2617
