### ISSUE TITLE
énergie nucléaire n'est pas neutre en CO2

### ISSUE THREAD

**Issue by pem07** [tmrowco/electricitymap-contrib#2920]
Bonjour, 

La carte avec les flux d'électricité est très bien fait, chapeau ! Néanmoins, indiquer l'électricité nucléaire de la France comme presque neutre en CO2 donne un image faussé.

**Comment by martin-laurent** [comment]
Bonjour,
L'intensité carbone de l'électricité nucléaire n'est pas indiquée comme neutre mais a 12 gCO2e/kWh. Cela prend en compte la durée de vie complete du systeme nucléaire. La source pour le nucléaire comme pour la plupart des autres sources d'électricité est [IPCC 2014](https://www.wikiwand.com/en/Life-cycle_greenhouse_gas_emissions_of_energy_sources#/2014_IPCC,_Global_warming_potential_of_selected_electricity_sources) que vous pouvez consulté ici: https://www.ipcc.ch/site/assets/uploads/2018/02/ipcc_wg3_ar5_annex-iii.pdf#page=7

**Comment by fconrotte** [comment]
oui et le tableau est résumé ici:
https://fr.wikipedia.org/wiki/%C3%89mission_de_gaz_%C3%A0_effet_de_serre_par_source_d%27%C3%A9nergie_%C3%A9lectrique

![image](https://user-images.githubusercontent.com/4604786/104429844-57af0a80-5586-11eb-94ce-81b457a5e8de.png)

**Comment by fconrotte** [comment]
Et comme expliqué pendant ces débats au Sénat, l'ADEME a fait le calcul à 6gr de CO2 par kwh pour le nucléaire français.

> Le résultat proposé par la base carbone de l'ADEME, largement utilisée pour les calculs des bilans réglementaires gaz à effet de serre (GES), est en réalité de 6g CO2/kWh pour l'énergie nucléaire en France.

https://www.senat.fr/questions/base/2019/qSEQ190209117.html

**Comment by corradio** [comment]
Thanks everyone for replying! I think this issue can be considered closed now.
