### ISSUE TITLE
Fix Switzerland's "unknown" CO2 intensity

### ISSUE THREAD

**Issue by Lukian52** [tmrowco/electricitymap-contrib#2929]
River power plants ("Laufwasserkraftwerke") are hydro and low carbon. However, you count them as high carbon like coal: 
They are "unknown" in the data source you have, as they feed in at a low level on the grid - and then you assume they are high carbon (which is coutious, but wrong in this case.

**Comment by q--** [comment]
See also: #2898

I'll give calculating the carbon intensity of "unknown"  a try

**Comment by Lukian52** [comment]
Thanks!

**Comment by PaulCornelissen** [comment]
@q-- @Lukian52 Luckily @Kikof2 already did al the calculations and documented them in #2898. It's 131grCO2eq/kWh. He just forgot to put them in the co2eq_parameters.json file. I'll do that and open a PR.
