### ISSUE TITLE
[mobile] first render doesn't show colorbar

### ISSUE THREAD

**Issue by corradio** [tmrowco/electricitymap-contrib#2934]
Can be reproduced in Chrome for Mac in responsive mobile mode.
Note that loading the `/map` endpoint instead of just `/` removes the error.

![image](https://user-images.githubusercontent.com/1655848/104921013-085b4680-5999-11eb-8c44-c78ba279317e.png)

**Comment by madsnedergaard** [comment]
Seems like it's something with the `useRefWidthHeightObserver()` hook. I can't quite figure out exactly why it's not re-rendering again on mobile 🤔 

This horrible workaround fixes it, but it hurts a bit to write it 😅 

![Screenshot 2021-01-27 at 16 59 22](https://user-images.githubusercontent.com/3296643/106017893-45be8300-60c1-11eb-8bce-c035e2e0f24e.png)

**Comment by corradio** [comment]
Super weird. Could it be something related to the resize watcher being set too late, thus we're missing some events?
Did you make sense of the fact that loading the /map endpoint instead of just / removes the error?

**Comment by skovhus** [comment]
Fixed in Marts: https://github.com/tmrowco/electricitymap-contrib/pull/3054
