### ISSUE TITLE
Underestimation of CO2 emission of Poland

### ISSUE THREAD

**Issue by mhooi** [tmrowco/electricitymap-contrib#2942]
After changing the overestimation of CO2 emissions / produced kWh of the Netherlands I had a look at the numbers of Poland. We can see that the fast majority of the electricity in Poland is generated by fossils fuel (Coal and Lignite), The current used emission factor for Poland is 820 gCO2eq/kWh. This value is based on 100% hard coal. We do know that a lot of electricity is generated by using Brown coal/Lignite (see also actual ENTSOE.EU data). 

Using the European ETS emission database and the data from the [European Environment Agency](https://www.eea.europa.eu/data-and-maps/daviz/gross-electricity-production-by-fuel-4#tab-googlechartid_chart_11_filters=%7B%22rowFilters%22%3A%7B%7D%3B%22columnFilters%22%3A%7B%22pre_config_sector%22%3A%5B%22Coal%20and%20lignite%22%3B%22Natural%20and%20derived%20gas%22%3B%22Nuclear%22%3B%22Oil%22%3B%22Other%20fuels%22%3B%22Renewables%22%5D%3B%22pre_config_ugeo%22%3A%5B%22Poland%22%5D%7D%7D ) I could derive the realized CO2 emission  per kWh for the fossil fuel part per year.

![poland](https://user-images.githubusercontent.com/65292771/105168920-1507a800-5b1b-11eb-8656-c2cedf242aea.PNG)

Looking at the graph you see a slight improvement over the years. Since the last known data is from 2016 and we assume some improvement since then I would like to propose to change the emission factor of the Coal part in Poland to 1225 gCO2eq/kWh. 

@PaulCornelissen , you've assisted greatly with changing the Dutch emission factors. Could you help again with this change request?

**Comment by mhooi** [comment]
> After changing the overestimation of CO2 emissions / produced kWh of the Netherlands I had a look at the numbers of Poland. We can see that the fast majority of the electricity in Poland is generated by fossils fuel (Coal and Lignite), The current used emission factor for Poland is 820 gCO2eq/kWh. This value is based on 100% hard coal. We do know that a lot of electricity is generated by using Brown coal/Lignite (see also actual ENTSOE.EU data).
> 
> Using the European ETS emission database and the data from the [European Environment Agency](https://www.eea.europa.eu/data-and-maps/daviz/gross-electricity-production-by-fuel-4#tab-googlechartid_chart_11_filters=%7B%22rowFilters%22%3A%7B%7D%3B%22columnFilters%22%3A%7B%22pre_config_sector%22%3A%5B%22Coal%20and%20lignite%22%3B%22Natural%20and%20derived%20gas%22%3B%22Nuclear%22%3B%22Oil%22%3B%22Other%20fuels%22%3B%22Renewables%22%5D%3B%22pre_config_ugeo%22%3A%5B%22Poland%22%5D%7D%7D) I could derive the realized CO2 emission per kWh for the fossil fuel part per year.
> 
> ![poland](https://user-images.githubusercontent.com/65292771/105168920-1507a800-5b1b-11eb-8656-c2cedf242aea.PNG)
> 
> Looking at the graph you see a slight improvement over the years. Since the known data is from 2016 and we assume some improvement since then I would like to propose to change the emission factor of the Coal part in Poland to 1225 gCO2eq/kWh.
> 
> @PaulCornelissen , you've assisted greatly with changing the Dutch emission factors. Could you help again with this change request?

**Comment by alixunderplatz** [comment]
If this emission factor change comes into effect for another country, we'd have to discuss other countries with a mix of lignite & hard coal as well (I made a list here in #162 : https://github.com/tmrowco/electricitymap-contrib/issues/162#issuecomment-376134598)

**Comment by mhooi** [comment]
> If this emission factor change comes into effect for another country, we'd have to discuss other countries with a mix of lignite & hard coal as well (I made a list here in #162 : [#162 (comment)](https://github.com/tmrowco/electricitymap-contrib/issues/162#issuecomment-376134598))

Of course you could argue that this should change for other lignite using countries as well, but this is a lot more work. Poland is in this case a very obvious one, the biggest lignite user of Europe. 

And we can use a country specific emission factor, just look at Estonia, it has a factor of 1515 gCO2eq/kWh due to the shale oil.

**Comment by madsnedergaard** [comment]
Thanks for the contribution @mhooi. Unfortunately, we don't currently add individual emission factors as it would be too difficult for us to validate all the different sources as they might be calculated using different criterias. We currently rely on IPC peer reviewed emission factors, but we also want to refine those and we hope to tackle this in the near future.

We're tracking the over-all progress of this in #738 and specifically the lignite and coal issue in #162 (I've updated the initial description to add your work here as a reference) :)

**Comment by mhooi** [comment]
Thanks @madsnedergaard for the reply. I still wonder why we can't change the emission factor for Poland. Looking at for example Estionia or the Netherlands, we've also adjusted the emission factors there for the Coal and Other part. 

Especially for Poland the displayed carbon intensity is way off. We know that the majority is produced by lignite. The emission /kWh is now around 50% off for this country. I don't think this is wat we want and it is easily adjusted.
