### ISSUE TITLE
Ability to switch between country data and region data

### ISSUE THREAD

**Issue by corradio** [tmrowco/electricitymap-contrib#2954]
Some areas have both country data and region data. This is the case for example of Norway and Denmark.
It would be great to be able to switch between country and region data.
Please thumbs up if you think this is a great idea!

Related issues:
- https://github.com/tmrowco/electricitymap-contrib/issues/2653

**Comment by madsnedergaard** [comment]
Sorry for messing up here, I'm consolidating this in https://github.com/tmrowco/electricitymap-contrib/discussions/3309
