### ISSUE TITLE
Transmission NO <> DE missing on map and values wrong

### ISSUE THREAD

**Issue by Maverick78de** [tmrowco/electricitymap-contrib#2958]
The cross border transmission between Norway and Germany (NORDLINK) is wrong. It shows 0MW while https://transparency.entsoe.eu/ is showing transmission. The Nordlink transmission was finally established in Dec 20

Also the link is missing on map.

![image](https://user-images.githubusercontent.com/19900958/106354370-a2a08000-62f1-11eb-92d6-afebb36bbdf2.png)

**Comment by Maverick78de** [comment]
The transmission is displayed now in country details.  It seems it was only a fault.
But the transmission is still missing on map

**Comment by ajoga** [comment]
Hi @Maverick78de 

The link seems to appear for me : 

![Screenshot_20210209_225423](https://user-images.githubusercontent.com/37543966/107433672-f26d1b80-6b29-11eb-8e0b-d2056dd9d7e2.png)

Is it not the case for you? Or maybe it was added since you opened the issue?

**Comment by Maverick78de** [comment]
No it doesn't appear. Tested Browser Chrome and Edge 

![image](https://user-images.githubusercontent.com/19900958/107476732-bca25400-6b76-11eb-8813-7f3c971a9268.png)

**Comment by Maverick78de** [comment]
Now it is visible. Something changed?
