### ISSUE TITLE
Notification feature with custom thresholds

### ISSUE THREAD

**Issue by Discostu36** [tmrowco/electricitymap-contrib#2959]
I'd love it if the app had a notification feature. Something like "renewable energy in Germany is above 60 % threshold!" Then I could load my pedelec, smartphone etc. at that moment to lower my carbon footprint.

**Comment by madsnedergaard** [comment]
Hey @Discostu36, we have created an electricityMap service on [ifttt.com/electricitymap](https://ifttt.com/electricitymap).

Maybe you can use that for now? :)

<img width="615" alt="Screenshot 2021-02-08 at 16 03 17" src="https://user-images.githubusercontent.com/3296643/107237605-35929600-6a27-11eb-9d76-0b01204e4326.png">

**Comment by Discostu36** [comment]
This is a good start, thanks. Only thing that is missing is setting a custom threshold. I'm in Germany, so if I only get notified as soon as Germany is below 150g/kwh, it will not happen very often.

**Comment by Kongkille** [comment]
I'll move this to discussions. I think IFTTT can solve a lot of these issues but I understand that it doesn't show custom thresholds
