### ISSUE TITLE
Consider using jsonlint-mod to catch duplicate keys

### ISSUE THREAD

**Issue by veqtrus** [tmrowco/electricitymap-contrib#2963]
One such issue found in #2851.

**Comment by skovhus** [comment]
@veqtrus thanks, that is a great idea!

**Comment by skovhus** [comment]
I'm trying this out. 

https://github.com/tmrowco/electricitymap-contrib/pull/2862 also introduced a duplicate entry for `CA-QC` in `coeq_parameters.json`
