### ISSUE TITLE
Barrier free colours

### ISSUE THREAD

**Issue by Freedoo** [tmrowco/electricitymap-contrib#2999]
Nearly 10% of the human beings are colorblind and therefore unable to distinguish the different colours on the website.
It would be no great effort to change the colours to a barrier free and colour blind friendly spectrum.

**Comment by madsnedergaard** [comment]
Hey @Freedoo, we agree - which is why already have a color-blind mode on the map that you can enable :)

<img width="864" alt="Screenshot 2021-02-17 at 09 16 14" src="https://user-images.githubusercontent.com/3296643/108179849-600ae000-7106-11eb-819f-5ba0a40686ce.png">

**Comment by Freedoo** [comment]
Oh, sorry, ashes on my head...

**Comment by madsnedergaard** [comment]
No worries, we're also investigating if we can make the button more prominent - so this is good feedback that it's currently not easily discovered :)
