### ISSUE TITLE
Wind/Solar overlays not working

### ISSUE THREAD

**Issue by davidbbs** [tmrowco/electricitymap-contrib#3001]
Toggling the wind/solar overlays on my mac 10.15 or iPhone 14.4 shows a flash of a white/transparent overlay and then nothing on Safari, Chrome, Firefox, or the app (on the iPhone). I have tried zooming in/out, changing the region of the world, updating/restarting browser, but I don't see anything. The color scales do appear above the carbon intensity scale at the bottom.

It appears this is broken, but there's no error message.

**Comment by FelixDQ** [comment]
I think weather data was unavailable for a few hours. Can you check if it works now?

**Comment by FelixDQ** [comment]
I'm closing this for now since the weather data is back up now, and we have a separate issue for showing the error message here https://github.com/tmrowco/electricitymap-contrib/issues/3001

Thanks for reporting the issue!
