### ISSUE TITLE
Show error message when wind or solar is unavailable

### ISSUE THREAD

**Issue by corradio** [tmrowco/electricitymap-contrib#3002]
Show an error message if the wind and/or solar data is not available when clicking the wind/solar layer buttons. 

Right now, there's no feedback when the enabling those layers if we're missing weather data (you click a button and nothing happens).

![image](https://user-images.githubusercontent.com/3296643/115720493-6b37f180-a37d-11eb-89e3-2cd99e397f9c.png)

**Comment by evcheng1** [comment]
I am interested in taking this issue. Thanks!
