### ISSUE TITLE
South Australia region does not show solar inputs

### ISSUE THREAD

**Issue by cy754** [tmrowco/electricitymap-contrib#3014]
Hello,
when you click on South Australia, the wind component is shown but rooftop and utility solar are not shown - making South Australia's CO2 performance seem worse than it actually is.

**Comment by Kongkille** [comment]
Hi @cy754. Thanks, I agree. We have had a few issues with Australian solar production. We are looking into this now with this PR #2860 

I'm closing this for now. Let me know if this issue is not encapsulated in the OpenNem PR :)
