### ISSUE TITLE
Separate Easter Island from SEN (Chile)

### ISSUE THREAD

**Issue by autipial** [tmrowco/electricitymap-contrib#3019]
Easter Island (Rapa Nui) is currently included in the Chilean national electric system (Chile-SEN), while it should be kept outside, as the island has its own network and is not connected to the Chilean mainland.

![rapa nui](https://user-images.githubusercontent.com/7460404/109807466-3aadc400-7c26-11eb-95ea-e83833c2cd5d.png)

I'm volunteer to give a try at fixing this one, if you agree that the island has indeed to be separated from SEN.

**Comment by jarek** [comment]
> I'm volunteer to give a try at fixing this one, if you agree that the island has indeed to be separated from SEN.

I think this is pretty clear, it's incredibly far from the mainland. Thank you! https://github.com/tmrowco/electricitymap-contrib/blob/master/web/generate-geometries.js will probably be the starting point for the fix.

**Comment by Kongkille** [comment]
Sounds great! @madsnedergaard did you look into some easier ways to generate geometries?

**Comment by madsnedergaard** [comment]
Thanks for starting this :)
I've previously had fun with separating islands from main zones (#2986) where I also documented how I did it.

Let me know if you need any help on this, it might be pretty tricky as it involves modifying geojson data and I spent quite some time figuring out how it all goes together :)
