### ISSUE TITLE
Probot automerge doesn't trigger CircleCI

### ISSUE THREAD

**Issue by FelixDQ** [tmrowco/electricitymap-contrib#3021]
Example: https://github.com/tmrowco/electricitymap-contrib/pull/3017/commits/fc06707ec92c9958aa60d0565719584f6135f1bb

This makes the PRs hang because they are waiting for the status checks from CircleCI.

Edit: The issue seems to stem from the user not having being added to CircleCI. @gwpicard has the same issue when making commits, but it was fixed by logging into CircleCI and giving it access. I wonder if it's possible to also add Probot. It might also be possible to change some settings in CircleCI to run pipelines from all users.

### Workaround
Update branches manually and use the built-in auto merge from Github instead

cc @skovhus

**Comment by madsnedergaard** [comment]
Should we consider moving from CircleCI to Github Actions? It's a bigger task, so we should consider if it's worth it.

**Comment by skovhus** [comment]
> Should we consider moving from CircleCI to Github Actions? It's a bigger task, so we should consider if it's worth it.

What the pros and cons? 🤔

**Comment by FelixDQ** [comment]
It works now :-)
![image](https://user-images.githubusercontent.com/12124251/112330513-661d4f00-8cb8-11eb-8c08-013d2d93a52c.png)
This was the setting that we needed to change
