### ISSUE TITLE
Properly reflect Swedish areas SE1-4

### ISSUE THREAD

**Issue by emilplan** [tmrowco/electricitymap-contrib#3033]
Hi!
I would be very cool to see the actual areas of Sweden SE1 through 4 since they are vastly different in both generation and consumption. 

You don't use entsoe.eu for Sweden for a good reason I guess. One would think that if both Denmark and Norway is using this successfully why not Sweden? 

Sweden is reported to use svk.se, they of course are aware of the 4 areas and the transmission between them. 

Just a friendly suggestion, love the service!

Thanks

**Comment by madsnedergaard** [comment]
Hey @emilplan, thanks for the suggestion. We would love to do that, but there's some data quality issues which means we can't do it right now.

We're tracking progress of the issue in https://github.com/tmrowco/electricitymap-contrib/issues/1397, so I'll close this issue to keep information gathered in one place :)
