### ISSUE TITLE
Suggested changes to the Wiki

### ISSUE THREAD

**Issue by srinathjayaraman** [tmrowco/electricitymap-contrib#3043]
I am part of a group of CS masters students who are currently pursuing a course on Software Architecture and selected electricitymap as our open source project of choice to study and hopefully contribute to. However, while we were attempting to setup the project in our local environments, we ran into a number of problems even though we followed the Wiki on the master repository. 

Technical specifications of **one of the machines** that was used to setup locally:
- Operating System: Windows 10 Home (x64) Version 2009 (build 19042.867)
- CPU: AMD Ryzen 5 3500U with Radeon Vega Mobile Graphics
- RAM: 6 GB Usable Installed Memory
- IDE: Pycharm Community Edition 2020.3.3

**Note:** While the people in our group used different machines, the fixes/workarounds listed below worked for all of us. The IDE and OS were the same - Pycharm Community Edition 2020.3.3 running on Windows 10

What follows is a list of problems we faced and how we were able to solve them and setup the project successfully on our local machines.

When we ran the ```poetry install -E parsers```  command, the following errors popped up for ```opencv-python``` (Note: we had already installed ```Cython``` at this point):

![image](https://user-images.githubusercontent.com/11828799/111084031-d08ffb80-8510-11eb-924a-1ae8f0384959.png)
![image](https://user-images.githubusercontent.com/11828799/111084019-c7069380-8510-11eb-8bac-9910a4bf5252.png)

After a lot of Google-fu and Stack Over Flow searches we finally figured out that ```cytoolz``` was the issue. But when we tried to install ```cytoolz```, we ran into this: 

![image](https://user-images.githubusercontent.com/11828799/111084126-2f557500-8511-11eb-9d38-7990cdec260b.png)
![image](https://user-images.githubusercontent.com/11828799/111084129-341a2900-8511-11eb-971e-79d37a471a71.png)

Essentially, both ```wheels``` and ```setup.py``` were failing with the same error - and yes we had already installed MicroSoft C++! 

Upon reaching out to the slack channel, it was recommended that we use python 3.6.x instead of 3.9.x (which was the latest version of python as of the time of opening this issue). We performed the following steps and the poetry issues were finally fixed!

1. Delete the local repository permanently (on Windows this is ```Shift``` + ```Delete```).
2. Install python 3.6.8 from python.org - this was the **last** feature release for python 3.6.x. Every release of 3.6.x after this was a security update.
3. Clone the electricitymap repo from github into pycharm again (do a fresh clone basically).
4. Ensure that Python 3.6 is the interpreter - **this step is crucial**. [Click here for a quick tutorial.](https://www.jetbrains.com/help/pycharm/configuring-python-interpreter.html#add_new_project_interpreter)
5. Make sure the clone is inside a virtual environment. Pycharm IDE lets you do this via GUI when you configure it to use python 3.6 as the interpreter - [click here for a quick tutorial](https://www.jetbrains.com/help/pycharm/creating-virtual-environment.html).
6. Check the version of poetry that you have installed. The latest version as of March 14 2021 was 1.1.5 and that is the recommended version for electricitymap.
7. If you do not have the latest version of poetry, run the ```poetry self update``` command. You can do this in the IDE itself.
8. Reinstall the basic python packages for version 3.6.x (wheel, numpy, pandas).
9. Run the ```poetry install -E parsers``` command again - it should work now!

Clarification on step 8 - these packages were already installed but on python **3.9.x**, not **3.6.x** which is the recommended version on the GitHub page for electricitymap. Pycharm shows a list of all packages installed when you select a specific version of python as the interpreter, which is how we realized we would have to reinstall the packages for python 3.6.x

Once this saga was over, we ran into some minor trouble while trying to run the parsers themselves. When we attempted to run the ```python test_parser.py FR price``` command as stated in the Wiki, this popped up:

![image](https://user-images.githubusercontent.com/11828799/111084784-71cc8100-8514-11eb-94bf-2bb8e0a3256f.png)

**Here is the offending code from the file ```test_parser.py```:**
```from electricitymap.contrib.parsers.lib.parsers import PARSER_KEY_TO_DICT```

**Here is what was recommended by the developers as a workaround:**
```from parsers.lib.parsers import PARSER_KEY_TO_DICT```

Apparently this problem is caused by the way Windows handles symlinks. The developers are currently working on a fix, but no timeline was provided at the time of opening this issue.

**Comment by skovhus** [comment]
Thank you so much for your thorough documentation here – we really appreciate it. 

I would love to improve our documentation so this shouldn't happen for a future contributor.

I see a few different topics:
- IDE setup
- Python environment
- usage of symlinks

**IDE setup**

I believe this is outside the scope of our wiki/project to document how to set up various IDEs. 

**Python environment**

It seems we need to make this more clear. Any idea on how to make it more clear here https://github.com/tmrowco/electricitymap-contrib/wiki/Set-up-local-environment ?

The best solution is likely to change https://github.com/tmrowco/electricitymap-contrib/blob/master/pyproject.toml#L12 to be more specific on the Python version. This would mean that it would fail when you tried to install the project.

As we do support Python 3.7 internally, we should change this to `python = '>= 3.6, < 3.8'`

**Usage of symlinks**

The symlinks were introduced to do the least possible changes once we migrated to Poetry. https://github.com/tmrowco/electricitymap-contrib/pull/2971

To avoid them we would need to move some code around. Note that both the usage of symlink and Python environment could be fixed by having a Dockerfile with the setup. Unfortunately this usually doesn't provide the best experience in terms of IDE.

> Once this saga was over, we ran into some minor trouble while trying to run the parsers themselves. When we attempted to run the python test_parser.py FR price command as stated in the Wiki, this popped up:

Does `poetry run python test_parser.py FR price` work?

**Comment by srinathjayaraman** [comment]
> I believe this is outside the scope of our wiki/project to document how to set up various IDEs.

Yes I understand that, it's why I included information about what IDE we used so if people need to perform a similar function (like setting up virtual env) in their own IDE's they can google it. It's really in there to provide as much clarity as possible on what caused our issues.

> As we do support Python 3.7 internally, we should change this to python = '>= 3.6, < 3.8'

Should I change the ```pyproject.toml``` and open a PR to commit to main?

> Does ```poetry run python test_parser.py``` FR price work?

I will try this and provide an update!

**Comment by skovhus** [comment]
> Should I change the pyproject.toml file locally and open a PR to commit to main?

That would be great! Thanks.

**Comment by srinathjayaraman** [comment]
> 
> 
> > Should I change the pyproject.toml file locally and open a PR to commit to main?
> 
> That would be great! Thanks.

Update 1: ```poetry run python test_parser.py FR price``` throws the same error in ```test_parser.py```.  The only way to get it working for now is to replace ```from electricitymap.contrib.parsers.lib.parsers import PARSER_KEY_TO_DICT``` with ```from parsers.lib.parsers import PARSER_KEY_TO_DICT``` as per the original suggestion from the devs.

Update 2: I have modified ```pyproject.toml``` file to say ```python = '>= 3.6, < 3.8'``` in my local setup. I did not delete the previous line, I commented it out. After modifying the ```pyproject.toml``` file I ran the ```python test_parser.py FR price``` command again and it ran without issue. Let me know if there are other tests you need me to run! The PR for this is [here.](https://github.com/tmrowco/electricitymap-contrib/pull/3048)

**Comment by srinathjayaraman** [comment]
> 
> 
> > Should I change the pyproject.toml file locally and open a PR to commit to main?
> 
> That would be great! Thanks.

Kenneth, can the wiki be updated with the info I've provided in this issue?

**Comment by skovhus** [comment]
Which information are you missing? 

The part about `from parsers.lib.parsers import PARSER_KEY_TO_DICT` should be fixed by updating the `test_parsers.py` file. And in the future by getting rid of the symlink.

**Comment by srinathjayaraman** [comment]
Ah correct, sorry I miscalculated. Since the permanent fix for the ```test_parsers.py``` file is to get rid of symlinks, is it alright to close this issue, or would you prefer that it be kept open for tracking purposes?

**Comment by skovhus** [comment]
Let us close. :)
