### ISSUE TITLE
Australian Data missing Wind and Solar generators

### ISSUE THREAD

**Issue by jstabler1** [tmrowco/electricitymap-contrib#3045]
Hi. Your representation of the Australian energy market is missing the generation by Solar generators. This can contribute upto 75% of the local demand in regions like South Australia and the asset class was the third highest contributor of energy during Jan-Feb 2021 after Black and Brown Coal. 

Comparative free data source: https://opennem.org.au/energy/nem/?range=1y&interval=1M

Josh

**Comment by corradio** [comment]
Thanks for reporting! We're already working on it at https://github.com/tmrowco/electricitymap-contrib/pull/2860
Hopefully we will get it merged soon.

Closing as it is a duplicate.
