### ISSUE TITLE
fix Italy-South

### ISSUE THREAD

**Issue by KabelWlan** [tmrowco/electricitymap-contrib#3049]
Hi everyone

Since Italy-South is down for quite a while I did some reseach. I found out that Italy-South contains of the bidding zones IT-South and IT-Rossano. Entsoe still reports data for IT-South but not for IT-Rossano. I reached out to Entsoe to find out more and I got the following response:

_Thank you for your message. 
Indeed, Italy reviews and changes their bidding zones every 2 year. The publication of IT-Rossano stoped, the publication of IT-Calabria started and IT-South was reduced on the 31.12.2020._ 

This means that we need to replace IT-Rossano with IT-Calabria in order to get it displayed on the map again.

Sadly I don't have the required knowledge and skills to do those changes. Could anyone else do them?

**Comment by Kongkille** [comment]
Hi, @KabelWlan thanks for the research on this. Tried to make a PR. I think it makes sense
