### ISSUE TITLE
Western Australia displays too much solar generation

### ISSUE THREAD

**Issue by KabelWlan** [tmrowco/electricitymap-contrib#3070]
Hi everyone

I'm very excited that the OpenNEM praser finally got merged.

While looking at the data I noticed that Western Australia reports too much solar. ElectricityMap shows a generation of about 3.7 GWs while OpenNEM reports 1.3 GWs. 
![WA solar](https://user-images.githubusercontent.com/49598085/112531039-66e0de80-8da7-11eb-8d2a-b7aea25378f6.png)
Coal, gas and wind generation are reported correctly. Is there an explanation for this deviation in solar?

Also there are no solar installed capacities shown (in whole Australia) even though they're listed in the zones file.

**Comment by jarek** [comment]
https://opennem.org.au/energy/wem/?range=1d&interval=30m data for solar shows values that look to be almost exactly half as what we get in https://data.dev.opennem.org.au/v3/clients/em/latest.json (to hopefully save you searching, WA solar rooftop is datapoint 56 right now). For example right now yesterday's peak solar rooftop production in latest.json is 2419 while their website shows 1214.

Both latest.json and the website say it's in MW, but maybe something is actually converted into average MWh over 30 minutes interpolated to 1 hour, or something?

**Comment by corradio** [comment]
cc @simonhac @nc9 maybe you can help?

**Comment by jufemaiz** [comment]
Use https://data.opennem.org.au/v3/clients/em/latest.json

**Comment by jarek** [comment]
latest.json is the file that seems to have doubled value, though?

If nothing else, a load curve going between 7.5 GW peak (80% of it solar) and 1.8 GW trough seems an improbably large swing. And the peak consumption just happens to be at solar noon? That'd be one heck of a grid.

![wa](https://user-images.githubusercontent.com/47415/116332398-aaac7680-a79f-11eb-9039-075db43cc875.png)

(screenshot times in UTC-4)

**Comment by jufemaiz** [comment]
@jarek the above linked one with odd data is from the dev subdomain.

Step change seen in the data on electricity map prod though.

![image](https://user-images.githubusercontent.com/16481/116357415-ca937700-a83f-11eb-8f88-a42d0d7f5c7f.png)
![image](https://user-images.githubusercontent.com/16481/116357442-d41cdf00-a83f-11eb-93af-c266932885b8.png)

That said, there's definitely a disalignment between the two. At 0400Z for instance:
- opennem (1200AWST): Total 2504MW | Solar 1064MW | Wind 26.1MW | Gas 693MW | Coal 711MW | Other 10.2MW
- electricitymap: Total 5230GW | Solar 3600MW | Gas 762MW | Wind 53.7MW | Coal 809MW | Other 10.5MW

**Comment by jufemaiz** [comment]
I have no idea how it's getting these numbers ftr.

**Comment by gwpicard** [comment]
@simonhac @nc9 Any idea on what might be causing this issue here?

**Comment by simonhac** [comment]
sorry, i have to defer to @nc9.

**Comment by corradio** [comment]
I realised that the `/em/latest.json` endpoint returns *two solar time series with the same id*:

![image](https://user-images.githubusercontent.com/1655848/120596193-bac11100-c443-11eb-8c67-9b19edcaea67.png)
![image](https://user-images.githubusercontent.com/1655848/120596208-c14f8880-c443-11eb-86c1-4e7753cdea97.png)

this causes us, in the parser, to have two duplicated columns, which get added up:

![image](https://user-images.githubusercontent.com/1655848/120596026-85b4be80-c443-11eb-80e2-81cb962c42b2.png)

**Comment by corradio** [comment]
I've made a PR to remove the first of them, which seems to match the opennem data. @nc9 are you able to fix that on your end as well 🙏 ? I'm worried that we might take the wrong series.

**Comment by nc9** [comment]
I can't believe we didn't notice this on our end! Our FE was picking up the first one and rendering that, rather than combining it.

This has been fixed now and it is deployed to our dev - it'll be deployed to our prod at some point today

https://github.com/opennem/opennem/blob/master/opennem/api/export/queries.py#L351-L352

We now also enforce unique ids in stat sets!

https://github.com/opennem/opennem/blob/43495cd57d02bd004dba5c50ca972e2fedb94d48/opennem/api/stats/schema.py#L207-L225

**Comment by KabelWlan** [comment]
The solar data is correct now. However, most of the time Western Australia doesn't show up on the map. Probably because the data is often delayed, right now it's almost 8 hours. 

Also WA displays rooftop and utility solar generation. All the other Australian zones do only show utility generation. Is that intentional or is it just not completely impementet yet?

**Comment by KabelWlan** [comment]
I'll close this issue since there's a new one (#3222) covering the point with the rooftop solar.
