### ISSUE TITLE
Change to zones.json for Quebec (CA-QC)

### ISSUE THREAD

**Issue by Daniel-Rochefort** [tmrowco/electricitymap-contrib#3072]
In the file electricitymap-contrib/config/zones.json, the Quebec part should be modified (but I don't have the skills to do it by myself) :

"CA-QC": {

"_comment": "https://www.hydroquebec.com/generation/generating-stations.html", also "hydro" capacity transfer from CA-NL equals 5428 which is reserved to CA-QC by contract until 2041,
"capacity": {           
"biomass": 257,           
"gas": 411,           
"hydro": 36765,           
"nuclear": 0,           
"solar": 0,           
"wind": 3508,           
"coal": 0
  },

Thanks for your help

**Comment by madsnedergaard** [comment]
Hey @Daniel-Rochefort, thanks for reporting this (and thanks @veqtrus for executing on it in #3073), it has now been merged and should be available on the map later today :)

**Comment by Daniel-Rochefort** [comment]
Thank you very much gang! I can't wait to see the result and share it!
On my side, my contacts at Hydro-Quebec (our national electricity company) told me that the connection with open data could be made very soon ... a matter of weeks.

"Nous planchons présentement sur la mise en ligne de données ouvertes. Les premiers jeux de données devraient être mis en ligne au cours des prochaines semaines. Parmi les premières données qui seront rendues publiques de cette manière, on retrouve justement les données qui pourront permettre la mise à jour d'Electricity Map."

**Comment by madsnedergaard** [comment]
Amazing news, looking forward to seeing Quebec on the map! Keep us updated on progress if you hear more :)
