### ISSUE TITLE
Add parser for Saudi Arabia

### ISSUE THREAD

**Issue by Nawaf-Najaei** [tmrowco/electricitymap-contrib#3074]
Hi,
Please check out this data source for electricity consumption.
https://datasource.kapsarc.org/explore/dataset/electricity-consumption-by-sectors/information/?disjunctive.region&disjunctive.type_of_consumption&sort=year

Let me know if this helps or if you need more data.
thanks

**Comment by martincollignon** [comment]
Hi @Nawaf-Najaei, thanks for bringing this data to our attention. We can only use hourly data, and ideally as real-time as possible. Do you know if this is available somewhere?

**Comment by Nawaf-Najaei** [comment]
Greetings @martincollignon ,
I'm working with government entities to provide that data as soon as possible.

Regards.

**Comment by martincollignon** [comment]
Sounds great! If that is the case, here is the ideal data we need:

- As granular as possible spatially (if there are several subregions)
- As real-time as possible (and max 2 hours delayed to be colored on the map)
- Divided by production source (we use the ones shown on the tab on the map!)
- Imports and exports to other countries should also be available to compute consumption

**Comment by q--** [comment]
Related: #2357

The website mentioned there has consumption, but for a country to show up on the map at minimum total production needs to be known (or it should be possible to calculate it from consumption + imports/exports).

(I never really looked into the app I also found in that issue.)

**Comment by gwpicard** [comment]
Closing this one - feel free to reopen if/once hourly data becomes available! Thanks @Nawaf-Najaei 😄
