### ISSUE TITLE
GB reported generation occassionally doubles

### ISSUE THREAD

**Issue by q--** [tmrowco/electricitymap-contrib#3075]
When it happens, it happens for e.g. gas and nuclear but not wind.

![GB reported generation is double the actual generation](https://user-images.githubusercontent.com/2470175/112757465-1f966000-8fea-11eb-89b0-413bde119d81.png)

I've seen this happen a few times before. Not very often, maybe once every few months.

Easiest way to reject this data would be to add a check if nuclear generation is quite a bit above installed capacity.

If desirable, it should also be possible to divide everything by two to get the right numbers when this happens

**Comment by gwpicard** [comment]
Looking at our data in the backend, it does seem like it's coming straight from the parser data for both gas and nuclear as you said. We'll have to see whether we can add additional validation checks to prevent the data from being stored into our historical data if it lands outside validation criteria. Thanks for raising this one!

**Comment by gwpicard** [comment]
Closing this one as we are now tracking it internally and will require some backend tooling and changes on our end - thanks again for raising this @q-- !
