### ISSUE TITLE
Puerto Rico down, probably blocked

### ISSUE THREAD

**Issue by q--** [tmrowco/electricitymap-contrib#3078]
Puerto Rico is down.

The "runtime errors" link to Kibana doesn't work for some reason, but when I run the parser locally I get connection timeout errors. The same happened when trying to access the [web site](https://aeepr.com/) in my browser.

However, loading the website through Tor Browser succeeded without issue.

So either they're detecting the parser and then blocking all connections from my (and ElectricityMap's) IP address afterwards, or they're e.g. blocking foreign IP addresses and not targeting the parser specifically.

**Comment by madsnedergaard** [comment]
Seems like they might be blocking based on geography:

<img width="1151" alt="Screenshot 2021-04-06 at 12 07 49" src="https://user-images.githubusercontent.com/3296643/113695122-ce186000-96d0-11eb-9f45-0fe3150c2fb4.png">
(Using https://www.uptrends.com/tools/uptime)

**Comment by madsnedergaard** [comment]
Help wanted for reaching out to them and seeing if we can get the IP for the parsers server (`146.148.127.137`) whitelisted :)

**Comment by martincollignon** [comment]
Any updates @madsnedergaard ?

**Comment by martincollignon** [comment]
Reached out to comprasaee@aeepr.com

**Comment by brandongalbraith** [comment]
There might be a significant delay in getting a response as Puerto Rico is transitioning its electrical infrastructure to private management by Luma Energy. The fix is likely easy (updating Geomatch rule on load balancer or WAF at Microsoft Azure hosting aeepr.com), but parser operating on or tunneling to an IP in North America is likely quicker.

**Comment by KabelWlan** [comment]
Puerto Rico is on the map again.

**Comment by madsnedergaard** [comment]
Brilliant 🥳
