### ISSUE TITLE
US-CAL-LDWP is down

### ISSUE THREAD

**Issue by madsnedergaard** [tmrowco/electricitymap-contrib#3088]
The zone is down (and has been for a while).

The parser fails with the following error message:

```
invalid point: {'datetime': datetime.datetime(2021, 4, 11, 9, 0, tzinfo=tzlocal()), 'production': {'coal': -25, 'gas': 1082, 'hydro': 370, 'unknown': 192, 'solar': 3, 'wind': 52}, 'storage': {}, 'source': 'eia.gov', 'zoneKey': 'US-CAL-LDWP', 'schemaVersion': 3}, reason:US-CAL-LDWP: key coal has negative value -25
```

Anyone knows why coal is reported as negative? 🤔 

### Links

- [Zone on emap](https://www.electricitymap.org/zone/US-CAL-LDWP)
- [Kibana logs](https://kibana.electricitymap.org/app/kibana#/discover/10af54f0-0c4a-11e9-85c1-1d63df8c862c?_g=(refreshInterval:('$$hashKey':'object:232',display:'5%20minutes',pause:!f,section:2,value:300000),time:(from:now-24h,mode:quick,to:now))&_a=(columns:!(message,extra.key,level),filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!t,index:'96f67170-0c49-11e9-85c1-1d63df8c862c',key:level,negate:!f,params:(query:ERROR,type:phrase),type:phrase,value:ERROR),query:(match:(level:(query:ERROR,type:phrase)))),('$state':(store:appState),meta:(alias:!n,disabled:!f,index:'96f67170-0c49-11e9-85c1-1d63df8c862c',key:extra.key,negate:!f,params:(query:US-CAL-LDWP,type:phrase),type:phrase,value:US-CAL-LDWP),query:(match:(extra.key:(query:US-CAL-LDWP,type:phrase))))),index:'96f67170-0c49-11e9-85c1-1d63df8c862c',interval:auto,query:(language:lucene,query:''),sort:!('@timestamp',desc)))

**Comment by FelixDQ** [comment]
It is most likely self-consumption. We've had this happening for some zones before. The usual fix (if the value is small enough) is to set the value to 0 if it's negative.

We could do the same for this zone, but we might also want to create a general fix at some point where we always clamp the values to 0 if they are negative (within a certain threshold). Or there might be smarter ways to handle self-consumption  🤔
