### ISSUE TITLE
Belgium: no live data for a week

### ISSUE THREAD

**Issue by checkxp** [tmrowco/electricitymap-contrib#3089]
Since about a week, Belgium doesn't have anymore data showing on electricitymap.

Since it was pulling the data from ENTSO-E, and that, in my experience, this wasn't very accurate, I suggest to now use the API from Elia (the national grid operator) to get the electricity generation data. This should be more reliable, although I'm unsure how they get the data for individual Solar-PV.

Their API isn't easy to find in my opinion, but my best attempt is to recover the data from the open data platform of Elia, located here: 
https://elia.opendatasoft.com/

**Comment by martincollignon** [comment]
I've written to ENTSO-E (data provider) to hear what is the issue with Belgian data

**Comment by martincollignon** [comment]
Update: they've reached out to their data provider.

**Comment by martincollignon** [comment]
Update from ENTSOE:

> Yes, indeed, I have received a comment from the data provider on your question. They noted that although every effort is made to ensure that the data to be published is as complete as possible in near real-time, they cannot guarantee 100% availability of these data. Automatic republishing mechanisms are provided to limit the duration and impact of such temporary unavailability. The causes of interruptions can be diverse, both at the level of the source data and at the level of the application process, and the data provider cannot document them systematically. This leads to having temporary unavailability of the data on the platform. 
> 
> Please let me know if you have further comments on this matter. I could follow up on this topic with the data provider. 

I have responded by reminding them of their obligation under EU legislation, let's see how it goes.

**Comment by checkxp** [comment]
Nice, very cool that they have already reacted. Thanks for reaching out to them. I indeed think it's inacceptable that the data is unavailable for so long! That could at some point be escalted, so that they fulfill their legal obligations.

I do wonder if it would be possible (and how difficult it could be) to get the info from the API of Elia directly (as I posted earlier). I'm not sure how complex this could be though.

**Comment by martincollignon** [comment]
Could you share access to the link above? It seems like you need to login?

**Comment by kepiej** [comment]
It seems https://www.elia.be/en/grid-data provides most of the required realtime data for a fallback parser?

**Comment by Fred-3000** [comment]
It's back up. 
The Elia website is insufficient, as it only has the planned generation for sources other than wind & solar, not the actual generation. Unless I'm missing something?

**Comment by kepiej** [comment]
Historical generation data (with 15min time intervals) up to the yesterday can be downloaded as CSV or Excel files (select "Generated Energy by CIPU units" in data to export): https://www.elia.be/en/grid-data/data-download-page
The Excel files contain a breakdown according to fuel type except for solar.
ENTSOE's data is therefore more complete. :)

**Comment by Fred-3000** [comment]
Ok, somehow I have never seen that exact page, their data pages are a bit confusing to me 😅
Solar could be extracted from the specific live solar dataset if wanted. 
But as long as the outages on ENTSO-E don't happen again I don't see a reason to create a new parser.

**Comment by martincollignon** [comment]
Closing as this is solved. The data provider to ENTSOE had issues with Daylight Saving Time (this is not a joke).
