### ISSUE TITLE
Corrupted arrow 

### ISSUE THREAD

**Issue by moinmoin2** [tmrowco/electricitymap-contrib#3110]
The arrow, about how  the electricty flows are partly corrupted

**Comment by madsnedergaard** [comment]
Hi @moinmoin2, could you give some more details about what you mean?

**Comment by KabelWlan** [comment]
I don't know if moinmoin2 meant this but I noticed that there are always two arrows in the USA showing the exact same flow of electricity. One is probably from the old zones and the other from the new ones you're using right now. At least the nameing of them would indicate it. 
![arrows](https://user-images.githubusercontent.com/49598085/116603429-36074280-a92d-11eb-88ae-a780ad93c2f3.png)

**Comment by moinmoin2** [comment]
Interestingly the arrows are on my firefox browser away and also on my mobile phone. It was in the european zone

**Comment by madsnedergaard** [comment]
@moinmoin2: Looks fine in Firefox on MacOS for me, could you take a screenshot if it's still wrong?

@kabelWlan: That is indeed a bug, I'll create a new issue for that specifically :)

**Comment by martincollignon** [comment]
We're tracking this internally, thanks for reporting the bug!
