### ISSUE TITLE
Flag of Switzerland

### ISSUE THREAD

**Issue by LordFreaky** [tmrowco/electricitymap-contrib#3111]
The flag of Switzerland is a square. This should be adapted in several places.
Thank you 👍

**Comment by madsnedergaard** [comment]
Hi @LordFreaky, thanks for the pointer - but as we're using the same icon package for all country flags to ensure they look identical, we can't make individual changes to a single country right now :)

**Comment by LordFreaky** [comment]
Therefore, you should change that.

**Comment by madsnedergaard** [comment]
Unfortunately this is not something we have the resources to prioritise at the moment, but we'd be happy to accept a pull request that addresses this if you want to fix it :)

**Comment by LordFreaky** [comment]
I know too little about the matter. Nevertheless, thank you for the suggestion.

Have a nice day
