### ISSUE TITLE
Installed solar capacity sweden

### ISSUE THREAD

**Issue by Henrik575** [tmrowco/electricitymap-contrib#3112]
Could you please update Swedens istalled solar capacity to 1090 MW in accordance with:

 https://www.energimyndigheten.se/nyhetsarkiv/2021/22-000-nya-natanslutna-solcellsanlaggningar-under-2020/

Thank you.

**Comment by madsnedergaard** [comment]
Hi @Henrik575, thanks for creating this issue - I've just created #3113 which will update the capacity :)

**Comment by Henrik575** [comment]
I am frequently bugging SVK to report live data to ENTSOE and also publish it on their website. They are concidering the question.

Meanwhile historic data han be found but I dont know if it han be made useful to your website (which I love by the way)

  https://mimer.svk.se/ProductionConsumption/ProductionIndex

**Comment by madsnedergaard** [comment]
Thanks for sharing (and for the kind words), we are actually already using data from SVK for the data shown on the map :)

I'll close this as the code change has been implemented, it should be available on the map within a day or two.
