### ISSUE TITLE
Oahu (Hawaii) live data unavailable

### ISSUE THREAD

**Issue by kepiej** [tmrowco/electricitymap-contrib#3116]
The website (https://www.islandpulse.org/) of the data source is live but also seems to have missing data:

![image](https://user-images.githubusercontent.com/16258942/116365055-2987ca80-a805-11eb-9c75-7fe23a53c6e2.png)

**Comment by madsnedergaard** [comment]
Hey @kepiej, thanks for finding this - not much we can do if the source is not returning proper data, but hopefully it will be back soon.

Feel free to reach out to them and let them know about it :)

**Comment by martincollignon** [comment]
No data since 15th April, I've reached out to https://blueplanetfoundation.org/contact/

**Comment by brandongalbraith** [comment]
Data for this data source is flowing again, EM showing real time mix again 👍

**Comment by madsnedergaard** [comment]
Great! 🙌
