### ISSUE TITLE
Wiki: document price and exchange methods

### ISSUE THREAD

**Issue by corradio** [tmrowco/electricitymap-contrib#3124]
The page https://github.com/tmrowco/electricitymap-contrib/wiki/Building-a-new-parser could contain a section about the price and exchange methods in parsers.
Inspiration can be found in the example parser here https://github.com/tmrowco/electricitymap-contrib/blob/master/parsers/example.py

**Comment by lorrieq** [comment]
Hey @corradio, considering the wiki files are not in the repo how do you like to review such changes?

**Comment by corradio** [comment]
> Hey @corradio, considering the wiki files are not in the repo how do you like to review such changes?

Are you able to access https://github.com/tmrowco/electricitymap-contrib/wiki? Or did you mean that you don't have access to change it?

**Comment by lorrieq** [comment]
I can access it and edit it. I was wondering if you would want to review my edits beforehand? Or you are happy for me to edit it and then make any comments afterwards?

**Comment by corradio** [comment]
@Kongkille @skovhus are you able to help orient @lorrieq ?

**Comment by skovhus** [comment]
@lorrieq we currently have no review process for the wiki. Feel free to change it and ping us here once you are done. Thanks!

**Comment by lorrieq** [comment]
Hey guys, I changed [the page](https://github.com/tmrowco/electricitymap-contrib/wiki/Building-a-new-parser) so have a look. You may want to request some edits on content or how I structured it.

Summary of edits:

- added the return format for all methods that I could see used in the config files
- `fetch_price`: description of `currency` and `price`, assuming day-ahead price is what is desired when available
- `fetch_exchange`: description of `sortedZoneKeys` and how to determine whether `netFlow` should be positive or negative
- some of the methods have no description, just the expected return format, as I'm not overly familiar with them
- nothing for `fetch_production_mix`, how does this differ to `fetch_production`

**Comment by skovhus** [comment]
@lorrieq thanks for improving this. I think this is a great iteration.
