### ISSUE TITLE
Dual exports shown for US zones

### ISSUE THREAD

**Issue by madsnedergaard** [tmrowco/electricitymap-contrib#3126]
## Description

As reported by @KabelWlan (thanks! 🙏) in #3110, we are indeed showing two similar (but naming wise different exports between same zones. See gif 👇 

### Expected behaviour

One export between two zones. Not two arrows.

### Screenshots

<img width="729" alt="Screenshot 2021-04-29 at 21 18 57" src="https://user-images.githubusercontent.com/3296643/116606145-9350c300-a930-11eb-8abe-2ff612e6b073.png">

<img width="1082" alt="Screenshot 2021-04-29 at 21 18 52" src="https://user-images.githubusercontent.com/3296643/116606152-95b31d00-a930-11eb-9b21-91d04f6b818e.png">

**Comment by FelixDQ** [comment]
This is actually due to the fact that we haven't removed the old US zones yet. It's tracked on our internal repo here: https://github.com/tmrowco/electricitymap/issues/34

Related issue: https://github.com/tmrowco/electricitymap-contrib/issues/2472

**Comment by martincollignon** [comment]
Closing as we're tracking internally and nothing can be done on the contrib side! Thanks for reporting @madsnedergaard and thanks for troubleshooting @FelixDQ !
