### ISSUE TITLE
Wrong installed capacity for wind power in Sweden

### ISSUE THREAD

**Issue by swakter** [tmrowco/electricitymap-contrib#3129]
Installed capacity for wind power in Sweden should be 10 GW (or more). Today it shows as 8.98 GW which is outdated and means the capacity factor is not correct.

Information about 10 GW is from Swedish wind energy organisation, last updated February 2021:
https://svenskvindenergi.org/wp-content/uploads/2021/02/Q4-2020-Statistics-and-forecast-Svensk-Vindenergi-2020-02-08-FINAL.pdf

**Comment by KabelWlan** [comment]
Hi @swakter 
Thanks for bringing this up. The Q1 2021 report should be released any day. Normally they release it 5-7 weeks after the end of the quarter. I‘ll change the capacity as soon as the newest data is available.
