### ISSUE TITLE
Add a "Why/About" section to the front page

### ISSUE THREAD

**Issue by Some-Other-Username** [tmrowco/electricitymap-contrib#3130]
If you stumble across the website, it is hard to understand why this project is so important.  I would suggest adding a Why/About section and link to it on the top right. Currently, the API page is the only help in figuring out how this project can be used and I assume a lot of non-technical people will never click on it. 

My suggestion would be to explain why the project is needed. To give examples where it helped to fight climate change. Talk about where you want to take it in the future and finally add a bit more "About" info.

**Comment by martincollignon** [comment]
Hi @Some-Other-Username, just so I understand better. What is unclear about the value?
- Is it why tracking real time value of carbon intensity is important?
- Is it the value of doing it open-source?
- It is the value of granularity?

**Comment by martincollignon** [comment]
Thank you a lot for this feedback, very valuable, @Some-Other-Username!

**Comment by skovhus** [comment]
We have released a new version of the website, and we would love to hear your feedback @Some-Other-Username 

Please see https://api.electricitymap.org/

I'm closing this issue for now, but we will read your comments.
