### ISSUE TITLE
API Pricing is outdated

### ISSUE THREAD

**Issue by Some-Other-Username** [tmrowco/electricitymap-contrib#3131]
The API pricing seems outdated. There are multiple issues:

1) The only tier available is "Enterprise" which makes the whole tier system seem unnecessary and outdated.
2) The FAQ Section talks about specific "Premium" prices to quote: "This means the "Premium" tier starts at 200€/month, with yearly commitment instead of 500€/month."
3) Overall given that this is an open-source project, don't you think there should also be a **limited** free tier? This way you would also give back to the open-source community.

**Comment by corradio** [comment]
Hi @Some-Other-Username ,

I'm cc'ing @Kongkille , our product manager, so he is aware about the feedback for 1 and 2.
Regarding 3, we actually have https://co2signal.com. At some point it might make sense to turn co2 signal into a limited free tier of the electricityMap API.

Olivier

**Comment by Some-Other-Username** [comment]
Thank you for the fast response. Maybe we can link to co2signal.com from the API page then?

**Comment by martincollignon** [comment]
Really good points - we're tracking this internally and will make updates soon!
We'll also find a way to link to CO2signal :)
