### ISSUE TITLE
California data source

### ISSUE THREAD

**Issue by suoko** [tmrowco/electricitymap-contrib#3137]
I found this website about CA
http://www.caiso.com/todaysoutlook/pages/supply.aspx

**Comment by jarek** [comment]
Thanks for the link! We use it in https://github.com/tmrowco/electricitymap-contrib/blob/master/parsers/US_CA.py and CAISO shows up on the map:

![us_ca](https://user-images.githubusercontent.com/47415/117550223-1fd44300-b00d-11eb-91a9-176ef4351980.png)
