### ISSUE TITLE
NordLink (DE->NO-NO2) shows 0 in Electricity Map but Statnett shows flow

### ISSUE THREAD

**Issue by jaffeldt** [tmrowco/electricitymap-contrib#3152]
Hi, please include NordLink-Cable between Norway and Germany:

https://www.statnett.no/en/for-stakeholders-in-the-power-industry/data-from-the-power-system/#nordic-power-flow

![image](https://user-images.githubusercontent.com/84115994/118077419-54048680-b3b4-11eb-8ac6-079b1474b0ce.png)

**Comment by jarek** [comment]
Thanks for reporting! Something weird is up.

Nordlink has been added in #2648 but per #2698 the exchange arrow only appears on the website when the Electricity Map server thinks the exchange actually transfers something. (See https://github.com/tmrowco/electricitymap-contrib/search?q=nordlink&type=issues for Nordlink other discussions)

We use ENTSOE for this exchange, one of the few Norway exchanges that uses ENTSOE to get the data, I wonder if there's a problem there? But ENTSOE is showing NO2->DE flow as well: https://transparency.entsoe.eu/transmission-domain/physicalFlow/show?name=&defaultValue=false&viewType=TABLE&areaType=BORDER_BZN&atch=false&dateTime.dateTime=14.05.2021+00:00|UTC|DAY&border.values=CTY|10YNO-0--------C!BZN_BZN|10YNO-2--------T_BZN_BZN|10Y1001A1001A82H&dateTime.timezone=UTC&dateTime.timezone_input=UTC

Here is what I see in ENTSOE right now:

![entsoe exchange](https://user-images.githubusercontent.com/47415/118214962-b99d5500-b43e-11eb-943d-92dfa6c4527f.png)

Here is what Electricity Map server reports, with `datetime` `2021-05-14T02:45:17.944Z`:

![em exc](https://user-images.githubusercontent.com/47415/118214898-98d4ff80-b43e-11eb-97db-bd74bf064ac9.png)

So is that last `0` in ENTSOE (for 02:15 - 02:30 UTC) messing things up? Does Statnett always submit 0 to ENTSOE before it knows the actual value?

Could we use the Statnett parser for this exchange instead?

**Comment by jarek** [comment]
Just looked again right now: ENTSOE reporting 0 on the most recent row once again

**Comment by lorrieq** [comment]
Hi @jarek, I could add a quick fix to ignore the most recent value if it's zero. If the flow actually goes to zero for an extended period of time we would not miss any data, it would just take 15 minutes longer to confirm a zero is actually a zero!

What do you think? Otherwise I'm happy to look into the Statnett parser.

**Comment by corradio** [comment]
Hello friends!
Have you tried writing to ENTSOE? Maybe they can ask the data provider.
I've personally had bad experiences with the Statnett parser as it sometimes showed a sign change (importing instead of exporting), and wasn't behaving consistently historically.

**Comment by lorrieq** [comment]
Thanks @corradio, I'll contact ENTSOE and see what they come back with

**Comment by lorrieq** [comment]
Hmmm.. I was just getting around to contacting ENTSOE and noticed the trailing zero wasn't appearing on ENTSOE and therefore the exchange was showing up on the electricitymap!

I will contact them in any case to see if they actually fixed something or if this issue could occur again.

**Comment by lorrieq** [comment]
From Entsoe: "Indeed when looking at the versioning and the different updates of the data, it is no longer initialized with 0. It seems that this issue has been solved permanently"

Ir looks like this has been corrected on their side and we can close this.

**Comment by KabelWlan** [comment]
@lorrieq Maybe you should implement your proposed fix for the value zero. In the last few days the problem seems to be back again...
