### ISSUE TITLE
Australia data » missing data, logs indicate high rates (approaching 100%) of timeouts

### ISSUE THREAD

**Issue by jufemaiz** [tmrowco/electricitymap-contrib#3153]
How it looks:

![image](https://user-images.githubusercontent.com/16481/118132402-02efa380-b443-11eb-8a8c-3672df260198.png)

Kibana logs show no major issues:

https://kibana.electricitymap.org/app/kibana#/discover/10af54f0-0c4a-11e9-85c1-1d63df8c862c?_g=(refreshInterval:('$$hashKey':'object:232',display:'5%20minutes',pause:!f,section:2,value:300000),time:(from:'2021-05-13T13:00:00.000Z',mode:absolute,to:'2021-05-13T13:30:00.000Z'))&_a=(columns:!(message,extra.key,level,_score),filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!t,index:'96f67170-0c49-11e9-85c1-1d63df8c862c',key:level,negate:!f,params:(query:ERROR,type:phrase),type:phrase,value:ERROR),query:(match:(level:(query:ERROR,type:phrase)))),('$state':(store:appState),meta:(alias:!n,disabled:!f,index:'96f67170-0c49-11e9-85c1-1d63df8c862c',key:extra.key,negate:!f,params:(query:AUS,type:phrase),type:phrase,value:AUS),query:(match:(extra.key:(query:AUS,type:phrase))))),index:'96f67170-0c49-11e9-85c1-1d63df8c862c',interval:auto,query:(language:lucene,query:''),sort:!('@timestamp',desc))

**Comment by jarek** [comment]
I see timeout errors in Kibana now. Times in screenshot are in UTC-4

![aus err](https://user-images.githubusercontent.com/47415/118211150-ab990580-b439-11eb-8cdf-e13b9ef48c68.png)

**Comment by jufemaiz** [comment]
Oh bugger thanks for that!

https://kibana.electricitymap.org/app/kibana#/discover/10af54f0-0c4a-11e9-85c1-1d63df8c862c?_g=(refreshInterval:('$$hashKey':'object:232',display:'5%20minutes',pause:!f,section:2,value:300000),time:(from:'2021-03-31T13:00:00.000Z',mode:absolute,to:'2021-05-31T13:59:59.999Z'))&_a=(columns:!(message,extra.key,level,_score),filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!f,index:'96f67170-0c49-11e9-85c1-1d63df8c862c',key:extra.key,negate:!f,params:(query:AUS,type:phrase),type:phrase,value:AUS),query:(match:(extra.key:(query:AUS,type:phrase)))),('$state':(store:appState),meta:(alias:!n,disabled:!t,index:'96f67170-0c49-11e9-85c1-1d63df8c862c',key:level,negate:!f,params:!(ERROR),type:phrases,value:ERROR),query:(bool:(minimum_should_match:1,should:!((match_phrase:(level:ERROR))))))),index:'96f67170-0c49-11e9-85c1-1d63df8c862c',interval:auto,query:(language:lucene,query:'fetch_production%20AND%20-%22Setting%20small%20value%20of%22%20AND%20%22timed%20out%22'),sort:!('@timestamp',asc))

That is *a lot* of problems with fetching.

![image](https://user-images.githubusercontent.com/16481/118215020-2999f280-b4b4-11eb-9cd8-14eca874d14c.png)

**Comment by corradio** [comment]
Thanks for reporting. This is due to the way we currently execute the parsers on our infrastructure.
We have planned to upgrade our infra, but we don't have a timeline yet. @skovhus @madsnedergaard could it make sense to just increase the timeout?

**Comment by skovhus** [comment]
We are looking into monitoring this more carefully. And we could increase the overall timeout.

Note that most of the time in the OPENNEM parser seems to be spend on the `Preparing final objects` step where we sum vectors. This can likely be optimized a lot.

```
2021-05-18 14:33:50,018 INFO     __main__                       Requesting https://data.opennem.org.au/v3/clients/em/latest.json..
2021-05-18 14:33:50,023 DEBUG    urllib3.connectionpool         Starting new HTTPS connection (1): data.opennem.org.au:443
2021-05-18 14:33:51,191 DEBUG    urllib3.connectionpool         https://data.opennem.org.au:443 "GET /v3/clients/em/latest.json HTTP/1.1" 200 91695
2021-05-18 14:33:51,205 DEBUG    __main__                       Parsing JSON..
2021-05-18 14:33:51,209 DEBUG    __main__                       Filtering datasets..
2021-05-18 14:33:51,209 DEBUG    __main__                       Concatenating datasets..
2021-05-18 14:33:51,229 DEBUG    __main__                       Preparing capacities..
2021-05-18 14:33:51,232 DEBUG    __main__                       Preparing final objects based on 2023 elements..
2021-05-18 14:33:54,853 DEBUG    __main__                       Validating..
2021-05-18 14:33:54,853 WARNING  __main__                       Setting small value of oil (-0.00489) to 0.
```

**Comment by jufemaiz** [comment]
QQ do most of the parsers deal with only small datasets? If so, OPENNEM parser may need to be a different type of parser (aggregate parser).

**Comment by skovhus** [comment]
Thanks for the suggestions here. 

We have increased our internal timeout and improved our monitoring, so we should be able to respond faster to issues like this.

> If I'm reading it right, Preparing final objects took 3.5 seconds in that log. 

Relatively we spend a lot of time preparing final objects, so if our servers are overloaded this could be a slow operation.
