### ISSUE TITLE
US-SW-PNM breaks EIA parser with None hydro

### ISSUE THREAD

**Issue by KabelWlan** [tmrowco/electricitymap-contrib#3158]
US-SW-PNM does not display any data. 
I guess the problem is the negative value for solar which is reported from EIA during some time of the night. I think this is going on since a few days already because yesterday was not the only day the value for solar was negative.

![negative solar](https://user-images.githubusercontent.com/49598085/118535736-1f455600-b74b-11eb-9eed-21376a0b5938.png)

link to EIA: https://www.eia.gov/electricity/gridmonitor/dashboard/electric_overview/balancing_authority/PNM
link to the zone: https://www.electricitymap.org/zone/US-SW-PNM

**Comment by jarek** [comment]
Looks like we need to amend the parser:

https://kibana.electricitymap.org/app/kibana#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:now-4h,mode:quick,to:now))&_a=(columns:!(_source),filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!f,index:'96f67170-0c49-11e9-85c1-1d63df8c862c',key:level,negate:!f,params:(query:ERROR,type:phrase),type:phrase,value:ERROR),query:(match:(level:(query:ERROR,type:phrase))))),index:'96f67170-0c49-11e9-85c1-1d63df8c862c',interval:auto,query:(language:lucene,query:pnm),sort:!('@timestamp',desc))

```
Traceback (most recent call last):
  File "/home/projects/feeder-electricity/src/lib/fetch_data.py", line 203, in launch_parsers
    objs = res.get(timeout) or []
  File "/usr/local/lib/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value
  File "/usr/local/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/home/projects/feeder-electricity/src/lib/fetch_data.py", line 199, in <lambda>
    *keys, session, logger=public_logger, **parser_kwargs
  File "/home/src/electricitymap/contrib/parsers/EIA.py", line 421, in fetch_production_mix
    if type == 'hydro' and point['value'] < 0:
TypeError: '<' not supported between instances of 'NoneType' and 'int'
```

**Comment by jakedorne** [comment]
Hiya, am I able to pick this one up? 😄
