### ISSUE TITLE
OpenNEM parser failing due to source giving data in future

### ISSUE THREAD

**Issue by madsnedergaard** [tmrowco/electricitymap-contrib#3172]
## Description

The OpenNEM parser is consistently failing due to this error:

```
data from AUS-NSW can't be in the future, data was 2021-06-05T01:45:00+10:00, now is 2021-06-04T05:54:07.684866+00:00
```

<img width="937" alt="Screenshot 2021-06-04 at 08 19 26" src="https://user-images.githubusercontent.com/3296643/120754923-97fb2f00-c50d-11eb-8acd-8250ebb0a489.png">

Example data from source:

<img width="573" alt="Screenshot 2021-06-04 at 08 02 37" src="https://user-images.githubusercontent.com/3296643/120753361-58334800-c50b-11eb-86f0-ca421b3cedd6.png">
 
### Error log example

https://kibana.electricitymap.org/app/kibana#/doc/96f67170-0c49-11e9-85c1-1d63df8c862c/logstash-2021.06.04/doc?id=grqW1XkB8os0h3-NI09R&_g=(refreshInterval:('$$hashKey':'object:232',display:'5%20minutes',pause:!f,section:2,value:300000),time:(from:now-24h,mode:quick,to:now))

## Steps to reproduce

1. Run `poetry run test-parser AUS-NSW`

**Comment by corradio** [comment]
If I understood correctly this seems to come from the data source, given that `history.last` is a date in the future?

**Comment by skovhus** [comment]
Note that this is filtered out in our backend, so the error doesn't affect the live map. But the underlying issue of the parser returning data for the future should be investigated.

**Comment by nc9** [comment]
Thanks for the report - i'm going to dig into this today (we just released v3.7 this morning which is a major release despite the minor version number bump)

**Comment by madsnedergaard** [comment]
Happy to hear! 
Just a quick update: I couldn't replicate it yesterday, so it could be that it only happens at specific times - I will try to look at the logs again today and see if there's a pattern :)

**Comment by madsnedergaard** [comment]
It seems like this somehow fixed itself (unless you guys changed something) 😅 

For a few days, we were getting a lot of errors - but now they're gone:
<img width="563" alt="Screenshot 2021-06-08 at 10 08 47" src="https://user-images.githubusercontent.com/3296643/121147888-91d4bd80-c841-11eb-8d6a-67ab9ff1bfa3.png">
[Link to Kibana logs for above view](https://kibana.electricitymap.org/app/kibana#/discover?_g=(refreshInterval:('$$hashKey':'object:232',display:'5%20minutes',pause:!f,section:2,value:300000),time:(from:'2021-05-31T22:00:00.000Z',mode:absolute,to:'2021-06-08T21:59:59.999Z'))&_a=(columns:!(message),filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!f,index:'96f67170-0c49-11e9-85c1-1d63df8c862c',key:extra.key,negate:!f,params:!(AUS-NSW,AUS-SA,AUS-QLD,AUS-VIC),type:phrases,value:'AUS-NSW,%20AUS-SA,%20AUS-QLD,%20AUS-VIC'),query:(bool:(minimum_should_match:1,should:!((match_phrase:(extra.key:AUS-NSW)),(match_phrase:(extra.key:AUS-SA)),(match_phrase:(extra.key:AUS-QLD)),(match_phrase:(extra.key:AUS-VIC)))))),('$state':(store:appState),meta:(alias:!n,disabled:!f,index:'96f67170-0c49-11e9-85c1-1d63df8c862c',key:level,negate:!f,params:(query:ERROR,type:phrase),type:phrase,value:ERROR),query:(match:(level:(query:ERROR,type:phrase)))),('$state':(store:appState),meta:(alias:!n,disabled:!f,index:'96f67170-0c49-11e9-85c1-1d63df8c862c',key:extra.key,negate:!t,params:!(AUS-SA-%3EAUS-VIC,AUS-NSW-%3EAUS-VIC,AUS-TAS-%3EAUS-VIC,AUS-NSW-%3EAUS-QLD),type:phrases,value:'AUS-SA-%3EAUS-VIC,%20AUS-NSW-%3EAUS-VIC,%20AUS-TAS-%3EAUS-VIC,%20AUS-NSW-%3EAUS-QLD'),query:(bool:(minimum_should_match:1,should:!((match_phrase:(extra.key:AUS-SA-%3EAUS-VIC)),(match_phrase:(extra.key:AUS-NSW-%3EAUS-VIC)),(match_phrase:(extra.key:AUS-TAS-%3EAUS-VIC)),(match_phrase:(extra.key:AUS-NSW-%3EAUS-QLD))))))),index:'96f67170-0c49-11e9-85c1-1d63df8c862c',interval:auto,query:(language:lucene,query:'message:%22can!'t%20be%20in%20the%20future%22'),sort:!('@timestamp',desc)))

**Comment by nc9** [comment]
@madsnedergaard I did! it was related to another issue with parsing all the different timezones, current server time (UTC) and network time *phew*

Sorry about the delay in getting to this again - been a busy week here where we released all of our major new features!

**Comment by madsnedergaard** [comment]
Haha fair, and thanks for looking into it! 😄 

Also congrats on the new release - it's really impressive that you now have data all the way back to 1998(!) and the stripes visualisation page is super cool too(!) 😎

**Comment by nc9** [comment]
@madsnedergaard thanks! we're pretty excited because we have the base in place now to do a lot more - especially with user-contributed data + content to maintain the index of stations
