### ISSUE TITLE
US-CAL-CISO down

### ISSUE THREAD

**Issue by KabelWlan** [tmrowco/electricitymap-contrib#3183]
US-CAL-CISO is down for some time already. I don't know much about the code and how to code but I noticed that I don't have access to the CISOs website from Switzerland. Tested it with an VPN to the USA and it worked. 

Using https://www.uptrends.com/tools/uptime I found out that the website is blocked for some locations but only a few ones like Italy, Belgium or Austria. 

What do you guys think? Could that be the problem?

**Comment by chalg** [comment]
Why would the website be blocked? Do we have to just wait?

**Comment by skovhus** [comment]
I've contacted the California ISO team. 🤞

**Comment by chalg** [comment]
I sincerely hope this is not a deliberate blockage. The energy transition in California is facing serious head winds and electricity sector emissions are increasing based on ElectricityMap data.
![cie_california_season_diag](https://user-images.githubusercontent.com/26208482/123492876-1dca5000-d65e-11eb-8a11-d57d8ee444d9.png)

**Comment by chalg** [comment]
Any udpate from the California ISO team?

**Comment by skovhus** [comment]
> Any update from the California ISO team?

Unfortunately not.

**Comment by FelixDQ** [comment]
An alternative here is to switch the data source to EIA. The downside being that EIA isn't real-time (up to ~30 hours lag), so it won't be colored on the map

**Comment by chalg** [comment]
Would it not be possible to run the existing scripts from another country that is not blocked? Or would this create too much of an adminstrative burden?

**Comment by chalg** [comment]
Update: A friend of a friend mentioned the below: “apparently they block when a site is scraping too much (bandwidth issue), maybe that’s it. My PGE CAISO person said use the Contact us page on http://CAISO.com, there are two numbers under System access or technical issues”
Would it be worth negotiating with them to unblock ElectricityMap with a lower scrape rate? I'm not sure how often the current one is, but even every 30 or 60 mins would be better than nothing?

**Comment by madsnedergaard** [comment]
> Update: A friend of a friend mentioned the below: “apparently they block when a site is scraping too much (bandwidth issue), maybe that’s it. My PGE CAISO person said use the Contact us page on http://CAISO.com, there are two numbers under System access or technical issues”
> Would it be worth negotiating with them to unblock ElectricityMap with a lower scrape rate? I'm not sure how often the current one is, but even every 30 or 60 mins would be better than nothing?

Thanks for the update.

As far as I can tell, the issue is not our server/IP, but that they blocked all access from specific countries :)

**Comment by chalg** [comment]
Yes agree, which is why it might be worth asking what their concern is. If it is related to site scraping using too much bandwidth, then we could negotiate lowering the cadence for the script being run? If it is just related to their escalating emissions and they don't want bad publicity, there is not much we can do. If I wanted to run this on my home computer in Australia (not blocked), which scripts would I require?

**Comment by jarek** [comment]
> If I wanted to run this on my home computer in Australia (not blocked), which scripts would I require?

https://github.com/tmrowco/electricitymap-contrib/blob/master/parsers/US_CA.py

See first two sections of https://github.com/tmrowco/electricitymap-contrib/wiki/Set-up-local-environment for some information on how to run locally.

**Comment by steren** [comment]
Are all parsers in a single service? If so, maybe it could be split in order to be deployed in various regions?

What platform is used to host the parsers?

**Comment by madsnedergaard** [comment]
> Are all parsers in a single service? If so, maybe it could be split in order to be deployed in various regions?
> 
> What platform is used to host the parsers?

Yes, currently the parsers are running on the same Compute Engine, but we want to migrate to Cloud Run services across multiple regions as soon as we have time/capacity to work on it :)

**Comment by jarek** [comment]
If we want CAISO back with least effort and they're not willing to unblock Belgium, another idea could be for someone with a machine/VPS in a non-blocked location to host a really basic proxy of the data file, and we change the URL that the parser accessses

**Comment by chalg** [comment]
> > If I wanted to run this on my home computer in Australia (not blocked), which scripts would I require?
> 
> https://github.com/tmrowco/electricitymap-contrib/blob/master/parsers/US_CA.py
> 
> See first two sections of https://github.com/tmrowco/electricitymap-contrib/wiki/Set-up-local-environment for some information on how to run locally.

I was able to run this on my local machine. Out of interest, which script/s take this JSON output and calculate the carbon intensity values (gCO2eq/kWh)?

**Comment by steren** [comment]
> Yes, currently the parsers are running on the same Compute Engine, but we want to migrate to Cloud Run services across multiple regions as soon as we have time/capacity to work on it :)

While a migration to Cloud Run could require some refactoring, running the CAISO parsers on a different VM in a different region (US) could mitigate the country-blocking issue.

Alternatively, as a short term fix, we could deploy a simple service on Cloud Run  in a US region that would simply relay the output of http://www.caiso.com/outlook/SP/fuelsource.csv on every request. I can write this code if you'd like.

**Comment by steren** [comment]
I wrote [this simple go server](https://github.com/steren/simple-get-server) that can be configured via an env var to fetch any `URL` and can be deployed to Cloud Run.

I configured and deployed it in `us-west1` in a test GCP project of mine, and it seems to work: https://caiso-electricity-production-proxy-n2k6p2rf7a-uw.a.run.app. 

If you'd like to use this workaround, please deploy the service in ElectricityMap's GCP project, do not use the URL I shared above.

**Comment by madsnedergaard** [comment]
> I wrote [this simple go server](https://github.com/steren/simple-get-server) that can be configured via an env var to fetch any `URL` and can be deployed to Cloud Run.
> 
> I configured and deployed it in `us-west1` in a test GCP project of mine, and it seems to work: [caiso-electricity-production-proxy-n2k6p2rf7a-uw.a.run.app](https://caiso-electricity-production-proxy-n2k6p2rf7a-uw.a.run.app).
> 
> If you'd like to use this workaround, please deploy the service in ElectricityMap's GCP project, do not use the URL I shared above.

Nice, this is probably the best workaround for now! I'll deploy the proxy and update the parser to use it! 👌

**Comment by madsnedergaard** [comment]
Aaand it's back up! Thanks for the help on this, everyone! 🙌 

<img width="915" alt="Screenshot 2021-07-19 at 16 12 34" src="https://user-images.githubusercontent.com/3296643/126173981-da69e74e-e861-404c-a9b3-5b27f8f0c309.png">
