### ISSUE TITLE
CA_AB website updated so need to update parser

### ISSUE THREAD

**Issue by jasonrwang** [tmrowco/electricitymap-contrib#3197]
The parser in https://github.com/tmrowco/electricitymap-contrib/blob/master/parsers/CA_AB.py needs to be updated. 

As per https://aeso.ca/market/market-updates/2021/new-fuel-type-additions-to-energy-trading-system-ets-reports/:

> * New categories, ‘Dual Fuel’, ‘Solar’, and ‘Energy Storage’ will be added as fuel types with their associated assets.
>  * New rows for the above fuel types will be added to the ‘GENERATION’ table at the top of the report.
>   * A new subcategory, ‘Gas Fired Steam’ will be added under the ‘Gas’ fuel type category.
 >  * The layout of the fuel type categories will be reorganized to improve readability.

I'm happy to take a crack at this, so feel free to assign to me. Just logging here for the record!

**Comment by brandongalbraith** [comment]
Check out https://github.com/tmrowco/electricitymap-contrib/pull/3189 for an in progress branch to update this parser.

**Comment by jasonrwang** [comment]
My apologies - I searched for a duplicate but didn't see it. Closing this!
