### ISSUE TITLE
Swedish regions

### ISSUE THREAD

**Issue by jollyhopp** [tmrowco/electricitymap-contrib#3198]
Is there any possibility to show the energy production/consumption to Swedens 4 bidding areas SE1,2,3,4?

Great work!

**Comment by skovhus** [comment]
Thanks for reaching out!

We have been in touch with SVK and we believe there is a decent chance they will release the data through ENTSOE soonish (which we use as our data provider for Sweden). Feel free to reach out to them directly if you want to hear a status on this.

I'm closing this in favor of https://github.com/tmrowco/electricitymap-contrib/issues/1397
