### ISSUE TITLE
NordLink connecting Norway and Germany

### ISSUE THREAD

**Issue by tschmidt123** [tmrowco/electricitymap-contrib#3200]
Hi EM Team,

I just wonder if you would have the chance to include the NordLink between Norway and Germany into your great map.
https://www.tennet.eu/de/strommarkt/transparenz/transparenz-deutschland/netzkennzahlen/zaehlwerte-der-lastfluesse-norwegen/

Thanks for your great job!

Kind regards,
Thomas

**Comment by jarek** [comment]
Hello! We do have NordLink, but per https://www.statnett.no/en/for-stakeholders-in-the-power-industry/data-from-the-power-system/#nordic-power-flow there is currently 0 flow. The exchange icon only appears when there is some flow.

There used to be a bug somewhere on data provider side (https://github.com/tmrowco/electricitymap-contrib/issues/3152) but it doesn't seem to be the case right now.
