### ISSUE TITLE
US-CENT-SWPP down

### ISSUE THREAD

**Issue by KabelWlan** [tmrowco/electricitymap-contrib#3212]
US-CENT-SWPP is down now too. The website is blocked outside of North America and South Corea according to Uptrends. I hope blocking will not become common for utilities to hide the power generation mix to people outside their country.

**Comment by jarek** [comment]
Seems more likely they're trying to apply security-by-obscurity - blocking non-American IP addresses will definitely deter evil foreign cyber hackers who would never just get a VPS or VPN...

**Comment by KabelWlan** [comment]
Seems to work again. I hope this is solved otherwise I‘d just reopen the issue.
