### ISSUE TITLE
CA-QC data is now available!

### ISSUE THREAD

**Issue by bouchecl** [tmrowco/electricitymap-contrib#3218]
Hydro-Québec has finally released a JSON file with the breakdown of generation in their balancing area by source. Data is updated hourly.
https://www.hydroquebec.com/data/documents-donnees/donnees-ouvertes/json/production.json

Although the fields are in French, the utility provides some documentation in English.
https://www.hydroquebec.com/documents-data/open-data/electricity-generation-quebec/

**Comment by jarek** [comment]
@pjakobsen commented yesterday in https://github.com/tmrowco/electricitymap-contrib/issues/1521 that he will try to create a parser, I assume from this data

**Comment by bouchecl** [comment]
>This is 6 hours :/. It would refer to a 411MW gas turbine https://en.wikipedia.org/wiki/Gentilly_Nuclear_Generating_Station#Gentilly-2 Maybe it doesn't run very frequently?

Bécancour is a combustion turbine. It's rarely used as a peaker, mostly in winter.

> Not sure how to classify those - might be good if someone can dig into statistical historical data if any is available, to see if any of these categories prevail. Electricity Map doesn't currently have a category for "biogas", we'd have to check what exactly that consists of.

Biogas = Landfill waste. It's a reference to is a 4.8 MW cogen unit running in Montreal http://eolectric.com/en/news/2017-10-16

**Comment by jarek** [comment]
> Biogas = Landfill. It's a reference to a 4.8 MW cogen unit running in Montreal http://eolectric.com/en/news/2017-10-16

Ah thanks! 4.8 MW isn't all that large compared to the ~500 MW total values being reported in the "other renewable" field (and certainly not large compared to the ~20 GW hydro generation).

Do you know roughly how much of "other renewable" is biomass and how much is independent hydro?

If we can't figure it out, or if hydro is not a large part of it, we can probably just use Electricity Map's default biomass value of 230 g CO2eq/kWh for this category. Hydro's CO2eq intensity is a lot lower so if anything it would only improve the total, while the biogas will be a tiny part of the total, so just assuming the biomass value of 230 is a decent approximation.

**Comment by bouchecl** [comment]
> Do you know roughly how much of "other renewable" is biomass and how much is independent hydro?

According to the most recent update to the 2020-2029 Supply plan http://publicsde.regie-energie.qc.ca/projets/529/DocPrj/R-4110-2019-B-0114-Demande-Piece-2021_02_25.pdf, 346 MW of it from 23 plants, is biomass, including the landfill one in Montreal and a few others,

**Comment by madsnedergaard** [comment]
Yeah, it's awesome! 🥳 
I think going with the default biomass value is fine for now, given that the amount is so low compared to hydro :)

> Would Electricity Map backend deal correctly if we first submit 0 for gas, as in the data file, and then provide a value later? Or do we have to submit a null when it's 0, because we don't know if it's actually 0 or not provided yet?

Ideally it should only be `0` if the production is actually `0`, so in this case it would be better to set it to `NULL` and then we can update the values when doing backfills later on.

**Comment by pjakobsen** [comment]
Part of the data for Quebec is available.  Cross-border exchange is missing.  It is possible to infer this from other regions.  This is beyond writing a simple parser, as the Quebec parser would depend on several other parsers being available and working.

**Comment by jarek** [comment]
The following border exchanges are available from other regions and already implemented:
- New Brunswick
- Ontario
- New York
- New England (NEISO) 

The major missing one appears to be Labrador, particularly given that energy from the 5.5 GW Churchill Falls station is almost entirely sent to Hydro-Québec. Unless we know that Churchill Falls generation is already included in the Quebec figures?

**Comment by christbelanger** [comment]
For Labrador, the portion of Churchill Falls that is under long-term contract with Hydro-Quebec is included in the JSON file (production.json).

For the others 4 regions, like already said, data is already available. Do we still have to fetch them from the same sources to include them in the parser ?

**Comment by jarek** [comment]
No, it's fine. The Quebec parser will return the generation taking place in Quebec (and Churchill Falls, which per this information is functionally Quebec for our purposes), and the other parsers provide the exchanges, then the Electricity Map backend puts it together.

![qc exchange](https://user-images.githubusercontent.com/47415/126500089-9ef51329-706a-44da-9c41-173b142ef1b8.png)

When we have live data for Quebec, the 27 g CO2eq/kWh figure (currently coming from yearly averages) will be replaced with number calculated from live generation.

**Comment by pjakobsen** [comment]
> Here's a summary of the Available capacity mix for 2020-2021
> Hydro: 40,211
> Thermal: 436
> Biomass: 374
> Wind:: 3,772
> PV: 10
> Total: 44,803

I'm using these numbers to fill out the zones.json for CA_QC parser.  What does PV stand for?   PhotoVoltaic?  Should I put "photovoltaic" in the zones.json, or "solar".   

Thanks again for helping out, I'm really a newbie when it comes to this type of data!  👍

**Comment by bouchecl** [comment]
> I'm using these numbers to fill out the zones.json for CA_QC parser. What does PV stand for? PhotoVoltaic? Should I put "photovoltaic" in the zones.json, or "solar".

Yes, PV stands for photovoltaic. As for your second question the CA-ON parser uses the word "solar".

**Comment by pjakobsen** [comment]
Got it.   In the [Quebec source](https://www.hydroquebec.com/data/documents-donnees/donnees-ouvertes/json/demande.json") I'm using, its called "solaire".

**Comment by pjakobsen** [comment]
This may seem like splitting hairs, but I feel it's politically expedient to change  "timezone": "America/Toronto", to     "timezone": "America/Montreal" in zones.json.  I checked to ensure both are supported by Python 3.   Let me know if this may cause a problem.

**Comment by pjakobsen** [comment]
Regarding the bounding boxes, why the long floats?  Isn't it sufficient to do something like:

`  "bounding_box": [
    [
      -79.76,
      44.99
    ],
    [
      -57.10,
       62.59
    ]
  ]`

**Comment by madsnedergaard** [comment]
> Regarding the bounding boxes, why the long floats? Isn't it sufficient to do something like:
> 
> ` "bounding_box": [ [ -79.76, 44.99 ], [ -57.10, 62.59 ] ]`

Perhaps - the coordinates comes from the [NACIS - natural earth](https://nacis.org/initiatives/natural-earth/) project
(in [generate-geometries.js](https://github.com/tmrowco/electricitymap-contrib/blob/master/web/generate-geometries.js)), and I think we'd rather use it as is to stay as close to the source as possible.

If we really wanted to reduce the amount of decimals, someone could change the script and manually inspect and verify every single zone to ensure it doesn't change anything - but sounds like a lot of work for not a lot of benefits in my opinion 😅 

How is the parser going, did you get `poetry run test` to work or do you need any help? :)

**Comment by pjakobsen** [comment]
Hi Mads, thanks for asking.   I plan to wrap up the project this weekend. 

`Ran 78 tests in 2.759s

FAILED (errors=4)
FAILED: python -u -m unittest discover parsers/test`

These 4 errors are all related to `FileNotFoundError: [Errno 2] No such file or directory: 'tesseract': 'tesseract'`:  

`======================================================================
ERROR: test_ignore_data_older_than_one_hour (test_SG.TestSolar)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/greendoor/.pyenv/versions/3.7.11/envs/electricity-map3.7/lib/python3.7/site-packages/freezegun/api.py", line 735, in wrapper
    result = func(*args, **kwargs)
  File "/Users/greendoor/projects/electricitymap-contrib/parsers/test/test_SG.py", line 37, in test_ignore_data_older_than_one_hour
    power = SG.get_solar(self.session, logger=self.logger)
  File "/Users/greendoor/projects/electricitymap-contrib/parsers/SG.py", line 76, in get_solar
    text = image_to_string(black_white, lang='eng')
  File "/Users/greendoor/.pyenv/versions/3.7.11/envs/electricity-map3.7/lib/python3.7/site-packages/pytesseract/pytesseract.py", line 193, in image_to_string
    return run_and_get_output(image, 'txt', lang, config, nice)
  File "/Users/greendoor/.pyenv/versions/3.7.11/envs/electricity-map3.7/lib/python3.7/site-packages/pytesseract/pytesseract.py", line 140, in run_and_get_output
    run_tesseract(**kwargs)
  File "/Users/greendoor/.pyenv/versions/3.7.11/envs/electricity-map3.7/lib/python3.7/site-packages/pytesseract/pytesseract.py", line 111, in run_tesseract
    proc = subprocess.Popen(command, stderr=subprocess.PIPE)
  File "/Users/greendoor/.pyenv/versions/3.7.11/lib/python3.7/subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "/Users/greendoor/.pyenv/versions/3.7.11/lib/python3.7/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'tesseract': 'tesseract'`

**Comment by pjakobsen** [comment]
To submit my parser, should I use a fork and issue a pull request or push directly from a clone of https://github.com/tmrowco/electricitymap-contrib ?  Also, it seems that many parsers do not have a fetch_price method. What determines whether the parser passes or fails  say `poetry run test-parser CA-QC`?  When I run various tests for different provinces, I see somewhat different json being produces from parser to parser.

**Comment by madsnedergaard** [comment]
> To submit my parser, should I use a fork and issue a pull request or push directly from a clone of [tmrowco/electricitymap-contrib](https://github.com/tmrowco/electricitymap-contrib) ?

Fork and pull request is the way to go :)
Commit your changes to a new branch and push, then go to this repo and it should show you this:

<img width="803" alt="Screenshot 2021-07-27 at 08 56 33" src="https://user-images.githubusercontent.com/3296643/127109711-cf534175-61e4-4aeb-be42-2ebaba99c250.png">

>  Also, it seems that many parsers do not have a fetch_price method. What determines whether the parser passes or fails say `poetry run test-parser CA-QC`? 
> When I run various tests for different provinces, I see somewhat different json being produces from parser to parser.

Production is the most important, everything else depends on what data is available from the source - for some we just don't have price, etc., so that's why the output is different.

But if you create the PR then I can checkout and test it 👌

**Comment by pjakobsen** [comment]
Thanks Mads.   I'm stuck on fetch_price and fetch_exchanges, simply due to a lack of electricity domain knowledge about how these things work.  I think I'll just push what I have, and then learn from any subsequent changes that you and others will surely make.  :)

**Comment by martincollignon** [comment]
@bouchecl it sounds like you had ideas on how to quantify the "Other mix". Could you help us out?

**Comment by bouchecl** [comment]
> @bouchecl it sounds like you had ideas on how to quantify the "Other " energy mix. Could you help us out?

Thanks for asking. As I said above, Hydro-Québec says the "autres" category in its source (production.json) is "Other renewables: Sum of the estimated output from facilities belonging to independent power producers using different sources (biomass, biogas or hydropower), from whom Hydro‑Québec can purchase some or all of the output." Rather than putting this category in "unknown", I would put this in "biomass", since it's all renewable, and mostly biomass. 

https://www.hydroquebec.com/documents-data/open-data/electricity-generation-quebec/

As for the capacity, I would use the numbers from the Resource Adequacy summary of December 2020. https://www.npcc.org/content/docs/public/library/resource-adequacy/2020/2020-12-01-quebec-comprehensive-review.pdf (table 6.1, page 18)

Hydro: 40,211
Thermal (combustion turbine): 436
Biomass: 374
Wind:: 3,772
PV: 10
Total: 44,803

**Comment by pjakobsen** [comment]
I will be happy to make that update to zones.json this evening.

**Comment by bouchecl** [comment]
> I will be happy to make that update to zones.json this evening.

Thanks. Great job with the parser, by the way!

**Comment by pbubik** [comment]
Yaay! I see Quebec! well done guys!

**Comment by jarek** [comment]
In addition to updating zones.json, we'll need to update the parser file, specifically the mapping of "autres" to `unknown` (but make sure to add a comment in the code on why "autres" will now be mapped to `biomass`

https://github.com/tmrowco/electricitymap-contrib/blob/3b70964cb284503473929b440c5e5f1f7322ef59/parsers/CA_QC.py#L28

and update the returned dictionary in https://github.com/tmrowco/electricitymap-contrib/blob/3b70964cb284503473929b440c5e5f1f7322ef59/parsers/CA_QC.py#L45

**Comment by christbelanger** [comment]
@jarek 
Just to confirm that "Thermal" (Bécancour) is natural gas and it'll be use only in peak periods during winter.
