### ISSUE TITLE
Can't install `pandas` to set up local environment

### ISSUE THREAD

**Issue by steren** [tmrowco/electricitymap-contrib#3223]
I am following https://github.com/tmrowco/electricitymap-contrib/wiki/Set-up-local-environment

When I type `poetry install -E parsers`, it stays stuck on `Installing pandas (0.23.4): Installing...`

It's not clear to me how I can debug what's wrong, running the command with `-v` or `-vv` don't produce more useful logs.

I'm using Python 3.8.6 64bit

**Comment by madsnedergaard** [comment]
Hi @steren, thanks for reporting this! 🙌 

I could reproduce the problem by changing to `python@3.8.6` and rerunning install - so it seems like using Python `3.7` is still required. 

I'll look into upgrading the Pandas version so we can make contributions more accessible :)

Meanwhile, I can recommend [pyenv](https://github.com/pyenv/pyenv) for a smooth Python version management experience (it basically uses whatever version is started in a `.python-version` file).

**Comment by skovhus** [comment]
If upgrading Pandas gives too many headaches we could change https://github.com/tmrowco/electricitymap-contrib/blob/master/pyproject.toml#L12 to not allow Python version 3.8. That will make Poetry fail when running with an unsupported Python version.

**Comment by madsnedergaard** [comment]
Sorry for the delay, vacation came in between - but it's pretty doable and I have an internal branch that works now. Need to do some final tests and verifications, but overall it's looking good :)

**Comment by skovhus** [comment]
It would be great to upgrade pandas so we can support Python 3.8! 👏 

But note that the underlying issue is the pyproject file allows Python 3.8. That is my bad... Until we upgrade Pandas/Python we should restrict the Python version in the pyproject file.

**Comment by skovhus** [comment]
This should be fixed now as Pandas has been upgraded. Please reopen if this is still a problem.
