### ISSUE TITLE
Data for Sweden 🇸🇪 

### ISSUE THREAD

**Issue by Manu1400** [tmrowco/electricitymap-contrib#3247]
https://driftsdata.statnett.no/Web/map/snpscustom give live data 🔥 about SE : 

. | SE
-- | -- |
PRODUCTION | 15 127 |
Nuclear | 4 479 |
Hydro | 6 708 |
Thermal | 441 |
Wind | 2 898 |
Not specified | 601 |
CONSUMPTION | 12 859 |
NET EXCHANGE | -2 268 |

FYI : _Statnett_ is a Norwegian transmission system operator. ([source](https://www.wikidata.org/wiki/Q602621))

## API used
GET https://driftsdata.statnett.no/restapi/ProductionConsumption/GetLatestDetailedOverview?timestamp=1627644060000
=> return JSON or XML (content negotation) 👍 

* JSON => Content-Length: 9019
* XML => Content-Length: 16736
=> prefer JSON

## API documentation
All routes API : https://driftsdata.statnett.no/restapi/

**Comment by martincollignon** [comment]
Hey @Manu1400 ! Would you mind continuing the discussion on #1397 and close this one?
From the looks of it, we may finally be able to split SE?

**Comment by Manu1400** [comment]
@martincollignon found on https://www.svk.se/en/national-grid/the-control-room/ 4 bidding areas :

* Luleå (SE1)
* Sundsvall (SE2)
* Stockholm (SE3)
* Malmö (SE4)

**Comment by skovhus** [comment]
Thanks @Manu1400! Let us close this issue and centralize the information in #1397
