### ISSUE TITLE
Atomic waste

### ISSUE THREAD

**Issue by TmShaz** [tmrowco/electricitymap-contrib#3259]
Consider to show atomic waste per MWh to show that e.g. France shifting the problem to the next generations.

**Comment by veqtrus** [comment]
[0.0047 g/kWh](https://www.edfenergy.com/fuel-mix) is negligible compared to 25+ (100+ for most countries).

**Comment by flacombe** [comment]
That's a good point to discuss.
Negligible or not we must agree on hypothesis to take to consider what is a waste or not.

Countries that operate civil nuclear power plant may have different strategies to process their fission products. Some of them choose to make most of their products a waste and wait a long time for their activity to get low. Other recycle a given part and then reduce their amount of waste.
Among those waste, some are low activity and other are high activity which don't have a comparable life time.
Once those hypothesis properly sourced and documented, time will come to choose what is relevant to show.
Things are a bit more complex than "Nuclear produces waste".
