### ISSUE TITLE
Consider redirecting http:// to https://

### ISSUE THREAD

**Issue by steren** [tmrowco/electricitymap-contrib#3260]
It seems like http://www.electricitymap.org/map is serving.
Consider adding an automatic redirect to https://www.electricitymap.org/map.

This is considered a best practice.

If the website is served via `web/server.js`, a middleware could be added to Express to implement this redirect.

If it's served via another method in production, it's also usual for web frontends to allow  setting this redirect.

**Comment by skovhus** [comment]
Very good point. `web/server.js` is serving the file, so adding an Express handler/middleware is a great idea.

**Comment by VenomFate-619** [comment]
Can I do this.if yes then please assign this issue to me.

**Comment by vamsi963601** [comment]
Added Express Middleware and waiting for PR approval. #3316

**Comment by corradio** [comment]
Turns out server.js is redirecting http://www.electricitymap.org to HTTPS but not http://www.electricitymap.org/map

**Comment by skovhus** [comment]
I cannot see any redirects in server.js – the only one left was cancelled out by the always `false` condition ([I just removed it here](https://github.com/tmrowco/electricitymap-contrib/pull/3395/files#diff-e649226fe936bd00b2da0b5580d6bead9cd40e422bf22e3aa88121e2eef55310L151))

**Comment by corradio** [comment]
> I cannot see any redirects in server.js – the only one left was cancelled out by the always `false` condition ([I just removed it here](https://github.com/tmrowco/electricitymap-contrib/pull/3395/files#diff-e649226fe936bd00b2da0b5580d6bead9cd40e422bf22e3aa88121e2eef55310L151))

Apologies you are correct. Redirect is served by cloudflare:
![image](https://user-images.githubusercontent.com/1655848/133991269-6de586c6-a63e-4d80-8940-dfd902942b18.png)
![image](https://user-images.githubusercontent.com/1655848/133991396-14f93f1b-e726-45d2-8a68-5c3620f12fa2.png)

I've now added a `/*` suffix, which causes a correct redirect for /map
![image](https://user-images.githubusercontent.com/1655848/133991490-9154e208-0230-42c4-8874-eac6cb201763.png)
![image](https://user-images.githubusercontent.com/1655848/133991528-6969ffa2-0235-491c-a53a-714a6d1fc31c.png)

I'm also closing this issue as this seems to be fixed!

**Comment by skovhus** [comment]
Nice!
