### ISSUE TITLE
One of PJM<->NYISO exchanges has wrong direction

### ISSUE THREAD

**Issue by jarek** [tmrowco/electricitymap-contrib#3277]
Right now the map is showing 1768 MW heading from PJM to New York, and 1768 MW heading from "PJM Interconnection, Llc" to "New York Independent System Operator".

I'm guessing the arrow angle for the PJM,LLC exchange is flipped? All other data (the tooltip text, the "sources of electricity" panels for both PJM and NY) seem to match that. But someone please verify.

![ny-pjm](https://user-images.githubusercontent.com/47415/128276239-c6f1b330-6aad-466e-819b-6853769baf3b.png)

![pjmllc](https://user-images.githubusercontent.com/47415/128276409-8c086bf7-ddb4-4dc5-81bc-abefe49dc337.png)

![pjm no llc](https://user-images.githubusercontent.com/47415/128276446-b3d938b3-8d2c-4cfd-abba-18c84acfbea2.png)

![nyiso](https://user-images.githubusercontent.com/47415/128276502-2c43c477-4fd4-4282-8253-c2d5d9a0cc7a.png)

![pjmllc panel](https://user-images.githubusercontent.com/47415/128276507-84123f20-8dd4-456a-a1eb-15cc1e764d16.png)

**Comment by jarek** [comment]
Check if https://github.com/tmrowco/electricitymap-contrib/pull/3329 fixed it once that's deployed

**Comment by madsnedergaard** [comment]
@jarek The changes to US zones is live now and as far as I can tell this issue is now resolved :)

**Comment by jarek** [comment]
Yeah seems good!
