### ISSUE TITLE
Netherlands is missing solar data

### ISSUE THREAD

**Issue by Manu1400** [tmrowco/electricitymap-contrib#3283]
### issue in ElectricityMap
In [Netherlands zone](https://www.electricitymap.org/zone/N)
>0 % of electricity available in 🇳🇱 comes **Netherlands** from solar
> 0.00W / 11.8GW

> 47.74% of electricity available in 🇳🇱 comes **Netherlands** from unknown

> The data provider (ENTSO-E) underreports solar and wind production. The unknown emission factor is adjusted to account for this.

### explain issue
* 0 W / 11.8GW is not possible at 16:14 !
* solar in the last 24 hours : 0 W

### QA from an other source

[Live data of a solar producter in Netherlands](https://monitoringpublic.solaredge.com/solaredge-web/p/site/public?name=Martien%20Manders&locale=en_US#/dashboard):
> `Current Power: 4.27 kW`
> `Last Updated: 08/06/2021 16:07`

**Comment by jarek** [comment]
Detailed data for Netherlands is no longer available. Solar generation is now rolled into "unknown" with an adjusted gCO2eq/kWh value. Please see https://github.com/tmrowco/electricitymap-contrib/issues/3015#issuecomment-888154930 for details.
