### ISSUE TITLE
Alternate source for Portugal Mainland (PT)

### ISSUE THREAD

**Issue by RavingSombra** [tmrowco/electricitymap-contrib#3297]
Seeing no data for Portugal and issue #1055 made me see what I could find.
There's data from REN (distribuitor and manager of the portuguese power grid) updated every 15 minutes
https://datahub.ren.pt/en/

![Screenshot 2021-08-10 at 11-45-23 REN Data Hub](https://user-images.githubusercontent.com/61268574/128854560-a0e562d7-f7d1-4744-a7e2-4265958508e8.png)

When hovering the graph it shows the value for each moment, in intervals of 15 minutes.

They have a contact form with "electricity data" as subject option, so this shouldn't be hard to add to the map https://datahub.ren.pt/en/contacts/

**Comment by jarek** [comment]
Per https://github.com/tmrowco/electricitymap-contrib/blob/830f1e6243965fb33012a922d4a541e7f48a957d/config/zones.json#L4592-L4618 Portuguese data should actually come from ENTSOE. [In ENTSOE generation data for Portugal]( https://transparency.entsoe.eu/generation/r2/actualGenerationPerProductionType/show?name=&defaultValue=false&viewType=TABLE&areaType=BZN&atch=false&datepicker-day-offset-select-dv-date-from_input=D&dateTime.dateTime=09.08.2021+00:00|UTC|DAYTIMERANGE&dateTime.endDateTime=09.08.2021+00:00|UTC|DAYTIMERANGE&area.values=CTY|10YPT-REN------W!BZN|10YPT-REN------W&productionType.values=B01&productionType.values=B02&productionType.values=B03&productionType.values=B04&productionType.values=B05&productionType.values=B06&productionType.values=B07&productionType.values=B08&productionType.values=B09&productionType.values=B10&productionType.values=B11&productionType.values=B12&productionType.values=B13&productionType.values=B14&productionType.values=B20&productionType.values=B15&productionType.values=B16&productionType.values=B17&productionType.values=B18&productionType.values=B19&dateTime.timezone=UTC&dateTime.timezone_input=UTC), data has been there up until August 9th at 14:00 UTC... hopefully it comes back to ENTSOE?

**Comment by RavingSombra** [comment]
Thanks for the reply!
Sorry for pointing out "add", I didn't take a look at the code itself.

Went ahead and checked again ENTSOE, which at the time of this reply has data until August 11th (today) at 13:00 UTC.
Looking at the interval from Aug 9 to 11, data seem to have been loaded today, somewhere from 13:00 UTC to 16:00 UTC.

I'm going to contact both REN and ENTSOE to see if there's something's up that can be fixed or an alternative.

**Comment by brandongalbraith** [comment]
[Portugal](https://www.electricitymap.org/zone/PT?wind=false&solar=false) data (provided via ENTSOE) looks like its been back for some time @RavingSombra, I think this issue can be closed @jarek.

**Comment by RavingSombra** [comment]
Thanks for the ping, I ended up forgeting about this.

I got a reply from REN. They're the ones feeding data to ENTSOE, though as you can tell it still updates a big chunk at a time, instead of hourly like other countries.

Alternative to this would be to get data from REN directly. They plan to add functionality to automatically gather data in a future version (no ETA/expected release). Though, they pointed me to another page on the website where data can be gathered, but would require work to adapt to this scenario.

Website: http://www.mercado.ren.pt/PT/Electr/InfoMercado/Prod/Paginas/Verificada.aspx
Documentation: https://www.mercado.ren.pt/PT/Electr/Comunicacao/WebServ/WSDoc/REN%20%e2%80%93%20SpecWSInfoMercado.pdf

Since data for Portugal is updated at a consistent rate, I'll close this issue.

**Comment by brandongalbraith** [comment]
@RavingSombra I am only a volunteer, so I can't speak for @tmrowco, but my understanding is that there's a strong desire for ENTSOE to be the source of truth when they provide coverage for a zone.
