### ISSUE TITLE
Live data for Peninsula Malaysia is unavailable 17th Aug 2021

### ISSUE THREAD

**Issue by aledrus** [tmrowco/electricitymap-contrib#3313]
Hi, I usually see data for Peninsula Malaysia but I can't see them today.
I don't know how far back this data missing error has been.

If I remember correctly, you source your data from www.gso.org.my which I have checked is online.

The kibana log says that "No exchange data is currently available for West Malaysia."

Can you teach me what it is that you do to extract data from West Malaysia? Perhaps I could help contribute with its maintenance.

**Comment by skovhus** [comment]
Hi @aledrus 

It would be great if you could look into this. 

Here is a few pointers to get you started:
- the zone is called `MY-WM` and is defined in https://github.com/tmrowco/electricitymap-contrib/blob/master/config/zones.json#L3978
- the source code for the parser is here: https://github.com/tmrowco/electricitymap-contrib/blob/master/parsers/MY_WM.py
- you can run the parser directly and investigate what is going on. You can also run `poetry run test_parser` to validate the parser

Let us know how it goes. :)

**Comment by aledrus** [comment]
Hello Kenneth

Thanks! I'll be happy to look into this.

Right now I've verified the data sources specified in the parser is
available. So it must be the parser problem or the source data has changed
in formatting or something. So I assume the parser may need a bit of
adaptation.

The thing is, I don't have any experience with Python, although I do have
experience in several older languages. I think I can figure this out if you
could help me with one thing.

How do I run the script? =)

You said run poetry run test_parser, but I don't know what that is.

I have downloaded Python IDLE Shell and I have tested some basic commands
eg print("hello"); And also I have copied the MY_WM.py and saved as a text
file under the same name on my Desktop.
I don't currently know how to test the MY_WM.py parser because I can't run
it. I typed MY_WM.py on the command line, I typed poetry, I typed run, but
they all resulted in command line NameErrors.

If you could just help me with this part, I should be able to figure out
the rest.

Thanks

**Comment by jarek** [comment]
See also recent discussion for Malaysia https://github.com/tmrowco/electricitymap-contrib/issues/3278

**Comment by skovhus** [comment]
Closing this in favour of https://github.com/tmrowco/electricitymap-contrib/issues/3278 😊

About the development environment setup I suggest you read the guide in https://github.com/tmrowco/electricitymap-contrib/wiki/Set-up-local-environment — I hope it helps. 🤞
