### ISSUE TITLE
[bug][frontend] USA - Doubled PJM exchange arrows

### ISSUE THREAD

**Issue by piotrek124-1** [tmrowco/electricitymap-contrib#3330]
![1](https://user-images.githubusercontent.com/66417442/130635537-977f53b2-4845-4cf7-9486-93c9cffc9b1f.png)
![2](https://user-images.githubusercontent.com/66417442/130635547-5d4b3dee-8026-4aa3-a44a-eb314c989616.png)

**Comment by madsnedergaard** [comment]
This will be fixed when https://github.com/tmrowco/electricitymap-contrib/pull/3329 is deployed :)
