### ISSUE TITLE
Update canonical link to exclude query parameters

### ISSUE THREAD

**Issue by madsnedergaard** [tmrowco/electricitymap-contrib#3363]
## Description

Currently, when searching for "electricitymap france" we get 5+ results for the same zone, but with a mix of query parameters enabled:

<img width="1359" alt="Screenshot 2021-09-07 at 10 54 47" src="https://user-images.githubusercontent.com/3296643/132316367-8fd34ba8-3c2f-4210-a891-279f516857de.png">

This makes it harder to know which one you need, and the links are essentially duplicates.

### Proposed solution

Unless we for some reason want to specifically have "zone with solar layer enabled" show up as a search result, I suggest that we update the canonical and alternate links in `<head />` to exclude query parameters.

<img width="583" alt="Screenshot 2021-09-07 at 10 51 20" src="https://user-images.githubusercontent.com/3296643/132316787-01c26d9f-daba-44ee-abcd-53b0092d4099.png">

<img width="566" alt="Screenshot 2021-09-07 at 10 54 06" src="https://user-images.githubusercontent.com/3296643/132316782-9b899fb3-e936-4700-9669-19298f900345.png">

#### Implications

The following parameters will no longer create unique search results:

- `?lang=XX` - so the same page will not show up in different languages like it currently does
- `?solar=X`
- `?wind=X`
- `?remote=X` (this is only used for local development, so it should never have been here in the first place)
- `?fbclid=XXX`
- other random parameters used by others when linking to the map (like UTM and diverse tracking)

**Comment by madsnedergaard** [comment]
If anyone can name reasons for not doing this, then I'd love to hear why as I might have missed something :)

**Comment by corradio** [comment]
> If anyone can name reasons for not doing this, then I'd love to hear why as I might have missed something :)

This makes a lot of sense! The only query string I would keep is the language one.

**Comment by skovhus** [comment]
Makes sense Mads. +1 on keeping the language.

**Comment by hboisgibault** [comment]
Hi guys, I opened a pull request to eliminate duplicate links in the metadata.

**Comment by gwpicard** [comment]
Thanks so much for the PR @hboisgibault !!

**Comment by corradio** [comment]
May I suggest keeping the issue open until the changes are caught by the search engines? Currently, this issue doesn't seem to be resolved (it might just take a bit of time)

**Comment by corradio** [comment]
It seems like this is not caught by search engines anymore! Feel free to re-open if you see it appearing again.
