### ISSUE TITLE
Improve text color on CO2 color rectangle

### ISSUE THREAD

**Issue by phiphou** [tmrowco/electricitymap-contrib#3365]
Hi,

Two years ago, I proposed you to use a background based color text for CO2 color rectangle. (#1886)

[You accepted](https://github.com/tmrowco/electricitymap-contrib/pull/2981) my proposition, and I was kind of proud of it. But, after some new tests, I realized it was not the best solution.

I said you to use the YIQ contrast method, what you did. But in some cases, when background color is brown, it doesn't produce a good result, especially on mobile with very low luminosity.

Instead of YIQ method, I tested the W3CAG method more in depth. With the default settings, result is close to the YIQ method and it doesn't solve the problem for these colors. So I modified it a bit. The idea is to switch to white text earlier on the color ramp. The switch should, in my opinion, starts around 400g/kWh.

You can play with this CodePen to see the difference between YIQ, W3CAG standard and my modified version : [https://codepen.io/phiphou/pen/YBeMxw](https://codepen.io/phiphou/pen/YBeMxw)

You can find more informations about W3CAG color contrast here : [https://www.w3.org/TR/WCAG20-TECHS/G17.html](https://www.w3.org/TR/WCAG20-TECHS/G17.html)

It is not standard, but it meets the needs well.

Here is how to implement my solution in [web/src/components/carbonintensitysquare.js](https://github.com/tmrowco/electricitymap-contrib/blob/edb856322ff308316a3994c3f8bd5a27d34fbbdf/web/src/components/carbonintensitysquare.js) : 

```javascript
const getTextColor = rgbColor=> {
  const colors = rgbColor.replace(/[^\d,.]/g, '').split(',');
  const r = parseInt(colors[0], 10);
  const g = parseInt(colors[1], 10);
  const b = parseInt(colors[2], 10)
  const rgbArr = [r, g, b];
  const computedArr = rgbArr.map (c => { 
    const s = c / 255;
    return s <= 0.03928 ? s / 12.92 : Math.pow((s + 0.055) / 1.055, 2.4);
  })
  const luminosity = 0.2126 * computedArr[0] + 0.7152 * computedArr[1] + 0.0722 * computedArr[2];
  // Here is the modification, I changed (1.05 * 0.05) whith (1.05 * 0.16)
  // Math.sqrt(1.05 * 0.16) - 0.05 is a constant, it can be replaced with it's 
  // approached value (0.35987803063838397) to avoid useless computations 
  return luminosity > Math.sqrt(1.05 * 0.16) - 0.05 ? "black" : "white";
}; 
```

**Comment by skovhus** [comment]
@phiphou thanks for taking your time to improve this! It indeed looks better. Do you agree @madsnedergaard?

**Comment by madsnedergaard** [comment]
Hi @phiphou, thanks for the original improvement - it was so much better than before :)
While it's a really nice codepen you did to show the difference, I have a harder time seeing the actual impact on this on the map. Would you mind showing some actual examples with the map where it would have an impact? You can just change it in Inspector Tools if getting the map running locally is too much work :)

**Comment by phiphou** [comment]
Here is a sample : 

![elecmap](https://user-images.githubusercontent.com/364418/132501918-62ee9a99-7ed1-48ed-b99c-8d62ece0caa6.png)

I think the modified version in the right image is better that the actual version on the left.

It's more visible on mobile devices, especially with low luminosity. From 400g/kWh, background start becoming quite dark, and the contrast between the background and the black text seems not big enough to me. Setting a white text make the rectangle more readable. 

I understand it's not a major improvement. Maybe we can let this issue opened and ask people to use my CodePen to determine at what value they think the switch to white should happen.

**Comment by madsnedergaard** [comment]
Thanks for the detailed explanation and screenshots 💪 

I still can't figure out what I find most readable, but I'm also on a nice retina screen - so I trust that this is more of a problem on the low luminosity screens.

I'd be happy merge this change if you make a PR :)

**Comment by phiphou** [comment]
I'm afraid I cannot do a PR. I let you implement the change in the next release.

**Comment by phiphou** [comment]
I will try to do it this weekend (it will be my first PR ever ;))

**Comment by phiphou** [comment]
One last argument : I made a test for color blind people, I think my proposition is better in each case : 

![colorblind](https://user-images.githubusercontent.com/364418/132727560-01f5ae40-2c6e-42b9-a052-2fd0146a317a.png)
