### ISSUE TITLE
Absolute Numbers for comparison

### ISSUE THREAD

**Issue by Tradenergy** [tmrowco/electricitymap-contrib#3384]
Dear fellows,

is there any way to display the abolute numbers of CO2 production in addition ? And not only the number per kWh. 

For example: Estland looks like the worst country due to "oil shale" production. 
But if we look at Germany which produces 25 GW of Coal energy compared to Estlands 500 MW (2% of germanys coal energy demand). Than in my opinion we do need an extra tab for "absolute numbers " for each country. 

Maybe a tab at the upper right corner where you can see consumption, production...
So when you switch to "Absolute" the actualCO2 emmisions wil be displayed by multiplication with the single energy emission factors. 

Thank you guys for taking your time reading this. 

KR
Anton

**Comment by jarek** [comment]
Hello Anton,

See the following issues for past discussions about "absolute numbers", including the Estonia vs Germany comparison:

https://github.com/tmrowco/electricitymap-contrib/issues/1933
https://github.com/tmrowco/electricitymap-contrib/issues/1163
https://github.com/tmrowco/electricitymap-contrib/issues/858
https://github.com/tmrowco/electricitymap-contrib/issues/618
https://github.com/tmrowco/electricitymap-contrib/issues/169#issuecomment-269651836

**Comment by Tradenergy** [comment]
Thanks a lot :)
