### ISSUE TITLE
Error after selecting a language

### ISSUE THREAD

**Issue by piotrek124-1** [tmrowco/electricitymap-contrib#3394]
# Description 
## Issue
Getting HTTP 500 error after choosing language.
![1](https://user-images.githubusercontent.com/66417442/133975749-f7a82df7-0e60-4215-8346-43d1f649d7ee.png)
Ubuntu 20.4 | Firefox 92.0

**Comment by skovhus** [comment]
Thanks for reporting this. We have fixed it now.
