### ISSUE TITLE
Total power consumption as a number

### ISSUE THREAD

**Issue by Troik** [tmrowco/electricitymap-contrib#3403]
Dear Ladies and Gentlemen, 

would it be possible, to show the total power consumption as a figure in the power consumption screen? (after tapping on a country). I think, that would increase the comprehensiveness of the data. 

Kind regards,

**Comment by jarek** [comment]
Hello,

Total electrical power available in a region is listed in the popup when you hover over or tap on one of the fuel categories:

![total](https://user-images.githubusercontent.com/47415/134602258-7daae0a2-8da3-4272-a95d-46634329de31.png)

**Comment by Troik** [comment]
Thanks!

**Comment by RobinFrcd** [comment]
I agree with this, I don't find this super user-friendly. This is indeed a really useful information, pretty sure it should be available on the main panel, no ?
