### ISSUE TITLE
Peninsular Malaysia - Data unavailable

### ISSUE THREAD

**Issue by drm295** [tmrowco/electricitymap-contrib#3451]
Greetings. Live data for Peninsular Malaysia has been unavailable for some time now. I'm a regular user of the source data website for my own personal analysis, but not a coder. Would like to collaborate with anyone who's familiar with the coding to make the data available on Electricity Map again. Thank you.

**Comment by jarek** [comment]
Thanks for the note! There is an earlier issue for this https://github.com/tmrowco/electricitymap-contrib/issues/3278. It hasn't been fixed yet but it should be possible, please follow the other issue for updates.
