### ISSUE TITLE
East Denmark wind capacity is too low

### ISSUE THREAD

**Issue by sandos** [tmrowco/electricitymap-contrib#3475]
As can be seen in the attached screenshot, the total wind capacity is either too low or the reported wind figures are too high for East Denmark, since it is currently reported was 123%

![image](https://user-images.githubusercontent.com/60831/140651656-9680f2ef-1bfb-4ba7-856b-014cbb0afbb9.png)

**Comment by KabelWlan** [comment]
Yeah I know… Still waiting for Entsoe to update their capacity list. However, in the meantime we could just add the capacity from the Kriegers Flak offshore wind farm. It came online in September and added more than 600 MW.

**Comment by KabelWlan** [comment]
I think this can be closed for now. I'll update the capacities again as soon as Entsoe releases new data.

**Comment by skovhus** [comment]
@KabelWlan thanks!
