### ISSUE TITLE
GR production parser down again

### ISSUE THREAD

**Issue by xneo1** [tmrowco/electricitymap-contrib#3479]
It's been down from 4/11/2021
_Live data is temporarily unavailable for this area._ 

Can you please re-check it?

**Comment by jarek** [comment]
Hello,

as per https://github.com/tmrowco/electricitymap-contrib/blob/master/DATA_SOURCES.md Greece data comes from ENTSOE. Whenever it's missing on Electricity Map, please check if data is on ENTSOE: https://transparency.entsoe.eu/generation/r2/actualGenerationPerProductionType/show?name=&defaultValue=false&viewType=TABLE&areaType=BZN&atch=false&datepicker-day-offset-select-dv-date-from_input=D&dateTime.dateTime=10.11.2021+00:00|CET|DAYTIMERANGE&dateTime.endDateTime=10.11.2021+00:00|CET|DAYTIMERANGE&area.values=CTY|10YGR-HTSO-----Y!BZN|10YGR-HTSO-----Y&productionType.values=B01&productionType.values=B02&productionType.values=B03&productionType.values=B04&productionType.values=B05&productionType.values=B06&productionType.values=B07&productionType.values=B08&productionType.values=B09&productionType.values=B10&productionType.values=B11&productionType.values=B12&productionType.values=B13&productionType.values=B14&productionType.values=B20&productionType.values=B15&productionType.values=B16&productionType.values=B17&productionType.values=B18&productionType.values=B19&dateTime.timezone=CET_CEST&dateTime.timezone_input=CET+(UTC+1)+/+CEST+(UTC+2)

**Comment by skovhus** [comment]
The challenge with Greece is that the data provided by ENTSO-E is too delayed for us to show it on the map currently. Notice that the data is available in the left panel if you click on the country.

<img width="598" alt="Screenshot 2021-11-18 at 16 41 34" src="https://user-images.githubusercontent.com/1260305/142447529-363a0f3c-c29a-4957-8012-4ccbc1c418ae.png">
<img width="650" alt="Screenshot 2021-11-18 at 16 41 29" src="https://user-images.githubusercontent.com/1260305/142447522-12b095d7-2e8b-4da7-b2c1-bd7b137da868.png">
