### ISSUE TITLE
Mistranslation in Czech version of electricityMap

### ISSUE THREAD

**Issue by gwpicard** [tmrowco/electricitymap-contrib#3482]
Issue raised by a contributor via email:

Among the types of power plants, oil is translated literally into "olej", which means usually oil used for cooking and
other uses, but never oil as a crude oil/petroleum. 

That is called "ropa" in Czech language.

A good first issue for someone who wants to get their hands dirty with the code!

**Comment by skovhus** [comment]
This can be fixed by updating https://github.com/tmrowco/electricitymap-contrib/blob/1ecb9c9bbc3b60fc04d7f1e20b1eea425798635d/web/locales/cs.json

**Comment by FelixDQ** [comment]
Fixed by https://github.com/tmrowco/electricitymap-contrib/pull/3581
