### ISSUE TITLE
Setup your local environment: missing dependency on tesseract

### ISSUE THREAD

**Issue by sackofguts** [tmrowco/electricitymap-contrib#3569]
I am following the Python instructions in the Wiki for setting up my development environment, and when I ran 
    poetry run test
I had four of the parser tests fail, all in the same way (see attached output [test-failure.txt](https://github.com/tmrowco/electricitymap-contrib/files/7599083/test-failure.txt)).   Here's one of the failures:

==============================================================                                                                                            
ERROR: test_allow_remote_clock_to_be_slightly_ahead (test_SG.TestSolar)                                                                                   
----------------------------------------------------------------------                                                                                    
Traceback (most recent call last):                                                                                                                        
  File "/Users/andrew/src/electricitymap-contrib/.venv/lib/python3.7/site-packages/freezegun/api.py", line 735, in wrapper                                
      result = func(*args, **kwargs)                                                                                                                      
        File "/Users/andrew/src/electricitymap-contrib/parsers/test/test_SG.py", line 43, in test_allow_remote_clock_to_be_slightly_ahead                 
            power = SG.get_solar(self.session, logger=self.logger)                                                                                        
              File "/Users/andrew/src/electricitymap-contrib/parsers/SG.py", line 76, in get_solar                                                        
                  text = image_to_string(black_white, lang='eng')                                                                                         
                    File "/Users/andrew/src/electricitymap-contrib/.venv/lib/python3.7/site-packages/pytesseract/pytesseract.py", line 193, in image_to_s\
tring                                                                                                                                                     
                        return run_and_get_output(image, 'txt', lang, config, nice)                                                                       
                          File "/Users/andrew/src/electricitymap-contrib/.venv/lib/python3.7/site-packages/pytesseract/pytesseract.py", line 140, in run_\
and_get_output                                                                                                                                            
                              run_tesseract(**kwargs)                                                                                                     
                                File "/Users/andrew/src/electricitymap-contrib/.venv/lib/python3.7/site-packages/pytesseract/pytesseract.py", line 111, i\
n run_tesseract                                                                                                                                           
                                    proc = subprocess.Popen(command, stderr=subprocess.PIPE)                                                              
                                      File "/Users/andrew/.pyenv/versions/3.7.9/lib/python3.7/subprocess.py", line 800, in __init__                       
                                          restore_signals, start_new_session)                                                                             
                                            File "/Users/andrew/.pyenv/versions/3.7.9/lib/python3.7/subprocess.py", line 1551, in _execute_child          
                                                raise child_exception_type(errno_num, err_msg, err_filename)                                              
                                                FileNotFoundError: [Errno 2] No such file or directory: 'tesseract': 'tesseract'      

After poking around in pytesseract, reading the [pytesseract README](https://github.com/madmaze/pytesseract) and trying to test pytesseract directly, I realized that I needed to install [tesseract](https://github.com/tesseract-ocr/tesseract).  I'm doing this on MacOS, so I used MacPorts to install tesseract and the tesseract-eng port, and now "poetry run test" is successful.

I am not sure if it is possible for the electricity-map install process (using poetry?) to check for the tesseract dependency, and (bonus) install it.

I would like to suggest a change to the [Setup Your Local Environment Wiki page ](https://github.com/tmrowco/electricitymap-contrib/wiki/Set-up-local-environment).  After step (2) please add something like "Ensure you have the dependency tool tesseract installed, following the instructions in [this guide](https://github.com/tesseract-ocr/tesseract)."

**Comment by skovhus** [comment]
Thanks for reporting this. 🙏🏼

We cannot do anything through poetry, but we should at least update the wiki with your suggestion. Feel free to do that. Everyone has assess to do this. 

As a service, then we could also provide an installation script that verifies that we have the required dependencies.

**Comment by sackofguts** [comment]
Thanks for the feedback!  I have edited the wiki page.

I am not sure of the best approach for an install script doing dependency checks, but I'm willing to take a crack at a pull request.  Are you able to point me in the right direction?

**Comment by skovhus** [comment]
I think having this in the wiki is good enough for now. Thanks for updating the wiki. 👏
