### ISSUE TITLE
Let people switch between languages easily

### ISSUE THREAD

**Issue by Raffox97** [tmrowco/electricitymap-contrib#437]
I was just thinking that it can be a good idea to let people switch between languages.

**Comment by corradio** [comment]
You actually can, manually, by navigating to
http://www.electricitymap.org?lang=de for example.
Not user friendly though..

**Comment by Raffox97** [comment]
Yeah it's true, in fact I was thinking in a system like that.
[http://i.imgur.com/20Jrc9x.png](url)

**Comment by corradio** [comment]
Hi @Raffox97 I'm closing this because it seems like only a very few people would benefit from this feature. Let me know if you believe this is important and has to be taken care of

**Comment by systemcatch** [comment]
This came up on Slack again. Probably worth looking at implementing a toggle of some kind or at least updating the documentation to show users how to switch using the url method.

**Comment by brunolajoie** [comment]
What about we simply force it as visible URL query string; so that it's
visible by default in the url?

**Comment by systemcatch** [comment]
That's an improvement (assuming we document it as well) but tbh I don't think non developers will understand how to use it.

**Comment by jld3103** [comment]
Look at #1837
