### ISSUE TITLE
split Australia (Tasmania) to show King island off grid system

### ISSUE THREAD

**Issue by strassburger** [tmrowco/electricitymap-contrib#636]
split Tasmania to show King island
Live data - King Island Advanced Hybrid Power Station

source
http://www.kingislandrenewableenergy.com.au/

**Comment by systemcatch** [comment]
I'll take a crack at doing this one.

**Comment by superlonglong** [comment]
the king island information page is notoriously unreliable.

hopefully their CSV is better, but dont assume that your code isnt working, it could just be garbage in, garbage out.

**Comment by systemcatch** [comment]
@superlonglong I've had a look at this one and it seems difficult.  There are csv files but I don't think they've been updated for several years.  As regards getting getting the live data the dashboard uses a websocket to connect to ajenti who then send the data back to the dashboard.  It's probably possible to scrape this connection but it might take a while to figure out the best way.

If you want to have a go at this feel free as I'm working on the El Salvador parser right now.

**Comment by superlonglong** [comment]
@systemcatch unfortunately im as useful as tits on a bull. i cant code :(

**Comment by strassburger** [comment]
@superlonglong 
"the king island information page is notoriously unreliable"
no doubt, but right now 100%wind
PS:
i did copy the Page "http://www.kingislandrenewableenergy.com.au/" local and get same results.
in the folder there in the is a java - scripts which i  can not handle: "js_52fac29959611f022bfac1ab349c3dce.js"
And an html: "dashboard.html"
Both are to much for me

**Comment by strassburger** [comment]
Have a little project now
[ki-2017-09-30.txt](https://github.com/tmrowco/electricitymap/files/1347552/ki-2017-09-30.txt)
 to read all data from King island:
May it help to put the data here too??
http://www.kingislandrenewableenergy.com.au/kiapp-dashboard/dashboard.html
Details:
[Readme.txt](https://github.com/tmrowco/electricitymap/files/1347548/Readme.txt)
[ki-script16.txt](https://github.com/tmrowco/electricitymap/files/1347549/ki-script16.txt)
[ki-2017-09-30.txt](https://github.com/tmrowco/electricitymap/files/1347555/ki-2017-09-30.txt)
Do not have the knowledge to integrate it in the co2 map.
Who can help?

**Comment by systemcatch** [comment]
Hey @strassburger thanks for having a go at this one.  It's not a bad idea to scrape this using some browser automation tricks.  I can basically follow what your script is doing.  How about creating a repo so people can view it on github.

A few points;

1. Since all of the parsers run every ~5 minutes there's no need for your script run continuously on a loop, it just needs to return a single usable data point when called.  The backend server can handle when to run the script.
2. The other parsers are all written in Python.  Whether a bash parser would work is a question for @corradio .  Personally if we can get it to return data in form like https://github.com/tmrowco/electricitymap/blob/master/parsers/example.py I don't see a big problem.

**Comment by corradio** [comment]
Thanks @systemcatch. I fully agree.
The missing part here is that we need to be able to show the topology for King Island using Natural Earth data. I haven't looked into that yet.
Also, does King Island have an interconnector to the mainland?

**Comment by strassburger** [comment]
@corrado
King Island do not have an an interconnector
Source:
http://www.kingislandrenewableenergy.com.au/stand-alone-power-systems/what-hybrid-grid-power-system
"The power grid on King Island is a good example of an off-grid system; it is entirely self-contained and allows King Island to be self-reliant for its electricity needs."
Maybe more in the tread of "splitting canary island #626":
That is the reason i am interested in it like in El Hierro, the off grid system of of the canary Island.
There at El Hierro also  missing part  is that we need to be able to show the topology for El Hierro using Natural Earth data

**Comment by corradio** [comment]
ok that's a thing less to do :)
So let's figure out if we can get the topology from Natural Earth polygons.
A quick look at the states and countries file:
```bash
cat world_states_props.json|grep AUS|jq '.name'
"Macquarie Island"
"Jervis Bay Territory"
"Northern Territory"
"Western Australia"
"Australian Capital Territory"
"New South Wales"
"South Australia"
"Victoria"
"Queensland"
"Norfolk Island"
"Tasmania"

cat world_countries_props.json|grep AUS|jq '.NAME_SORT'                           electricitymap/git/master
"Ashmore and Cartier Islands"
"Tasmania"
"Macquarie Island"
"Australia"
"Coral Sea Islands"
```

What kind of administrative area is the King Island?

**Comment by strassburger** [comment]
Thank you @systemcatch.
Would like to give all my data to github, but do not know how, sorry.
Same: python i only took one side look in it.... Not really home there... 
Do you have a hint of a "How to" for me?
Have it public under this link and there in the directory King-Island  
https://webmail.freenet.de/Cloud/?shareToken=0bf8c2e9d960a96ad3e9799475fd2b2702ca5d7852d7811970e90bff388c40d3#files/
Still working on it 
See the readme there.

**Comment by strassburger** [comment]
@corradio 
King island is administrated by Tasmania.
Hydro Tasmania is running the king Island project.

**Comment by corradio** [comment]
Seems like it might be possible to grab the GeoJSON from here:
https://tinyhousecollaborativeoz.carto.com/tables/local_government_areas_oz_merge/public
But might require some work.

**Comment by systemcatch** [comment]
@strassburger 
You can follow the steps [here](https://github.com/new) to create a new repo.  Then you need to add your King Island folder which you can do by [dragging and dropping](https://help.github.com/articles/adding-a-file-to-a-repository/).

**Comment by strassburger** [comment]
@systemcatch 
done, hope in a form with sense:
https://github.com/strassburger/KI-grid-data

**Comment by systemcatch** [comment]
Looks good.  I'm having some trouble installing xdotool so haven't been able to run your script yet.  Regardless the next steps are a) to make it return only one datapoint rather than looping and requiring ctrl-c to stop and b) return data in a form like this;
`{
      'countryCode': 'FR',
      'datetime': '2017-01-01T00:00:00Z',
      'production': {
          'biomass': 0.0,
          'coal': 0.0,
          'gas': 0.0,
          'hydro': 0.0,
          'nuclear': null,
          'oil': 0.0,
          'solar': 0.0,
          'wind': 0.0,
          'geothermal': 0.0,
          'unknown': 0.0
      },
      'storage': {
          'hydro': -10.0,
      },
      'source': 'mysource.com'
    }`
I see bash does have the equivalent of dictionaries, but you could also just pipe your output to a python script or use python read the data file that's generated.

**Comment by strassburger** [comment]
@systemcatch 
Tanks for crosschecking.
may help to install xdotool on ubuntu-machine:
"sudo apt-get install xdotool"
If you have other OS:
http://tuxradar.com/content/xdotool-script-your-mouse
there getting started.
It would be great if you could install xdotool  on a machine with good internet connection.

Right now my personal goal is  to collect all data available to make a data base for king Island.
There are still some other problems:
- Check if data input is not frozen: was yesterday on my machine
- build a routine to start the firefox window new to solve the problem
- my  machine with the firefox-window: in two month i am abroad with really poor internet connection
a:) I see a problem if the firefox window will not be open all the time. it needs ca 60s to show really data.
b:) Still i am a really newbee in python and  try to get my personal goal without python....

**Comment by jarek** [comment]
Thanks for the research @strassburger!

For purposes of Electricity Map, it looks like we can request the data more directly.

The page http://www.kingislandrenewableenergy.com.au/kiapp-dashboard/dashboard.html 
loads in a number of JSON files with XMLHttpRequest (async web request). This can be seen in a browser developer console (press F12 in Firefox with that page open, then reload page).

Of most interest to us is http://www.kingislandrenewableenergy.com.au/kiapp-dashboard/data/automatic/dashboard.json which seems to have the actual info displayed in the dashboard page, in a fairly easy to parse JSON format.

**Comment by systemcatch** [comment]
@jarek Those json files don't update anymore, I think they were just used for testing when the system started in 2014 (last update).  It seems like they get their live data via a websocket connection to ajenti.

**Comment by jarek** [comment]
Ah sorry, I have my Firefox set up to block content from other domains so I never saw that being loaded (and of course it was also getting blocked when the bash script tried to use Firefox for scraping...). Please ignore my post then

**Comment by systemcatch** [comment]
No worries.  Another possibility is we could contact the people who run the site and ask them for access to their data stream.  That would make things easy.

**Comment by strassburger** [comment]
@systemcatch 
"ask them for access to their data stream"
Good luck.
I asked for data without getting any respond.....

**Comment by strassburger** [comment]
@corradio 
link to king island map:
https://strassburger.carto.com/builder/ea70c07d-3728-4401-9e5d-2b765185b2bc/embed
Hope helps

**Comment by corradio** [comment]
Do you have it as JSON / GeoJSON? I must admit I haven't had time to dig
further into the link to see if one could extract it from there.

**Comment by strassburger** [comment]
@corradio 
Hope is the right one
[cartodb_query.geojson.zip](https://github.com/tmrowco/electricitymap/files/1379766/cartodb_query.geojson.zip)

**Comment by corradio** [comment]
Great. I'll update the topo as soon as I get the chance. Thanks for your
patience and for pushing here!

**Comment by corradio** [comment]
I suggest we do this as part of the rewrite of the country topo system.

**Comment by corradio** [comment]
Countrytopos.js supports geojson so if anybody wants to work on this, there should be no blockers now!

**Comment by strassburger** [comment]
@systemcatch
To go a half step further:
did put three files adapted to electricitymap.org to the reposito
https://github.com/strassburger/KI-grid-data
Readme-EM.txt
ki-script-EM-INI-01
ki-script-EM-call-01

Maybee the funkcion of the ini-script can be transfered in python.

please check if it may help to get a step further.
I did not found a way to put the data direct into a python script, sorry.
Python i am a really newbee...
Really need help in getting the data out of the data file and in the correct json form....

Also the countrytopos i am afraid to touch.
Can you push a little??
Thank you.

**Comment by systemcatch** [comment]
Hi @strassburger, I should be able to split off King Island on the map now that we have the correct shapefile for it. For your script I will take a closer look when I have more time but it looks like it still runs continuously. 

What needs to happen is the script starts, gets one datapoint for the current system status then writes that data to a file or the terminal output. Essentially it does this already, you just need to make it stop automatically rather than requiring Ctrl + C.

**Comment by strassburger** [comment]
@chris,
Spilt king Island will be a big step.
Changed the name of the script(s):
Preparing firefox window:
ki-script-EM-INI-01
the script to be called, i only tested it manuel after running the ini-script:
ki-script-EM-call-01
Hope helps.

**Comment by strassburger** [comment]
@systemcatch @corradio 
Asked king Island people second time to deliver live data.
Hope helps.
So we would not have to play around with my bash scripts.
If there will be no answer in a week may bee you can make a official letter @corradio 
Will report.

**Comment by corradio** [comment]
Perfect thanks

**Comment by systemcatch** [comment]
It would be so much easier to get access to their live data. As the bash scripts currently require opening a firefox window on a screen I don't know if the EM server can do this. If not they will need substantial changes to work.

**Comment by corradio** [comment]
I agree

**Comment by strassburger** [comment]
To get a step further:
Right now the king Island side do not deliver data at all. It is frozen like hell like a lot of time.
So it may be a good occasion to ask for data with an official mail.
Here is my letter i wrote two days ago:

[King-Island-Mail-02.txt](https://github.com/tmrowco/electricitymap/files/1723496/King-Island-Mail-02.txt)

PS:
a back door. could adapt my script to another more server-friendly browser.
Do you have a hint which one?

**Comment by corradio** [comment]
I've looked a bit more at their webpage and it seems like they are using websockets using https://www.asp.net/signalr.
Seems like the dashboard is preloaded with data here:
http://www.kingislandrenewableenergy.com.au/kiapp-dashboard/data/automatic/dashboard.json

If we could try on a browser that has websockets disabled, I believe signalr will fallback to typical HTTP requests that we can then hook onto.

**Comment by strassburger** [comment]
@corradio,
got the local test installation of EM now.
Try to get a little step further.
But first  think it is a good idea to test out your hint:
"If we could try on a browser that has websockets disabled, I believe signalr will fallback to typical HTTP requests that we can then hook onto."
Would like to test a server  fiendly browser.
Tried Midori but do not have any idea how to switch off websockets......
So can not help, need help...

**Comment by strassburger** [comment]
@corradio 
Hi corradio,
Pelase try to contact official to the management of King Island
Think David is the competent person to realise a json data stream to us.
Thank you
Rainer

Got a contact person at king Island:
davidj.brown@hydro.com.au
Program Implementation Manager, Hybrid Energy Solutions

BSc(Eng), MBA(TechMgmt), MIEAust, CPEng, NPER

My conversation with David:

Hello David,

thanks for the rapit respond and the ref to your app.

Problem of me/us  is that i/we  can not use your app.

I am working with other volunteers to get King Island to the world map of  https://www.electricitymap.org.

It is pretty hard to get the data we need out of the "http://www.kingislandrenewableenergy.com.au/"

It would be perfekt if you would be able to help us with data in form of "json".

Also in Flinders Island data we are interested

.

I personaly did push that El Hierro, an other Island project, is shown in 

https://www.electricitymap.org/?page=country&solar=false&remote=true&wind=false&countryCode=ES-CN-HI

That is a referebce of the form we can show the world King Island and Flinders Island.

 A cooperation of your company in sending data in a readable form for us would help us a lot.

Please let us know if you are abke to help to get your projects in the electricitymap.org.

I would pass it then to more competent people to clear out the tech details.

 

Thank you in advance.

 Rainer Strassburger
rainer@strassburger.name

Last Mail of David:
Hi Rainer 

Thanks for your e-mail, our contact people passed on your message to me.  Thanks for raising the issue with us, we’ll get the data feed to the web site checked out to ensure it feeds data correctly again.  It’s a shame as the King Island system is running 100% renewable when I checked just now.


In case you aren’t aware, there is a free iPhone app for the King Island system available for download from the Apple App Store (search on KIREIP), we don’t currently have one for Android.  The app is showing correct information.  We also expect to release both iPhone and Android apps for our recently completed Flinders Hub project in the next couple of weeks.  The flinders Hub project used similar technology to King Island in a smaller system and has already achieved significant reductions in diesel fuel usage, including a continuous period of over 90 hours of 100% renewable energy operation.  We also have apps for the system on Rottnest Island that we commissioned recently.

Thanks again for your interest and advising us of the issue, we’ll get it followed up.
Kind Regards

David J Brown

**Comment by corradio** [comment]
Just wrote to him, let's see what happens.

**Comment by corradio** [comment]
Just wrote to him, let's see what happens.

**Comment by strassburger** [comment]
No cooperation of hydro.com
No interest any more.
Thanks to everybody here,

**Comment by alixunderplatz** [comment]
@strassburger There is hope for King Island, maybe I have found a workaround ;)
(you guys know I love optical character recognition 😆)
I updated my knowledge of making screenshots of websites in python ([here](https://medium.com/@ronnyml/website-screenshot-generator-with-python-593d6ddb56cb)).


```
# screenshot_maker.py :)
# Saves a screenshot from http://www.kingislandrenewableenergy.com.au/kiapp-dashboard/dashboard.html dashboard 

from selenium import webdriver
import time

# make sure to have the correct path to webdriver.exe in the (...) or directly in the path of this screenshot_maker.py

driver = webdriver.Chrome()
driver.get('http://www.kingislandrenewableenergy.com.au/kiapp-dashboard/dashboard.html')

# make sure to wait long enough for the dashboard to refresh from the initially displayed "default" values # 49, 7 -2, 1002 kW is the default screen we need to skip (better exclude this combo of values from being parsed)
# > 3 seconds time.sleep() recommended
time.sleep(3)

screenshot = driver.save_screenshot('KingIsland_screenshot.png')
driver.quit()
```

@systemcatch I'm sure you'll find a way to improve image quality/size and simply 'OCR' the data out of it :)
the default image size worked fine for me on [tesseract.js](http://tesseract.projectnaptha.com/), but maybe this depends on the default screenshot size on each system

@corradio will this workaround possibly work on the server? If not, feel free to re-close 😉


Here is some of the outcome:
1.
![image](https://user-images.githubusercontent.com/25743609/50665042-806f9300-0faf-11e9-87e0-303f27e9e99c.png)

2.
![image](https://user-images.githubusercontent.com/25743609/50665460-10620c80-0fb1-11e9-8cdd-ba08e0045b10.png)

3.
![image](https://user-images.githubusercontent.com/25743609/50666062-62a42d00-0fb3-11e9-89b3-0623e67cd230.png)

Output of 3)
```
451 48 -6 701 z
38% 4% 58% g
’3 ' Q - . i 6 0
§ * v
W
0 1194 49.90 0
= ‘Vvll ‘.
W *5 g
5 ‘wnvhm
‘ g
```

**Comment by systemcatch** [comment]
One thing which I could do is to split the island off from Tasmania using the same method I did for the Balearic Islands.

**Comment by jarek** [comment]
New URLs as pointed out in #2097: https://www.hydro.com.au/clean-energy/hybrid-energy-solutions/success-stories/king-island , https://data.ajenti.com.au/KIREIP/index.html - but looks like the same Websockets-based app

**Comment by ajoga** [comment]
I fooled around the webpage https://data.ajenti.com.au/KIREIP/index.html, and it seems to use SignalR

I can get the payload with python print in the debug logs, here is where I am so far : https://gist.github.com/ajoga/44f2f84783e492398efd72a1a8257f23


1. L40, I can't manage to get my callback function to be called when I get a message from the server. That's where I'm suck at. 
2. I'm unsure about the "authentication" bits. A hit on the /negotiate endpoint yields a ConnectionToken to pass later on to the websocket. You may need to replay the curl to update the token in order to successfully fetch the payloads. 

I'm probably not going to push that more as I'm really starting to dry up on this

**Comment by ajoga** [comment]
See PR #2456. I have a working parser. 

It's however probably not safe to merge like that because of the authentication bits that are hardcoded. Help/feedback on that welcome

**Comment by strassburger** [comment]
Thanks to ajoga, look like it works now
