### ISSUE TITLE
Timezones / sunrise / sunset times to give data more context

### ISSUE THREAD

**Issue by corradio** [tmrowco/electricitymap-contrib#802]
Would be nice to indicate daytime (sunrise / sunset) in the history graphs to better understand patterns in different time zones.

Potential API: https://sunrise-sunset.org/api

Should probably be done server side to avoid sending too many requests.

Please thumbs up if you'd like this prioritised!

**Comment by jarek** [comment]
It is also possible to get sunrise/sunset times for given position with https://pypi.python.org/pypi/pyephem/3.7.6.0

The API is a little funky, quick intro:

````
In [29]: location = ephem.Observer()
In [30]: location.lat = str(52.5)  # must be given as str!
In [31]: location.lon = str(13.4)
In [32]: sun = ephem.Sun()
In [41]: location.next_setting(sun).datetime()
Out[41]: datetime.datetime(2017, 10, 30, 15, 40, 38, 389741)
In [42]: location.previous_rising(sun).datetime()
Out[42]: datetime.datetime(2017, 10, 29, 5, 56, 54, 210714)
````

You can also do `location = ephem.city('Copenhagen')` but the list of supported cities is not extensive (e.g. no Belfast).

Note that ephem always works with UTC, so those datetimes above are UTC. Catch ephem.NeverUpError and ephem.AlwaysUpError in polar regions.

**Comment by jarek** [comment]
Another, slightly simpler alternative:

Many parsers now have a "timezone" variable to convert time reported by sources to UTC. We could unify it and report it to the front-end, then the front-end could draw ticks for midnight/6/noon/18 in the region's timezone, rather than as currently in the user's timezone.

Side note: this approach as well as sunrise/sunset would be problematic for the U.S., since it is a very large area. But that's our only area this large, and we're actively trying to split it up...

**Comment by corradio** [comment]
That is a very good point. Maybe the first step is to populate zones.json
with associated timezones?
We could even pass the timezones to each parser, as an extra argument

**Comment by jarek** [comment]
One more note: timezone database isn't small (it has to take in differences like e.g. Queensland not having daylight time change while NSW does). I don't know how this looks performance-wise in JavaScript land (sending tz db to each browser?). It might not actually be a large problem in practice though...

**Comment by corradio** [comment]
Hmm. Maybe using timezones is not the best thing then.
Maybe we should directly use sunrise/sunset times.. and maybe a simple
model based on lon/lat will do?

Olivier

**Comment by jarek** [comment]
We could do the timezone stuff on the server side and send local timestamps as well as UTC timestamps with the intensity data. I know it works well in Python and anyway many parsers already use pytz.

**Comment by corradio** [comment]
That would also be useful from a datascience perspective (knowing the local
time).
I suggest:
1/ verify that we can collect one timezone per zone
2/ collect them
3/ find a js library that can compute local time
4/ implement

**Comment by systemcatch** [comment]
Do we want to create a separate file for timezone data (e.g. in parsers.lib) or put it in the zones file?

**Comment by corradio** [comment]
in the zones files is best. I think I might already have added one (but not
sure - can't remember).

**Comment by jarek** [comment]
> 1/ verify that we can collect one timezone per zone

I went through timezone map and tried to identify exceptions:

Where we currently have data (or have identified a source):
- Brazil timezones don't fully line up with electricity zones, compare map on https://en.wikipedia.org/wiki/Time_in_Brazil
  - all of Northeast is UTC-3 with no DST - pop 57 million
  - all of South is UTC-3 with DST - pop 30 million
  - electrical "Central" is made up of governmental "Southeast", "Central-West", and parts of "North". Southeast are UTC-3 with DST, Central-West is split into UTC-3 with DST and UTC-4 with DST, and the bits of North are part UTC-4 with no DST and part UTC-5. Southeast has 86 million people, Central-West 16 million (split roughly evenly into UTC-3 and UTC-4 parts), those parts of North 2.5 million - so we could probably just go with Southeast
  - North is part UTC-3, part UTC-4, part UTC-5 in extreme west. UTC-3 population is around 10 million, UTC-4 and UTC-5 population is 4.5 million total.
- some provinces of Argentina are legally able to observe or not observe daylight savings unlike other provinces - but currently they are all the same
- Crimea and Donbass now observe Moscow time but we have them as part of Ukraine which has different time (what is the electrical reality?)
- Jan Mayen is currently drawn same as Norway while it's in a different timezone, however it should be split out from continental Norway anyway
- United States grid regions don't follow geographical, political, nor time regions

Where we don't yet have data:
- Mexico has 3 time zones, split on state borders - I don't know what the electrical system is like
- Russia spans 9 time zones and I think grid regions span timezones
- Kazakhstan has two time zones
- Mongolia has two time zones
- Indonesia: 3 time zones: borders mostly follow major islands, on Borneo they follows province borders
- Abkhazia is shown on Wikipedia's map as following Moscow time but text in Wikipedia says it follows Georgia time (what is the electrical reality?)
- Canada: parts of eastern British Columbia are in Alberta's timezone - about 10% of the province's population
- Canada: Newfoundland and Labrador (which is one Canadian province) observes separate timezones (but Labrador is less than 10% of the province's population)
- Canada: Nunavut has 3 different timezones and one area that doesn't observe DST - but there is no wide-area electrical grid
- Greenland: 4 different timezones observed, but no wide-area electrical grid

Cases involving less than 1% of the population:
- extreme east Quebec
- extreme west Ontario
- probably more

**Comment by corradio** [comment]
Thanks for this wonderful overview.
It seems like we would make some errors if we associate a timezone per zone (i.e. country).
I know simple models exist for computing sunrise/sunset based on lon lat and time of the year.
Maybe we could write a script that takes all zones and puts then through that model, finding ranges of sunrise/sunset for each zone, and this would give us indicative sunrise / sunset times across the zone.
I realise it might be a bit of work, but it might be the only choice we have as I see it?
What do others think?
Olivier

**Comment by corradio** [comment]
I've used this library https://github.com/Triggertrap/sun-js to figure out sunrise/sunset times given a lon lat.
We could simply use the of the bounding box of the zone as reference.
@jbuverud maybe a simple white overlay with opacity < 1 should suffice?
@jbuverud if you think this adds value, then let's do it, else, I suggest we close the issue as we won't have time to work on it. Let us know your thoughts.

**Comment by systemcatch** [comment]
Closing this for now, feel free to reopen if you want ot pursue this.

**Comment by martincollignon** [comment]
Could be done as part of Hacktoberfest.
