### ISSUE TITLE
Hovering on top of "%renewable" and "%low-carbon" gauges could say what it comprises of

### ISSUE THREAD

**Issue by brunolajoie** [tmrowco/electricitymap-contrib#842]
With a tooltip, we could precise:

- Renewables: "biomass, hydro, geothermal, solar, wind"
- Low-carbon: "renewables and nuclear"

![image](https://user-images.githubusercontent.com/22095643/32600903-59ea4e14-c541-11e7-90ed-bef6e62f714e.png)

**Comment by corradio** [comment]
I like that.

**Comment by grady-lad** [comment]
I can take a look at this if its available ?

**Comment by corradio** [comment]
Go ahead!

**Comment by grady-lad** [comment]
will take a look this week!

**Comment by corradio** [comment]
@grady-lad any updates? cc @jbuverud

**Comment by grady-lad** [comment]
@corradio Hey sorry never got around to doing this. Consider it up for grabs for ever wants it!

**Comment by jzlcdh** [comment]
@corradio Sorry to be picky but the tooltip might need to have exceptions for particular countries. For example  [here in Turkey geothermal may unfortunately not be low carbon](https://pangea.stanford.edu/ERE/db/GeoConf/papers/SGW/2017/Fridriksson.pdf)

**Comment by brunolajoie** [comment]
It's better to improve the code step by step: Let's first close this issue and discuss potential refining later on.

**Comment by corradio** [comment]
@jzlcdh that's interesting, but as @brunolajoie says we should open a separate issue for that (this issue is only about the frontend part, not the backend / calculation)

**Comment by jzlcdh** [comment]
Yes you are right it should be easy to do the basic hover tip I guess, so how do I assign myself this issue?

**Comment by corradio** [comment]
Github does not allow us to assign people who are not members of the
project.
If you say you'll take it, then that should be sufficient!

**Comment by corradio** [comment]
Closing this as it's not a priority. Feel free to re-open if you think otherwise!
