### ISSUE TITLE
Orkney Islands

### ISSUE THREAD

**Issue by systemcatch** [tmrowco/electricitymap-contrib#896]
See @jarek 's comment in #596.

There is live generation data at http://anm.ssepd.co.uk/.  They have a connector to the UK mainland and lots of wind generation.  There are Wave and Tidal energy test facility's but I think it's mainly for R&D rather than regular power generation at the moment.  However there is serious potential for that to change in the future.

The Islands are very committed towards renewable energy, innovation and sustainability.
http://www.orkney.com/invest/sectors/energy
http://www.oref.co.uk/

**Comment by Bjarkigd** [comment]
If memory serves, then Orkney does from time to time produce even more than they can export, as the connection to the mainland can't handle it.

**Comment by alixunderplatz** [comment]
Live generation data has moved to https://www.ssen.co.uk/ANM/

**Comment by pascalheraud** [comment]
OK, I will start on this.

**Comment by pascalheraud** [comment]
For Orkney Islands, the point is to display it on map. The code seems to be GB-ORK but I'm not sure coords are included into naturalearth. Any idea ?

**Comment by jarek** [comment]
In the Natural Earth shapefiles, the Orkneys have their own shape, tagged with:
code_hasc = GB.MO
adm1_code = GBR-2744
gn_a1_code = GB.V9

Extracting them by one of those in topogen.sh should be doable.

While we are looking at the map, it might also be good to separate out Shetland from mainland GB, as there is no grid connection. The codes are GB.AR, GBR-2747, and GB.W3 respectively.

**Comment by corradio** [comment]
Any news here @pascalheraud ?

**Comment by systemcatch** [comment]
I'm going to take a look at getting this one up and running. Can you guys figure out some of the carbon intensities we should be using here.

**Comment by systemcatch** [comment]
Quick question, can we create the GB shape from a mix of subunit and state shapes? There's 80+ adm1 regions which is going to be a pain to work with. It'd be nice to keep the England & Wales subunits and just build Scotland from regions.

**Comment by corradio** [comment]
there's no reason why we couldn't code it that way!

**Comment by systemcatch** [comment]
Reading the latest Energy audit from http://www.oref.co.uk/resources/orkney-energy-audit/ it mentions the following capacity figures.

Wind - 48MW
Solar - 1.2MW
Wave - research only at the moment but leases held for 550MW in future.
Tide - same as above for 530MW.

@alixunderplatz any idea for their carbon intensity?
