### ISSUE TITLE
Units missing from left panel charts

### ISSUE THREAD

**Issue by brunolajoie** [tmrowco/electricitymap-contrib#968]
- Add units to the top right corner of each chart
- Convert second chart units in GW
![image](https://user-images.githubusercontent.com/22095643/34480219-5eb6622c-efab-11e7-8b00-eba20531365b.png)

**Comment by corradio** [comment]
@jbuverud if I remember correctly you had a prototype of this working no?

**Comment by jbuverud** [comment]
No prototype, just visual ideas. I was considering adding a vertical axis label with the unit, and then maybe add k/M/G-prefixes to the ticks so they don't overflow. However now that I think about it some more I think this will look strange, seeing that we want the ticks to be on the right side of the graph, and the unit label should be with the ticks. Maybe the best solution is simply to add the units (with prefixes) directly in the ticks.

**Comment by max-arias** [comment]
This ticket should be closed, fyi
